### ISSUE TITLE
zimbra imapsync 

### ISSUE THREAD

**Issue by arun31cs12** [imapsync/imapsync#100]
how can i sync gmail in zimbra

**Comment by gilleslamiral** [comment]
The basic example should do the job
https://imapsync.lamiral.info/#DOC_BASIC_UNIX
  ./imapsync   \
    --host1 test1.lamiral.info  \
    --user1 test1               \
    --password1  "secret1"      \
    --host2 test2.lamiral.info  \
    --user2 test2               \
    --password2  "secret2"

For Gmail read also
https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt
