### ISSUE TITLE
skipmess not working becasue:  uninitialized value $string_len

### ISSUE THREAD

**Issue by cgrzemba** [imapsync/imapsync#102]
I attempt to skip messages with skipmess, but this throws an error. In this case the regex for skipmess is
`--skipmess m{^Subject: Re:.*}ism`

```
msg INBOX/23926 {4570}        copied to INBOX/2          2.64 msgs/s  25.559 KiB/s 19.356 KiB copied  ETA: Thu Jul 20 08:36:37 2017  192 s  507/509 msgs left
- msg INBOX/23977 {11054} S[11054] F[\Seen] I[ 5-Mar-2015 21:52:52 +0100] (Subject:[Re: [board] I'd like to join opencsw gcc project]) skipped by --skipmess
Use of uninitialized value $string_len in concatenation (.) or string at /usr/bin/imapsync line 5458.
msg INBOX/23977 {}            copied to INBOX/3          3.50 msgs/s  35.154 KiB/s 30.151 KiB copied  ETA: Thu Jul 20 08:35:50 2017  145 s  506/509 msgs left
msg INBOX/23994 {8526}        copied to INBOX/4          4.17 msgs/s  40.148 KiB``
```
And finaly the message which intented for skipping will copied.

environment: Fedora 23, Perl 5.22.2, imapsync 1.727

**Comment by gilleslamiral** [comment]
Hi Carsten,

This time you found a ugly bug!

Fix it with

    -         if ( ( not $string ) and ( not $string_len ) ) {
    +         if ( ( not $string ) or  ( not $string_len ) ) {

**Comment by greem** [comment]
I'm just testing imapsync to move 20000 users from Google to O365 and have just happened across this very same bug, trying to exclude messages of Content-Type: message/partial.

Took me a while to find it, was about to add a patch here and then saw you'd resolved it anyway. Cheers!

**Comment by gilleslamiral** [comment]
Solved. Closing. Happy Sunday, it's Indian summer here!
