### ISSUE TITLE
Install on OpenSuse

### ISSUE THREAD

**Issue by radek-sprta** [imapsync/imapsync#103]
Hello,

are you planning to add install instructions for OpenSuse?

**Comment by gilleslamiral** [comment]
Hi!

I don't have access to an OpenSuse system and I'm too lazy to install one, you're the first one to ask this specific request.  Installing imapsync on any system is described at the end of 
https://imapsync.lamiral.info/INSTALL.d/INSTALL.ANY.txt
in the section "Installing imapsync on other Unixes".

**Comment by radek-sprta** [comment]
Hello.

I had a bit of a trouble getting all the dependencies, but I'll try giving it another go later.

**Comment by gilleslamiral** [comment]
No news good news? Closing
