### ISSUE TITLE
Get the size of each mailbox

### ISSUE THREAD

**Issue by dbareiro** [imapsync/imapsync#106]
Hi, Gilles.

Thank you very much for providing this great tool to work with IMAP.

I would like to know if there is any way to run imapsync against a single server to determine the size of each mailbox to know the total volume of information to migrate. This would allow designing a migration plan based on the observed volume.

Thanks in advance.

Kind regards,
Daniel

**Comment by gilleslamiral** [comment]
Hi Daniel,

Run:

    imapsync ... --justfoldersizes

on the same mailbox, ie, host1/user1 == host2/user2. 
You'll then have the same piece of information twice but you'll have it.

**Comment by dbareiro** [comment]
Hi, Gilles.

Thanks for your prompt reply! I had not seen that option. Thanks also for the indication to repeat the values of host, user and password.

Kind regards,
Daniel
