### ISSUE TITLE
How to install dependencies in Debian 9

### ISSUE THREAD

**Issue by wanderleihuttel** [imapsync/imapsync#107]
I was trying to install the imap sync in Debian, but I can't install dependencies.
https://imapsync.lamiral.info/INSTALL.d/INSTALL.Debian.txt

There is some repository necessary to include?

Best regards
Wanderlei

**Comment by gilleslamiral** [comment]
No particular repository than the classic ones. What fails with the apt command given in INSTALL.Debian.txt?

**Comment by wanderleihuttel** [comment]
Hellos @gilleslamiral.

I've reached install running imapsync and getting the errors and installing modules with MCPAN

perl -MCPAN -e 'install Mail :: IMAPClient'
perl -MCPAN -e 'install Digest :: HMAC_SHA1'
perl -MCPAN -e 'install IO :: Tee'
perl -MCPAN -e 'install Unicode :: String'
perl -MCPAN -e 'install Readonly'
perl -MCPAN -e 'install Authen :: NTLM'
perl -MCPAN -e 'install Data :: Uniqid'
perl -MCPAN -e 'install JSON :: WebToken'
perl -MCPAN -e 'install Crypt :: OpenSSL :: RSA'
perl -MCPAN -e 'install Test :: MockObject'

Congrats for the imapsync !!!

Best Regards
Wanderlei

**Comment by gilleslamiral** [comment]
Hi Wanderlei,

I've tested the "Debian 9" section of file 
https://imapsync.lamiral.info/INSTALL.d/INSTALL.Debian.txt
with a classical stretch sources.list:
``` 
deb http://deb.debian.org/debian stretch main contrib 
deb http://deb.debian.org/debian stretch-updates main contrib
deb http://security.debian.org/ stretch/updates main contrib
```
and everything went ok, no modules were missing after the apt install command and the command didn't fail. 
So, I wonder what precisely went wrong with your Debian 9 and the apt command.

**Comment by wanderleihuttel** [comment]
Hello @gilleslamiral !

My mistake! I accidentally disable a default repository of Debian 9. Now everything worked fine!
Thanks for imapsync and sorry for this!

Best regards!
