### ISSUE TITLE
Install instructions for Debian outdated !!

### ISSUE THREAD

**Issue by vincegre** [imapsync/imapsync#108]
Hi

In Debian install process you indicate that command:

` wget -N https://imapsync.lamiral.info/dist/imapsync`

but looks like URL is wrong (404 error !!).

Thanks

Vincèn

**Comment by gilleslamiral** [comment]
I'm sorry for that, it's now:
https://imapsync.lamiral.info/dist2/

I published the dist/ url on the main page,
it was a "try it before buying" attempt,
and the result was clear: no sales any more...

I just made a marketing mistake,
the message "I want/need you to pay if possible"
was not enough clear and incentive. 

So I'm back to the model
"buy before try (or search by yourself) and I refund if asked to"
and sales got back. 

For those who don't pay no matter the incentive, it's ok, they get imapsync on github :-)

The very latest imapsync that passes unit tests is 
https://imapsync.lamiral.info/imapsync
but I don't consider it a release that can go into massive publication without further approval.
