### ISSUE TITLE
Failed to remove two folders/labels

### ISSUE THREAD

**Issue by elvisef** [imapsync/imapsync#109]
Hello, Could someone write me, what is wrong here ?
Here is the folders listing, for two hosts (these are Polish names in the
host1):

> Host1 folders list:
> [INBOX]
> [[Gmail]]
> [[Gmail]/Czat]
> [[Gmail]/Kosz]
> [[Gmail]/Oznaczone gwiazdk&AQU-] = [[Gmail]/Oznaczone gwiazdkďż˝]
> [[Gmail]/Spam]
> [[Gmail]/Wa&AXw-ne] = [[Gmail]/Waďż˝ne]
> [[Gmail]/Wersje robocze]
> [[Gmail]/Wszystkie]
> [[Gmail]/Wys&AUI-ane] = [[Gmail]/Wysďż˝ane]

> Host2 folders list:
> [INBOX]
> [INBOX.Chats]
> [INBOX.Drafts]
> [INBOX.Sent]
> [INBOX.Trash]
> [INBOX.spam]
> [[Gmail]]

> Folders in host2 not in host1:
> [INBOX.spam]
> [INBOX.Trash]
> [INBOX.Sent]
> [INBOX.Drafts]
> [INBOX.Chats]

I want to remove host2 folders (only two): "[Gmail]" and "INBOX.Chats", and not
create any others on host2.

Host1 is a google GMAIL.
Host2 is a web hosting.

I'm using this sort of command (as an example):
```
imapsync \
--host1 example.com \
--user1 example@example1.com --password1 example --ssl1 --port1 993 \
--host2 example.com \
--user2 example@example2.com --password2 example --ssl2 --port2 993 \
--delete2foldersonly "[Gmail]" \
--delete2foldersonly "INBOX.Chats" \
--justfolders \
--dry
```

All I can see is:

> Deleted INBOX.spam	(not really since --dry mode)
> Deleted INBOX.Trash	(not really since --dry mode)
> Deleted INBOX.Sent	(not really since --dry mode)
> Deleted INBOX.Drafts	(not really since --dry mode)
> Deleted INBOX.Chats	(not really since --dry mode)

What is wrong here ? 

Good day!

**Comment by gilleslamiral** [comment]
Hi Elvis,

First, only one --delete2foldersonly  is effective, the last one on the command line I guess.
The argument is a regex. Regexes are something special. The OR can be obtained by a tube | character.

Use: 

    imapsync ... --delete2foldersonly "/INBOX.Chats|Gmail/"

**Comment by elvisef** [comment]
I wasn't sure if there should be a regex pattern, and no matter what I tried (even regexps), nothing finally worked.

Thanks, it works now : )
