### ISSUE TITLE
High CPU load and very poor performance

### ISSUE THREAD

**Issue by cyberdaemon** [imapsync/imapsync#11]
Hi,

I´m running imapsync-1.569-1.el6.noarch on a Centos 6.5 x64 system. I´m trying to sync from a dovecot imap to a cyrus imap server but the performance is very poor 

0.01 msgs/s  63.780 KiB/s  ETA: Mon Dec  2 22:31:21 2013  28528 s  328 msgs left
0.01 msgs/s  65.135 KiB/s  ETA: Tue Dec  3 01:17:36 2013  38356 s  327 msgs left
0.01 msgs/s  65.076 KiB/s  ETA: Mon Dec  2 21:44:20 2013  25560 s  326 msgs left
0.01 msgs/s  65.238 KiB/s  ETA: Mon Dec  2 23:08:44 2013  30484 s  325 msgs left
0.01 msgs/s  65.181 KiB/s  ETA: Mon Dec  2 21:26:25 2013  24344 s  324 msgs left
0.02 msgs/s  65.122 KiB/s  ETA: Mon Dec  2 20:18:12 2013  20251 s  323 msgs left
0.02 msgs/s  65.235 KiB/s  ETA: Mon Dec  2 19:46:36 2013  18332 s  322 msgs left

and the cpu is during the sync at 100%
Can you please help me out with this issue? Thank you

**Comment by DubbaThony** [comment]
I suffer from same Issue,
CPU has 100% load, both servers are remote, both preety close. It kickstarts somewhat nicely, but than after few mails it just begins to go extremly slow, (1 mail per 5-10 minutes) and lies about its actuall speed (i dont belive 4 megs in 10 minutes is even near 500kb/s)

my settings are imapsync --host1 foo.com --user1 "sb@foo.com" --password1 "$ecret" --ssl1 --host2  bar.com --user2 "sb@bar.com" --password2 "$ecret" --ssl2 --folderec "2012"

**Comment by gilleslamiral** [comment]
Hi Thony,

What gives a second run? Same issue at the same place?

**Comment by DubbaThony** [comment]
Well, I restarted run few times. both servers are comercial hostings and it was struggling with insane slow-motion, than I went sleep and next day it apears it "unlocked" self as most of runs finished at night, now when I start new run speed is ok.

Im having really hard times trying to reproduce issue :(

**Comment by gilleslamiral** [comment]
It could be also the tcp stack.
Ok, try to strace the process next time, showing on what system call it stalls.
I close the issue.
Thanks.
