### ISSUE TITLE
How to force replace all messages ?

### ISSUE THREAD

**Issue by elvisef** [imapsync/imapsync#110]
I recently moved my inbox mail from Gmail to my domain.
Unfortunately almost all messages have bad encoding (I used version 1.7xxx of imapsync).
I want to move them again, but to not duplicate it and FORCE replacing existing ones, with new ones, this time encoding shoulb be ok, with version 1.8xxx that I am using now (I checked that with Sent folder move).

Do you have any idea ? Any command example ?

**Comment by gilleslamiral** [comment]
Hi!

Well, the encoding of 1.8xx is the same as 1.7xx so I guess it won't solve your encoding issue.
There is no force update in imapsync, you're the first to ask for this force feature in 16 years!

**Comment by elvisef** [comment]
Wow... glad to hear : ))

Ok, I think I got it.
The problem is with my email web client.
I used Squirrel mail so far, but for a very short time, few days only.
The problem is still there I think...
Every mail sent had bad encoding...
Now I see, using Roundcube, that almost all emails are good, except ones I used to make conversation with.

Btw., I asked about forcing moving emails, because of that sample situation:

> mail A (gmail)
> mail B (other mail)
> 
> moving messages from A to B... but there's a C mail hosting..
> ok, moving emails from C to B...
> 
> ooops, someone has just sent me an email to the B !

So for instance, In case of bad encoding (fixing encoding), I can't just remove all inbox and move it again, because I could miss all new messages, that were sent directly to B (if messages from A or C had bad encoding). What to do in that situation ?

**Comment by gilleslamiral** [comment]
I understand the need. Is there some characteristic header lines for  the buggy email? If yes, we can search for them and delete/move them before a new sync.

**Comment by gilleslamiral** [comment]
Hi, thinking about your A B C scenario, there is a solution to replace buggy emails without removing new good emails from elsewhere. Instead of removing all messages, just move them all in a subfolder TEMP, then resync the good and fixed messages from A and C to B, then at last resync TEMP to B, the buggy emails won't be synced but the "new" ones will be synced. You have to take care to not sync TEMP inside itself.

**Comment by elvisef** [comment]
Yeah, that seems a good option : )
I did not want to do this that way, to not exceed the quota.
But I'll try it soon, if I have time.

Anyway thanks for this good advice.

**Comment by elvisef** [comment]
One more thing..

I am just moving my messages from gmail account to other hosting, and  interesting situation takes place.
Only let's say 500messages came into gmail account from last moving.

And these messages have been copied of course, but the script is still running like there were all messages to be moved, but.. the amount is not changed. So the script is running and.. replacing them or just checking every message ?

msg [Gmail]/Wszystkie/22543 {10418}       copied to INBOX/27422      1.96 msgs/s  409.525 KiB/s 339.395 MiB copied  
msg [Gmail]/Wszystkie/22544 {12340}       copied to INBOX/27423      1.96 msgs/s  409.383 KiB/s 339.407 MiB copied  
msg [Gmail]/Wszystkie/22545 {10295}       copied to INBOX/27424      1.96 msgs/s  409.181 KiB/s 339.416 MiB copied  
msg [Gmail]/Wszystkie/22546 {14293}       copied to INBOX/27425      1.96 msgs/s  408.936 KiB/s 339.430 MiB copied  
msg [Gmail]/Wszystkie/22547 {10457}       copied to INBOX/27426      1.96 msgs/s  408.795 KiB/s 339.440 MiB copied  
msg [Gmail]/Wszystkie/22548 {10418}       copied to INBOX/27427      1.96 msgs/s  408.648 KiB/s 339.450 MiB copied  
msg [Gmail]/Wszystkie/22549 {14292}       copied to INBOX/27428      1.96 msgs/s  408.511 KiB/s 339.464 MiB copied  
msg [Gmail]/Wszystkie/22550 {14292}       copied to INBOX/27429      1.96 msgs/s  408.370 KiB/s 339.477 MiB copied  

It says "copied" but nothing is being copied, because all messages are already copied.
Just curious.

**Comment by gilleslamiral** [comment]
You mean the host2 is not Gmail but takes new copies of messages without really taking them, am I right?

I though only Gmail had this behavior, when the classical  headers Message-Id and Received are somehow different for imapsync but the messages are not different for Gmail.

**Comment by gilleslamiral** [comment]
No news. Closing.
