### ISSUE TITLE
Moving emails from mbox file to IMAP server

### ISSUE THREAD

**Issue by dbareiro** [imapsync/imapsync#111]
Hi, Gilles.

I have some users who have their email locally, on their computers in mbox format (several Gigabytes).

Is it possible to use imapsync to move these emails in mbox files to an IMAP server?

Thanks in advance.

Kind regards,
Daniel

**Comment by gilleslamiral** [comment]
Imapsync doesn't do mbox to imap transfers.
Imaptools from Rick Sanders does, see MboxtoIMAP.pl at
https://imapsync.lamiral.info/S/imap_tools.V1.333/

**Comment by dbareiro** [comment]
Hi, Giles.

Thanks for your reply. Much appreciated.

It seems it is the official repository:
https://github.com/mtsatsenko/imaputils.git

I'm trying to copy emails to a Gmail test account. Something like this:

```
$ iu-mboxtoimap -m . -f mbox -i imap.gmail.com:993/test@gmail.com/password -I -L iu-mboxtoimap.log
Starting
Authenticating as test@gmail.com
unexpected LOGIN response: 1 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)
```
I was looking at the page mentioned in the output but I'm not sure where the error is. Maybe it's failing because the connection method does not use SSL?

Thanks for your time.

Kind regards,
Daniel

**Comment by gilleslamiral** [comment]
The copy https://github.com/mtsatsenko/imaputils.git happened when Rick abandoned the GPL licence, it's 6 years old. Rick died in January 2017 and put all imap-tools again under a free licence. The last officiel website copy is 
https://web.archive.org/web/20161228145952/http://www.athensfbc.com/imap_tools/ and the imap-tools copy at https://imapsync.lamiral.info/S/imap_tools.V1.333/ is one of the latest. The very latest is version 1.347, March 2016, but I don't have it, I only saw the announce on imap-tools mailing-list.

**Comment by andrewnimmo** [comment]
I recently realised I have a copy of version 1.347, sent to me by Rick on 10 March 2016. I have created a public repository at https://github.com/andrewnimmo/rick-sanders-imap-tools, and updated the `index.html` with content from the original site, courtesy of the Wayback Machine.

**Comment by gilleslamiral** [comment]
Hi Andrew, 
Thanks, this is great news!
I'm going to remove the obsolete copy at  https://imapsync.lamiral.info/S/imap_tools.V1.333/

**Comment by gilleslamiral** [comment]
Thanks!
I've updated https://imapsync.lamiral.info/S/external.shtml
to point ImapTools users to https://github.com/andrewnimmo/rick-sanders-imap-tools
