### ISSUE TITLE
Out of memory error on SmartOS

### ISSUE THREAD

**Issue by alexanderharm** [imapsync/imapsync#113]
I use the latest version of imapsync to transfer roughly 3.000 messages to another account. However, imapsync always fails with error "Out of memory". Disk and memory are fine. The output reads:

    Host2 folder [OCB.Nigeria] considering 19 messages
    Use of uninitialized value in division (/) at ./imapsync line 6063.
    C1: Memory consumption: 0.0 MiB
    Use of uninitialized value in division (/) at ./imapsync line 6183.
    M1: Memory consumption: 0.0 MiB
   Out of memory!

Any idea?

    Here is <UUID>, a 0.2 GiB [solaris] system (SunOS <UUID> 5.11 joyent_20170720T001051Z i86pc)
    with Perl 5.26.0 and Mail::IMAPClient 3.39
    $Id: imapsync,v 1.836 2017/09/05 16:14:53 gilles Exp gilles

**Comment by alexanderharm** [comment]
Although memory consumption seemed fine I double memory allocation and it worked afterwards. Sorry to bother.

**Comment by gilleslamiral** [comment]
You had "only" 200 MB and it's the average value for a sync but it's easily not enough. 
Doubling solved the memory issue, good!
Another issue is "Memory consumption: 0.0 MiB", the 0.0 is false of course but it means imapsync could not get the true value. imapsync does `ps -o vsz -p 12345` to get the memory used by the pid 12345. I guess that this command fails on Solaris. If you know the correct command to get the memory of a process on solaris, from its pid, I will fix imapsync.

**Comment by alexanderharm** [comment]
Actually that command seems to work fine on SmartOS/Solaris and additionally it seems to work in the first half of the sync. All of a sudden it starts to fail:

*Beginning:*

    Folder   35/41 [INBOX.Trash]                       -> [Trash]
    FL: Memory consumption: 178.5 MiB
    Host1 folder [INBOX.Trash] has 800 messages in total (mentioned by SELECT)
    Host2 folder [Trash] has 800 messages in total (mentioned by SELECT)
    Host2 folder [Trash] permanentflags:
    Host1 folder [INBOX.Trash] considering 800 messages
    Host2 folder [Trash] considering 800 messages
    cache directory: /tmp/imapsync_cache/xxx/xxx/localhost/xxx@xxx/INBOX/Trash/Trash

*At some point:*

    msg INBOX.OCB.Nigeria/18 {46422}          copied to OCB.Nigeria/18         2.85 msgs/s  685.419 KiB/s 89.802 MiB copied  ETA: Sun Dec  3 08:37:31 2017  615 s  1751/2133 msgs left
    C3: Memory consumption: 226.3 MiB
    C1: Memory consumption: 226.3 MiB
    M1: Memory consumption: 226.3 MiB
    M2: Memory consumption: 226.3 MiB
    M3: Memory consumption: 226.3 MiB
    C2: Memory consumption: 226.3 MiB
    A1: Memory consumption: 226.3 MiB
    A2: Memory consumption: 226.3 MiB
    msg INBOX.OCB.Nigeria/19 {55447}          copied to OCB.Nigeria/19         2.85 msgs/s  684.254 KiB/s 89.855 MiB copied  ETA: Sun Dec  3 08:37:31 2017  614 s  1750/2133 msgs left
    C3: Memory consumption: 226.3 MiB
    C1: Memory consumption: 226.3 MiB
    M1: Memory consumption: 226.3 MiB
    Use of uninitialized value in division (/) at ./imapsync line 6190.
    M2: Memory consumption: 0.0 MiB
    Use of uninitialized value in division (/) at ./imapsync line 6261.
    M3: Memory consumption: 0.0 MiB
    Use of uninitialized value in division (/) at ./imapsync line 6070.
    C2: Memory consumption: 0.0 MiB
    Use of uninitialized value in division (/) at ./imapsync line 6475.
    A1: Memory consumption: 0.0 MiB
    Use of uninitialized value in division (/) at ./imapsync line 6483.
    A2: Memory consumption: 0.0 MiB
    msg INBOX.OCB.Nigeria/20 {43128355}       copied to OCB.Nigeria/20         2.70 msgs/s  943.624 KiB/s 130.985 MiB copied  ETA: Sun Dec  3 08:38:11 2017  647 s  1749/2133 msgs left
    Use of uninitialized value in division (/) at ./imapsync line 6112.
    C3: Memory consumption: 0.0 MiB

**Comment by gilleslamiral** [comment]
Hi Alexander,

Ok, I guess that when memory is exhausted then the memory measurement by a system call, a fork to ps, can't be done and that explains the wrong value. Anyway imapsync could report this a better way.
Thanks!

**Comment by alexanderharm** [comment]
Well, the last output was on a working setup with the double memory. So memory exhaustion should not be the issue.

**Comment by gilleslamiral** [comment]
Since the new message copied is 43 MB, imapsync will need 100 MB added to the 226 MB, we are near the double now.

**Comment by alexanderharm** [comment]
Not sure I follow you. The machine the message was produced on, had now 512MB of RAM and even more swap. The sync was successful with zero errors. The only remarkable thing is that it stops giving the memory usage at one point in the transfer. I will retry with 1GB of RAM and see if it still happens, OK?

**Comment by alexanderharm** [comment]
I did increase the zone's memory to 1G and indeed now the memory debugging works find. I wonder why it didn't work with 512M considering that imapsync never uses more than 380M (`Memory consumption: 380.8 MiB`). Just to be sure I tested again with 512M and the error occurs again even though imapsync finishes successfully with zero errors. Well, at long as it works :-)

**Comment by gilleslamiral** [comment]
Ok. So the debugging memory stuff really sucks in imapsync, it starts to fail before memory becomes an real issue. Memory usage value is just sugar anyway. I didn't encounter your issue while developing it. Maybe it's the Perl fork implementation (doubling memory crunch?) or something else. Let's put it aside for now, I'll take a closer look at it if someone else reports it.

**Comment by jrab66** [comment]
i have the same problem using imapsync in a smalll vps! in linux you can use a swap file :) and problem solve.

**Comment by gilleslamiral** [comment]
Solved. Closing.
Not bored, readers?
