### ISSUE TITLE
"Killed"

### ISSUE THREAD

**Issue by simbalion** [imapsync/imapsync#115]
Performing a dry run, I see error "Killed". It apparently happens while fetching the folder contents from host1. It happens at the same place each time, at folder 11 of 18.

**Comment by simbalion** [comment]
I've gotten farther by using the --exclude option with the folder it's been dying on, and now it gets to the copying stage and dies with the same error. "Killed".

I ran several tests, twice it died just prior to copying, and once it died during the copy phase.

**Comment by gilleslamiral** [comment]
How much memory do the imapsync process has? See
https://imapsync.lamiral.info/FAQ.d/FAQ.Memory.txt
What says the command `dmesg`? Do you have something like this:
`Out of memory: Kill process 31631 (imapsync) score 78 or sacrifice child
Killed process 31631 (imapsync) total-vm:334360kB, anon-rss:145800kB, file-rss:28kB
`

**Comment by simbalion** [comment]
Gah, I had forgotten to configure a swap file. Sorry for wasting your time!
