### ISSUE TITLE
Missing Invoice

### ISSUE THREAD

**Issue by bitstarr** [imapsync/imapsync#116]
Hey Gilles,

We we fooled by your licence trick on your website. But it's ok, because your tool is a time saver.

But please send us an invoice! We bought on 2017/10/26, an i e-mailed you from my work mail about that on 2017/11/27.

Sorry for abusing this channel, but you don't seem to read your mails :(

**Comment by gilleslamiral** [comment]
Hi Sebastian,

I've just resent it to Daniel W. at revolte. 
I read all my emails, sometimes good ones go to Spam accidentally. 
imapsync in the email title makes them pass to my imapsync work folder straight.

**Comment by bitstarr** [comment]
Well yours was gone to spam too :(

I mailed you again because of another issue with the invoice

Thank you and sorry again for abusing github for my little problem.

please close this issue.

**Comment by gilleslamiral** [comment]
Hi Sebastian,
I've received an "read acknowledgement"  from Daniel at revolte but nothing else from revolte, even in my spam folders. Use gilles@lamiral.info it's directly my machine.

**Comment by bitstarr** [comment]
Great, we got it :)
thanks @gilleslamiral

**Comment by gilleslamiral** [comment]
Good!
