### ISSUE TITLE
Imapsync - ONET.PL - APPEND INBOX

### ISSUE THREAD

**Issue by Kowalec** [imapsync/imapsync#118]
Hi,

i have a problem with sync from onet.pl

I use this command:

`imapsync --host1 imap.poczta.onet.pl -user1 myuser@onet.pl --password1 mypassword  --ssl1 --host2 mail1.bluesky.local --user2 email --password2 my2password --addheader --useuid --maxlinelength 1000 --maxsize 1000000 --syncinternaldates`

And i see this error:

`- msg INBOX/3 {33423} could not append ( Subject:[Londyn - hotele do 30% taniej], Date:["23-Nov-2017 11:35:01 +0100"], Size:[33423] ) to folder INBOX: Error sending '35 APPEND INBOX () "23-Nov-2017 11:35:01 +0100" {33423}': 35 NO [SERVERBUG] Inter... occurred. Refer to server log for more information. [2017-12-15 11:39:12] (0.000 + 0.000 secs).
- msg INBOX/4 {113082} could not append ( Subject:[=?UTF-8?Q?Fw:_Twoje_Zg=C5=82oszenie_oczekuje_n?=], Date:["23-Nov-2017 11:32:52 +0100"], Size:[113082] ) to folder INBOX: Error sending '36 APPEND INBOX () "23-Nov-2017 11:32:52 +0100" {113082}': 36 NO [SERVERBUG] Inte... occurred. Refer to server log for more information. [2017-12-15 11:39:12] (0.000 + 0.000 secs).
msg INBOX/5 skipped (1058314 exceeds maxsize limit 1000000 bytes)
- msg INBOX/6 {71782} could not append ( Subject:[=?UTF-8?Q?Fw:_Twoje_Zg=C5=82oszenie_oczekuje_na_?=], Date:["23-Nov-2017 11:33:09 +0100"], Size:[71782] ) to folder INBOX: Error sending '37 APPEND INBOX () "23-Nov-2017 11:33:09 +0100" {71782}': 37 NO [SERVERBUG] Inter... occurred. Refer to server log for more information. [2017-12-15 11:39:12] (0.000 + 0.000 secs).
msg INBOX/7 skipped (2100591 exceeds maxsize limit 1000000 bytes)
- msg INBOX/8 {89791} could not append ( Subject:[Twoje =?UTF-8?B?WmfFgm9zemVuaWUgb2N6ZWt1amUgbmEgcmVhbGl6YWNqxJkgWzIwMTcv?=], Date:["23-Nov-2017 11:38:55 +0100"], Size:[89791] ) to folder INBOX: Error sending '38 APPEND INBOX () "23-Nov-2017 11:38:55 +0100" {89791}': 38 NO [SERVERBUG] Inter... occurred. Refer to server log for more information. [2017-12-15 11:39:12] (0.000 + 0.000 secs).
- msg INBOX/9 {87170} could not append ( Subject:[Twoje =?UTF-8?B?WmfFgm9zemVuaWUgb2N6ZWt1amUgbmEgcmVhbGl6YWNqxJkgWzIwMTcv?=], Date:["23-Nov-2017 11:39:15 +0100"], Size:[87170] ) to folder INBOX: Error sending '39 APPEND INBOX () "23-Nov-2017 11:39:15 +0100" {87170}': 39 NO [SERVERBUG] Inter... occurred. Refer to server log for more information. [2017-12-15 11:39:13] (0.000 + 0.000 secs).
- msg INBOX/10 {906510} could not append ( Subject:[=?UTF-8?B?WnJlYWxpem93YWxpxZtteSBUd29qZSBaZ8WCb3N6ZW5pZSBbMjAxNy8xMS9J?=], Date:["23-Nov-2017 11:41:49 +0100"], Size:[906510] ) to folder INBOX: Error sending '40 APPEND INBOX () "23-Nov-2017 11:41:49 +0100" {906510}': 40 NO [SERVERBUG] Inte... occurred. Refer to server log for more information. [2017-12-15 11:39:13] (0.000 + 0.000 secs).
- msg INBOX/11 {907097} could not append ( Subject:[=?UTF-8?Q?Fw:_Zrealizowali=C5=9Bmy_Twoje_Zg?=], Date:["23-Nov-2017 11:39:09 +0100"], Size:[907097] ) to folder INBOX: Error sending '41 APPEND INBOX () "23-Nov-2017 11:39:09 +0100" {907097}': 41 NO [SERVERBUG] Inte... occurred. Refer to server log for more information. [2017-12-15 11:39:13] (0.000 + 0.000 secs).
- msg INBOX/12 {14255} could not append ( Subject:[=?UTF-8?Q?Fw:_Rezerwacja_nr_2017/11/BST/5912/1_zosta=C5=82a_anulowana?=], Date:["23-Nov-2017 11:39:21 +0100"], Size:[14255] ) to folder INBOX: Error sending '42 APPEND INBOX () "23-Nov-2017 11:39:21 +0100" {14255}': 42 NO [SERVERBUG] Inter... occurred. Refer to server log for more information. [2017-12-15 11:39:13] (0.000 + 0.000 secs).
`

When I use --debug - then i see:

https://pastebin.com/PEGZxQxK

Thx :-)

**Comment by greem** [comment]
The server response says:

"42 NO [SERVERBUG] Inter... occurred. Refer to server log for more information."

...which rather implies that you need to either look in the server log (or ask the server admin to do it for you). I'm assuming you're the admin as the --host2 attribute ends '.local' ;)

**Comment by Kowalec** [comment]
ok. i find problem - i use bad user

I must now use user - email - to run command

thx :-)
