### ISSUE TITLE
Error while transfering from Gmail to Gmail

### ISSUE THREAD

**Issue by remialvado** [imapsync/imapsync#120]
Hi,

I use imapsync to backup gmail accounts for my company (a small startup). Basically, when an employee leaves, we migrate his/her account to a backup account. It allow us to keep track of every mails without having to continue to pay $3/month to Google.
I did not have issues at the beginning (I've started to do that a few month ago) but, lately, most of the transfers fail due to errors looking like this one : `- msg INBOX/6257 {8040843} couldn't append  (Subject:[[TOOLS] campaign stats]) to folder john-INBOX: * BYE System Error`

I'm using imapsync on an Ubuntu server and run it using screen to ensure that my command keeps running even if my laptop disconnect. I've tried to do the same using some Docker images but I get the same kind of issue. I'm using vers 1.607 on Ubuntu and 1.727 on my Docker container.

Do you have any idea what is happening and how I can fix that? Do you have an option to retry in case of an error?

Thanks for your hard work!

**Comment by gilleslamiral** [comment]
Hi Remi,

The message "BYE System Error" comes directly from the host2 server. 
Does it happens for the same message on each run?

**Comment by gilleslamiral** [comment]
No news. Closing
