### ISSUE TITLE
CentOS 6 build ?tip? ExtUtils::Embed and PAR::Packer

### ISSUE THREAD

**Issue by jhalbrecht** [imapsync/imapsync#121]
While attempting to build imapsync on an aging CentOS 6.8 vm I ran into a lot of trouble, at least for me, installing ExtUtils::Embed and PAR::Packer

I found the solution in a comment on a StackOverflow question [Why won't cpanm install dependencies?](https://stackoverflow.com/questions/32149876/why-wont-cpanm-install-dependencies)

`yum install "perl(ExtUtils::Embed)"`

Then no problem installing `cpanm PAR::Packer`

Maybe in a FAQ, README, Doc or Wiki?

**Comment by gilleslamiral** [comment]
Hi Jeff,
The Perl package PAR::Packer is not necessary to run imapsync. 
PAR::Packer is used to build a imapsync binary. 
I've added it in the prerequisites in order to be able to build a binary easily on any distribution.
Maybe a mistake.
Thanks for the tip anyway!
