### ISSUE TITLE
skipmess exclude all except syntax

### ISSUE THREAD

**Issue by jhalbrecht** [imapsync/imapsync#122]
Email on the current, soon to be old CentOS 6 server, host0.redacted.net, is in unix passwd Mbox format. The new CentOS 7 server, host1.redacted.net, is in Maildir format. dediserve0 has multiple ~ thirteen (13) email addresses in the Mbox by nature of the postfix main.cf mydestination configuration setting. I want them all into separate virtual mailboxes on dediserve1. 

I'm hoping someone can help me with a regex for --skipmess

I made a test run this afternoon with a new linux Maildir user sampson (my dog) I created five paragraphs of [SAMUEL L. IPSUM](http://slipsum.com/) in imapsynctest.input creating two hundred emails all delivered into the one sampson Mbox. 
``` bash
#!/bin/bash
        for i in `seq 1 100`;
        do
                echo $i
                mail -s "imapsync testing $i" sampson@jeffa.org < ~root/imapsynctest.input
                mail -s "imapsync testing $i" sampson@jeffa.biz < ~root/imapsynctest.input
        done
```
then ran imapsync
``` bash
imapsync        --host1 dediserve0.jhalbrecht.net --user1 sampson --password1 'poit' \
                --host2 dediserve1.jhalbrecht.net --user2 sampson@jeffa.org --password2 'splat' \
                --automap --delete1 --noexpungeaftereach
```
I timed it.
``` bash
[root@dediserve0 ~]# time bash imapsynctest.sh
[...]
real    0m4.046s
user    0m0.803s
sys     0m0.232s
[root@dediserve0 ~]# 
```
The report indicated (in part)

``` log
Messages deleted on host1         : 208
Messages deleted on host2         : 0
Total bytes transferred           : 532812 (520.324 KiB)
Total bytes duplicate host1       : 0 (0.000 KiB)
Total bytes duplicate host2       : 0 (0.000 KiB)
Total bytes skipped               : 0 (0.000 KiB)
Total bytes error                 : 0 (0.000 KiB)
Message rate                      : 60.9 messages/s
Average bandwidth rate            : 152.4 KiB/s
Reconnections to host1            : 0
Reconnections to host2            : 0
Memory consumption                : 306.4 MiB
Biggest message                   : 2619 bytes (2.558 KiB)
Memory/biggest message ratio      : 122686.1
Start difference host2 - host1    : -207 messages, -531731 bytes (-519.269 KiB)
Final difference host2 - host1    : 209 messages, 533893 bytes (521.380 KiB)
```
I timed it to judge what it will be like on the ~1700 messages in my real Mbox with at least five addressees that I want to separate on the new server. And WOW! it's a lot faster than I imagined.

It worked pretty well but it put both sampson@jeffa.org and sampson@jeffa.biz in sampson@jeffa.org on the new server.

Looks like skipmess might be the option I need. 

You know though a new switch that checks the To: header and skips all except that match might be handy. Something like `--processonlyto` wouldn't even have to use a regex on the command line. `--processonlyto sampson@jeffa.org` 

Meanwhile might someone help me with a regex for the --skipmess that would skip all To: headers except one. That way I can process the old Mbox several times to move the combined emails into seperate mailboxs on the new server.

**Comment by jhalbrecht** [comment]
Doh! Actually I should be looking at --search1 can it be instructed to look at only the To: header? Not just any string To: in the entire message.

I'm trying --search1 'To: sampson@jeffa.org' I'd like to skip capitalization except for the T in To: in the header.

**Comment by jhalbrecht** [comment]
can `--pipemess` return an empty message that imapsync will ignore and move on to the next message?

**Comment by jhalbrecht** [comment]
OK sorry. Thousand pardons. I just found http://imapsync.lamiral.info/FAQ.d/FAQ.Messages_Selection.txt I'll leave this open a bit for some roasting and close it on success.

**Comment by jhalbrecht** [comment]
--search1 'TO "sampson@jeffa.org"' works great.

**Comment by gilleslamiral** [comment]
Hi Jeff,

You're good, you found your Graal by yourself!

Just a comment, option --search would be safer in a general context. 
Anyway, `--delete1 --search1` is ok for your purpose.

My warning is that `--search1 xxx` is like `--search1 xxx --search2 ALL` 
so it can be very bad with `--delete2` since it will delete some messages on host2 that ARE on host1! (the ones not found by `--search1 xxx`)
 `--search xxx` won't do such a cleanup.
