### ISSUE TITLE
Doubts about the tool.

### ISSUE THREAD

**Issue by krubenrc** [imapsync/imapsync#123]
Hello, i have doubts, i wait that you can help me, please.

I have two accounts, sales and contact, and in the new server the two accounts are merged into a single account called sales.

it's possible?

Also, the tool say me that i have 20.000 emails, but when it finish, i have only 6.000 emails migrate, is normal?

A regards and very thank you.

**Comment by gilleslamiral** [comment]
Hi doubter,

It is possible to merge two account by running two transfers to the same destination account.

For the 20000/6000 diff: Imapsync doesn't sync duplicates but I doubt that 14000 are duplicates of 6000. Run a second time and show me the log if you can.

**Comment by gilleslamiral** [comment]
No news. Closing.
