### ISSUE TITLE
Handling Folders with leading and trailing spaces

### ISSUE THREAD

**Issue by mrunc** [imapsync/imapsync#125]
Just noticed some ....'s account with leading and trailing spaces in folder names

`
Host1 folder FOL1 : Could not select: 17 NO [NONEXISTENT] Unknown Mailbox: FOL1  (now in authenticated state) (Failure)
Folder    6/18 [FOL1 / FOL2 ]                     -> [Orgnization/Folder]
Host1 folder FOL1 / FOL2 : Could not select: 18 NO [NONEXISTENT] Unknown Mailbox: FOL1 / FOL2      (Failure)
Folder    7/18 [FOL1 / FOL2 / FOL3]                -> [Orgnization/Folder]
Host1 folder [FOL1 / FOL2 / FOL3] has 1897 messages in total (mentioned by SELECT)`

**Comment by gilleslamiral** [comment]
Can you select them with another imap client?

**Comment by gilleslamiral** [comment]
No news. Closing
