### ISSUE TITLE
 What happens if I change smtp transport on host2 to host1 and synced email ?

### ISSUE THREAD

**Issue by sparadrus** [imapsync/imapsync#127]
Hi, 
I've created the domain "EXEMPLE.FR" and the accounts on my multi-domains server, it's the host2.

I change the transport on this host2 to deliver mails send by my others users to the host1....

So, how imapsync pull email to host2 ? by SMTP? If that, the synchronised email are send in their turn to host1 ? This configuration can provocate a "cercle vicieux" :) ?
Actually, i turn off the transport when i synced email, but it's probably useless.

Thanks,
Regards,
Philippe

**Comment by gilleslamiral** [comment]
Imapsync does imap only? It gets messages, using imap, from host1 and put them, using imap, to host2. 
For the MX change see https://imapsync.lamiral.info/FAQ.d/FAQ.Migration_Plan.txt

**Comment by sparadrus** [comment]
Merci je vais réviser les fondamentaux...
