### ISSUE TITLE
Sync gmail to zimbra

### ISSUE THREAD

**Issue by maurizio-cavagnetto** [imapsync/imapsync#128]
Hi I have to sync a mailbox from gmail to zimbra. This mailbox have a lot of mail (about 12 Gb) and I need to sync inbox, sent and some other folder  (in gmail label). I have a lot of message with label for example university, ToVerify, ToRemeber etc...
I can found these mails into booth gmail folder (the mail have two labels: inbox and university) and when I sync mailbox I found this mail  twice inside Zimbra (in Inbox ad in university). Could You help me with an example command with right parameters to sync these mails into a university folder only? Thank you very much for your help.
Maurizio

**Comment by greem** [comment]
I recently moved nearly 18000 users from Google to Office365.

You may find the following options helpful:

            --folderlast 'INBOX' \
            --folderlast '[Gmail]/Important' \
            --folderlast '[Gmail]/All Mail' \
            --skipcrossduplicates \
            --useheader="X-Gmail-Received" \
            --useheader "Message-Id" \
            --exclude "\[Gmail\]$" \
            --exclude 'All Mail' \
            --exclude 'Junk' \
            --exclude 'Bin' \
            --exclude 'Spam' \
            --exclude 'Deleted Items' \
            --exclude 'Deleted Messages' \
            --exclude 'Trash' \

...amongst others. You'll probably find

http://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt

useful, too.

**Comment by gilleslamiral** [comment]
Background knowledge to explain what happens: Gmail presents labels as folders in IMAP.
To avoid syncing Gmail labels in different host2 folders there is the option `--skipcrossduplicates`.

In your case, a solution would be:

    imapsync ... --skipcrossduplicates --folderfirst university ... --folderlast Inbox --folderlast Sent ...

More details, quoting https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt
```
--skipcrossduplicates is optional but it can save Gigabytes of hard
disk memory. Within imap protocol, Gmail presents Gmail labels as 
folders, so a message labeled "Work" "ProjectX" "Urgent" ends up 
in three different imap folders "Work" "ProjectX" and "Urgent"
after an imap sync. Option --skipcrossduplicates prevent this behavior.

An issue with --skipcrossduplicates is that the first label synced
by imapsync goes to its corresponding folder but other labels are
then ignored. You can choose what labels have the 
priority by using the --folderfirst option. For example
--folderfirst "Work" will sync messages labeled "Work" before
messages labeled "CanWait" or "Urgent". By default imapsync 
syncs folders (Gmail labels) using the classical alphanumeric order.

--folderlast "CanWait" will sync only messages that have the
label CanWait and only it.

--folderlast "[Gmail]/All Mail", in conjunction with option 
--skipcrossduplicates, will only put in "[Gmail]/All Mail"
the messages that are not labeled at all.
```
