### ISSUE TITLE
Perl warning about uninitialized variables

### ISSUE THREAD

**Issue by ydroneaud** [imapsync/imapsync#13]
Using imapsync v1.569 commit 8f266abab84bbffb350582da08f07c824d2bd9e0, on a Debian squeeze system using libmail-imapclient-perl  3.31-2:

Host1 separator and prefix: [.][INBOX.]
Host2 separator and prefix: [.][]
++++ Calculating sizes on Host1
Host1 folder [INBOX]

Use of uninitialized value in hash element at /usr/share/perl5/Mail/IMAPClient.pm line 2252.
Use of uninitialized value $size in addition (+) at ./imapsync line 2845.
Use of uninitialized value $list[1] in sort at ./imapsync line 1790.
Use of uninitialized value $list[1] in sort at ./imapsync line 1790.
Use of uninitialized value $list[0] in sort at ./imapsync line 1790.
Use of uninitialized value $list[0] in sort at ./imapsync line 1790.
 Size: 1878559958 Messages: 82928 Biggest:  15513754

**Comment by aconitumnapellus** [comment]
To "fix" this, add this line unter `use warnings ;`
`no warnings 'uninitialized' ;`

The warnings will disappear then.

**Comment by gilleslamiral** [comment]
I hope this 5 year old issue is fixed in next releases with something else than 
no warnings 'uninitialized'
