### ISSUE TITLE
Folders list1 diferent to Folder list2 

### ISSUE THREAD

**Issue by jorgemop** [imapsync/imapsync#130]
[root@xxx LOG_imapsync]# imapsync --buffersize 8192000 --subscribe --subscribed --ssl1 --ssl2 --host1 192.168.255.254 --port1 993 --authmech1 PLAIN --user1 user@domains --authuser1 user@domains --password1 pass --host2 192.168.255.255 --port2 993 --authmech2 PLAIN --user2 user1@domain --authuser2 user@domains --password2 pass --showpasswords --errorsmax 150
Transfer started at Sat Mar 24 09:31:17 2018
PID is 30465
Log file is LOG_imapsync/2018_03_24_09_31_17_user@domains.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
$RCSfile: imapsync,v $ $Revision: 1.684 $ $Date: 2016/03/17 08:35:03 $
Here is a [linux] system (Linux ntplanta1.paisa.com.ve 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64)
With perl 5.10.1 Mail::IMAPClient  3.37
Command line used:
/usr/bin/imapsync --buffersize 8192000 --subscribe --subscribed --ssl1 --ssl2 --host1 192.168.255.254 --port1 993 --authmech1 PLAIN --user1 user@domains --authuser1 user@domains --password1 pass --host2 192.168.255.255 --port2 993 --authmech2 PLAIN --user2 user@domains --authuser2 user@domains --password2 pass --showpasswords --errorsmax 150
Temp directory is /tmp  ( to change it use --tmpdir dirpath )
PID file is /tmp/imapsync.pid ( to change it use --pidfile filepath ; to avoid it use --pidfile "" )
Modules version list:
Mail::IMAPClient     3.37
IO::Socket           1.31
IO::Socket::IP       ?
IO::Socket::INET     1.31
IO::Socket::SSL      1.31
Net::SSLeay          1.35
Compress::Zlib       2.021
Digest::MD5          2.39
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.01
Term::ReadKey        2.30
File::Spec           3.3
Time::HiRes          1.9721
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.29
Data::Uniqid         0.12
JSON                 ?
JSON::WebToken       ?
Crypt::OpenSSL::RSA  ?
LWP                  5.833
HTML::Entities       3.64
Filesys::DfPortable  ?
( use --no-modules_version to turn off printing this Perl modules list )
Use --sslargs1 SSL_verify_mode=1 for SSL_VERIFY_PEER on host1
Use --sslargs2 SSL_verify_mode=1 for SSL_VERIFY_PEER on host2
ssl debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use PLAIN authentication on host1
Host2: will try to use PLAIN authentication on host2
Host1: imap connexion timeout is 120 seconds
Host2: imap connexion timeout is 120 seconds
Host1: IMAP server [192.168.255.254] port [993] user [user@domains]
Host2: IMAP server [192.168.255.255] port [993] user [user@domains]
Host1: connecting and login on host1 [192.168.255.254] port [993] with user [user@domains]
Host1 banner: * OK ntplanta1.paisa.com.ve Zimbra IMAP4rev1 server ready
Host1: 192.168.255.254 says it has CAPABILITY for AUTHENTICATE PLAIN
Host1: success login on [192.168.255.254] with user [user@domains] auth [PLAIN]
Host2: connecting and login on host2 [192.168.255.255] port [993] with user [user@domains]
Host2 banner: * OK IMAP4rev1 proxy server ready
Host2: 192.168.255.255 says it has CAPABILITY for AUTHENTICATE PLAIN
Host2: success login on [192.168.255.255] with user [user@domains] auth [PLAIN]
Host1: state Authenticated
Host2: state Authenticated
Host1 capability: IMAP4rev1 ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ LOGIN-REFERRALS MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST
Host2 capability: IMAP4rev1 ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ LOGIN-REFERRALS MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST

Host2: found quota, presented in raw IMAP
Sending: 4 GETQUOTAROOT INBOX
Sent 22 bytes
Read:   * QUOTAROOT "INBOX" ""
        * QUOTA "" (STORAGE 102397 2048000)
        4 OK GETQUOTAROOT completed

Host2: Quota current storage is 104854528 bytes. Limit is 2097152000 bytes. So 5.00 % full
Host1: found 45 folders.
Host2: found 39 folders.
Host1: checking all wanted folders exist.
Host1: checking all wanted folders are selectable. Use --nocheckselectable to avoid this check.
Host1: guessing separator from folder listing: [/]
Host1: separator given by NAMESPACE: [/]
Host2: guessing separator from folder listing: [/]
Host2: separator given by NAMESPACE: [/]
Host1: guessing prefix from folder listing: []
Host1: prefix given by NAMESPACE: []
Host2: guessing prefix from folder listing: []
Host2: prefix given by NAMESPACE: []
Host1 separator and prefix: [/][]
Host2 separator and prefix: [/][]
Turned off automapping folders ( use --automap to turn on automapping )

++++ Listing folders
All foldernames are presented between brackets like [X] where X is the foldername.
When a foldername contains non-ASCII characters it is presented in the form
[X] = [Y] where
X is the imap foldername you have to use in command line options and
Y is the uft8 output just printed for convenience, to recognize it.

Host1 folders list:
[Asana]
[Baan - AIX]
[Base de Datos]
[Bitacoras]
[Bitacoras/Humanix]
[Chats]
[Contacts]
[Correo]
[Drafts]
[Emailed Contacts]
[INBOX]
[Junk]
[Mario]
[Mario/Primeros dias]
[Pass]
[Pastca]
[Pastca/Bodegon]
[Pastca/Personal]
[Pastca/juegos]
[Proveedores]
[Proveedores/AV]
[Proveedores/Baan]
[Proveedores/CANTV]
[Proveedores/Digitel]
[Proveedores/Gandalf]
[Proveedores/HP]
[Proveedores/Hardware]
[Proveedores/Juniper]
[Proveedores/McAfee]
[Proveedores/Microsoft]
[Proveedores/Movistar]
[Proveedores/Oracle]
[Proveedores/SVN]
[Proveedores/Satelca-Barcelona]
[Proveedores/Zimbra]
[Proveedores/redes]
[Proveedores/venred - paisasite]
[Sala de servidores]
[Sala de servidores/Usu Criticos]
[Sala de servidores/VPN]
[Sent]
**[Soporte]
[Telecom]**
[Trash]
[galsync's _zimbra]

Host2 folders list:
[Asana]
[Baan - AIX]
[Base de Datos]
[Bitacoras]
[Bitacoras/Humanix]
[Correo]
[Drafts]
[INBOX]
[Junk]
[Mario]
[Mario/Primeros dias]
[Pass]
[Pastca]
[Pastca/Bodegon]
[Pastca/Personal]
[Pastca/juegos]
[Proveedores]
[Proveedores/AV]
[Proveedores/Baan]
[Proveedores/CANTV]
[Proveedores/Digitel]
[Proveedores/Gandalf]
[Proveedores/HP]
[Proveedores/Hardware]
[Proveedores/Juniper]
[Proveedores/McAfee]
[Proveedores/Microsoft]
[Proveedores/Movistar]
[Proveedores/Oracle]
[Proveedores/SVN]
[Proveedores/Satelca-Barcelona]
[Proveedores/Zimbra]
[Proveedores/redes]
[Proveedores/venred - paisasite]
[Sala de servidores]
[Sala de servidores/Usu Criticos]
[Sala de servidores/VPN]
[Sent]
**missing**
[Trash]

Host1 subscribed folders list:
Folders mapping from --automap feature (use --f1f2 to override any mapping):

Folders mapping from --f1f2 options, it overrides --automap:

Folders sizes before the synchronization.
You can remove foldersizes listings by using "--nofoldersizes" and  "--nofoldersizesatend"
but then you will also loose the ETA (Estimation Time of Arrival) given after each message copy.
++++ Calculating sizes of 0 folders on Host1
Host1 Nb folders:                0 folders
Host1 Nb messages:               0 messages
Host1 Total size:                0 bytes (0.000 KiB)
Host1 Biggest message:           0 bytes (0.000 KiB)
Host1 Time spent:              1.6 seconds
++++ Calculating sizes of 0 folders on Host2
Host2 Nb folders:                0 folders
Host2 Nb messages:               0 messages
Host2 Total size:                0 bytes (0.000 KiB)
Host2 Biggest message:           0 bytes (0.000 KiB)
Host2 Time spent:              0.0 seconds
++++ Looping on each one of 0 folders to sync
++++ End looping on each folder

Folders sizes after the synchronization.
You can remove this foldersizes listing by using  "--nofoldersizesatend"
++++ Calculating sizes of 0 folders on Host1
Host1 Nb folders:                0 folders
Host1 Nb messages:               0 messages
Host1 Total size:                0 bytes (0.000 KiB)
Host1 Biggest message:           0 bytes (0.000 KiB)
Host1 Time spent:              0.0 seconds
++++ Calculating sizes of 0 folders on Host2
Host2 Nb folders:                0 folders
Host2 Nb messages:               0 messages
Host2 Total size:                0 bytes (0.000 KiB)
Host2 Biggest message:           0 bytes (0.000 KiB)
Host2 Time spent:              0.0 seconds
++++ Statistics
Transfer started on               : Sat Mar 24 09:31:17 2018
Transfer ended on                 : Sat Mar 24 09:31:20 2018
Transfer time                     : 3.6 sec
Folders synced                    : 0/0 synced
Messages transferred              : 0
Messages skipped                  : 0
Messages found duplicate on host1 : 0
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 0
Messages void (noheader) on host2 : 0
Messages deleted on host1         : 0
Messages deleted on host2         : 0
Total bytes transferred           : 0 (0.000 KiB)
Total bytes duplicate host1       : 0 (0.000 KiB)
Total bytes duplicate host2       : 0 (0.000 KiB)
Total bytes skipped               : 0 (0.000 KiB)
Total bytes error                 : 0 (0.000 KiB)
Message rate                      : 0.0 messages/s
Average bandwidth rate            : 0.0 KiB/s
Reconnections to host1            : 0
Reconnections to host2            : 0
Memory consumption                : 350.7 MiB
Biggest message                   : 0 bytes
Start difference host2 - host1    : 0 messages, 0 bytes (0.000 KiB)
Final difference host2 - host1    : 0 messages, 0 bytes (0.000 KiB)
Detected 0 errors

**Comment by gilleslamiral** [comment]
No clue, can you use a recent imapsync? I don't like to debug old stuff.

**Comment by branzo** [comment]
What about using --subscribe_all?

**Comment by gilleslamiral** [comment]
I think it was the presence of the option `--subscribed `
which limits the complete list of folders synced to only the subscribed folders.

The other option `--subscribe` (without the "d") was useless since it is activated by default.

https://imapsync.lamiral.info/README
```
     --subscribed        : Transfers subscribed folders.
     --subscribe         : Subscribe to the folders transferred on the
                           host2 that are subscribed on host1. On by default.
     --subscribeall      : Subscribe to the folders transferred on the
                           host2 even if they are not subscribed on host1.

```
