### ISSUE TITLE
--delete2 does not delete emails on host2 that are deleted on host1

### ISSUE THREAD

**Issue by bkroggel** [imapsync/imapsync#133]
_Not sure if that is the right place for such a question so please @gilleslamiral feel absolutely free to close this issue if you thing that it is not appropriate._

First of all I usually run imapsync with pretty much the example config I posted below while my intend is to keep an exact copy of `first@domain.com` in my `second@domain.com`.
```
./imapsync_bin_Darwin --host1 host1.domain.com   --user1 first@domain.com  --password1 'XXX' --ssl1 \
                      --host2 host2.domain.com   --user2 second@domain.com   --password2 'XXX' \
                      --f1f2    "Inbox=INBOX" \
                      --f1f2    "Junk-E-Mail=INBOX.Junk" \
                      --f1f2    "Deleted Messages=INBOX.Trash" \
                      --f1f2    "Trash2=INBOX.Trash" \
                      --automap  --skipemptyfolders --delete2 \
                      --useuid --tmpdir /path/to/tmp
```

What happened today is, that I recognized, that my host2 domain actually has close to 200 emails in its trash-folder, while there are 0 deleted emails present on any folder at host1 which is matched with the host2-trash-folder.
Since this isn‘t any production ready environment right now I played a little bit around with `--expunge2`, `--uidexpunge2` and also tried to do a `--usecache` without `--useuid` in order to fix any potential issues with the cached emails — however it looks like there is no file currently present in my cache-locations trash-folder either while I am still not able to delete those emails via an imapsync operation.

Does anybody know what is going on or how I could solve that issue?

Btw. I should mention that imapsync was most surely running while I cleared my trash-folder on host1 — but as far as I understood imapsync that should have been taken into account on a second run and cleared the trash-folder on host2 as well.

**Comment by gilleslamiral** [comment]
Hi!

> while there are 0 deleted emails present on any folder at host1

Try without --skipemptyfolders

**Comment by bkroggel** [comment]
Hey!
Thanks a lot @gilleslamiral. This change actually worked as expected and I now do have once again an exact copy of host1 in my host2 inbox — though now empty folders got transferred as well, but I suspect I could set an exception for them.

Just to clarify things. Is that the expected behavior?
I was actually thinking that if I do have messages in a folder on host2 and delete the messages in the corresponding folder of host1 the --delete2 flag gets triggered and will delete those messages. Shouldn‘t it make any difference if I keep 1 message in the folder on host1 (where all messages but the single one will be deleted on host2) or if I clear the host1 folder entirely (where—at least I—would expect to clear all corresponding emails in the host2 folder)?

**Comment by gilleslamiral** [comment]
Yes, it is the expected behavior. When using  `--skipemptyfolders`, imapsync avoid to sync empty folders, no matter they weren't empty before. Imapsync is stateless. 
You're right, leave one message in a folder and 
`imapsync ... --skipemptyfolders`  won't skip  a non-empty folder.
If you remove a folder on host1 then imapsync won't remove it on host2 by default since it is a very dangerous behavior. But with `--delete2folders` it will.

Maybe what you look for is the option  `--delete1emptyfolders`

``` 
$ imapsync --help
...
Options/deletions:

  --delete1           : Deletes messages on host1 server after a successful
                        transfer. Option --delete1 has the following behavior:
                        it marks messages as deleted with the IMAP flag
                        \Deleted, then messages are really deleted with an
                        EXPUNGE IMAP command. If expunging after each message
                        slows down too much the sync then use
                        --noexpungeaftereach to speed up.
  --expunge1          : Expunge messages on host1 just before syncing a folder.
                        Expunge is done per folder.
                        Expunge aims is to really delete messages marked deleted.
                        An expunge is also done after each message copied
                        if option --delete1 is set.
  --noexpunge1        : Do not expunge messages on host1.
  --delete1emptyfolders : Deletes empty folders on host1, INBOX excepted.
                          Useful with --delete1 since what remains on host1
                          is only what failed to be synced.

  --delete2           : Delete messages in host2 that are not in
                        host1 server. Useful for backup or pre-sync.
  --delete2duplicates : Delete messages in host2 that are duplicates.
                        Works only without --useuid since duplicates are
                        detected with an header part of each message.

  --delete2folders    : Delete folders in host2 that are not in host1 server.
                        For safety, first try it like this (it is safe):
                        --delete2folders --dry --justfolders --nofoldersizes
  --delete2foldersonly   reg : Deleted only folders matching regex.
                               Example: --delete2foldersonly "/^Junk$|^INBOX.Junk$/"
  --delete2foldersbutnot reg : Do not delete folders matching regex.
                               Example: --delete2foldersbutnot "/Tasks$|Contacts$|Foo$/"

  --expunge2          : Expunge messages on host2 after messages transfer.
  --uidexpunge2       : uidexpunge messages on the host2 account
                        that are not on the host1 account, requires --delete2

```

**Comment by bkroggel** [comment]
Thanks a lot for the clarification.
You are right, I kind of missed the point of Imapsync being stateless and therefore doesn‘t even know about the fact if a folder previously carried some emails or not.

I basically used `--skipemptyfolders` to "clean up" my mailboxes and skip folders I haven‘t used in a while (and which are empty) but as I've seen now I probably should have used `--exclude` or delete the folders on *host1* in the first place.

Thanks again!

Since my question is definitely answered and everything works as expected, I am going to close this issue.
Have a nice day :)
