### ISSUE TITLE
Syncing from Gmail: --automap does not respect --subfolder2

### ISSUE THREAD

**Issue by dgasaway** [imapsync/imapsync#134]
When using --automap (or as part of --gmail1) with --subfolder2 'Gmail', I found that the automap would map the gmail sent folder to INBOX.Sent rather than INBOX.Gmail.Sent, as expected.  As I was also using --delete2 --delete2folders, it wanted to delete my entire existing Sent folder.

**Comment by gilleslamiral** [comment]
Well, conjonction of options may sometimes becomes a headache, both for the users and the designer.
As the master of the behavior I came to decide the following to build the host2 folder name from a host1  folder name:

1. If --f1f2 is used then it prevales everything.
2. If --automap is used and folder matches then it is what is applied.
3. If --regextrans2 is used then it is applied, unless 1 or 2. --subfolder2 is a --regextrans2 

Add `--f1f2  INBOX.Sent=INBOX.Gmail.Sent` and the host2 ` INBOX.Sent` might disappear on next run.

**Comment by dgasaway** [comment]
Fair enough.  I wanted to keep imapsync absolutely constrained to a single folder*.  I thought imapsync would make this really simple - point it at a folder and give it free reign to do as it saw fit.  From your response, it's a little more complicated.  I won't argue with the design if this is, in fact, by design.  I'm a software developer, so I can relate.  I'll just avoid --gmail1 and --automap.  Thanks.

* For years, I had imapsync intermingle messages from different sources in the same folders; ultimately, that had too many compromises (not really the program's fault).

**Comment by gilleslamiral** [comment]
To keep imapsync constrained to a single folder is made simple by using --subfolder2, the equivalent `--regextrans2` option was well known to get a headache quickly. But it is this way as far as it is not asked to do also something else with other options, which is asked by --gmail1. I guess that what would work for your case, with still the benefit of --gmail1, would be:

`imapsync ...  --subfolder2 Gmail --gmail1 --noautomap`

Have  a try!

**Comment by gilleslamiral** [comment]
No news. Closing
