### ISSUE TITLE
Is syncing of Cyrus Imap folder shares possible?

### ISSUE THREAD

**Issue by marcusvalentine** [imapsync/imapsync#135]
For example, on an Cyrus imap server, the mailbox user.westside is shared with users flora and megan.

The cyrus user was given all privileges to all mail mailboxes on the source and destination servers to allow the sync to be done as user cyrus.
```
source server> lam user.westside
westside lrswipcda
flora lrswipktecd
cyrus lrswipkxtecda
megan lrswipktecd
```
After syncing, on the destination server
```
destination server> lam user.westside
cyrus lrswipkxtecdan
westside lrswipkxtecdan
```
Thanks

**Comment by gilleslamiral** [comment]
I'm not sure to understand the question.
Do you want to sync a shared folder or the fact that it is shared and how?

**Comment by marcusvalentine** [comment]
I would like to sync the folder share permissions (shown by listaclmailbox) from source to destination, so in the example above, when the ACLs are listed on the destination server, they would read the same as the source server.

**Comment by gilleslamiral** [comment]
There is the option --syncacls 
Have a try!

**Comment by marcusvalentine** [comment]
That's the badger. Sorry - I did not spot that flag in the documentation

**Comment by gilleslamiral** [comment]
Does --syncacls work for you?

**Comment by marcusvalentine** [comment]
Yes, --syncacls worked very well. Thank you for your help.
