### ISSUE TITLE
ImapSync to Exchange 2016 (authuser2)

### ISSUE THREAD

**Issue by gbennett68** [imapsync/imapsync#136]
Having issues authenticating to Exchange 2016 with authuser2.  Here is my syntax:

.\imapsync.exe --host1 oldmail@local.com --user1 test@external.com --password1 ******  ^
               --host2 newmail@local.com --authuser2 admin@local.com --user2 test@local.com --password2 ******  ^
               --automap --exchange2 --delete2 --expunge2 --delete2folders --disarmreadreceipts 

No matter what, I get:
Host2 failure: Error login on [newmail@local.com] with user [test@local.com] auth [PLAIN]: 2 NO AUTHENTICATE failed.

Here is what I have done/tried:
- Added admin full rights on test mailbox
- IMAP4 is enabled on newmail
- Set IMAP4 logon method to basic (plain text)
- Tried all sorts of syntax variations from FAQ.Exchange.txt
- Made sure passwords are okay (FAQ.Passwords_on_Windows.txt)

Everything works great if I sync with the test users password (not using authuser2).

**Comment by gbennett68** [comment]
NOTE:
Installed on CentOS 7, with same result.

**Comment by gilleslamiral** [comment]
No one reported me that authenticate on 2016 with --authuser2 works. Try the other syntax.

https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt
```
  imapsync ... --user2 "domain\admin2\user2" --password2 adminpassword2 ...
or 
  imapsync ... --user2 "admin2@domain\user2" --password2 adminpassword2 ...

where "domain" is set be the user's UPN in Active Directory
or the NETBIOS or DNS name of the domain.

The exact format might vary depending on local configuration and you
should experiment with the different formats.
```
Maybe the Office365 item can help:
```
Q. How to migrate from or to Office 365 with an admin/authuser account?

Note from Yago Torres Fernandez:
(a working command using admin/authuser on host2 Office 365)

  imapsync ... --authuser2 user_admin@domain.com --user2 user_to_be_migrated@domain.com  ^
               --password2 XXXX --ssl2  ^

but previous in Office365 you must do something like that, using powershell:

  Add-MailboxPermission -identity user_to_be_migrated@domain.com -user user_admin@domain.com -accessrights fullaccess -inheritancetype all

PLAIN authentication is the only way to go with --authuser1 for now.
So don't use --authmech1 SOMETHING with --authuser1 admin_user,
it will not work.
Same behavior with the --authuser2 option.

Note from Martin Paulucci:
I had to remove the domain part for the user
but not for the admin.  Example:

  imapsync ... --authuser2 user_admin@domain.com --user2 user_to_be_migrated
```
See also:
http://www.linux-france.org/prj/imapsync_list/msg02203.html

**Comment by gbennett68** [comment]
Hi Gilles,
Thanks for getting back to me.
Unfortunately, none of those combinations seem to work.

**Comment by MolallaComm** [comment]
I can confirm that this does work with exchange 2016 - the key is to not use the built-in Administrator account which Microsoft seems to have blocked access to in imap.  I'm doing a zimbra->exch2016 migration and this works:

root@ubuntu:~# imapsync --host1 zimbra -port1 993 --user1 account@domain.com --authuser1 admin --password1 'adminpw' --ssl1 -host2 exch2016 -port2 993 --user2 account@domain.com --authuser2 accountwfullaccess@domain.com --password2 'accountwfullaccesspw' --ssl2

The admin account you use needs to have full access to the account(s) you want to sync which you can setup in the gui or via powershell and again - don't use administrator@domain.com - as that will never work because IMAP LOGIN is disabled for that account apparently under all circumstances.

**Comment by gbennett68** [comment]
Hi MolallaComm,
Yes, that appears to have worked; thanks for the tip.
I have been delaying cut-over because I have been relying on senior users to sync their own email.  This will really help a lot.

**Comment by gilleslamiral** [comment]
The section 
"Q. How to migrate from or to Exchange 2016 with an admin/authuser account?"
of https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt
is updated with the MolallaComm's comment
https://github.com/imapsync/imapsync/issues/136#issuecomment-397020248
Thanks!

Closing.

**Comment by Noxyron** [comment]
Hi guys. For a long time I could not start synchronization, I use admin rights and the --authuser2 switch when I migrated from Mdaemon to Exchange2016. I always got the error:
"Host2 failure: Error login on [mx.server.com] with user [mydomainuser] auth [PLAIN]: 2 NO AUTHENTICATE failed."
In order for ImapSync to log into the user’s mailbox with administrator rights, you need to give the administrator the permissions to the mailbox of this user with the command “Add-MailboxPermission -Identity DomainUser -User DomainAdmin -AccessRights FullAccess -InheritanceType All -AutoMapping $ false” using MS Exchange PowerShell. Without this, synchronization will not work.

**Comment by gilleslamiral** [comment]
Added your comment in the FAQ
https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt

**Comment by ciclonite** [comment]
Hi all,
I've tried all' the solution above with exchange2019, without success. Someone have successfully migrated to exchange2019?
This is the error
`Host2: connecting and login on host2 [mailserver.xx.locale:993] port [993] with user [cm.locale\winadmin2\user1]
Host2 IP address: 192.168.1.14
Host2 banner: * OK The Microsoft Exchange IMAP4 service is ready.
Host2 capability before authentication: IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+ AUTH
Host2 info: authmech [LOGIN] user [xx.locale\winadmin2\user1] authuser [] IsUnconnected []
Host2 failure: Error login on [mailservel.xx.locale:993] with user [xx.locale\winadmin2\user1] auth [LOGIN]: 2 NO LOGIN failed.
Exiting with return value 16 (EXIT_AUTHENTICATION_FAILURE) 1/50 nb_errors/max_errors
Disconnecting from host1 
`
This is an example i've tried all the combination.
thanks.

**Comment by ciclonite** [comment]
Hi, problem solved, for those have problem to authenticate, please check also that the certificate is correct.
Take a look at : http://clintboessen.blogspot.com/2018/03/binding-certificate-breaks-imap-or-pop.html
Thanks!

**Comment by gilleslamiral** [comment]
> Hi, problem solved, for those have problem to authenticate, please check also that the certificate is correct.
> Take a look at : http://clintboessen.blogspot.com/2018/03/binding-certificate-breaks-imap-or-pop.html
> Thanks!

Thanks, I've updated the FAQ with your link:
https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt

````
Q. How to sync from XXX to Exchange 2010/2013/2016/2019

R0. IMAP is not enable by default on Exchange, see how to enable it:
https://docs.microsoft.com/en-us/exchange/enable-imap4-in-exchange-2013-exchange-2013-help
Also read
http://clintboessen.blogspot.com/2018/03/binding-certificate-breaks-imap-or-pop.html
````

**Comment by Ekinci-IT** [comment]
--authuser2 with Exchange 2019 IMAP fails – "NO AUTHENTICATE"

Description:

Hi,

I'm attempting to use imapsync to migrate mail from an external provider to an on-premises Microsoft Exchange 2019 server.

I'm trying to authenticate using the --authuser2 option (admin account with full access to all mailboxes), as described in the documentation.

Command example:

```
imapsync \
  --host2 exchange.example.local \
  --user2 user@example.com \
  --authuser2 admin@example.com \
  --password2 ADMINPASS \
  --justlogin
```
Result:


```
Host2 failure: Error login on [exchange.example.local] with user [user@example.com] auth [LOGIN]: 2 NO AUTHENTICATE
What I checked:
```

- IMAP is enabled and working on Exchange 2019
- Admin user (admin@example.com) has FullAccess to all mailboxes via Add-MailboxPermission
- Set-ImapSettings -LoginType PlainTextLogin is configured
- IMAP is available via SSL on port 993
- TLS certificate is valid and matches the FQDN
- Direct IMAP login with individual user credentials works fine
- Admin login to own mailbox also works fine

Expected behavior:

IMAP login with --authuser2 should allow proxy login to target mailboxes when FullAccess is granted – as confirmed by previous users with Exchange 2016 and 2019.

Actual behavior:

Exchange responds with:

`NO AUTHENTICATE`
even though all known configuration steps have been applied.

Question:

Is there any known limitation or change in Exchange 2019 that prevents authuser2 proxy login from working?

Are there additional Exchange settings required to support this?

If Exchange cannot support proxy IMAP auth, is there a supported alternative for use with imapsync (e.g., EWS or MAPI)?

Thanks in advance!

**Comment by gilleslamiral** [comment]
The strange thing about 

> ```
> imapsync \
>   --host2 exchange.example.local \
>   --user2 user@example.com \
>   --authuser2 admin@example.com \
>   --password2 ADMINPASS \
>   --justlogin
> ```
> 
> Result:
> 
> ```
> Host2 failure: Error login on [exchange.example.local] with user [user@example.com] auth [LOGIN]: 2 NO AUTHENTICATE
> ```


is that --authuser2  normally uses PLAIN instead of LOGIN so I don't understand the issue, there is some inconsistency here

**Comment by Ekinci-IT** [comment]
But where is the inconsistence?
i've checked all (certificate, plantextlogin, user and adminname and password).

Any ideas?

Here a log from last try:
`Here is imapsync 2.303 ./imapsync on host imapsync, a linux system with 2.1/3.8 free GiB of RAM, 11.97% used by processes.
with Perl 5.38.2 and Mail::IMAPClient 3.43
Transfer started at Donnerstag 08 Mai 2025-05-08 13:23:20 +0000 UTC
PID is 31150 my PPID is 1112
Log file is LOG_imapsync/2025_05_08_13_23_20_302__user_example_com.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
Load is 0.00 0.01 0.00 1/160 on 4 cores
Real user id is localuser (uid 1000)
Effective user id is localuser (euid 1000)
$RCSfile: imapsync,v $ $Revision: 2.303 $ $Date: 2025/02/24 15:52:54 $
Command line used, run by /usr/bin/perl:
./imapsync --host2 mail.example.com --user2 user@example.com --authuser2 admin@example.com --password2 MASKED --authmech2 PLAIN --ssl2 --justlogin
Current directory is /home/localuser
Temp directory is /home/localuser/tmp ( to change it use --tmpdir dirpath )
Creating temp directory /home/localuser/tmp
kill -QUIT 31150 # special behavior: call to sub catch_exit
kill -TERM 31150 # special behavior: call to sub catch_exit
kill -INT 31150 # special behavior: call to sub catch_reconnect
kill -HUP 31150 # special behavior: call to sub catch_print
kill -USR1 31150 # special behavior: call to sub toggle_sleep
Logging to a logfile by default. To turn off logging, use --nolog
File /home/localuser/tmp/imapsync.pid does not exist
PID file is /home/localuser/tmp/imapsync.pid ( to change it, use --pidfile filepath ; to avoid it use --pidfile "" )
Writing my PID 31150 in /home/localuser/tmp/imapsync.pid
Writing also my logfile name in /home/localuser/tmp/imapsync.pid : LOG_imapsync/2025_05_08_13_23_20_302__user_example_com.txt
Modules version list ( use --no-modulesversion to turn off printing this Perl modules list ):
Authen::NTLM         1.09
CGI                  Not installed
Compress::Zlib       2.207
Crypt::OpenSSL::RSA  0.33
Digest::HMAC_MD5     1.04
Digest::HMAC_SHA1    1.04
Digest::MD5          2.58_01
Digest::SHA          6.04
Encode               3.19
Encode::IMAPUTF7     1.05
File::Copy::Recursive 0.45
File::Spec           3.88
Getopt::Long         2.54
HTML::Entities       3.81
IO::Socket           1.52
IO::Socket::INET     1.52
IO::Socket::INET6    2.73
IO::Socket::IP       0.4101
IO::Socket::SSL      2.085
IO::Tee              0.65
JSON                 4.10
JSON::WebToken       0.10
LWP                  6.76
MIME::Base64         3.16_01
Mail::IMAPClient     3.43
Net::Ping            2.76
Net::SSLeay          1.94
Term::ReadKey        2.38
Test::MockObject     1.20200122
Time::HiRes          1.9775
Unicode::String      2.10

Info: will resync flags for already transferred messages. Use --noresyncflags to not resync flags.
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host2: SSL default mode is like --sslargs2 "SSL_verify_mode=0", meaning for host2 SSL_VERIFY_NONE, ie, do not check the server certificate.
Host2: Use --sslargs2 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the server certificate. of host2
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use PLAIN authentication on host2
Host1: imap connection timeout is 120 seconds
Host2: imap connection timeout is 120 seconds
Host1: imap connection keepalive is on on host1. Use --nokeepalive1 to disable it.
Host2: imap connection keepalive is on on host2. Use --nokeepalive2 to disable it.
Host2: IMAP server [mail.example.com] port [993] user [user@example.com]
Host2: connecting and login on host2 [mail.example.com] port [993] with user [user@example.com]
Host2 IP address: 10.0.0.1 Local IP address: 10.0.0.100
Host2 banner: * OK The Microsoft Exchange IMAP4 service is ready.
Host2 capability before authentication: IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+ AUTH
Host2: mail.example.com says it has CAPABILITY for AUTHENTICATE PLAIN
Host2 info: authmech [PLAIN] user [user@example.com] authuser [admin@example.com] IsUnconnected []
Host2 failure: Error login on [mail.example.com] with user [user@example.com] auth [PLAIN]: 2 NO AUTHENTICATE failed.
Host2: failed login on [mail.example.com] with user [user@example.com] auth [PLAIN]
++++ Listing 1 errors encountered during the sync ( avoid this listing with --noerrorsdump ).
Err 1/1: Host2 failure: Error login on [mail.example.com] with user [user@example.com] auth [PLAIN]: 2 NO AUTHENTICATE failed.
The most frequent error is ERR_AUTHENTICATION_FAILURE_USER2. Check the credentials for user@example.com.
Exiting with return value 162 (EXIT_AUTHENTICATION_FAILURE_USER2) 1/50 nb_errors/max_errors PID 31150
Removing pidfile /home/localuser/tmp/imapsync.pid
Log file is LOG_imapsync/2025_05_08_13_23_20_302__user_example_com.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )
`

**Comment by gilleslamiral** [comment]
> --authuser2 normally uses PLAIN instead of LOGIN so I don't understand the issue, there is some inconsistency here

That's not true, I checked the code of the Perl module Mail::IMAPClient
https://metacpan.org/release/PLOBBES/Mail-IMAPClient-3.43/source/lib/Mail/IMAPClient.pm
and --authuser2 doesn't use PLAIN by default. Do no confusion was in your issue, only in my mind...

That said, all my knowledge about Exchange is in the FAQ
https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt
and it comes from users, I never uses Exchange, so I'm quite not the best person to debug this.

Reading FAQ.Exchange.txt about your issue, I noticed this:
````
======================================================================
Q. For Exchange I have double and triple checked the username and
   password spelling but I still get a "LOGIN failed". Any clue?


R1. Disable double-step authentication, also known as 2-factor,
    2-step authentication on the Azure/Active Directory portal.

R2. Microsoft introduced something called "security defaults" which is
enabled by default for new tenants. One of the rules blocks IMAP
access as of imapsync.  The funny thing is that you can't disable
single rules of this security package without buying additional
licenses.  Switching the whole thing off allows the login.

Also, disable double-step authentication on the Azure/Active Directory
portal.

See here:
https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults
Thanks to Stephan Buhre for this R2 answer.

R3. I want to migrate to Exchange 2019. I haven't been able to sync
using admin credentials even if I've tried and made all the
configuration mentioned in the FAQ.Exchange.
The error was always "LOGIN failed".

My problem was that I have been used an admin account which haven't
attached a mailbox in Exchange. This is my admin account which I use
only for configuration in Exchange, not for emails.

So, after I've created in Exchange a mailbox for this user, the sync
started to work.  I can confirm that imapsync is working for Exchange
2019, with plain authentication, and full permissions of admin account
(this account must have mailbox attached) applied to regular user
mailbox account.

It doesn't work with the --authuser2 parameter. The syntax that
works for me is:

  imapsync ... --host2 192.168.xxx.yyy  --user2 domain.local\admin.account\regular.user --password2 "xxxxxxx"
or 
  imapsync ...--host2 192.168.xxx.yyy  --user2 admin.account@mycompany.com\regular.user --password2 "xxxxxxx" 
````

but you said "Admin login to own mailbox also works fine".

So, no clue for now.

**Comment by mega-main** [comment]
Faced with the same problem, everything has been checked several times. It turned out that the second IMAP service was not running, you need to check if the MSExchangeIMAP4 and MSExchangeIMAP4BE services are running. After launching the second service (MSExchangeIMAP4BE), the authorization started working.
