### ISSUE TITLE
IBM Domino/Notes Admin Access

### ISSUE THREAD

**Issue by aledr** [imapsync/imapsync#139]
Hi!

Is it possible to use admin access on Domino?

Thanks.

**Comment by gilleslamiral** [comment]
Hi Alexandre,

Nobody has reported me yet that Domino can do admin authentication:
https://imapsync.lamiral.info/FAQ.d/FAQ.Admin_Authentication.txt
But if you find a way I'll be glad to update the FAQs about it.

Imapsync domino related FAQ:
https://imapsync.lamiral.info/FAQ.d/FAQ.Domino.txt

**Comment by aledr** [comment]
Hi Gilles!

I can access other users accounts with an admin account (mine itself) on the webmail or Lotus Notes client.
Also found some tools that can connect as admin on all accounts.
But using  '--authuser[12]'  on imapsync makes it access the 'authuser' mailbox instead of the source/target user.

Thanks.

**Comment by gilleslamiral** [comment]
I'm glad there is a admin account in Lotus Notes, it's a good start.
The problem is how to use it in IMAP?
There are several different methods used by different vendors. 
Is there one for Domino, using IMAP? If yes, which one?

**Comment by gilleslamiral** [comment]
If the admin account can see all users mailboxes in his proper imap hierarchy
then it's also a way to sync those mailboxes using one admin account.
I found this:
https://www.ibm.com/support/knowledgecenter/en/SSKTMJ_8.5.3/com.ibm.help.domino.admin85.doc/H_PROVIDING_IMAP_USERS_WITH_ACCESS_TO_OTHER_MAIL_FILES_OVER_MIDTOPIC_48694537629387271_MIDTOPIC_287396979229484424.html

**Comment by aledr** [comment]
It can't. And SmartCloud support says that this is a know limitation. No chance for IMAP migrations using an admin account.
I'll close the case, thanks!

**Comment by gilleslamiral** [comment]
Thanks Alex for this input.
If Domino is at host1, you might try the second suggestion, accessing all mailboxes at once with just one powerful IMAP user account and syncing only one sub hierarchy at a time, one for each user at host2.

**Comment by aledr** [comment]
According to my tests and the IBM support, it can't be done on the SmartCloud Notes.
I can give you access for test if you want.

**Comment by gilleslamiral** [comment]
No thanks. We're in a dead end for an admin access on this platform.
I've updated the FAQ:
https://imapsync.lamiral.info/FAQ.d/FAQ.Admin_Authentication.txt

Imapsync tips about imap admin authentication.
...
Known imap server software NOT supporting imap admin authentication:

  * Domino Lotus Notes.
  * SmartCloud Notes.
