### ISSUE TITLE
Folders did not sync ...!

### ISSUE THREAD

**Issue by qhayati** [imapsync/imapsync#144]
Hi

I recently moved all of our mailbox from dovcote vto Office 365.

Unfortunately in some of the mail box (1 or 2 mailboxes ) we have problem , they cannot sync all folders, they just synced some folder 3-or 4 folders.

i face with this errors....

i used following command for all of the mailboxes 

@imapsync  --user1 ++++++  --password1  +++++++  --authuser2 ********	--user2 ***** 	--password2 ***** --host1 imap.ourdomain.com --host2 outlook.office365.com --ssl2

Host1 folder [INBOX.Sent] has 17272 messages in total (mentioned by SELECT)
Host2 folder [Sent] has 17245 messages in total (mentioned by SELECT)
Host2 folder [Sent] permanentflags: \Seen \Answered \Flagged \Deleted \Draft $MDNSent
Host1 folder [INBOX.Sent] considering 17272 messages
Host2 folder [Sent] considering 17245 messages
- msg INBOX.Sent/2245 {58835} could not append ( Subject:[RE: Antwort: RE: Antwort: RE: Antwort: RE: Antwort: RE: Antwort: RE: AW: Antwort: AW: Termine Skirunde], Date:["29-Dec-2009 10:36:00 +0100"], Size:[58835] ) to folder Sent: socket closed while reading data from server (4x)
- msg INBOX.Sent/2247 {66440} could not append ( Subject:[RE: Antwort: RE: Antwort: RE: Antwort: RE: Antwort: RE: Antwort: RE: Antwort: RE: AW: Antwort: AW: Termine Skirunde], Date:["29-Dec-2009 10:45:00 +0100"], Size:[66440] ) to folder Sent: socket closed while reading data from server (4x)
- msg INBOX.Sent/3488 {63290} could not append ( Subject:[RE: Don't go there. Hotel Horror Stories!], Date:["06-May-2010 11:26:00 +0200"], Size:[63290] ) to folder Sent: socket closed while reading data from server (4x)
- msg INBOX.Sent/5393 {39635} could not append ( Subject:[[Fwd: The latest from Daniel Edward Craig's blog: Dedicated to ], Date:["28-Jan-2011 12:40:35 +0100"], Size:[39635] ) to folder Sent: socket closed while reading data from server (4x)
DEBUG: IO/Socket/SSL.pm:1184: local error: SSL write error (5)
DEBUG: IO/Socket/SSL.pm:1184: local error: SSL write error (5)
DEBUG: IO/Socket/SSL.pm:1184: local error: SSL write error (5)
DEBUG: IO/Socket/SSL.pm:1184: local error: SSL write error (5)
- msg INBOX.Sent/6393 {342515} could not append ( Subject:[[Fwd: RE: Support MU marketing at newest Facebook game]], Date:["23-May-2011 15:29:54 +0200"], Size:[342515] ) to folder Sent: Error sending '930 APPEND Sent (\Seen) "23-May-2011 15:29:54 +0200" {342515}': Write failed 'Broken pipe'; Error sending '933 APPEND Sent (\Seen) "23-May-2011 15:29:54 +0200" {342515}': Write failed 'Broken pipe'; Error sending '936 APPEND Sent (\Seen) "23-May-2011 15:29:54 +0200" {342515}': Write failed 'Broken pipe'; Error sending '939 APPEND Sent (\Seen) "23-May-2011 15:29:54 +0200" {342515}': Write failed 'Broken pipe'
- msg INBOX.Sent/8105 {40888984} could not append ( Subject:[Date: Tue, 31 Jan 2012 17:52:06 exceeded

DEBUG: IO/Socket/SSL.pm:1184: local error: SSL write error (5)
- msg INBOX.Sent/12202 {562811} could not append ( Subject:[RE: RE: RE: Ihr Fall 87009: Bitte senden Sie uns Ihre Buchungsunterlagen], Date:["03-Dec-2014 13:45:00 +0100"], Size:[562811] ) to folder Sent: Error sending '975 APPEND Sent (\Seen) "03-Dec-2014 13:45:00 +0100" {562811}': Write failed 'Broken pipe'; Error sending '978 APPEND Sent (\Seen) "03-Dec-2014 13:45:00 +0100" {562811}': Write failed 'Broken pipe'; Error sending '981 APPEND Sent (\Seen) "03-Dec-2014 13:45:00 +0100" {562811}': Write failed 'Broken pipe'; Error sending '984 APPEND Sent (\Seen) "03-Dec-2014 13:45:00 +0100" {562811}': W

for "NO Maximum size of appendable message has been exceeded"  i applied  following power shell coomand: 
Set-mailbox -Identity $UPN -MaxReceiveSize 150mb -MaxSendSize 150mb

I tries --ssl1 , --tls1 too ...

much appreciated if you can help

thanks

**Comment by qhayati** [comment]
i cannot skip them . i move all mailboxes, more than 2000. i have problem just on 2 or 3 mailboxes

**Comment by gilleslamiral** [comment]
For the SSL errors, see:
https://imapsync.lamiral.info/FAQ.d/FAQ.SSL_errors.txt
For the maxsize issue, see:
https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt

Don't hesitate to come back upon failure of this reading!

**Comment by gilleslamiral** [comment]
No response, closing issue. Don't hesitate to come back.
