### ISSUE TITLE
Makefile:59: *** empty variable name.  Stop.

### ISSUE THREAD

**Issue by pgera** [imapsync/imapsync#147]
On RHEL 7, any make command (for eg., make install) generates this error with the 1.882 tarball. This is unrelated to the actual functionality of the application, but causes rpm builds to fail due to make install. The line in question is "DIST_PATH ::= dist2/"

**Comment by gilleslamiral** [comment]
Replace all `::=` by `:=`
See https://www.gnu.org/software/make/manual/make.html#Flavors

> Both forms are equivalent in GNU make; however only the ‘::=’ form is described by the POSIX standard (support for ‘::=’ was added to the POSIX standard in 2012, so older versions of make won’t accept this form either).

**Comment by gilleslamiral** [comment]
Same as closed https://github.com/imapsync/imapsync/issues/162
closing.
