### ISSUE TITLE
cpanm command created by the prerequistites script doesn't work properly

### ISSUE THREAD

**Issue by simbalion** [imapsync/imapsync#149]
I asked in #perl on freenode and received a solution:

`22:57 <simbalion> Hi, I use this app that creates a list of dependencies like 'cpanm "thinger:thing foo:baraka etc:andso-on"' meant to be run as a single command but every time I try it only installs the first item... is the syntax wrong or is this a quirk specific to Debian 9?`

`23:01 <Grinnz> don't use double quotes`

`23:01 <Grinnz> each module name should be its own argument`

`23:02 <Grinnz> if you're gonna quote it should be like `cpanm 'Module::Name' 'Module::Name' ...``

`23:07 <simbalion> I see, I will write the author of the app`

I hope that's enough detail :)

and thanks for this amazing tool

**Comment by gilleslamiral** [comment]
Ok. A bug then. The fix is simple anyway. 

Would you prefer a list of cpanm commands like:

    cpanm Foo::bar
    cpanm Blabla::gogo
or like before:

    cpanm Foo::bar Blabla::gogo

**Comment by simbalion** [comment]
Is it not possible to put each module in it's own set of quotes?

Working with the present implementation is a minor inconvenience, at worst, so no hurry.

**Comment by gilleslamiral** [comment]
Don't you know a single Perl module that would need quotes?

**Comment by simbalion** [comment]
Please pardon my ignorance but I'm a complete newb with perl. I've only just started learning Python, my focus is on system administration rather than development. Else I would have offered my own patch for this. You are probably better suited to recommend the appropriate solution than me.

**Comment by gilleslamiral** [comment]
No problem. 
So, as a system administrator, would you prefer a list of cpanm commands like:

     cpanm Foo::bar
     cpanm Blabla::gogo
     ...

or like before:

    cpanm Foo::bar Blabla::gogo ...

**Comment by simbalion** [comment]
Either works really. With a vertical list there's more clicking involved (to copy/paste), but other than that they seem equally helpful.

**Comment by gilleslamiral** [comment]
Ok. I leave it on a single command line

    cpanm Foo::bar Blabla::gogo ...

**Comment by simbalion** [comment]
I saw that in a recent download, and that works well!
