### ISSUE TITLE
Any way to run it as a daemon ?

### ISSUE THREAD

**Issue by pgera** [imapsync/imapsync#150]
Is there any way to keep an IMAP idle connection open (rfc2177), and sync from source to sink whenever a mail comes in ? I currently run an imapsync cronjob every 15 mins, which is acceptable, but seems suboptimal. Is there some elegant way of incorporating this in imapsync ? 

Edit: I found this: https://imapclient.readthedocs.io/en/2.1.0/advanced.html#watching-a-mailbox-using-idle. I can probably hack something quick and dirty with this.

**Comment by pgera** [comment]
Not sure about the details of the idle refc, but it seems more involved than I thought originally. This blog: http://blog.wrouesnel.com/articles/A%20better%20Getmail%20IDLE%20client/ and the related script https://gist.github.com/wrouesnel/6905023 seem like a good starting point though. I'll try it and see how it goes.

**Comment by gilleslamiral** [comment]
Looks complicated in the usage. A thing like:
  login , loop { idle-imapsync/done or relogin if disconnect } 
is a quick way to start with. Directly.

**Comment by gilleslamiral** [comment]
You haven't said what is the purpose or context of running imapsync often.
- Backup? often a bad idea
- Presyncs? often is useless unless data change much but then presync are useless.
- ?

**Comment by pgera** [comment]
The use case is actually a bit silly. The organization for account1 (source) recently stopped allowing automatic store and forwarding or pop3 access due to some data related policy changes. Until now, I used to do everything from account2 (sink, personal gmail) by using the automatic forwarding feature from account1. Gmail also lets you set up the smtp details, so you can also send the email as account1 from gmail. I never had to log in to account1 at all for my workflow. I don't use any local imap clients either. Just the gmail website. After the policy change, I'm using the imapsync cronjob as a workaround.

**Comment by gilleslamiral** [comment]
Ok. It's not silly. 
What's silly is your need to read your new emails more than once every half an hour!
I experimented that reading email on demand, when I want to, is efficient to get free time.
A better method is to not read email at all but I like reading it once in a while so I keep this practice :-)

**Comment by pgera** [comment]
Yes, I wasn't too concerned about getting the email instantly. The cronjob is perfectly fine. I was just wondering about the IDLE based solution as an engineering curiosity. A couple of other points: 

- Are there rate limit considerations to be aware of in running imapsync as a cronjob ? In most cases, it is not really fetching anything, since there isn't that much new mail, but it is still hitting up both the servers every 15 mins. 

- This solution has been working well, but I noticed something. For mail moved this way using imapsync, gmail doesn't show the "signed by" field in the website. I think gmail uses dkim and spf signatures. Does imapsync affect signatures if the message is not modified at all ? I'm not too familiar with the specs on these things. Or will it always fail the signature because the destination address is different ?

**Comment by gilleslamiral** [comment]
> Are there rate limit considerations to be aware of in running imapsync as a cronjob?

I guess that opening and closing a connection every 15 minutes is less consuming than maintaining the connection all time with IDLE.

> Does imapsync affect signatures if the message is not modified at all ?

The response seems to be in the question, isn't it? no modification implies no affect?

**Comment by pgera** [comment]
>The response seems to be in the question, isn't it? no modification implies no affect?

Right, but the SPF signatures are a bit different as they deal with who is allowed to send messages. That is outside the scope of imapsync, but the side-effect is that if you use imapsync, you kind of lose the spf verification features. Essentially, if you sync from A to B, and A receives a message with a bad SPF signature, B will have no way to tell that (from what I can tell).

**Comment by gilleslamiral** [comment]
Ok, rereading your first I start to understand the issue. Like you say, spf is for sending messages, and sending them using smtp. Plus, spf uses only the envelope part of a message, the purpose is to reduce easily forged email header  "From: foo.xxx". 
When imapsync syncs a message, it uses imap and only the body (body here is body+headers) of the message. Imapsync doesn't play with the envelope because there is no envelope in imap. Imapsync uses the credentials to sync directly a mailbox to a mailbox.
I don't know what "signed by" means in Gmail but I guess the fix has to be done there.

**Comment by gilleslamiral** [comment]
To sum up the discussion:
* No way to run imapsync as a daemon, by itself.
* As a solution: run imapsync regularly.
* SPF issue could be solve by imapsync (--pipemess), maybe not.

I'm closing this issue.
