### ISSUE TITLE
Question regarding ongoing "syncs"

### ISSUE THREAD

**Issue by propagare** [imapsync/imapsync#151]
Hello,

My server is still working but I want to sync all accounts to my new one till the original source is gone. How should I do this? Just a cron job? Or do I have to set special options?

Thanks in advance.

**Comment by gilleslamiral** [comment]
Imapsync syncs a mailbox at a time and does only pass at each run. For different mailboxes run different imapsync processes. Resync until the original source is completely unchanged or gone.
For exact syncs see --delete2* options in the README.

**Comment by propagare** [comment]
I successfully used the imapsync loop script once for several accounts. I do not understand your answer. English isn't my first language. 

I try to reformulate my initial question: 
Can I re-run the same imapsync loop conf over and over again (e.g. via cron) or do I need to use one of the options above with my planned setup? Atm I suspect to add --delete2duplicates to my loop script.

**Comment by propagare** [comment]
You are great. Thanks for your clear answers! Have a good day Sir!
