### ISSUE TITLE
 Can't locate File/Copy/Recursive.pm  in @INC

### ISSUE THREAD

**Issue by jasonmcewen** [imapsync/imapsync#153]
When I try to run `./imapsync` I get the following error:

```
Can't locate File/Copy/Recursive.pm in @INC (you may need to install the File::Copy::Recursive module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at ./imapsync line 705.
BEGIN failed--compilation aborted at ./imapsync line 705.
```

I'm on OS X High Sierra.

Any help greatly appreciated!

**Comment by gofaniyi** [comment]
Having the same problem when I try to run `./imapsync`

`Can't locate File/Copy/Recursive.pm in @INC (you may need to install the File::Copy::Recursive module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./imapsync line 705.
BEGIN failed--compilation aborted at ./imapsync line 705.`

I'm also on OS X High Sierra. Any help will be greatly appreciated.

**Comment by gofaniyi** [comment]
@jasonmcewen. The File::Copy::Recursive Perl module is missing. You can run the command below. It solves the current error you getting. 
`sudo apt-get install libfile-copy-recursive-perl`. 

Although running `./imapsync` produces another error. This is shown below.
`Can't locate IO/Socket/SSL.pm in @INC (you may need to install the IO::Socket::SSL module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./imapsync line 714.
BEGIN failed--compilation aborted at ./imapsync line 714.`

**Comment by gilleslamiral** [comment]
Use the Mac binary:
https://imapsync.lamiral.info/dist/imapsync_bin_Darwin

**Comment by gofaniyi** [comment]
@gilleslamiral Thanks for the swift response. I was actually faced with the problem on my Linux server. I was able to resolve all the errors by installing all the following. 

`sudo apt-get install libfile-copy-recursive-perl
sudo apt-get install libio-socket-ssl-perl
sudo apt-get install libio-tee-perl
sudo apt-get install libunicode-string-perl
cpan Mail::IMAPClient
cpan Term::ReadKey
cpan Digest::MD5
cpan Term::ReadKey
cpan IO::Socket::SSL
cpan File::Spec
cpan Digest::HMAC_MD5
cpan Authen::NTLM
cpan Readonly
cpan  Sys::MemInfo
cpan Regexp::Common`

My Imapsync now works like magic. @jasonmcewen I hope this helps. 
@gilleslamiral I will try the library on my Mac. Thanks

**Comment by gilleslamiral** [comment]
Hi!
https://github.com/imapsync/imapsync/blob/master/INSTALL.d/INSTALL.ANY.txt
https://github.com/imapsync/imapsync/blob/master/INSTALL.d/

```
=================================
== Installing imapsync on Unix ==
=================================

There are specific INSTALL files in the imapsync directory INSTALL.d/ 
Those documents are also available at https://imapsync.lamiral.info/INSTALL.d/

- Mac OS X
- FreeBSD
- CentOS
- CPanel
- Debian
- Ubuntu
- AWS EC2
- Online UI like /X

```

**Comment by jasonmcewen** [comment]
Thanks, the Mac OS X build worked fine for me.

**Comment by Abouabdahsk** [comment]
Same issue but on windows. I have it installed but I can't locate it

**Comment by gilleslamiral** [comment]
Have you followed 
https://imapsync.lamiral.info/README_Windows.txt
?
