### ISSUE TITLE
Exchange 2007 folders ending with a space cause a crash due to an Exchange bug

### ISSUE THREAD

**Issue by darkpixel** [imapsync/imapsync#154]
I can duplicate this on multiple user accounts.

Create a handful of folders under your inbox as a test and make sure to create one with a space at the end (like 'TEST ').

It will look like imapsync processes the folder correctly:

```
Folders sizes before the synchronization.
You can remove foldersizes listings by using "--nofoldersizes" and  "--nofoldersizesatend"
but then you will also loose the ETA (Estimation Time of Arrival) given after each message copy.
++++ Calculating sizes of 40 folders on Host1
Host1 folder    1/40 [Contacts]                          Size:         0 Messages:     0 Biggest:         0
Host1 folder    2/40 [Deleted Items]                     Size: 193087487 Messages:  1399 Biggest:  14310400
Host1 folder    3/40 [Deleted Items/INVOICES Sent]       Size:         0 Messages:     0 Biggest:         0
Host1 folder    4/40 [Drafts]                            Size:     13106 Messages:     1 Biggest:     13106
Host1 folder    5/40 [INBOX]                             Size:  16739987 Messages:    19 Biggest:   7632418
Host1 folder    6/40 [INBOX/EOM Reports ]                 Size:  24163582 Messages:     5 Biggest:  15966580
```

...but the next folder will report an error about the socket being closed unexpectedly and the rest of the sync process fails.

It's not an imapsync bug--Exchange logs a vague error about the IMAP service, but I figure it might be something for the documentation.  I'm not sure if it's fixed in newer versions of Exchange--my goal is to migrate everyone off Exchange. ;)

**Comment by darkpixel** [comment]
Here's a better example of another one I just ran into:

```
ost1 folder   25/76 [INBOX/Forecast - Weekly]           Size:  61552788 Messages:   412 Biggest:  18835555
Host1 folder   26/76 [INBOX/redacted]           Size:  45009679 Messages:   272 Biggest:  15256749
Host1 folder   27/76 [INBOX/redacted]                 Size: 797703688 Messages:  1253 Biggest:   6412845
Host1 folder   28/76 [INBOX/Haley Cox]                   Size:    434847 Messages:     6 Biggest:    378426
Host1 folder   29/76 [INBOX/Health Plan ]        Size:         0 Messages:     0 Biggest:         0
Host1 folder   30/76 [INBOX/redacted]               Host1 Folder INBOX/redacted: Could not select: socket closed while reading data from server (4x)
Host1 folder   31/76 [INBOX/redacted]       Host1 Folder INBOX/redacted: Could not select: socket closed while reading data from server (4x)
```

**Comment by darkpixel** [comment]
This is the useless information that Exchange logs:

![screenshot from 2018-10-22 17-15-09](https://user-images.githubusercontent.com/158380/47326559-213fea80-d61e-11e8-983c-fd5b494de45c.png)

Like I said, doesn't appear to be an imapsync error, but it might be something for the FAQ or maybe imapsync could print out a warning with the solution.

**Comment by gilleslamiral** [comment]
To sum up, using another imap tool like Thunderbird or Outlook, change the folder name to exclude the trailing space.

Closing.
