### ISSUE TITLE
Error when running imapsync.pl

### ISSUE THREAD

**Issue by markdewet** [imapsync/imapsync#155]
Hi, 
I'm very new to linux so please bear with me. I have an Ubuntu server 18.04 server with iRedMail installed which includes Roundcube. I installed rcimapsync exactly as per your instructions in the readme, and all seemed to install correctly as I received no errors. However I then set it up  to fetch mail from a remote server as follows:
![image](https://user-images.githubusercontent.com/44492920/47552515-2eeabe00-d905-11e8-8744-2926929903cd.png)
and also added the line in the readme to my crontab but nothing happens at all. Things I did and noted:
1: there is no imapsync.pl in /var/mail as per the crontab line, so I copied the imapsync.pl file into that folder.
2: I tried running the imapsync.pl manually with perl and I get the error "cant lock /var/run/imapsync/imapsync-all.lock at /var/mail/imapsync.pl line 79"
3: I then tried to run imapsync.pl directly from the /plugins/imapsync/bin folder and got the same result as above, namely "cant lock /var/run/imapsync/imapsync-all.lock at /opt/www/roundcubemail-1.3.6/plugins/imapsync/bin/imapsync.pl line 79
I have also noted that there is no /var/run/imapsync/ folder present.
Please can you assist to get this plugin working?
Thanking you,
Mark

**Comment by gilleslamiral** [comment]
There is no "cant lock" string in the imapsync source code. 
Are you sure it's imapsync?

**Comment by markdewet** [comment]
> 
> 
> There is no "cant lock" string in the imapsync source code.
> Are you sure it's imapsync?

My apologies this error is actually for rcimapsync and I incorrectly posted it here. Mt humble apologies

**Comment by gilleslamiral** [comment]
No problem,
I'm happy to learn there is a new concurrent tool out there.

I'll take a look at
https://plugins.roundcube.net/packages/servergurus/rcimapsync

rcimapsync looks  promising since the description is "including a completely rewritten and much more secure imapsync.pl Perl Script". 

I would appreciate to know how imapsync is insecure!

**Comment by gilleslamiral** [comment]
I've seen that
https://github.com/server-gurus/RCimapSync
uses imapsync, the installation mentions `apt-get install imapsync`
So, well, I'm a little disappointed by the "completely rewritten and much more secure" statement.
It's an alternative to the online interface /X
