### ISSUE TITLE
tag without package name pls

### ISSUE THREAD

**Issue by computersalat** [imapsync/imapsync#156]
Hi,
is it possible to create the next (following) tag just with the `version` ?
Cause downloading via `wget` has two different results:
downloading without `content-disposition` will result in:
```
imapsync-1.882.tar.gz
and
imapsync-imapsync-1.882/
```
downloading with `content-disposition` will result in:
```
imapsync-imapsync-1.882.tar.gz
and
imapsync-imapsync-1.882/
```
but it should be like this:
```
imapsync-1.882.tar.gz
and
imapsync-1.882/
```
so if your next tag would be e.g. `1.900`, then
downloading without taking care of `content-disposition` could be achieved with:
```
wget 'https://github.com/imapsync/imapsync/archive/1.900/imapsync-1.900.tar.gz'
```
resulting in:
```
imapsync-1.900.tar.gz
and
imapsync-1.900/
```

**Comment by gilleslamiral** [comment]
Where is it configurable on github?

**Comment by computersalat** [comment]
you define it while creating the tag
```
git tag 2.0.0
```
instead of
```
git tag imapsync-2.0.0
```

**Comment by gilleslamiral** [comment]
Ok, thanks!
I'm not currently the git integrator, Nicolas is. I plan to be, still along with Nicolas.
I leave this open in order to think of it until put in the Makefile.

**Comment by nbebout** [comment]
I will look at this later today.

**Comment by nbebout** [comment]
I added the tag with the new format.
