### ISSUE TITLE
Github priviledges

### ISSUE THREAD

**Issue by gilleslamiral** [imapsync/imapsync#157]
Hi Nicolas,

There is still "No description, website, or topics provided." on top of the page
https://github.com/imapsync/imapsync

I can't edit this part, I guess it's because of too small privileges on this imapsync project. 
Can you fix my privileges or update the topic description?

Thanks in advance!

**Comment by nbebout** [comment]
I set a description and website.  I also increased your privileges, which hopefully will let you change it in the future.  I am not sure what privileges are needed to change those settings.

**Comment by gilleslamiral** [comment]
It worked! I have the edit button now
