### ISSUE TITLE
Mail count difference between two accounts

### ISSUE THREAD

**Issue by tingvold** [imapsync/imapsync#158]
Hi,

I'm in a process where I'm migrating my iCloud/MobileMe account to G-Suite (Gmail).

I'm running from git source, and launch imapsync with the following parameters;

```
./imapsync --host1 $icloud_ipv4 --ssl1 --user1 user --passfile1 pw.icloud --host2 $gmail_ipv4 --ssl2 --user2 user --passfile2 pw.gmail --gmail2 --regextrans2 s,^Archive,LOL,
```

After the initial sync (~15GB of mails), I ran it again, and see the following;

```
[...]
Host1 folder [INBOX] considering 58839 messages
Host2 folder [INBOX] considering 58244 messages
[...]
```

... and no emails are copied, or marked for copy. To make this even more weird, these numbers differ from both "clients" (MailMate on my Mac for the iCloud, webmail via mail.google.com for Gmail);

- iCloud/MailMate for INBOX: 58934
- Gmail/mail.google.com for INBOX: 45379

All the folders I've "sanity checked" thus far, has inconsistent numbers between the four counters (imapsync Host1/Host2 and the two "clients").

Some of the folders have matching numbers on "imapsync Host1" (iCloud) and MailMate, leading me to believe the other discrepancies between iCloud and MailMate are "old" sync-issues (i.e. emails that has been deleted on the server, but not on the client, and for some reason not been synced). It does not explain why imapsync sees far less emails on Host2 (Gmail) compared to Host1 (iCloud), and does nothing about them.

Why Gmail (mail.google.com) shows even fewer emails than imapsync sees on Host2 (Gmail), is also somewhat weird (that their web interface sees less emails than their IMAP interface).

Any thoughts before I start debugging this to oblivion?

**Comment by gilleslamiral** [comment]
Imapync doesn't synchronize duplicates on host1. 
Can you show me the final stats?

**Comment by jallakim** [comment]
```
Host1 Nb messages:          637418 messages
[…]
Host2 Nb messages:          606034 messages
[…]
++++ Statistics
Transfer started on               : Sun Nov 11 01:33:45 2018
Transfer ended on                 : Sun Nov 11 04:05:50 2018
Transfer time                     : 9125.2 sec
Folders synced                    : 110/110 synced
Messages transferred              : 17 
Messages skipped                  : 637390
Messages found duplicate on host1 : 25485
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 0
Messages void (noheader) on host2 : 0
Messages deleted on host1         : 0
Messages deleted on host2         : 0
Total bytes transferred           : 253206401 (241.476 MiB)
Total bytes duplicate host1       : 662188310 (631.512 MiB)
Total bytes duplicate host2       : 0 (0.000 KiB)
Total bytes skipped               : 16603046634 (15.463 GiB)
Total bytes error                 : 111559476 (106.391 MiB)
Message rate                      : 0.0 messages/s
Average bandwidth rate            : 27.1 KiB/s
Reconnections to host1            : 0
Reconnections to host2            : 0
Memory consumption at the end     : 0.0 MiB (started with 214.6 MiB)
Biggest message                   : 55806399 bytes (53.221 MiB)
Memory/biggest message ratio      : 0.0
Start difference host2 - host1    : -31395 messages, -1998484974 bytes (-1.861 GiB)
Final difference host2 - host1    : -31384 messages, -1745318729 bytes (-1.625 GiB)
Detected 5 errors

++++ Listing 5 errors encountered during the sync ( avoid this listing with --noerrorsdump ).
Err 1/5: Host2 Folder FOO/Inbox: Could not select: 33 NO [NONEXISTENT] Unknown Mailbox: FOO/Inbox (now in authenticated state) (Failure)
Err 2/5: - msg […] could not append ( Subject:[…], Size:[55753077] ) to folder […]: Error sending […]: 303 BAD [TOOBIG] Message too large. https://support.google.com/mail/answer/6584#limit
Err 3/5: Could not create folder [FOO/Inbox] from [FOO/Inbox]: 438 NO [ALREADYEXISTS] Folder name conflicts with existing folder name. (Failure)
Err 4/5: - msg […] could not append ( Subject:[…], Size:[55806399] ) to folder […]: Error sending […]: 961 BAD [TOOBIG] Message too large. https://support.google.com/mail/answer/6584#limit
Err 5/5: Host2 Folder FOO/Inbox: Could not select: 1084 NO [NONEXISTENT] Unknown Mailbox: FOO/Inbox (now in authenticated state) (Failure)
```

Error 1, 3 and 5 is because case-insensitive labels at Gmail (Host1 has FOO/INBOX and FOO/Inbox), which I haven't bothered to fix yet.

I hardly believe that I have 25485 duplicate emails. How does imapsync define "duplicate"?

There also seems to be a difference, even when taking the duplicates into consideration. Notice that it finds 637418 emails on Host1, and 606034 on Host2. It finds 25485 duplicates, but there's still 5899 emails "missing" on Host2...

**Comment by jallakim** [comment]
Trying to find two emails that imapsync thinks are duplicate. Maybe `--debug` should show the specific emails that it thinks are duplicate? Currently it only seems to count them, but not actually print something for each duplicate it finds.

I've found a small folder that it thinks has two duplicates;

```
Host1 selected: 157  duplicates: 2
[…]
Host2 folder Lists/Foo selected: 155 messages,  duplicates: 0
```

**Comment by jallakim** [comment]
I see.

`--debugcrossduplicates` doesn't really show anything more in the logs (as far as I can see, at least) -- even if I drop `--debug` and only use `--debugcrossduplicates` it doesn't really print anything about what UIDs are skipped.

Wouldn't `--skipcrossduplicates` only be relevant when copying *from* Gmail? That's not what I'm doing; I'm moving from a normal IMAP server (with "real" folders), to Gmail (which uses "fake" folders, aka labels), so this shouldn't even be what's causing this? (which would explain why nothing is printed when using `--debugcrossduplicates`).

**Comment by gilleslamiral** [comment]
If  `--debugcrossduplicates` doesn't print anything then there is no crossduplicates.
As you suggest `--skipcrossduplicates` is only activated with `--gmail2` alone in more recent releases.

How many messages in folder `FOO/Inbox`?
With no debug option, do you have any "skipped" word in the log ?

**Comment by gilleslamiral** [comment]
So far,

Host1 Nb messages:          637418 messages
Messages transferred              : 17 
Messages skipped                  : 637390
FOO/Inbox has 7 messages
Err 2/5: - msg […] could not append 
Err 4/5: - msg […] could not append

637390 + 17 + 7 +2 = 637416 = 637418  - 2

Imapsync a relatively coherent, only 2 messages are missing from the count.
It can be 2 messages deleted during the sync.
Now I don't explain why more than 5000 are not seen in the duplicates count or on host2.

**Comment by jallakim** [comment]
Yeah, those ~5k emails are the only "worry" I have now.

I added some more debug messages to the code, to see what emails `imapsync` thinks are duplicate.

```
diff --git a/imapsync b/imapsync
index 44011e0..e4eca75 100755
--- a/imapsync
+++ b/imapsync
@@ -1937,6 +1937,7 @@ FOLDER: foreach my $h1_fold ( @h1_folders_wanted ) {
                         $h1_total_bytes_duplicate += $h1_size;
                         $h1_nb_msg_duplicate += 1;
                         $h1_nb_msg_processed +=1 ;
+                       $debug and myprint( "Host1 duplicate message found ( idate: $h1_fir_ref->{$m}->{'INTERNALDATE'} )\n" );
                 }
         }
         my $h1_msgs_duplicate_nb = scalar  @h1_msgs_duplicate  ;
```

Maybe this should be added as a separate debug flag? (could even show more information, such as the subject or similar, so that it's easy to manually check them if-need-be). Maybe something like `--debugduplicates` or similar.

The messages I've looked through so-far, are in fact positive duplicates. Current culprit is probably that I've used `imapfilter` for many years sorting my emails, where I've seen that it some times triggers on the same email twice (i.e. if two instances of it was running, or similar), which probably has caused these duplicates.

Secondly, the difference in email counts between Gmail Webmail and Gmail IMAP, is 100% most likely because Gmail Webmail counts an entire discussion/thread as one count in the list (so a thread of 100 replies would only count as 1 "email").

Do you have any idea of how I should proceed to figure out where/what the missing ~5k emails are?

**Comment by gilleslamiral** [comment]
> Do you have any idea of how I should proceed to figure out where/what the missing ~5k emails are?

Concentrate on a small folder where this issue occurs.

Can you send me a whole log, not compressed, with no debug option, a normal one of a resync.

**Comment by jallakim** [comment]
Do you want the “whole log” for the entire sync (all folders), or on a sync with only one folder where I can find the discrepancy?

**Comment by gilleslamiral** [comment]
You have not found the discrepancy so give me the whole log. 
Let that be a challenge...First to find out what's wrong? Ready?

**Comment by jallakim** [comment]
Just sent the full log to your email.

(Subject: imapsync GitHub-issue #158 log)

**Comment by gilleslamiral** [comment]
Hi Joachim,

There is 6084 crossduplicates found in the log:
```
grep ' is also in Host2 folders ' imapsync_2018_11_17_23_29_46_995_joachim*.txt | wc -l 
6084
```

I leave you the exact count of what happens as an exercise...

**Comment by gilleslamiral** [comment]
Well, imapsync considers some messages as cross-duplicates when it finds them in several different folders on host2. I plan to count them but counting is quickly a mess when all situations considered. 
You can choose the folders where you want to see the only copy with:

    imapsync ... --folderfirst ThisFolder  --folderfirst ThisFolderAlso ...
And also you can choose the folders where you don't want to see the copy with:

    imapsync ... --folderlast ThisFolder  --folderlast ThisFolderToo

Any combination is allowed.

**Comment by strarsis** [comment]
@gilleslamiral: I have a similar issue, but no GMail is used on either sides.
Transfer seems to be successful, but there is still a discrepancy of mail items (including a discrepancy of size), also after subsequent runs.

mail.source should be migrated to mail.target:
````
./imapsync \
      --automap \
      --useheader ALL --addheader \
      --idatefromheader \
      --delete2 --delete2folders \
      --host1 mail.source --user1 source-user --password1 source-password \
      --host2 mail.target  --user2 target-user  --password2 target-password
````

**Comment by gilleslamiral** [comment]
Imapsync doesn't sync duplicates by default.
It's been a decade since I've seen  "--useheader ALL" working! it usually never works.

**Comment by strarsis** [comment]
@gilleslamiral:
I am now using this command with `useuid` and `usecache`:
````
./imapsync \
      --automap \
      --useheader ALL --addheader \
      --useuid --usecache \
      --idatefromheader \
      --host1 source --user1 user1 --password1 password1 \
      --host2 target --user2 user2 --password2 password2
````
And it seems that there is no difference left now after the transfer.

**Comment by gilleslamiral** [comment]
Good!

Option --useuid implies --usecache,  inhibits --useheader and also sync duplicates.
Perfect sync.

**Comment by gilleslamiral** [comment]
Imapsync now presents a more synthetic view of how when the sync at the end.
Example:
```` 
...
The sync looks good, all 2111 identified messages in host1 are on host2.
There are 3 unidentified messages (usually Sent or Draft messages). To sync them add option --addheader
The sync is strict, all 2111 identified messages in host2 are on host1.
Detected 0 errors
````
There's more, since revision 1.950, 2019/07/28, folders sizes are presented per folder from host1 and host2 as well as the differences between them.

I'm closing this thread.
