### ISSUE TITLE
PREFIX=/usr/local

### ISSUE THREAD

**Issue by tobias2k** [imapsync/imapsync#16]
The makefile uses /usr as the default prefix; IMO /usr/local would be a safer default, because most of the mainstream distros reserve /usr for the package manager, while packages installed from source go into /usr/local. AFAIK, it's more common to see packages default to /usr/local when pulled from source control, and distros to change this to /usr when building packages for their repositories.

**Comment by gilleslamiral** [comment]
In 2019, prefix in the Makefile is still

    PREFIX ?= /usr
