### ISSUE TITLE
Can't make install -- error Makefile:72: *** multiple target patterns.  Stop.

### ISSUE THREAD

**Issue by jasgggit** [imapsync/imapsync#162]
HI, I'm trying to install latest build on a Ubuntu 14.04 LTS but I keep getting this error::

root@xpto:~/imapsync# make install
Makefile:72: *** multiple target patterns.  Stop.

I've tried the build 1.836 and that one installs ok.

Regards.
JG

**Comment by gilleslamiral** [comment]
What do you mean by latest build on a Ubuntu 14.04 LTS? After 1.836?

**Comment by gilleslamiral** [comment]
I might be related to
https://github.com/imapsync/imapsync/issues/147

**Comment by jasgggit** [comment]
Sorry if I misunderstood the build number, but I installed using git , I assumed to be the latest.
The 1.836 I downloaded manually from github/releases.
Removed the git installed and unzipped the downloaded one. That one installed correctly and without any error.
Regards and thanks

**Comment by jasgggit** [comment]
Don’t see the correlation, it’s a Ubuntu 14.04, but if you wish I can try revert to a previous backup of the vm and try it.
Let me know, but for now it’s working fine with the 1.836.
Regards.
JG

**Comment by gilleslamiral** [comment]
You're right. Do the commands

     date;uname -a

have a colon in the output?

**Comment by jasgggit** [comment]
Hi, 


root@techbox:~# date;uname -a
Fri Dec 21 06:40:42 WET 2018
Linux techbox.xpto.com 3.13.0-164-generic #214-Ubuntu SMP Wed Dec 5 10:42:33 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Nope.

**Comment by jasgggit** [comment]
Sorry, too early in the morning ...
There is, in the date separator.

**Comment by gilleslamiral** [comment]
I  quote:
https://www.gnu.org/software/make/manual/html_node/Error-Messages.html
>  ‘multiple target patterns. Stop.’ means there are multiple patterns in the target section; 

You had:
    Makefile:72: *** multiple target patterns. Stop.

What I don't understand is that there is no target on line 72, it's a variable affectation:

    HELLO ::= $(shell date;uname -a)

**Comment by mundeez** [comment]
I have the same problem, how was this solved?

**Comment by gilleslamiral** [comment]
Changed ::= to := to be old make than 2012 compatible.

`````
Makefile revision 1.274
date: 2018/11/05 11:16:17;  author: gilles;  state: Exp;  lines: +24 -24
Changed ::= to := to be old make than 2012 compatible.
````

**Comment by goodvibesjumper** [comment]
> Changed ::= to := to be old make than 2012 compatible.
> 
> ```
> Makefile revision 1.274
> date: 2018/11/05 11:16:17;  author: gilles;  state: Exp;  lines: +24 -24
> Changed ::= to := to be old make than 2012 compatible.
> ````
> ```

I needed to replace all the ::= lines with :=  on my Ubuntu 14.04

**Comment by nintox** [comment]
where do i change it from ::= to := ?

**Comment by gilleslamiral** [comment]
Fixed. Closing.
