### ISSUE TITLE
Problem syncing Zarafa to Open-Xchange with admin account.

### ISSUE THREAD

**Issue by ilmarsL** [imapsync/imapsync#164]
Hi, I ran into problem while trying to sync Zarafa to OX using admin account(syncing with user password works fine).
I used the following parameters:
`--host1 www.myZarafaServer.com --user1 "userName" --authuser1 "adminAccount" --password1 "adminPass"  ^
               --host2 www.myOXServer.com  --user2 "user@domain.com" --authuser2 "root" --password2 "rootPass"  ^
               --automap --subscribeall --addheader --idatefromheader` 

For some reason I'm getting the flowing error:
`Host1 failure: Error login on [www.myZarafaServer.com] with user [userName] auth [PLAIN]: 2 NO LOGIN wrong username or password`

Has anyone ever managed to sync from Zarafa using admin credentials?

**Comment by gilleslamiral** [comment]
I don't know if Zarafa can do admin auth via imap but if you find the answer, yes or no and how, I will update the doc FAQ.Admin_Authentication.txt

https://imapsync.lamiral.info/FAQ.d/FAQ.Admin_Authentication.txt
````
It can be useful to authenticate without knowing each user password.
Using an admin account to authenticate is not a standard feature
supported by all imap servers. Sometimes it is implemented via --authuser1
sometimes not. It depends on the server software and its configuration.
You have to figure out what is the imap software server,
find out if it supports an admin account and how, 
if an admin account is actually configured and
finally check an authentication via this admin account for
a standard user.

Known imap server software supporting imap admin authentication:

  * Exchange 2003/2007/2010/2013. See the file FAQ.Exchange.txt
  * Office365. See the file FAQ.Exchange.txt
  * Gmail. See the file FAQ.XOAUTH2.txt
  * Dovecot. See the file FAQ.Dovecot.txt
  * Zimbra. See the file FAQ.Zimbra.txt
  * UW-imap. See the file FAQ.General.txt
  * Cyrus-imap. See the file FAQ.General.txt
  * Sun Java Enterprise System/SunOne/iPlanet. See the file FAQ.General.txt

Known imap server software NOT supporting imap admin authentication:

  * Domino Lotus Notes.
  * SmartCloud Notes.

````

**Comment by gilleslamiral** [comment]
No news. Closing
