### ISSUE TITLE
Trying command when NOT connected! at /usr/local/share/perl/5.22.1/Mail/IMAPClient.pm line 122.

### ISSUE THREAD

**Issue by omlet05** [imapsync/imapsync#165]
Hi,

I'm trying to migrate a big mailbox from a Kerio server to G-Suite.
This mailbox migration is random sometime it connects well or sometimes not.

This time I directly had problems:

> Host1: checking all wanted folders are selectable. Use --nocheckselectable to avoid this check.
> Trying command when NOT connected! at /usr/local/share/perl/5.22.1/Mail/IMAPClient.pm line 122.
> 	Mail::IMAPClient::LastError(Mail::IMAPClient=HASH(0x2d5ba58), "NO not connected") called at /usr/local/share/perl/5.22.1/Mail/IMAPClient.pm line 1545
... on the whole mailbox with a lot of perl errors.

and ending with:

> ++++ Statistics
> Transfer started on               : Thu Jan 10 11:05:35 2019
> Transfer ended on                 : Thu Jan 10 11:18:39 2019
> Transfer time                     : 784.1 sec
> Folders synced                    : 0/0 synced
> Messages transferred              : 0 
> Messages skipped                  : 0
> Messages found duplicate on host1 : 0
> Messages found duplicate on host2 : 0
> Messages void (noheader) on host1 : 0
> Messages void (noheader) on host2 : 0
> Messages deleted on host1         : 0
> Messages deleted on host2         : 0
> Total bytes transferred           : 0 (0.000 KiB)
> Total bytes duplicate host1       : 0 (0.000 KiB)
> Total bytes duplicate host2       : 0 (0.000 KiB)
> Total bytes skipped               : 0 (0.000 KiB)
> Total bytes error                 : 0 (0.000 KiB)
> Message rate                      : 0.0 messages/s
> Average bandwidth rate            : 0.0 KiB/s
> Memory consumption                : 225.8 MiB
> Biggest message                   : 0 bytes (0.000 KiB)
> Memory/biggest message ratio      : NA
> Detected 1 errors

Command used:
`imapsync --logdir=/tmp/imapsync/LOG/ --host1 HOST1 --user1 XXXX --password1 MASKED --ssl1 --host2 imap.gmail.com --port2 993 --user2 XXX@gmail --password2 MASKED --ssl2 --regextrans2 s{Sent$}{[Gmail]/Sent Mail} --regextrans2 s{Sent Items$}{[Gmail]/Sent Mail} --regextrans2 s{Sent Messages$}{[Gmail]/Sent Mail} -
-regextrans2 s{Drafts$}{[Gmail]/Drafts} --errorsmax 999999999 --maxsize 25000000 --exclude Trash|Spam|Drafts|Deleted Items --automap --addheader --buffersize 8192000 --nofolder
sizes 
`

modules version list:
`Modules version list:
Mail::IMAPClient     3.38
IO::Socket           1.38
IO::Socket::INET     1.35
IO::Socket::INET6    2.72
IO::Socket::SSL      2.024
Net::SSLeay          1.72
Compress::Zlib       2.069
Digest::MD5          2.54
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Term::ReadKey        2.33
File::Spec           3.56
Time::HiRes          1.9726
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON                 2.90
JSON::WebToken       0.10
Crypt::OpenSSL::RSA  ?
LWP                  ?
HTML::Entities       3.69
Getopt::Long         2.45
Test::MockObject     1.20150527`

Do you have any ideas of how to fix this error? All other accounts works great. This one is very big and has a lot of attachments.

**Comment by gilleslamiral** [comment]
Try  --nocheckselectable 

    imapsync ... --nocheckselectable

**Comment by omlet05** [comment]
Dear Gilles,

Seems to be fixed. Thanks a lot!
Fighting with this now:
> Failure: lost connection for host2 [imap.gmail.com]: (len=44) socket closed while reading data from server



Regards!

**Comment by gilleslamiral** [comment]
The whole log is better to investigate problems

**Comment by gilleslamiral** [comment]
Fixed and no news. Closing
