### ISSUE TITLE
NO Mailbox isn't selectable

### ISSUE THREAD

**Issue by strarsis** [imapsync/imapsync#167]
@gilleslamiral: `imapsync` reports errors that some folders aren't selectable:
````
Err 1/12: Host1 Folder FolderName: Could not select: 28 NO Mailbox isn't selectable (0.000 + 0.000 secs).
````

The mentioned folders are empty when viewed in Thunderbird.
Also many folders in error list are not even listed in Thunderbird, 
some seem to be a part of an existing folder name, like 'Test' of 'Test-Folder',
but this could also be just coincidence (the user may have created two folders with 
slightly different names in the past or renamed a folder).

**Comment by gilleslamiral** [comment]
A complete listing would better help.

**Comment by strarsis** [comment]
@gilleslamiral: A complete listing would mean the complete (redacted) log?
Or the summary at the end? How can I provide further information?

**Comment by gilleslamiral** [comment]
At least I need the folder listings at the beginning.

**Comment by gilleslamiral** [comment]
No news. Closing.
