### ISSUE TITLE
Option --addheader missing in them

### ISSUE THREAD

**Issue by sirio81** [imapsync/imapsync#173]
Hi, I just built imapsync 1.882 on ubuntu 16.04.
I noticed reading the man that the option --addheader  is missing.

`man imapsync | grep -F -- '--addheader'`

**Comment by sirio81** [comment]
Ops, this is a duplicate of
https://github.com/imapsync/imapsync/issues/80

**Comment by gilleslamiral** [comment]
> Ops, this is a duplicate of
> #80

So I close it
