### ISSUE TITLE
Duplicate folders on Gmail.

### ISSUE THREAD

**Issue by omlet05** [imapsync/imapsync#174]
Dear,

I tried to avoid white space error during a gmail migration and applied --regextrans2 "s/[ ]+/_/g".
Unfortunately I previously already synced some accounts and now i've got duplicate folder like this:
"Foo Bar" and "Foo_Bar". I'm ok to keep all folder with _ but I want to delete all folders with space.

I already try to apply:
--delete2folders but failed because of the --regextrans2 "s/[ ]+/_/g"
--delete2foldersonly "/[ ]/" failed also for the same purpose.

Do you have any idea of how to cleanup messed up account?

**Comment by omlet05** [comment]
I think that I get it. I'm going to run --delete2folders and check for whitespace error after migration.

**Comment by gilleslamiral** [comment]
Gmail accepts white spaces in folders names so the regex to convert all spaces to _ is too strong. But edging white spaces in folders names are still forbidden. Next release will adapt to this when using option `--gmail2 `

I don't understand why --delete2folders doesn't work here.

**Comment by omlet05** [comment]
Sorry Gilles but I can't test anymore.
I ran --delete2folders and kept the whitespace error for now.

**Comment by gilleslamiral** [comment]
To sum up, option` --gmail2` had been changed (release 1.936 might be) to only remove the edging blanks of folders names.

To fix the previous mess, use 
````
imapsync ... --delete2foldersonly "m, ," --delete2foldersbutnot 'm,Gmail,' 
````

Closing this issue.
