### ISSUE TITLE
Gmail Suite app password not working..

### ISSUE THREAD

**Issue by nicmar** [imapsync/imapsync#175]
Hi, I was looking forward to test this app, but when syncing from Amazon workmail to Google Gsuite, it's not working. I have 2FA on the account, so apparently it needs an app password.

First it said this when I used the regular password:
Host2 failure: Error login on [imap.gmail.com] with user [xxx@domain.com] auth [LOGIN]: 2 NO [ALERT] Application-specific password required: https://support.google.com/accounts/

So I created an app password, and used that, and it says:
Host2 failure: Error login on [imap.gmail.com] with user [xxx@domain.com] auth [LOGIN]: 2 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)

I tried to create an app password twice, same issue. Anyone experienced this before?
I'm not sure if there is any other host than imap.gmail.com..

**Comment by nicmar** [comment]
I figured it out, you also need to enable imap access unsecure apps in Google admin panel. Like this:

1. Go to Google Admin Console 
2. Click Security > Basic Settings.
3. Look for Less Secure apps, click Go to settings for less secure apps.
4. Select on Allow users to manage less secure apps
5. Click Save

**Comment by gilleslamiral** [comment]
Thanks for your input!
It's a known issue, documented in the Gmail FAQ
````
https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt
=======================================================================
Q. I can't authenticate with Gmail via IMAP
   and Gmail says "Please log in via your web browser"

R0. My current settings on two Gmail accounts are made
with three steps 0) 1) 2)

0) Login via a web browser to the Gmail account concerned.

1) The 2-step verification is OFF
https://myaccount.google.com/security?hl=en&pli=1&nlr=1#signin

2) Access for less secure apps is turned ON
https://www.google.com/settings/security/lesssecureapps
https://support.google.com/accounts/answer/6010255?hl=en

R1. See Coert Grobbelaar solution:
https://web.archive.org/web/20150906230041/http://security.stackexchange.com/questions/86404/how-do-i-interact-with-google-to-import-email-via-imapsync

R2. I had the same issue one time (mars 2015) logging to Gmail 
with imapsync.
The Gmail imap message error said "Please log in via your web browser"
so I logged for this account via a web browser. Then,
it asked me to receive a code via a mobile, I said yes,
I entered the code and everything went ok on next syncs
with imapsync. 


=======================================================================
````

**Comment by gilleslamiral** [comment]
> @gilleslamiral  I enabled two-factor authentication and then created the password for a third-party apps and was able to log in

Ok. fixed.
