### ISSUE TITLE
Please help Office365 online Archive migration

### ISSUE THREAD

**Issue by pauldavey64** [imapsync/imapsync#177]
I am attempting to back up a office365 account over to a zimbra server.  I have been able to migrate all the main email but I am having an issue dealing with the online archives for each account.

**Comment by gilleslamiral** [comment]
Can you detail your issue?

**Comment by greem** [comment]
Archives aren't available over IMAP:

https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/client-features

IMAP and POP | Not supported

**Comment by gilleslamiral** [comment]
Thanks Graeme!
I close the ticket.

**Comment by pauldavey64** [comment]
Thank you for the info,  
The big problem is our environment has roughly 300 email accounts that need to be backed up and removed from office365,  the config was setup that all email accounts move any email older then 1 year into an online archive.   I was hoping there would have been an option to pull that email as well.

**Comment by pauldavey64** [comment]
I just found this to work well for restoring mail back into the primary accoun t
https://www.u-btech.com/articles/how-to-restore-archive-data-en
