### ISSUE TITLE
Error LOGIN autentication 

### ISSUE THREAD

**Issue by joaolm2** [imapsync/imapsync#178]
Hello.
I am experiencing an unreachable problem while migrating from an email server
Insistentemente error of login in host1, being that I checked password several times, tried with tls, ssl and did not obtain success

Can someone help me, please?

Below the command I'm using with -debug enabled

The migration is zimbra to zimbra. I am using the latest version of imaosync

I also tried to use authentication with the zimbra admin user, but the same error occurs

imapsync --host1 189.89.224.15 --ssl1 --sslargs1 "SSL_verify_mode=0" --user1 miquele_souza@gruponazare.com.br --password1 zaqxswcde --host2 188.138.57.79 --ssl2 --sslargs2 "SSL_verify_mode=0" --user2 miquele_souza@gruponazare.com.br --password2 sm1234 --debugimap1
Here is imapsync 1.939 on host nazare-mail.gruponazare.com.br, a linux system with 0.3/11.6 free GiB of RAM
with Perl 5.16.3 and Mail::IMAPClient 3.37
Transfer started at Tue Jun  4 11:03:47 2019
PID is 29499 my PPID is 29464
Log file is LOG_imapsync/2019_06_04_11_03_47_855_miquele_souza@gruponazare.com.br_miquele_souza@gruponazare.com.br.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
Load is 2.28 2.86 2.76 5/515 on 4 cores
Current directory is /opt/zimbra
Real user id is zimbra (uid 995)
Effective user id is zimbra (euid 995)
$RCSfile: imapsync,v $ $Revision: 1.939 $ $Date: 2019/05/27 21:58:33 $ 
Command line used, run by /usr/bin/perl:
/bin/imapsync --host1 189.89.224.15 --ssl1 --sslargs1 SSL_verify_mode=0 --user1 miquele_souza@gruponazare.com.br --password1 MASKED --host2 188.138.57.79 --ssl2 --sslargs2 SSL_verify_mode=0 --user2 miquele_souza@gruponazare.com.br --password2 MASKED --debugimap1
Temp directory is /tmp ( to change it use --tmpdir dirpath )
kill -QUIT 29499 # special behavior
kill -TERM 29499 # special behavior
kill -INT 29499 # special behavior
kill -HUP 29499 # special behavior
File /tmp/imapsync.pid does not exist
PID file is /tmp/imapsync.pid ( to change it, use --pidfile filepath ; to avoid it use --pidfile "" )
Writing my PID 29499 in /tmp/imapsync.pid
Writing also my logfile name in /tmp/imapsync.pid : LOG_imapsync/2019_06_04_11_03_47_855_miquele_souza@gruponazare.com.br_miquele_souza@gruponazare.com.br.txt
Modules version list:
Authen::NTLM         1.09
CGI                  3.63
Compress::Zlib       2.069
Crypt::OpenSSL::RSA  0.28
Data::Uniqid         0.12
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Digest::MD5          2.52
File::Copy::Recursive 0.38
File::Spec           3.40
Getopt::Long         2.4
HTML::Entities       3.69
IO::Socket           1.34
IO::Socket::INET     1.33
IO::Socket::INET6    2.72
IO::Socket::IP       0.37
IO::Socket::SSL      2.020
IO::Tee              0.64
JSON                 2.59
JSON::WebToken       0.10
LWP                  6.13
Mail::IMAPClient     3.37
Net::Ping            2.38
Net::SSLeay          1.72
Term::ReadKey        2.33
Test::MockObject     1.20120301
Time::HiRes          1.9725
URI::Escape          3.31
Unicode::String      2.09
( use --no-modulesversion to turn off printing this Perl modules list )
Info: will resync flags for already transferred messages. Use --noresyncflags to not resync flags.
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host1: SSL default mode is like --sslargs1 "SSL_verify_mode=0", meaning for host1 SSL_VERIFY_NONE, ie, do not check the certificate server.
Host1: Use --sslargs1 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the certificate server of host1
Host2: SSL default mode is like --sslargs2 "SSL_verify_mode=0", meaning for host2 SSL_VERIFY_NONE, ie, do not check the certificate server.
Host2: Use --sslargs2 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the certificate server of host2
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connection timeout is 120 seconds
Host2: imap connection timeout is 120 seconds
Host1: IMAP server [189.89.224.15] port [993] user [miquele_souza@gruponazare.com.br]
Host2: IMAP server [188.138.57.79] port [993] user [miquele_souza@gruponazare.com.br]
Host1: connecting and login on host1 [189.89.224.15] port [993] with user [miquele_souza@gruponazare.com.br]
Connecting with IO::Socket::SSL PeerAddr 189.89.224.15 PeerPort 993 Proto tcp Timeout 120 Debug 1 SSL_cipher_list DEFAULT:!DH SSL_verifycn_scheme imap SSL_verify_mode 0
Connected to 189.89.224.15
Read: 	* OK nazare-mail.gruponazare.com.br Zimbra IMAP4rev1 server ready
Host1 IP address: 189.89.224.15
Host1 banner: * OK nazare-mail.gruponazare.com.br Zimbra IMAP4rev1 server ready
Sending: 1 CAPABILITY
Sent 14 bytes
Read: 	* CAPABILITY IMAP4rev1 AUTH=PLAIN ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ LOGIN-REFERRALS MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST
  	1 OK CAPABILITY completed
Host1 capability before authentication: IMAP4rev1 AUTH=PLAIN ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ LOGIN-REFERRALS MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST
Sending: 2 LOGIN miquele_souza@gruponazare.com.br zaqxswcde
Sent 52 bytes
Read: 	2 NO LOGIN failed
ERROR: 2 NO LOGIN failed at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1364.
	Mail::IMAPClient::__ANON__('2 NO LOGIN failed\x{d}\x{a}') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1400
	Mail::IMAPClient::_get_response('Mail::IMAPClient=HASH(0x2276540)', 2, undef) called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1326
	Mail::IMAPClient::_imap_command_do('Mail::IMAPClient=HASH(0x2276540)', 'LOGIN miquele_souza@gruponazare.com.br zaqxswcde') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1225
	Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x2276540)', 'LOGIN miquele_souza@gruponazare.com.br zaqxswcde') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 583
	Mail::IMAPClient::login('Mail::IMAPClient=HASH(0x2276540)') called at /bin/imapsync line 5291
	main::authenticate_imap('Mail::IMAPClient=HASH(0x2276540)', 189.89.224.15, 993, 'miquele_souza@gruponazare.com.br', undef, 'zaqxswcde', 1, 120, 0, ...) called at /bin/imapsync line 5252
	main::login_imap(189.89.224.15, 993, 'miquele_souza@gruponazare.com.br', undef, 'zaqxswcde', 1, 120, 0, 1, ...) called at /bin/imapsync line 1539
ERROR: 2 NO LOGIN failed at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1274.
	Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x2276540)', 'LOGIN miquele_souza@gruponazare.com.br zaqxswcde') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 583
	Mail::IMAPClient::login('Mail::IMAPClient=HASH(0x2276540)') called at /bin/imapsync line 5291
	main::authenticate_imap('Mail::IMAPClient=HASH(0x2276540)', 189.89.224.15, 993, 'miquele_souza@gruponazare.com.br', undef, 'zaqxswcde', 1, 120, 0, ...) called at /bin/imapsync line 5252
	main::login_imap(189.89.224.15, 993, 'miquele_souza@gruponazare.com.br', undef, 'zaqxswcde', 1, 120, 0, 1, ...) called at /bin/imapsync line 1539
Host1 failure: Error login on [189.89.224.15] with user [miquele_souza@gruponazare.com.br] auth [LOGIN]: 2 NO LOGIN failed
Exiting with return value 16
Log file is LOG_imapsync/2019_06_04_11_03_47_855_miquele_souza@gruponazare.com.br_miquele_souza@gruponazare.com.br.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )

**Comment by joaolm2** [comment]
Hello.
I identified the problem.
Imap was enabled only in the global settings, thus not allowing authenticity for the domain.
After enabling imap in COS, imapsync ran normally

**Comment by gilleslamiral** [comment]
Good!

Please change the password since it is in the log with --debugimap1
Now public...

**Comment by joaolm2** [comment]
Great
After the publication had changed the credentials

Now edit password on post for a generic password

Thanks for listening

**Comment by diegosomar** [comment]
In my case, using dollar symbol in password causes the error `NO Login failed`

**Comment by gilleslamiral** [comment]
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt
```
=======================================================================
              Imapsync issues with passwords on Unix.
=======================================================================


=======================================================================
Q. On Unix, some passwords contain some weird *(),;&~ characters. 
   Login fails.

R1. Enclose the password within single-quotes in the imapsync
    command line:

    imapsync ... --password1 'passw*(),;&rd~'

```
