### ISSUE TITLE
Can imapsync be compiled under alpine?

### ISSUE THREAD

**Issue by belegnar** [imapsync/imapsync#179]

**Comment by gilleslamiral** [comment]
Alpine is a Linux system, I guess Perl is available on it.
Imapsync is a Perl script so it might run under Alpine and also be compiled with the "pp" command.

**Comment by belegnar** [comment]
it is not so easy because perl libs require a lot of `.h` files which are absent or based in unusual places within alpine
compiled `imapsync` is present in packages, but it is not very recent

**Comment by gilleslamiral** [comment]
If you have docker on Alpine then there is a recent imapsync docker image at
https://hub.docker.com/r/gilleslamiral/imapsync/

**Comment by belegnar** [comment]
It's a `debian:stretch` image

**Comment by gilleslamiral** [comment]
Yes but if you have the docker command under Alpine then you can use this docker image as is. It's the docker principle, this imapsync docker image can be run on any system (Linux, Mac, Windows or whatever) that has the docker command installed.

**Comment by belegnar** [comment]
But the issue is about `alpine` docker image. I don't want to start the image in alpine, i'm looking for recent `FROM: alpine` image

**Comment by gilleslamiral** [comment]
Can explicit a little more your goal and your context?
As I understand it until now is that you want to make an imapsync binary and embed it under an Alpine docker image? Is that right?

**Comment by belegnar** [comment]
I just want this code works with fresh version of `imapsync`
```
FROM alpine:3.8
RUN imapsync --version
```

**Comment by gilleslamiral** [comment]
Help yourself. First try to have imapsync on a guenuine Alpine, then on a docker Alpine.
Follow:
https://imapsync.lamiral.info/INSTALL.d/INSTALL.ANY.txt
````
===============================================================
               Installing imapsync on other Unixes
===============================================================

Purchase imapsync at
https://imapsync.lamiral.info/
or get it anywhere.

You have access to a compressed tarball called imapsync-1.xxx.tgz
where 1.xxx is the version number. Untar the tarball where
you want:

  cd 
  tar xzvf  imapsync-1.xxx.tgz

Go into the directory imapsync-1.xxx

  cd imapsync-1.xxx

You can easily detect any missing Perl modules via the 
script prerequisites_imapsync located in the INSTALL.d directory:

  sh INSTALL.d/prerequisites_imapsync

or 

  cd INSTALL.d/
  sh prerequisites_imapsync

You don't need to be root to run the previous command. You have
to be root if you want the Perl modules to be available for the 
whole system, for all users.

You may be in one of following cases: 
- you are not root.
- you are in a environment where modifying system Perl 
  modules can break other things or where you're not allowed to
  change the whole system.

The "make" command is a prerequisite to build some Perl modules.
Install make in case it is not already installed.

Run the "cpanm" command with the missing Perl modules as arguments.
For example it can be:

  cpanm Authen::NTLM Data::Uniqid File::Copy::Recursive IO::Tee Mail::IMAPClient Unicode::String

Once you've run the "cpanm" command, you can rerun "sh prerequisites_imapsync" 
to verify everything is ok:

  sh prerequisites_imapsync 

When everything is ok the script execution ends with this sentence
"All needed modules are already installed"

Now imapsync should work on your system. To check it run:

  ./imapsync --testslive
````

**Comment by belegnar** [comment]
No way to work, because there are a lot of `.h` files absent in alpine

**Comment by gilleslamiral** [comment]
So you say it yourself: no way.
(Why ask then?)

**Comment by belegnar** [comment]
Because there is alpine package of imapsync, but not very recent. I'm not very familiar with perl scripts and dependecies, so i'm looking for a manual, how imapsync may be compiled within alpine image

**Comment by gilleslamiral** [comment]
There is no more dependency between imapsync 1.882 (Alpine imapsync) and 1.921 (Github imapsync) so it should be strait to go from one to the other. just replace it.

**Comment by belegnar** [comment]
But it should be compiled in alpine. I can't just replace alpine binary 1.882 with debian binary 1.921

**Comment by gilleslamiral** [comment]
A Perl script is not a binary. I doubt that Alpine imapsync is a binary. Show me it is

**Comment by gilleslamiral** [comment]
Digging a little into Alpine and its imapsync package I found that imapsync under Alpine seems not compiled. The log of the build says:
https://build.alpinelinux.org/buildlogs/build-edge-x86_64/community/imapsync/imapsync-1.882-r0.log
````
...
mkdir -p /home/buildozer/aports/community/imapsync/pkg/imapsync/usr/bin
install imapsync /home/buildozer/aports/community/imapsync/pkg/imapsync/usr/bin/imapsync
chmod 755 /home/buildozer/aports/community/imapsync/pkg/imapsync/usr/bin/imapsync
...
````
No compilation there, just a copy of the imapsync file script to /usr/bin/imapsync
I'm thinking that you haven't understood very well your context, your needs and your purpose yet.
Plenty of room to learn here.
