### ISSUE TITLE
--delete2duplicates fails when host1 dies in the process

### ISSUE THREAD

**Issue by dddns** [imapsync/imapsync#180]
Howdy,
Imapsync, so great tool!

I've found, i believe something to improve, using: --delete2duplicates to prevent duplicates in destination host.
case 1 works fine, case 2 doesn't.
i could also be doing something wrong, but it also may need some improvement, here's the command:

imapsync --addheader --host1=192.168.69.222 --user1 cxxxxxxxx@xx.pt --password1='a.1976' --host2 192.168.69.223 --user2 cxxxxxxxx@xx.pt --password2='a.1976' --delete2duplicates

Case 1:
- if the account on host2 for some reason get's full, due to lower quota than host1 or other reason, and if i run the command again, imapsync deletes the duplicates on host2.

Case 2:
- if during the process host1 dies, imapsync will exit due to the connection reset by peer/not running nothing in port 143, but if i run the command again, imapsync doesn't delete the duplicates in host2

**Comment by gilleslamiral** [comment]
Hi!
Well it's surprising since imapsync is stateless and duplicates on host2 are independent of host1.
Or aren't they with imapsync?
Can you confirm and show me a log of a next run that fails to remove duplicates?

**Comment by gilleslamiral** [comment]
No news. Closing.
