### ISSUE TITLE
whitespaces in folder names

### ISSUE THREAD

**Issue by diginfo** [imapsync/imapsync#188]
Hi;

How can I specify a folder that includes whitespaces ?? - I have browsed through the issues, faq and documentation, but I can't seem to find an answer.

```
--folder "my Folder"
--folder "'my Folder'"
--folder "my\sFolder"
--folder "my\x20Folder"
```

I am sure it must be documented somewhere, but I have spent at least 30 minutes looking for it :-)

**Comment by gilleslamiral** [comment]
On Windows:

    --folder "my Folder"

On Linux:

    --folder "my Folder"

or 

    --folder 'my Folder'
