### ISSUE TITLE
Examples of incremental backup

### ISSUE THREAD

**Issue by 5u623l20** [imapsync/imapsync#190]
Can you share an example of incremental backup of Mailboxes in the FAQs/README/DOCS?

**Comment by gilleslamiral** [comment]
What do you mean exactly by incremental backup? 
Can you give me an example behavior?

Imapsync does incremental syncs by default. Next runs only sync differences between the source and destination accounts.

**Comment by 5u623l20** [comment]
I meant an one-way backup of the imap accounts once everynight. In case of any hardware failure or data lost. In case of hardware failure I can modify the DNS to point to this imap server and everything is up and running with little loss.

> What do you mean exactly by incremental backup?
> Can you give me an example behavior?
> 
> Imapsync does incremental syncs by default. Next runs only sync differences between the source and destination accounts.
This is exactly what I wanted to know. Only problem is if the user changes their password. :(

**Comment by gilleslamiral** [comment]
An exact sync is your goal:

    imapsync ... --delete2 --delele2folders
