### ISSUE TITLE
Weird Problem with cron and emails

### ISSUE THREAD

**Issue by mindrunner** [imapsync/imapsync#192]
I am facing a strange problem. I am running imapsync with cron every hour. I have two different jobs running:
![screenshot_20190921_162923](https://user-images.githubusercontent.com/1413542/65379868-01c99b80-dc8d-11e9-8a06-9a5eab4841fc.png)

The first script syncs a gmail account to a dovecot server. The second script mirors this to another server in a webhosting mailbox.
![screenshot_20190921_163058](https://user-images.githubusercontent.com/1413542/65379909-7ac8f300-dc8d-11e9-88fb-85eb1f2f03ac.png)

Both do work fine. If I run them manually, I can see the whole log in stdout as I would expect.

The cron daemon is configured to send me the stdout of the tasks in an email, which is working fine with all Jobs, except the one mirroring from Gmail.

So, I think, it cannot be cron or the server, becuase generally emails are coming through.
Then, I cannot be imapsync in general, because the other job is doing great.

So, what is it then? Maybe related to the fact, that I use gmail? Sounds super odd, but it's the only thing I see right now.

Any thoughts?

**Comment by gilleslamiral** [comment]
> So, I think, it cannot be cron or the server,

please, reconsider this point of view.
Why?

Well, even I'm experienced sysadmin,  I still struggle with cron, 25 years after I started to deal with it... 

First, it NEVER works the first time I put a script in cron, even it works on the command line. Permissions, environment variable, default behavior, some star * * * not well counted, time, to name possible issues.

By default, cron sends an email only on failure of a script. Could it be this?

**Comment by mindrunner** [comment]
Yeah, i totally get what you mean and agree on those cron behaviors you are experiencing.

> By default, cron sends an email only on failure of a script. Could it be this?

`Exiting with return value 0 (EX_OK: successful termination)`
Is what I get from the other imapsync job. So I suppose it should always send emails.

I am setting`MAILTO=my@em.ail` explicitly as the first line of my crontab to enable the email sending. I am on Arch Linux and have `core/cronie` as my cron daemon installed. But I also think, this thread should probably in some other bugtracker.

**Comment by mindrunner** [comment]
Alright... Totally not related to imapsync, but I post the answer here for reference just in case someone else finds this ticket here.

Cron opens the connection to the mailserver as soon as the first output by the run command is generated. On very long running tasks, this can lead to several problems and thus, no mail is sent. An easy solution is to buffer the output with `sponge` which can be found in `moreutils`.
