### ISSUE TITLE
Debian 10 Buster support?

### ISSUE THREAD

**Issue by myvesta** [imapsync/imapsync#194]
Is there any plan to support Debian 10 Buster?

**Comment by gilleslamiral** [comment]
The installation process is exactly the same as Debian 9:
See https://imapsync.lamiral.info/INSTALL.d/INSTALL.Debian.txt

**Comment by myvesta** [comment]
Before I posted this ticket I thought I can try with Deb9 steps... ehhh... sorry because I didn't :)
Glad to see it's already compatible.
Thanks for updating readme file.

**Comment by gilleslamiral** [comment]
> Before I posted this ticket I thought I can try with Deb9 steps... ehhh... sorry because I didn't :)

I then did it and wandered what could be wrong since it worked like a charm...
That's ok anyway
