### ISSUE TITLE
File::Tail Dependency missing in documentation

### ISSUE THREAD

**Issue by MyFriendlyUserName** [imapsync/imapsync#197]
**Environment:** 
Docker / Ubuntu:Latest

**Steps taken:**
1. `docker container run -it ubuntu`
2. `cd /opt`
3. `apt update && apt install git`
4. `git clone https://github.com/imapsync/imapsync`
5. `cd imapsync/`
6. `apt-get install <all dependencies from https://github.com/imapsync/imapsync/blob/master/INSTALL.d/INSTALL.Ubuntu.txt>`
7. `cpanm Mail::IMAPClient`
8. `./imapsync --testslive`

Error message:

> Can't locate File/Tail.pm in @INC (you may need to install the File::Tail module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./imapsync line 840.
> BEGIN failed--compilation aborted at ./imapsync line 840.

After installing the dependency via `cpanm File::Tail` everything works fine.

Can you please update the documentation?

Thanks!

Regards,
Thomas

**Comment by gilleslamiral** [comment]
https://imapsync.lamiral.info/INSTALL.d/INSTALL.Ubuntu.txt
is ok so next github publishing will fix that.

**Comment by MyFriendlyUserName** [comment]
Thank you!
