### ISSUE TITLE
Possibility to sync recurring and delete messages older than x-days?

### ISSUE THREAD

**Issue by typoworx-de** [imapsync/imapsync#200]
I would like to integrate imapsync as alternative to getmail in ISPconfig. Getmail somehow 'sucks' as it produces duplicate messages on target-mailbox.

I'm searching for a feature that is able to clean-up (delete) messages being older than a given time of days to clean-up the source IMAP account after sync. I did not found a feature like that yet - but is it possible somehow?

It would work similary to ```--delete``` flag, but wait the given number of days in age for e-mails until they are deleted.

**Comment by gilleslamiral** [comment]
To sync messages older that 365 days and delete them after a successful sync, use:

    imapsync ... --minage 365 --delete1

If you need to also sync the other messages, then run a normal call after or before.
