### ISSUE TITLE
Flag problem running ImapSync

### ISSUE THREAD

**Issue by mthld** [imapsync/imapsync#201]
Hi,

I'm encountering a strange problem with ImapSync when I try to sync two mailboxes.
I believe it's related to a flag issue, that ImapSync doesn't strip and that is incompatible with the destination server:

```
Host1: flags init msg INBOX/37210 date ["09-Jun-2015 16:16:11 +0200"] flags [\Indexed \Seen] size [20156]
Host1: flags filt msg INBOX/37210 date ["09-Jun-2015 16:16:11 +0200"] flags [\Indexed \Seen] size [20156]
- msg INBOX/37210 {20156} could not append ( Subject:[=?ISO-8859-15?Q?Dossier_n=B02015117440_/__R=E9f?=], Date:["09-Jun-2015 16:16:11 +0200"], Size:[20156], Flags:[\Indexed \Seen] ) to folder INBOX: Error sending '17 APPEND INBOX (\Indexed \Seen) "09-Jun-2015 16:16:11 +0200" {20156}': 17 BAD Error in IMAP command APPEND: Invalid system flag \INDEXED (0.001 + 0.000 secs).
```

Thanks in advance for your help.
Best,

**Comment by mthld** [comment]
FYI I tried following what is written in [the FAQ](https://github.com/imapsync/imapsync/blob/master/FAQ.d/FAQ.Flags.txt), as running it with the option:
```
--regexflag 's/\\FORWARDED|\\Indexed|\\ATTACHED//gi'
```

But that doesn't help, I get this other error:
```
Unrecognized escape \I passed through in regex
```

Thanks,

**Comment by gilleslamiral** [comment]
It looks like a quoting issue. The arguments

    imapsync ...  --regexflag 's/\\Indexed//gi'

are a example of a shell syntax to invoke imapsync. In result, imapsync process should receive 

    imapsync ... --regexflag s/\\Indexed//gi

without the quotes since they are removed by the shell. 
I wonder how you ended up with the quotes inside imapsync, did you use

    "imapsync ...  --regexflag 's/\\Indexed//gi'"

or similar?

**Comment by mthld** [comment]
Hi @gilleslamiral 

Merci beaucoup pour ton aide !
The problem was indeed caused by the quotes. In fact, ImapSync is running inside a Docker container, which is part of [the Mailcow distribution](https://github.com/mailcow/mailcow-dockerized).

To make it work options should be added like this:
```
--regexflag=s/\\Indexed//gi
```

Without spaces, without quotes.
