### ISSUE TITLE
Ignore already synced but moved or deleted messages?

### ISSUE THREAD

**Issue by Netstat64** [imapsync/imapsync#203]
i presynced a mailbox and the user started to play around with it, on host2.
He moved a few messages from the Inbox to a subfolder (deleted them).

When i rerun the sync, all messages that the user moved to the subfolder, will be synced again.
Is it possible to check if the Message already exist anywhere else (subfolders) and ignore them?

right now i just want to sync the new incomming mails, so im using --folder "INBOX" 
Is this the reason why it ignores the subfolders, while checking for already existing mails?

**Comment by gilleslamiral** [comment]
> Is it possible to check if the Message already exist anywhere else (subfolders) and ignore them?

Yes but it's not a panacea for all situations. 
Sync both folders INBOX and Trash and add --skipcrossduplicates --folderlast INBOX, like this:

    imapsync ... --folder INBOX --folder Trash --skipcrossduplicates --folderlast INBOX

A better way to ignore moves on host2 is to do to use --delete1 instead, quoting
https://imapsync.lamiral.info/FAQ.d/FAQ.Migration_Plan.txt

````  
...
 * Do a postsync. A postsync is a sync with the following options 
   --maxage 1 --delete1 --folder INBOX

   This postsync will move the last new messages arrived on host1 to
   host2 during the TTL interval and delete them on host1. Do not use
   the option --delete2 in a postsync.
````
