### ISSUE TITLE
Add throttle / slow down option ? 

### ISSUE THREAD

**Issue by masbaehr** [imapsync/imapsync#204]
Hi, is there a way i could intentionally slower the whole procedure? Like just a few mails / second max.  I'd like to save some CPU credits on an EC2 instance.

**Comment by gilleslamiral** [comment]
There is a way, several ways, to limit imapsync transfers, either by bytes/s or messages/s.

https://imapsync.lamiral.info/README

````
  OPTIONS/behavior

     --maxmessagespersecond int : limits the number of messages transferred per second.

     --maxbytespersecond int : limits the average transfer rate per second.
     --maxbytesafter     int : starts --maxbytespersecond limitation only after
                               --maxbytesafter amount of data transferred.

     --maxsleep      int : do not sleep more than int seconds.
                           On by default, 2 seconds max, like --maxsleep 2
````

**Comment by masbaehr** [comment]
Okay - thanks that will suffice! Sorry i didn'T read the readme correctly i was searching for "throttle"  :/

**Comment by gilleslamiral** [comment]
Thanks for your feedback, I will add throttle in the REAME!

**Comment by masbaehr** [comment]
Thanks. If you do - could you also write some sentence about how the value can be specified ? e.g i've found this info on the site where it says you can specify it like 20_000 which was not something very obvious

https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt

**Comment by gilleslamiral** [comment]
You can also 20000

**Comment by 50m-0m** [comment]
Сосите хуй
