### ISSUE TITLE
Exiting with return value 8 (EXIT_PID_FILE_ERROR)

### ISSUE THREAD

**Issue by alfabravo-git** [imapsync/imapsync#205]
Ciao.
When two users run imapsync on the same server (CentOS 7) with two different users, the second receives this error:

_Could not open /tmp/imapsync.pid for writing. Check permissions or disk space: Permission denied
Exiting with return value 8 (EXIT_PID_FILE_ERROR)_

To avoid conflict, can the _--pidfile_ switch be the right way?

Thanks a lot.
AB

**Comment by gilleslamiral** [comment]
Yes, use --pidfile to avoid the conflict. You can even use an empty string `""` if you don't use the pid file.

  imapsync ...  --pidfile ""

**Comment by alfabravo-git** [comment]
Thanks a lot.
