### ISSUE TITLE
INSTALL.Darwin.txt and location of imapsync_bin_Darwin

### ISSUE THREAD

**Issue by richardgmcmahon** [imapsync/imapsync#206]
Hello,

I suggest that location of imapsync_bin_Darwin is added to INSTALL.Darwin.txt and/or it is added to the github repo

i.e. https://imapsync.lamiral.info/dist/imapsync_bin_Darwin

Thanks

**Comment by gilleslamiral** [comment]
Ok,

Updated upstream for the next release:
https://imapsync.lamiral.info/INSTALL.d/INSTALL.Darwin.txt
