### ISSUE TITLE
does not login gmail account

### ISSUE THREAD

**Issue by cheney-yan** [imapsync/imapsync#214]
Version: 1.983

Commandline: 
```
    imapsync \
    --host1 imap.gmail.com --user1 email1 --password1 'pass1' \
    --host2 imap.gmail.com --user1 email2 --password1 'pass2' 
```
And it prints out 
```
Host1: Will just connect to imap.gmail.com without login
...
Host2: Will just connect to imap.gmail.com without login
```

Also tried using `--gmail1` option and the same result.

I think it is more of the combination of paramters but I could not figure out where is wrong. Could you please help?

**Comment by gilleslamiral** [comment]
>     imapsync \
>     --host1 imap.gmail.com --user1 email1 --password1 'pass1' \
>     --host2 imap.gmail.com --user1 email2 --password1 'pass2'

It lacks --user2
Fix:

````
imapsync \
    --host1 imap.gmail.com --user1 email1 --password1 'pass1' \
    --host2 imap.gmail.com --user2 email2 --password2 'pass2' 
````

**Comment by cheney-yan** [comment]
Aha, how can I ignore this! My bad. Thanks @gilleslamiral
