### ISSUE TITLE
Switches for 365 (--office1 and --office2)

### ISSUE THREAD

**Issue by alexkuc** [imapsync/imapsync#222]
Hello!

My use case. Transfer emails from generic imap server (3rd party) to Microsoft 365. Currently, I am in testing phase so everything I run is on dummy / fake accounts. I was able to transfer to emails without using `--office2`.

My question: is it necessary to use `--office2` for my use case or not? I didn't run into any issues described in  [FAQ.Exchange.txt](https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt).

**Comment by gilleslamiral** [comment]
> My question: is it necessary to use `--office2` for my use case or not?

No
>  I didn't run into any issues described in [FAQ.Exchange.txt](https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt).

Good! 
The important thing is that you what to do in case you encounter them
