### ISSUE TITLE
issue with --pidfile "" and --nolog

### ISSUE THREAD

**Issue by mmuyskens** [imapsync/imapsync#225]
Hello,

I'm passing --pidfile "" and --nolog and it doesn't appear to be working correctly;

Here is imapsync 1.977 on host my.host.com, a linux system with 1.6/7.6 free GiB of RAM
with Perl 5.16.3 and Mail::IMAPClient 3.37
Transfer started at Mon Jul  6 21:36:54 2020
PID is 16913 my PPID is 16911
Log file is LOG_imapsync/2020_07_06_21_36_54_253__.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
Load is 0.09 0.15 0.17 1/517 on 8 cores
Current directory is /var/tmp/imapsync_cgi/f3fe531fc772ae891c45e326eedca8a14c21401f
Real user id is imapsync (uid 1022)
Effective user id is imapsync (euid 1022)
$RCSfile: imapsync,v $ $Revision: 1.977 $ $Date: 2019/12/23 20:18:02 $ 
Command line used, run by /usr/bin/perl:
/usr/bin/imapsync --pidfile "" --nolog --user1 source@email.com --password1 MASKED --host1 localhost --user2 destination@email.com --password2 MASKED --host2 localhost
Temp directory is /var/tmp/imapsync_cgi/f3fe531fc772ae891c45e326eedca8a14c21401f ( to change it use --tmpdir dirpath )
Under cgi context
Umask set with 0077 (was 0022)
REMOTE_ADDR is 1.2.3.4
REMOTE_HOST is 1.2.3.4
HTTP_REFERER is https://host.com/
HTTP_USER_AGENT is Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
SERVER_SOFTWARE is software 11.88.0.11
SERVER_PORT is 2083
HTTP_COOKIE is cookies=enabled; timezone=America/Los_Angeles
kill -QUIT 16913 # special behavior: call to sub catch_exit
kill -TERM 16913 # special behavior: call to sub catch_exit
kill -INT 16913 # special behavior: call to sub catch_reconnect
kill -HUP 16913 # special behavior: call to sub catch_print
kill -USR1 16913 # special behavior: call to sub toggle_sleep
File /var/tmp/imapsync_cgi/f3fe531fc772ae891c45e326eedca8a14c21401f/imapsync.pid does not exist
Error reading file /var/tmp/imapsync_cgi/f3fe531fc772ae891c45e326eedca8a14c21401f/imapsync.pid : No such file or directory
PID file is /var/tmp/imapsync_cgi/f3fe531fc772ae891c45e326eedca8a14c21401f/imapsync.pid ( to change it, use --pidfile filepath ; to avoid it use --pidfile "" )
Writing my PID 16913 in /var/tmp/imapsync_cgi/f3fe531fc772ae891c45e326eedca8a14c21401f/imapsync.pid
Writing also my logfile name in /var/tmp/imapsync_cgi/f3fe531fc772ae891c45e326eedca8a14c21401f/imapsync.pid : LOG_imapsync/2020_07_06_21_36_54_253__.txt
Info: will resync flags for already transferred messages. Use --noresyncflags to not resync flags.
Exiting after a justconnect on host(s):  
Exiting with return value 0 (EX_OK: successful termination) 0/20 nb_errors/max_errors
Log file is LOG_imapsync/2020_07_06_21_36_54_253__.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )

**Comment by gilleslamiral** [comment]
In CGI context, there is no way to change the pidfile and the logfile, the options are ignored.

**Comment by mmuyskens** [comment]
If it's ignored, any idea why it is dying? That's the full output. The sync doesn't actually occur.

**Comment by gilleslamiral** [comment]
Is it imapsync 1.977 unchanged?
It looks like the host values are not passed.

**Comment by mmuyskens** [comment]
Correct - completely unmodified. I actually was using an older version prior and updated prior to  opening this issue. The older version actually said that host1 wasn't being passed, but Command line used actually shows it. Is there any sort of debug flags that I can use that would assist with this?

**Comment by gilleslamiral** [comment]
> Command line used actually shows it. 
> Is there any sort of debug flags that I can use that would assist with this?

The goal and the context should help
Are you writing some visual interface and some wrapper script that calls imapsync with options?

**Comment by mmuyskens** [comment]
It's essentially a cPanel integration - a PHP script that calls imapsync directly using shell_exec.

**Comment by gilleslamiral** [comment]
Ok. You're using imapsync as a command line but via a web server so it act as a cgi while it shouldn't.

2 solutions at least:

- Use the command:

`     SERVER_SOFTWARE=0    imapsync --user1 foo ...`

or 

- Edit imapsync, search "sub under_cgi_context" and replace "return 1" by "return 0" in it

The former solution is more sustainable than the second

**Comment by mmuyskens** [comment]
Excellent! SERVER_SOFTWARE=0 did the trick! I really appreciate your assistance!
