### ISSUE TITLE
How to bulk massively (10 users) with IMAPSYNC

### ISSUE THREAD

**Issue by vicentematus** [imapsync/imapsync#226]
First, thank you so much Gilles. You saved my life.

Second, i have to migrate 18 mails in total, which 8 are from a specific domain, and the other 10 are from another domain. My question is how do i make the file to bulk parallel users?, [checked the documentation](https://imapsync.lamiral.info/FAQ.d/FAQ.Massive.txt). And i have some questions:

The old emails are from a cPanel IMAP server (Horde) and we want to transfer to Gmail. So you have can have an idea.

Is this format right? (just an example)
`imap.example.com;user@example.com;123456;imap.gmail.com;user@gmail.com;123456;`

And should i repeat this format for every mail?

After that, how should i run the script in Linux to iterate every user?

Thanks Gilles.

**Comment by gilleslamiral** [comment]
The format you present is ok, An file example is:
https://imapsync.lamiral.info/examples/file.txt

Run this input file in a shell with this script:
https://imapsync.lamiral.info/examples/sync_loop_unix.sh

Those files are also in the tarball.

https://imapsync.lamiral.info/#DOC_MASS

**Comment by gilleslamiral** [comment]
Thanks for closing!

**Comment by vicentematus** [comment]
Sorry for the  4 year delay lol. I solved the migration with your help 🫡
