### ISSUE TITLE
Imapsync with maxage or without age limit not working

### ISSUE THREAD

**Issue by danykallery** [imapsync/imapsync#238]
I am trying to sync from one of the old server to new infrastructure and both are using Zimbra servers.

I had done this with one server and it worked well but second server onwards I need to add maxage 1700 but getting the following error.

Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1771.
Use of uninitialized value $h2_msgs[0] in hash slice at /usr/bin/imapsync line 1772.
Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1806.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.
Host1 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
Host1 Archiv/ size 0 ignored (no wanted headers so we ignore this message. To solve this: use --addheader)
Use of uninitialized value $h2_msgs[0] in hash slice at /usr/bin/imapsync line 1860.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.
Host2 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
Host2 Archiv/ size 0 ignored (no wanted headers so we ignore this message)
Folder    2/12 [Archiv/Gesendet]                   -> [Archiv/Gesendet]
Host1 folder [Archiv/Gesendet] has 4877 messages in total (mentioned by SELECT)
Host2 folder [Archiv/Gesendet] has 0 messages in total (mentioned by SELECT)
Host1 folder [Archiv/Gesendet] considering 1 messages
Host2 folder [Archiv/Gesendet] considering 1 messages
Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1771.
Use of uninitialized value $h2_msgs[0] in hash slice at /usr/bin/imapsync line 1772.
Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1806.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.
Host1 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]

-----------------------------------------------------------
Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1771.
Use of uninitialized value $h2_msgs[0] in hash slice at /usr/bin/imapsync line 1772.
Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1806.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.
Host1 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
Host1 RSS-Feeds/ size 0 ignored (no wanted headers so we ignore this message. To solve this: use --addheader                                                                                                     )
Use of uninitialized value $h2_msgs[0] in hash slice at /usr/bin/imapsync line 1860.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.
Host2 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
Host2 RSS-Feeds/ size 0 ignored (no wanted headers so we ignore this message)
Folder   12/12 [Sent]                              -> [Sent]
Host1 folder [Sent] has 663 messages in total (mentioned by SELECT)
Host2 folder [Sent] has 1467 messages in total (mentioned by SELECT)
Host1 folder [Sent] considering 1 messages
Host2 folder [Sent] considering 1 messages
Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1771.
Use of uninitialized value $h2_msgs[0] in hash slice at /usr/bin/imapsync line 1772.
Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1806.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.
Host1 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
Use of uninitialized value $h2_msgs[0] in hash slice at /usr/bin/imapsync line 1860.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.
Host2 uid  no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
- msg Sent/ S[0] F[] I[] has RFC822.SIZE null!
- msg Sent/ skipped.
++++ End looping on each folder
++++ Statistics
Transfer started on               : Sun Oct  4 20:35:07 2020
Transfer ended on                 : Sun Oct  4 20:35:46 2020
Transfer time                     : 39.7 sec
Folders synced                    : 12/12 synced
Messages transferred              : 0
Messages skipped                  : 12
Messages found duplicate on host1 : 0
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 4
Messages void (noheader) on host2 : 10
Messages deleted on host1         : 0
Messages deleted on host2         : 0
Total bytes transferred           : 0 (0.000 KiB)
Total bytes duplicate host1       : 0 (0.000 KiB)
Total bytes duplicate host2       : 0 (0.000 KiB)
Total bytes skipped               : 0 (0.000 KiB)
Total bytes error                 : 0 (0.000 KiB)
Message rate                      : 0.0 messages/s
Average bandwidth rate            : 0.0 KiB/s
Memory consumption                : 368.5 MiB
Biggest message                   : 0 bytes (0.000 KiB)
Memory/biggest message ratio      : NA
Detected 0 errors

Adding my Imapsync script below.

/usr/bin/imapsync  --nofoldersizes  --skipsize  --syncinternaldates --search --maxage 1700 --ssl1 --nosyncacls --subscribe --host1 $host1 --authuser1 email@email.de --password1 MASKED --user1 $oldmailid --host2 $host2 --user2 $newmailid --authuser2 email@email.de --password2 MASKED --ssl2 --split1 100 --split2 100 --errorsmax 2000 --exclude '(?i)\b(Junk|Spam|Drafts|Trash|Deleted|Journal|Notes|Tasks|Outbox|Calendar|Contacts)\b' --useheader 'Message-Id' >> $statuslog

**Comment by gilleslamiral** [comment]
Remove --search


Nota bene: https://imapsync.lamiral.info/FAQ.d/FAQ.Zimbra.txt
...
Please, don't follow
https://wiki.zimbra.com/wiki/Guide_to_imapsync
It's obsolete and it will give you, and me, more difficulties than 
doing a standard sync without additional options.

**Comment by danykallery** [comment]
Thank you so much @gilleslamiral that was a perfect solution and now it works!.

**Comment by gilleslamiral** [comment]
Thanks too!
