### ISSUE TITLE
imapsync seems to have a folder depth limit

### ISSUE THREAD

**Issue by ianw1974** [imapsync/imapsync#242]
I have multiple sub-folders, and it seems imapsync only goes as deep as 2 folders.  Is there a way to specify folder depth, or support going deeper than just 2 folders?

For example, I have (indents showing sub-folder):

```
Folder 1
  Folder 2
    Folder 3
```

Folder 1 and Folder 2 synced.  But there is no Folder 3.  All emails have valid headers, so it's not because a message is missing header info.

**Comment by gilleslamiral** [comment]
Imapsync has no folder depth limit. 
Can you show me log?

**Comment by ianw1974** [comment]
I should have probably checked that first.  It copied, the problem was roundcube webmail didn't automatically show folders higher than a depth of two.  I had to go into folder settings in roundcube and enable folders at a depth of 3 or higher.

This could be useful info to anyone who might encounter this.

**Comment by guysoft** [comment]
@ianw1974 How are you searching in roundcube?
I also have an issue with imapsync not showing certain emails, and I am not sure because they are not in a deep folder, or if imap is not getting all files.

**Comment by ianw1974** [comment]
@guysoft check the imapsync log files, but I expect everything is fine here.  Better is go into the roundcube settings as mentioned in the folder settings.  Then you can set the folder depth, as I believe it defaults to 2.  If there are no errors in the imapsync logs, then chances are all the emails are there, just roundcube is the problem.
