### ISSUE TITLE
Outlook.com: "--minage" parameter not working on "Sent" folder

### ISSUE THREAD

**Issue by heinrich-ulbricht** [imapsync/imapsync#243]
My goal is to sync old messages from outlook.com and the `--minage` parameter does allow exactly that. Good.

Using the `--minage` parameter I could sync old messages from my _Inbox_. Good. 

What did NOT work was the _Sent_ folder. No messages were synced at all. When I removed the `--minage` parameter the folder would sync.

As a workaround I tried the following IMAP search: `--search "SENTBEFORE 31-Dec-2013"` - with the same negative result. No messages were synced from the `Sent` folder.

As another workaround I tried this IMAP search: `--search "BEFORE 31-Dec-2013"`. Now this did sync messages. And from your FAQ I learned that this does not use the `Date:` header of emails but the internal IMAP server date. (By the way the `Date:` header is present and looks fine on all emails.)

All in all this does not look like a problem with imapsync but with outlook.com. I'm creating this ticket nevertheless to provide some Google juice and to maybe get feedback from you or others who have more experience with imapsync or outlook.com than I do.

(tested with imapsync 1.977)

**Comment by gilleslamiral** [comment]
I have a the account gilles.lamiral@outlook.com and I checked the following with two runs with SENTBEFORE and a different date. The selected messages are different and correspond to the messages in the Sent folder so I couldn't reproduce your issue.
Can you you me the log of the same command line?
```
imapsync ... --folder Sent --search "SENTBEFORE 31-Dec-2013" --debugimap
and 
imapsync ... --folder Sent --search "SENTBEFORE 31-Dec-2014" --debugimap
```

**Comment by heinrich-ulbricht** [comment]
Ok I swear I saw what I was seeing. Unfortunately I cannot reproduce it exactly since I already removed the messages. I tested with some recent ones and also `--search "SENTBEFORE 31-Dec-2020"` - it works as expected. Either it was a cloud hiccup or I did something wrong.

Thanks for looking into this. It seems the problem is gone just by doing so...
