### ISSUE TITLE
Synchronizing from Gmail via --gmail1: add --regextrans2 for "[Google Mail]"

### ISSUE THREAD

**Issue by heinrich-ulbricht** [imapsync/imapsync#244]
Synching from Gmail creates _[Google Mail]_ sub-folders in the destination, at least for my account. This might not be desired.

Looking at the [FAQ](https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt) it seems that the `--gmail1` parameter already contains a `--regextrans2 "s,\[Gmail\].,,"` which gets rid of _[Gmail]_ sub-folders. I suggest adding `--regextrans2 "s,\[Google Mail\].,,"` as well since this is basically the same use case.

Note: I have an old Gmail account from the time where Google wasn't allowed to call its service _Gmail_ in Germany but had to resort to _Googlemail_. This changed in 2012. I assume that only German Google accounts from before 2012 are affected. And while writing this I wonder if it's worth the effort. No hard feelings if this ticket gets closed.

**Comment by gilleslamiral** [comment]
>  And while writing this I wonder if it's worth the effort.

I feel the same. You're the first to report it for now.
