### ISSUE TITLE
No tag or release for version 1.977

### ISSUE THREAD

**Issue by mtalexander** [imapsync/imapsync#251]
There isn't a tag for release 1.977.  This means that attempts to fetch a tarball for the source for that release using the version number, for example using

~~~
https://github.com/imapsync/imapsync/tarball/imapsync-1.977
~~~

don't work.  There also isn't a GitHub release for that version, but I don't care about that so much.  The absence of a tag makes it difficult to update the MacPorts port file to that version.

**Comment by gilleslamiral** [comment]
I guess it's full related to the issue: https://github.com/imapsync/imapsync/issues/156

**Comment by gilleslamiral** [comment]
Is it possible to add this tag via github on the current release?

**Comment by nbebout** [comment]
I will look at this and #156 later today.

**Comment by nbebout** [comment]
Tag added.
