### ISSUE TITLE
[cgi:error] AH01215

### ISSUE THREAD

**Issue by mmomasters** [imapsync/imapsync#252]
[cgi:error] AH01215: imapsync: CGI::param called in list context from imapsync line 9435, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/local/share/perl5/CGI.pm line 414

**Comment by mmomasters** [comment]
fixed

**Comment by gilleslamiral** [comment]
How fixed?

**Comment by mmomasters** [comment]
It was only a warning with version imapsync,v 1.727
