### ISSUE TITLE
auth [LOGIN]: 2 NO LOGIN failed

### ISSUE THREAD

**Issue by aitemat** [imapsync/imapsync#255]
Hi everyone,
I have an error with Imapsync when I run the script .bat, then it notification error. 
The script I run : sync_loop_windows.bat
Please help me.

> ( use --no-modulesversion to turn off printing this Perl modules list )
Info: will resync flags for already transferred messages. Use --noresyncflags to not resync flags.
Host1: probing ssl on port 993 ( use --nosslcheck to avoid this ssl probe )
Host1: sslcheck detected open ssl port 993 so turning ssl on (use --nossl1 --notls1 to turn off SSL and TLS wizardry)
Host2: probing ssl on port 993 ( use --nosslcheck to avoid this ssl probe )
Host2: sslcheck detected open ssl port 993 so turning ssl on (use --nossl2 --notls2 to turn off SSL and TLS wizardry)
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host1: SSL default mode is like --sslargs1 "SSL_verify_mode=0", meaning for host1 SSL_VERIFY_NONE, ie, do not check the certificate server.
Host1: Use --sslargs1 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the certificate server of host1
Host2: SSL default mode is like --sslargs2 "SSL_verify_mode=0", meaning for host2 SSL_VERIFY_NONE, ie, do not check the certificate server.
Host2: Use --sslargs2 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the certificate server of host2
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connection timeout is 120 seconds
Host2: imap connection timeout is 120 seconds
Host1: IMAP server [mail.xyz.com] port [993] user [aitemat@xyz.com]
Host2: IMAP server [test.xyz.com] port [993] user [aitemat@test.xyz.com]
Host1: connecting and login on host1 [mail.xyz.com] port [993] with user [aitemat@xyz.com]
Host1 IP address: 103.113.82.6
Host1 banner: * OK IceWarp 12.2.1.0 x64 IMAP4rev1 Wed, 02 Dec 2020 16:35:20 +0700
Host1 capability before authentication: IMAP4rev1 AUTH=DIGEST-MD5 AUTH=CRAM-MD5 AUTH=NTLM AUTH=GSSAPI SORT THREAD=ORDEREDSUBJECT UIDPLUS QUOTA ACL NAMESPACE CHILDREN IDLE ID UNSELECT METADATA X-ICEWARP-SERVER X-MOVE MSEARCH XLIST CREATE-SPECIAL-USE X-ICEWARP-PRIVATEBUSY X-ICEWARP-PROVISIONS X-ICEWARP-CHANGEPASSWORD X-ICEWARP-DIAL X-ICEWARP-CONDSTORE LOGINDISABLED AUTH THREAD
Host1: success login on [mail.xyz.com] with user [aitemat@xyz.com] auth [LOGIN]
Host2: connecting and login on host2 [test.xyz.com] port [993] with user [aitemat@test.xyz.com]
Host2 IP address: 103.113.81.26
Host2 banner: * OK The Microsoft Exchange IMAP4 service is ready.
Host2 capability before authentication: IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+ AUTH
Host2 info: authmech [LOGIN] user [aitemat@test.xyz.com] authuser [] IsUnconnected []
Host2 failure: Error login on [test.xyz.com] with user [aitemat@test.xyz.com] auth [LOGIN]: 2 NO LOGIN failed.
Exiting with return value 16 (EXIT_AUTHENTICATION_FAILURE) 1/50 nb_errors/max_errors
Disconnecting from host1 mail.xyz.com user1 aitemat@xyz.com
Log file is LOG_imapsync/2020_12_02_16_35_18_797_aitemat@xyz.com_aitemat@test.xyz.com.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )
==== Ended imapsync from --host1 mail.xyz.com --user1 aitemat@xyz.com to --host2 test.xyz.com --user2 aitemat@test.xyz.com ====

**Comment by gilleslamiral** [comment]
First thanks to have upgraded imapsync and solved the first IceWarp authentication issue.
For the next authentication failure with Exchange, see 
https://imapsync.lamiral.info/FAQ.d/FAQ.Authentication_failure.txt
and
https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt
...
IMAP access to an Exchange account is not always allowed by default so it has to be allowed in the server configuration part.
https://docs.microsoft.com/en-us/exchange/enable-imap4-in-exchange-2013-exchange-2013-help
Also read
http://clintboessen.blogspot.com/2018/03/binding-certificate-breaks-imap-or-pop.html

**Comment by aitemat** [comment]
Hi @gilleslamiral ,
I follow the guide of you, but it continues to login fail.
Is there any way to Imapsync authentication port 143?
Thank you

**Comment by aitemat** [comment]
Hi @gilleslamiral ,
I have solved my problem. On file.txt :
`mail.xyz.com;aitemat@xyz.com;P@ssword1;test.xyz.com;test25;P@ssword2;`
uncheck @domain on user exchange mail.
It good work
