### ISSUE TITLE
outlook.com does support IMAP

### ISSUE THREAD

**Issue by creativetags** [imapsync/imapsync#26]
your list of supported servers states outlook.com doesn't support IMAP but they actually do now:

IMAP Server: imap-mail.outlook.com     993     SSL
SMTP Server: smtp-mail.outlook.com     587     TLS

**Comment by gilleslamiral** [comment]
Dear Mark,

My list mention Hotmail.
I'm not aware of that, is Hotmail Outlook.com now?

It looks like this is the case. Hotmail is dead and replaced by Outlook.com.
And Outlook.com looks like Office365, but I'm not sure of that.

I'm going to fix this.
Good news for imapsync and Outlook users.

Le 24/02/2015 17:13, Mark Robinson a écrit :
> your list of supported servers states outlook.com doesn't support IMAP but they actually do now:
>
> IMAP Server: imap-mail.outlook.com 993 SSL
> SMTP Server: smtp-mail.outlook.com 587 TLS
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/26>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by creativetags** [comment]
I believe hotmail, msn and live.com are all outlook.com now and Office 365 is based on Exchange server but the web interface is shares a lot with outlook.com

**Comment by SheepDomination** [comment]
Would you require a mail server for hotmail, I would hope not unlike a conventional domain used for email.

**Comment by gilleslamiral** [comment]
> Would you require a mail server for hotmail? I would hope not unlike a conventional domain used for email.

Hotmail does not require a mail server. Hotmail is a mail server, isn't it?
Maybe I don't understand your question.
