### ISSUE TITLE
EON-IMAP server allows for message body without terminating linefeed

### ISSUE THREAD

**Issue by derekbsnider** [imapsync/imapsync#267]
Hi there,

We're trying to use imapsync to sync between an imap server identified as "EON-IMAP", which seems to allow for message bodies to terminate without a linefeed, such that the fetch request for the body ends with the terminating right bracket at the end of the final data line.

The problem is that the receiving imap server we are using, does not seem to like this, and thus the final line goes missing.

Could we have an optional feature to add a terminating linefeed / CRLF to messages which are missing it?

**Comment by derekbsnider** [comment]
This the (redacted) output from an IMAP FETCH command to the source/legacy imap server:

```
A3 UID FETCH 12345 BODY[]
* 1234 FETCH (FLAGS (\SEEN) UID 12345 BODY[] {604}
X-Eon-Dm: xxxxxxxx.xxxxx.net
Received: by xxxxxxxx.mta.xxxxxxxx.net (EON-PICKUP)
        id xxxxxxxx.xxxxxxxxx.xxxxx; Fri, 17 May 2019 08:45:28 -0700
MIME-Version: 1.0
Content-Type: text/html; charset="UTF-8"
Message-Id: <20190517084528.xxxxxxxx@xxxxxxxx.xxxxx.net>
Date: Fri, 17 May 2019 08:45:28 -0700
From: "Xxxxxxx Xxxxxx" <xxxx@airmail.net>
To: <xxxx@airmail.net>
Subject: Xxxx
X-Eon-Sig: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X-Eip: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

<DIV style="font-family:Arial, sans-serif; font-size:10pt;">Xxxxxxxxx<DIV>Xxxxxxxxx</DIV></DIV>)
A3 OK UID completed
```

**Comment by gilleslamiral** [comment]
Option `--regexmess` to the rescue!

    imapsync ... --regexmess "s{(?<![\n])\z}{\r\n}gxms"

Tell me if it works.

I see you're a coder, so I leave you the understanding as an exercise. Tip: `perldoc perlre`
I'm kidding, just ask if you want to know and learn.

**Comment by derekbsnider** [comment]
Awesome, thank you so much. This did work. I am a coder (mainly C/C++), but have to admit that I'm not all that proficient with perl regular expressions (or even PERL in general).

Thanks again,
-Derek

**Comment by gilleslamiral** [comment]
> This did work. 

Great!
