### ISSUE TITLE
minage and maxage not working

### ISSUE THREAD

**Issue by necouchman** [imapsync/imapsync#27]
I'm finishing up a migration effort (GroupWise to Zimbra) where I used imapsync to migrate stuff.  A few users didn't get everything in their mailbox, either because of a stupid GW setting that limited IMAP to only see 20K items per folder, or because their account on the destination side hit its quota.  So, I'm trying to go back and migrate things from very large folders with many years of e-mail.  Most users have given me a date range that is missing, so I'm trying to use the --minage and --maxage parameters to limit it down to today - end date for min age and today - start date for max age.  However, it seems to be pulling in (and duplicating!) all of the messages, which is leading to some annoyance and frustration as people have to manually remove all of the duplicate instances.  The full command I'm using is below - maybe someone can point out where I have options that might be causing issues for the minage and maxage parameters?  In theory the below command should only migrate e-mails from the INBOX folder that are older than 26 days old and newer than 246 days?

~/bin/imapsync \
  --timeout 0 --maxsize 52428800 --buffersize 52428800 \
  --fastio1 --fastio2 \
  --nofoldersizes --nosyncacls --subscribe --syncinternaldates \
  --noauthmd5 --authmech2 PLAIN \
  --exclude '(?i)\b(Junk|Spam|Trash|Calendar|Tasks)\b' \
  --skipheader 'X-*' \
  --skipheader '^Content-Type' \
  --regexflag 's/\\\\(?!Answered|Flagged|Deleted|Seen|Recent|Draft)[^\s]*\s*//ig' \
  --regextrans2 's,:,-,g' \
  --regextrans2 's,\",'\'',g' \
  --regextrans2 's,\s+(?=/|$),,g' \
  --regextrans2 's,^(Briefcase|Contacts|Emailed Contacts|Notebook|Tasks)(?=/|$), $1 Folder,ig' \
  --regextrans2 's/Sent Items$/Sent/' \
  --host1 old.imap.server --port1 993 --host2 new.zimbra.server --sep1 "/" --prefix1 "" \
  --gwtapp1 "trustedapp" --gwtappkey1 "<app key>" \
  --user1 "Old User" --user2 "Old.User" --password1 "blah" \
  --authuser2 "migration.account@mydomain.com" --password2 blahPassword \
  --regextrans2 's,\",-,g' \
  --regextrans2 's,&AAo-|&AA0ACg-|&AA0ACgANAAo-(?=/|$),,g' \
  --ssl1 --tls2 --authmech1 LOGIN \
  --nofoldersizes --skipsize \
  --search1 "NOT HEADER Sender @lists.mydomain.com" \
  --useheader ALL --delete2duplicates \
  --folder INBOX --minage 26 --maxage 246

**Comment by gilleslamiral** [comment]
Dear Necouchman,

This command line is a big mess.

My advices for the duplicate issue (or any other issue) are:
- start basic, remove any option you don't fully understand, especially all --skipheader and --useheader ALL
- stop playing with real user accounts, they are fully right to complain.
- start with a test account on host2.
- fix the duplicate issue within a simple folder, with for example --folder TEST
- play then with a big account on host1 and still a test account on host2.
- fix all issues encountered on the test account.
- fix the real user accounts, one by one at start, with the good options found with the test account.


Le 04/03/2015 23:54, necouchman a écrit :
> I'm finishing up a migration effort (GroupWise to Zimbra) where I used imapsync to migrate stuff. A few users didn't get everything in their mailbox, either because of a stupid GW setting that limited IMAP to only see 20K items per folder, or because their account on the destination side hit its quota. So, I'm trying to go back and migrate things from very large folders with many years of e-mail. Most users have given me a date range that is missing, so I'm trying to use the --minage and --maxage parameters to limit it down to today - end date for min age and today - start date for max age. However, it seems to be pulling in (and duplicating!) all of the messages, which is leading to some annoyance and frustration as people have to manually remove all of the duplicate instances. The full command I'm using is below - maybe someone can point out where I have options that might be causing issues for the minage and maxage parameters? In theory the below command should only migra
> te e-mails from the INBOX folder that are older than 26 days old and newer than 246 days?
>
> ~/bin/imapsync \
> --timeout 0 --maxsize 52428800 --buffersize 52428800 \
> --fastio1 --fastio2 \
> --nofoldersizes --nosyncacls --subscribe --syncinternaldates \
> --noauthmd5 --authmech2 PLAIN \
> --exclude '(?i)\b(Junk|Spam|Trash|Calendar|Tasks)\b' \
> --skipheader 'X-/' \
> --skipheader '^Content-Type' \
> --regexflag 's/\\(?!Answered|Flagged|Deleted|Seen|Recent|Draft)[^\s]/\s*//ig' \
> --regextrans2 's,:,-,g' \
> --regextrans2 's,\",'\'',g' \
> --regextrans2 's,\s+(?=/|$),,g' \
> --regextrans2 's,^(Briefcase|Contacts|Emailed Contacts|Notebook|Tasks)(?=/|$), $1 Folder,ig' \
> --regextrans2 's/Sent Items$/Sent/' \
> --host1 old.imap.server --port1 993 --host2 new.zimbra.server --sep1 "/" --prefix1 "" \
> --gwtapp1 "trustedapp" --gwtappkey1 "" \
> --user1 "Old User" --user2 "Old.User" --password1 "blah" \
> --authuser2 "migration.account@mydomain.com <mailto:migration.account@mydomain.com>" --password2 blahPassword \
> --regextrans2 's,\",-,g' \
> --regextrans2 's,&AAo-|&AA0ACg-|&AA0ACgANAAo-(?=/|$),,g' \
> --ssl1 --tls2 --authmech1 LOGIN \
> --nofoldersizes --skipsize \
> --search1 "NOT HEADER Sender @lists.mydomain.com" \
> --useheader ALL --delete2duplicates \
> --folder INBOX --minage 26 --maxage 246
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/27>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by necouchman** [comment]
I'll try to reduce it down a little bit and take your suggestions.  The "mess" is mostly what was recommended to me by a company that specializes in migrations to the Zimbra platform, so it isn't stuff I made up or pulled out on my own, it was what they told me to do.  Anyway, I'll see if removing some of those options helps, and will do it to a test account/folder, first.

**Comment by gilleslamiral** [comment]
Hi,

Remove all options but the 6 mandatory ones (-host1 --host2 --user1
--user2 --password1 --password2 ) and let's work together to build a
good imapsync FAQ item with GroupWise as host1. I won't do anything
else myself, even if I play with imapsync and imap servers since 15
years now.

Why?
Less time spent making the job done.

The command line shown suggest those specialists are fake ones on that
part. (No problem with that, I'm a fake on so many things...).

 > I'll try to reduce it down a little bit and take your
 > suggestions. The "mess" is mostly what was recommended to me by a
 > company that specializes in migrations to the Zimbra platform, so it
 > isn't stuff I made up or pulled out on my own, it was what they told
 > me to do. Anyway, I'll see if removing some of those options helps,
 > and will do it to a test account/folder, first.

 > Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/27#issuecomment-77497471>.
 >

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by necouchman** [comment]
Well, I just figured out which option was causing the problem.  It was the --search option - apparently the --search "NOT HEADER Sender @lists.mydomain.com" option was overriding the --minage and --maxage parameters.  Does order of the parameters matter, or will the --search option always override those if both are present?

**Comment by gilleslamiral** [comment]
Hi,

 > Well, I just figured out which option was causing the problem. It
 > was the --search option - apparently the --search "NOT HEADER Sender
 > @lists.mydomain.com" option was overriding the --minage and --maxage
 > parameters. Does order of the parameters matter, or will the
 > --search option always override those if both are present?

I've looked at the code and --search is always done before; and
--search replaces any search by --minage or --maxage, which are
I think an underlying IMAP SEARCH command. If you want both related by a AND
then you have to put both in the --search command. I'm not sure we
can have three, it seems we can.

RFC 3501 - INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4rev1
https://tools.ietf.org/html/rfc3501#section-6.4.4

http://imapsync.lamiral.info/FAQ
=======================================================================
Q. Is there a way we can specify a date range to sync emails?
    If yes, can you please share an example?

R. Yes, with the --search option.

   imapsync ... --search "SENTSINCE 1-Jan-2010 SENTBEFORE 31-Dec-2010"

    Jan
    Feb
    Mar
    Apr
    May
    Jun
    Jul
    Aug
    Sep
    Oct
    Nov
    Dec

=======================================================================



It doesn't solve the duplicate issue you mentioned earlier. How about it?


 > — Reply to this email directly or view it on GitHub
 > <https://github.com/imapsync/imapsync/issues/27#issuecomment-77595991>.

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by necouchman** [comment]
Okay, thanks - that helps a lot.  I'll see about specifying the age + my other search criteria in the search option.

I think the duplicate issue is all related to this.  Here's what I think happened:
- search1 was defined with my criteria, and was identifying a bunch of messages on host1 that needed to be transferred.  search1 was also overriding minage and maxage, which resulted in it transferring all of the messages in a given folder or mailbox on host1 that matched the search criteria, not just the ones in the date range.
- Because search2 and/or search were *not* specified, the minage and maxage parameters were applying to host2, and the search was not applying to host2, which means it was looking for the messages on host2 that matched the minage and maxage parameters - which don't exist.
- The odd mismatch of search logic between search1 and minage/maxage resulted in imapsync transferring everything and not being able to accurately compare host1 messages to host2 messages to detect duplicates.

That's my best guess at this point!

**Comment by gilleslamiral** [comment]
Hi Necouchman,

Sorry for the delay.

It looks like you offer a good explanation.

A possible solution is to ask imapsync to search ALL messages on
host2 while still keeping a different --search1:

   imapsync ... --search2 ALL

As long as you --delete2 is not used it should not delete good
messages on host2. But --delete2duplicates should clean the
duplicates.  Anyway, --dry is a must for this. Or better, a test
account.

 > Okay, thanks - that helps a lot. I'll see about specifying the age +
 > my other search criteria in the search option.  I think the
 > duplicate issue is all related to this. Here's what I think
 > happened:

 >  * search1 was defined with my criteria, and was identifying a bunch
 > of messages on host1 that needed to be transferred. search1 was also
 > overriding minage and maxage, which resulted in it transferring all
 > of the messages in a given folder or mailbox on host1 that matched
 > the search criteria, not just the ones in the date range.
 >
 > * Because search2 and/or search were /not/ specified, the minage and
 >maxage parameters were applying to host2, and the search was not
 >applying to host2, which means it was looking for the messages on
 >host2 that matched the minage and maxage parameters - which don't
 >exist.
 >
 > * The odd mismatch of search logic between search1 and minage/maxage
 >resulted in imapsync transferring everything and not being able to
 >accurately compare host1 messages to host2 messages to detect
 >duplicates.



-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by necouchman** [comment]
Thanks for the additional hints.  I've pretty much finished up the migrations, but will keep this in mind in the future if I have other stuff I need to pull over from our old GroupWise system.

**Comment by gpothier** [comment]
I think it would be a good idea for imapsync to fail when a --maxage / --minage option is given along with a --search option, as in this case it doesn't behave as expected.

**Comment by gilleslamiral** [comment]
Ok. Just added that in the TODO file:
```` 
SUGGESTED 2020_03_02 by https://github.com/gpothier
https://github.com/imapsync/imapsync/issues/27#issuecomment-593425945
Bugfix. Do fail when --minage or --maxage are employed with --search
Or make them be consistent, ie, do an AND between them.
Or at least document the bad current behavior which is that
--search overrides any --minage or --maxage 
````
