### ISSUE TITLE
Remove All problematic flags at once

### ISSUE THREAD

**Issue by sunil-saini** [imapsync/imapsync#270]
Hi Gilles LAMIRAL,

while doing imapsync we are getting flags errors -

`msg INBOX/OUTBOX/669 {304236} could not append ( Subject:[MASKED], Date:["MASKED"], Size:[304236], Flags:[\Indexed \Seen] ) to folder OUTBOX: Error sending '503 APPEND OUTBOX (\Indexed \Seen) "MASKED" {304236}': 503 BAD Error in IMAP command APPEND: Invalid system flag \INDEXED (0.001 + 0.000 secs)`

`msg INBOX/17440 {51576} could not append ( Subject:[MASKED], Date:["MASKED"], Size:[51576], Flags:[\Seen \X-EON-HAS-ATTACHMENT] ) to folder INBOX: Error sending '33 APPEND INBOX (\Seen \X-EON-HAS-ATTACHMENT) "MASKED" {51576...AD Error in IMAP command APPEND: Invalid system flag \X-EON-HAS-ATTACHMENT (0.001 + 0.000 secs).
`

So we added **--regexflag 's/\FORWARDED|\Indexed|\ATTACHED|\RECEIPTCHECKED//gi'** parameter.

But as these un supported flags keep coming and it's not possible to know them all beforehand. So is there any way that we can specify that other than these few flags ( like \Answered \Flagged \Deleted \Seen \Draft $NotJunk ) , ignore all flags while syncing.

**Comment by gilleslamiral** [comment]
I've just updated the imapsync FAQ.Flags.txt document
https://imapsync.lamiral.info/FAQ.d/FAQ.Flags.txt

The last two are your concern
- Removing all problematic flags I've seen so far in one line
- Removing all flags but the standard ones from the IMAP RFC

````
=======================================================================
Q. How to fix this error: BAD Invalid system flag \FORWARDED

R. Filter flag \FORWARDED with --regexflag like this:

On Windows:

  imapsync.exe ... --regexflag "s/\\FORWARDED//gi" 

On Unix:

  imapsync ... --regexflag 's/\\FORWARDED//gi' 

or (on Unix)

  imapsync ... --regexflag "s/\\\\FORWARDED//gi" 

Other related flags to remove are \Indexed and \ATTACHED

Windows:   imapsync.exe ... --regexflag "s/\\Indexed//gi" 
Unix:      imapsync ...     --regexflag 's/\\Indexed//gi' 

Windows:   imapsync.exe ... --regexflag "s/\\ATTACHED//gi" 
Unix:      imapsync ...     --regexflag 's/\\ATTACHED//gi' 

Removing usually problematic flags in one line:

Windows:   imapsync.exe ... --regexflag "s/\\FORWARDED|\\Indexed|\\ATTACHED|\\RECEIPTCHECKED//gi" 
Unix:      imapsync     ... --regexflag 's/\\FORWARDED|\\Indexed|\\ATTACHED|\\RECEIPTCHECKED//gi' 

Removing all problematic flags I've seen so far in one line:
Windows:   imapsync.exe ... --regexflag "s/\\RECEIPTCHECKED|\\Indexed|\\X-EON-HAS-ATTACHMENT|\\UNSEEN|\\ATTACHED|\\X-HAS-ATTACH|\\FORWARDED|\\FORWARD|\\X-FORWARDED|\\\$FORWARDED|\\PRIORITY|\\READRCPT//g"
Unix:      imapsync     ... --regexflag 's/\\RECEIPTCHECKED|\\Indexed|\\X-EON-HAS-ATTACHMENT|\\UNSEEN|\\ATTACHED|\\X-HAS-ATTACH|\\FORWARDED|\\FORWARD|\\X-FORWARDED|\\\$FORWARDED|\\PRIORITY|\\READRCPT//g'

Removing all flags but the standard ones from the IMAP RFC:
Windows:   imapsync.exe ... --regexflag "s/.*?(?:(\\(?:Answered|Flagged|Deleted|Seen|Draft)\s?)|$)/defined($1)?$1:q()/eg"
Unix:      imapsync     ... --regexflag 's/.*?(?:(\\(?:Answered|Flagged|Deleted|Seen|Draft)\s?)|$)/defined($1)?$1:q()/eg'

=======================================================================
````
