### ISSUE TITLE
Azure Hosted Exchange 2 Factor Auth (Office 365)

### ISSUE THREAD

**Issue by rotor-head** [imapsync/imapsync#277]
***Consider adding this to the FAQ.Exchange.txt***

We encountered an issue when attempting to move messages to a new domain that was created using Azure/AD based Exchange. By default, 2 Factor Auth is turned on for the entire domain. Until it is disabled, authentication for LOGIN will fail on all accounts.

This article from GoDaddy support shows the steps to disable:
https://www.godaddy.com/help/enable-or-disable-security-defaults-40128

Hope this helps

**Comment by gilleslamiral** [comment]
There are some line about 2 Factor Auth  in the document FAQ.Office365.txt
(see below) but it is the Office365 faq, it's not the Exchange faq.

I'm not very aware of Microsoft services. If I understand you well I should add
"Disable double-step authentication on the Azure/Active Directory portail."
also on the FAQ.Exchange.txt document. Can you confirm this?
https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt


https://imapsync.lamiral.info/FAQ.d/FAQ.Office365.txt
````
...
=======================================================================
Q. For Office365 I have double and triple checked the username and
   password spelling but I still get a "LOGIN failed". Any clue?

R0. Imapsync doesn't support OAUTH2 authentication for Office365 accounts yet.

R1. Disable double-step authentication on the Azure/Active Directory portail.

R2. Also check a license is assigned to that account in Office365.

R3. MS introduced something called "security defaults" which is enabled 
by default for new tenants. One of the rules blocks IMAP access as of imapsync. 
The funny thing is that you can't disable single rules of this security 
package without buying additional licenses.
Switching the whole thing off allow the login.
See here:
https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults
Thanks to Stephan Buhre for this R3 answer.

R4. Is there special characters the password?
    https://imapsync.lamiral.info/FAQ.d/FAQ.Authentication_failure.txt
    https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Windows.txt
    https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt
    https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Mac.txt

R5. Triple check the hostname then. Try all of these:
 * outlook.office365.com
 * imap-mail.outlook.com
 * imap.outlook.com


=======================================================================
````

**Comment by rotor-head** [comment]
R3 that Stephan Buhre noted is one-in-the-same of what I posted. The "security defaults” is two-factor, or 2-step, authentication. I was digging in the Exchange FAQ for answers. Additionally, I would have overlooked it, only due to Microsoft’s labeling the feature as ’Security Defaults’  - which means absolutely nothing to me as an IT professional. 

Office365 (which is their consumer based offering) is treated differently from Azure/Active Directory where Microsoft uses Exchange in its service branding to attract IT professionals. 

1. I might suggest simply including the phrase "Disable double-step authentication on the Azure/Active Directory portal” in Stephan’s note - just in case there are others like me who need more hints. It doesn’t warrant an additional entry.

2. Consider including a link in the Exchange FAQ pointing back to the Office365 note (or duplicate the entry in the Exchange FAQ) given that the Azure/Active Directory offerings is essentially a hosted Exchange offering.
 
Hope that helps!

**Comment by gilleslamiral** [comment]
I'm very ok with redundancy, my goal is to help users, no matter the ways, knowing there are several ways. I'm also aware to avoid confusing documentation.


I updated the FAQ.Exchange.txt
https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt
with:
````
=======================================================================
Q. For Exchange I have double and triple checked the username and
   password spelling but I still get a "LOGIN failed". Any clue?


R1. Disable double-step authentication, also known as 2-factor,
    2-step authentication on the Azure/Active Directory portal.

R2. Microsoft introduced something called "security defaults" which is enabled
by default for new tenants. One of the rules blocks IMAP access as of imapsync. 
The funny thing is that you can't disable single rules of this security 
package without buying additional licenses.
Switching the whole thing off allows the login.
Also, disable double-step authentication on the Azure/Active Directory portal.
See here:
https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-security-defaults
Thanks to Stephan Buhre for this R3 answer.

R3. Are there special characters in the password?
    https://imapsync.lamiral.info/FAQ.d/FAQ.Authentication_failure.txt
    https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Windows.txt
    https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt
    https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Mac.txt

=======================================================================
 ````

**Comment by rotor-head** [comment]
That looks good to me!
