### ISSUE TITLE
--minage issue

### ISSUE THREAD

**Issue by vprasad84** [imapsync/imapsync#282]
Hello,

We are using imapsync to move older emails older than 18 days

imapsync --folder "INBOX" --minage 18 --delete1 --authmech1 PLAIN --authmech2 PLAIN --authuser1 ${admacc1} --authuser2 ${admacc2} \
         --host1 "$HOST1" --user1 "$u1" --password1 "${admpass1}" --host2 "$HOST2" --user2 "$u2" --password2 "${admpass2}" \
         --port1 ${PORT1} --ssl1  --port2 ${PORT2} \
         --syncinternaldates --addheader --noauthmd5 >> ${LOGTO} 2>&1 &

Use of uninitialized value $msgs[0] in hash slice at /usr/bin/imapsync line 4458.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.
Use of uninitialized value $size in addition (+) at /usr/bin/imapsync line 4479.
Use of uninitialized value $list[1] in sort at /usr/bin/imapsync line 2829.
Use of uninitialized value $list[1] in sort at /usr/bin/imapsync line 2829.
Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1771.
Use of uninitialized value $h1_msgs[0] in hash slice at /usr/bin/imapsync line 1806.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.

**Comment by gilleslamiral** [comment]
Try the same with the option --noabletosearch

**Comment by vprasad84** [comment]
Thanks. It resolved!

**Comment by gilleslamiral** [comment]
What was the imap software server?

**Comment by vprasad84** [comment]
IceWarp

**Comment by gilleslamiral** [comment]
Thanks!

https://imapsync.lamiral.info/FAQ.d/FAQ.IceWarp.txt

**Comment by OneMonister** [comment]
FYI: it seems we have the same issue here when trying to archive message older than 3600 days with --minage command

```
imapsync  --host1 xxx  --user1 xxx  --password1 'xxx'  --port1 993  --ssl1 \
          --host2 xxx  --user2 xxx  --password2 'xxx'  --port2 143  --nossl2 \
          --automap  --minage 3600  --delete1  --syncduplicates  --nofoldersizes  --nofoldersizesatend  --logdir /home/folderpathxxx
```


triggers the following error

```
Use of uninitialized value $h1_msgs[0] in hash slice at /bin/imapsync line 2407.
Argument "" isn't numeric in sort at /bin/imapsync line 2419.
Use of uninitialized value $h1_msgs[0] in hash slice at /bin/imapsync line 2442.
Use of uninitialized value in split at /usr/share/perl5/vendor_perl/Mail/IMAPClient/MessageSet.pm line 30.
Host1: folder [INBOX.Archivio 2011-6Giu2017] selected 1 messages, duplicates 0
Host2: folder [INBOX.Archivio 2011-6Giu2017] selected 0 messages, duplicates 0
- msg INBOX.Archivio 2011-6Giu2017/ S[0] F[] I[] has RFC822.SIZE null!
- msg INBOX.Archivio 2011-6Giu2017/ skipped.
Host1: Expunging folder INBOX.Archivio 2011-6Giu2017 
```

By adding **--noabletosearch** works, but I don't know how to find out what is the IMAP server.
