### ISSUE TITLE
Migration from CPanel to Zimbra

### ISSUE THREAD

**Issue by samrocks1011** [imapsync/imapsync#295]
I am trying to migrate data from Cpanel to Zimbra using authuser.  Cpanel Server the authuser is not working and the following error comes. 

Error: Host1 failure: Error login on [Cpanel URL] with user [xyz@example.com] auth [PLAIN]: 2 NO [AUTHENTICATIONFAILED] Authentication failed.  

The auth user successfully works with Zimbra Server.

Below is the command that i am using for sync. 
imapsync --host1 "cpanel" --user1  --authuser1  --password1 MASKED --host2 "zimbra"  --user2  --authuser2  --password2 MASKED --port2 993 --authmech2 plain --ssl2 --allowsizemismatch --useuid --exclude Contacts --exclude Calendar --noauthmd5 --noerrorsdump --split1 100 --split2 100 --usecache --tmpdir /home/sandeep/zoro/tmp --errorsmax 1000

Can anyone help me to resolve this issue. 

Thanks in advance.

**Comment by gilleslamiral** [comment]
What is the imap software server?

Admin authentication via --authuser is not available on all imap software servers and when it is it has to be configured.
https://imapsync.lamiral.info/FAQ.d/FAQ.Admin_Authentication.txt

**Comment by samrocks1011** [comment]
@gilleslamiral 

Imap software is  Dovecot 

--------Error--------

Imap software is  Dovecot 

Read:   * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Host1 IP address: 192.185.99.150
Host1 banner: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Sending: 1 CAPABILITY
Sent 14 bytes
Read:   * CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN
Read:   1 OK Pre-login capabilities listed, post-login capabilities have more.
Host1 capability before authentication: IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN
Host1: hosturl says it has CAPABILITY for AUTHENTICATE PLAIN
Sending: 2 AUTHENTICATE PLAIN
Sent 22 bytes
Read:   +
Sending: cnBhdGlsQHpjYmwuaW4AemNibABXZWJtYWlsQDc4OQ==
Sent 46 bytes
Read:   2 NO [AUTHENTICATIONFAILED] Authentication failed.
ERROR: 2 NO [AUTHENTICATIONFAILED] Authentication failed. at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 3189.
        Mail::IMAPClient::authenticate('Mail::IMAPClient=HASH(0x3aa77a8)', 'PLAIN', 'CODE(0x35059d8)') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 561
        Mail::IMAPClient::login('Mail::IMAPClient=HASH(0x3aa77a8)') called at /home/sandeep/imapsync line 7032
        main::authenticate_imap('Mail::IMAPClient=HASH(0x3aa77a8)', 'hosturl', 993, 'emailid', undef, 'Webmail@789', 1, 120, 0, ...) called at /home/sandeep/imapsync line 6993
        main::login_imap('hosturl', 993, 'emailid', undef, 'password', 1, 120, 0, 1, ...) called at /home/sandeep/imapsync line 1744
        main::single_sync() called at /home/sandeep/imapsync line 1152
Host1 info: authmech [PLAIN] user [emailid] authuser [authuser] IsUnconnected []
Host1 failure: Error login on [hosturl] with user [emailid] auth [PLAIN]: 2 NO [AUTHENTICATIONFAILED] Authentication failed.
Exiting with return value 16 (EXIT_AUTHENTICATION_FAILURE) 1/1000 nb_errors/max_errors PID 94796
Removing pidfile /home/sandeep/zoro/tmp/imapsync.pid

**Comment by gilleslamiral** [comment]
You name it!

https://imapsync.lamiral.info/FAQ.d/FAQ.Dovecot.txt
````
=======================================================================
Q. How to migrate to Dovecot with an admin/MasterUser account?

R. Dovecot uses the same syntax as uw-imap

  imapsync ... --user2="loginuser*admin_user" --password2 "admin_user_password"

To setup a Dovecot MasterUser follow the document
https://doc.dovecot.org/configuration_manual/authentication/master_users/

=======================================================================
````

**Comment by samrocks1011** [comment]
@gilleslamiral 

I tried this. It's not working in my case.  My services are hosted on Hostgator. 

I tried configuring the user on Outlook using Admin Auth the same configured successfully. So the Admin auth is working in case of Outlook but incase of Imapsync is not working.

Also as per the Hostgator Support, all the settings are fine at their end.

**Comment by gilleslamiral** [comment]
Do you have password characters other than letters or numbers?
In that case, can you change the password so that it contains only letters or numbers?
If security is your concern, just make it random and longer.

https://imapsync.lamiral.info/FAQ.d/FAQ.Authentication_failure.txt
````
...
   * If you can authenticate successfully with an other imap client software 
     like Thunderbird or Outlook or Sparrow then it is a very good sign to 
     authenticate successfully with imapsync. Examine the parameters of 
     this other imap client and copy them as is for imapsync.

   * Use option --showpasswords
     At the beginning of the output, imapsync dumps all its command
     line parameters; it's the line after "Command line used:".
     With --showpasswords, imapsync prints the passwords received 
     instead of the string MASKED. It helps for debugging quoting issues.
     Option --showpasswords shows passwords again when the IMAP dialog
     is dumped by --debugimap option. Search for a line like 
     "Sending: 2 LOGIN test1 secret1" (secret1 is the password here)


   * It is sometimes very hard to quote correctly unusual characters,
     especially on Windows (and Mac sometimes). See 
     https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Windows.txt
     https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt
     https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Mac.txt
     
     The quickest trick may be to change the password temporally
     with easy characters like the classical alphabet, a long
     string still ensure strong security.
````

**Comment by samrocks1011** [comment]
@gilleslamiral 
Sorry for the late response. got stuck in some personal stuff.  I have changed the password and set with only number and characters but the issue remains the same. It works with Outlook but not with imapsync. I think the HostGator dovecot setting are not configured to support Imapsync and that the reason the admin auth is not working. Even we do not have the root access to server to check the same. 

Thanks for all the support that you have provided. 

Regards,
Sandeep Patel

**Comment by gilleslamiral** [comment]
I didn't find any document relating the admin authentication on HostGator, if you have one I'll be glad to read it.
Same thing for the admin authentication in Outlook, I have never eared about it.

If you have root access to the HostGator host then you can change the Dovecot configuration and make it suitable for your need. 

There is no several ways to authenticate with an admin account in Dovecot so your case let me curious about it.
