### ISSUE TITLE
Square Brackets

### ISSUE THREAD

**Issue by Taruga** [imapsync/imapsync#3]
How to avoid this problem:

msg INBOX/75223 {2952} couldn't append  (Subject:[Terminal de Recolha de Dados - ScanPhone Honeywell]) to folder INBOX: 20 NO APPEND error converting message

Seems that square brackets causes the error, as I have a bunch of them with the same error and all of them have square brackets in the subject

**Comment by gilleslamiral** [comment]
The brackets are from imapsync, subject is inside brackets, to see the leading blanks if any.
