### ISSUE TITLE
Feature request: ability to print message subject

### ISSUE THREAD

**Issue by cyberic99** [imapsync/imapsync#30]
Hello

I'd like to be able to print the messages subjects, on some logs: 
For instance:
> msg INBOX.Archived/95551 marked \Deleted on host2 [GyDD6WpsFEtyBzNFnv]
> msg [Gmail]/All Mail/281079 copying to INBOX.Archived 

It would be great to be able to print the email subject, in order to debug or to get more useful information.

Thanks

**Comment by gilleslamiral** [comment]
Dear cyberic99,

I've put this request in the TODO file.

Le 12/05/2015 15:34, cyberic99 a écrit :
> Hello
>
> I'd like to be able to print the messages subjects, on some logs:
> For instance:
>
>     msg INBOX.Archived/95551 marked \Deleted on host2 [GyDD6WpsFEtyBzNFnv]
>     msg [Gmail]/All Mail/281079 copying to INBOX.Archived
>
> It would be great to be able to print the email subject, in order to debug or to get more useful information.


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by cyberic99** [comment]
Thanks!
