### ISSUE TITLE
pod2man: Unable to format

### ISSUE THREAD

**Issue by CGeorges** [imapsync/imapsync#31]
I believe it's this bug here https://bugs.mageia.org/show_bug.cgi?id=10663 because make install fails on ubuntu 14.04:

All needed modules are already installed
imapsync syntax OK
pod2man < /dev/null
pod2man: unable to format
make: *** [W/imapsync.1] Error 1

**Comment by gilleslamiral** [comment]
Hi Georges,

It works fine on my "Ubuntu 12.04.5 LTS"
pod2man may have regressed, not capable to parse a null file anymore.

Le 04/06/2015 14:56, Georges Chitiga a écrit :
> I believe it's this bug here https://bugs.mageia.org/show_bug.cgi?id=10663 because make install fails on ubuntu 14.04:
>
> All needed modules are already installed
> imapsync syntax OK
> pod2man < /dev/null
> pod2man: unable to format
> make: *** [W/imapsync.1] Error 1
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/31>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by CGeorges** [comment]
Hi Gilles,

 

I believe that's the case, yes. Though, the installation is done and works fine on 14.04 so it shouldn't be a problem but could create confusion, at first I didn't realise that imapsync was compiled and working so I retried the installation a few times.

**Comment by klonos** [comment]
Is this still an issue? Did not receive any such errors when compiling in Ubuntu 15.04.

**Comment by gilleslamiral** [comment]
In the Makefile, commented 
  pod2man < /dev/null
