### ISSUE TITLE
Connection successfull but no emails/folders found or synced

### ISSUE THREAD

**Issue by PabReg** [imapsync/imapsync#328]
Hello,

Trying to syn emails from Exchange online to local Zimbra.
Zimbra is installed on Centos 7 machine and I installed imapsync on same machine.

imapsyn version - 2.200

I'm running basic command from example:
imapsync \
       --host1 test1.lamiral.info --user1 test1 --password1 secret1 \
       --host2 test2.lamiral.info --user2 test2 --password2 secret2

Additional parameters used: --no-modulesversion --noid

It looks like that connection to both servers is successfull but no Folders or emails listed and nothing is copied or synced.
Logs do not show any errors. I tried running --debug and --debugimap but it did not helped me to realise the problem.
How can I troubleshoot this issue?

Log below with some information hidden

Here is imapsync 2.200 on host test.************.lt, a linux system with 7.8/11.6 free GiB of RAM
with Perl 5.16.3 and Mail::IMAPClient 3.37
Transfer started at Tuesday 12 April 2022-04-12 14:36:10 +0300 EEST
PID is 11898 my PPID is 10321
Log file is LOG_imapsync/2022_04_12_14_36_10_842_***************_.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
Load is 2.31 0.83 0.30 2/508 on 8 cores
Current directory is /root
Real user id is root (uid 0)
Effective user id is root (euid 0)
$RCSfile: imapsync,v $ $Revision: 2.200 $ $Date: 2022/04/04 16:05:55 $
Command line used, run by /usr/bin/perl:
/usr/bin/imapsync --no-modulesversion --noid --host1 outlook.office365.com --user1 MASKED --password1 MASKED --host2 test.************.lt --user1 MASKED --password2 MASKED
Temp directory is /tmp ( to change it use --tmpdir dirpath )
kill -QUIT 11898 # special behavior: call to sub catch_exit
kill -TERM 11898 # special behavior: call to sub catch_exit
kill -INT 11898 # special behavior: call to sub catch_reconnect
kill -HUP 11898 # special behavior: call to sub catch_print
kill -USR1 11898 # special behavior: call to sub toggle_sleep
File /tmp/imapsync.pid does not exist
PID file is /tmp/imapsync.pid ( to change it, use --pidfile filepath ; to avoid it use --pidfile "" )
Writing my PID 11898 in /tmp/imapsync.pid
Writing also my logfile name in /tmp/imapsync.pid : LOG_imapsync/2022_04_12_14_36_10_842_***************_.txt
Info: will resync flags for already transferred messages. Use --noresyncflags to not resync flags.
Host1: probing ssl on port 993 ( use --nosslcheck to avoid this ssl probe )
Host1: sslcheck detected open ssl port 993 so turning ssl on (use --nossl1 --notls1 to turn off SSL and TLS wizardry)
Host2: probing ssl on port 993 ( use --nosslcheck to avoid this ssl probe )
Host2: sslcheck detected open ssl port 993 so turning ssl on (use --nossl2 --notls2 to turn off SSL and TLS wizardry)
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host1: SSL default mode is like --sslargs1 "SSL_verify_mode=0", meaning for host1 SSL_VERIFY_NONE, ie, do not check the server certificate.
Host1: Use --sslargs1 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the server certificate. of host1
Host2: SSL default mode is like --sslargs2 "SSL_verify_mode=0", meaning for host2 SSL_VERIFY_NONE, ie, do not check the server certificate.
Host2: Use --sslargs2 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, check the server certificate. of host2
Host1: Will just connect to outlook.office365.com without login
Host1: connecting on host1 [outlook.office365.com] port [993]
Host1 IP address: 52.97.218.66 Local IP address: 10.*.*.*
Host1 banner: * OK The Microsoft Exchange IMAP4 service is ready. [QQBTADgAUABSADAANABDAEEAMAAwADEANgAuAGUAdQByAHAAcgBkADAANAAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
Host1 capability: IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
Host2: Will just connect to test.************.lt without login
Host2: connecting on host2 [test.************.lt] port [993]
Host2 IP address: 10.*.*.* Local IP address: 10.*.*.*
Host2 banner: * OK IMAP4rev1 proxy server ready
Host2 capability: ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE IMAP4rev1 LIST-EXTENDED LIST-STATUS LITERAL+ MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR SEARCHRES SORT THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN XLIST AUTH=PLAIN
Exiting after a justconnect on host(s): outlook.office365.com test.************.lt
Exiting with return value 0 (EX_OK: successful termination) 0/50 nb_errors/max_errors PID 11898
Removing pidfile /tmp/imapsync.pid
Log file is LOG_imapsync/2022_04_12_14_36_10_842_re************a_.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )

**Comment by gilleslamiral** [comment]
You have two --user1

**Comment by PabReg** [comment]
OMG what a shame. Thank you for your answer and sorry for creating unnecessary Issue
