### ISSUE TITLE
folder with whitespaces

### ISSUE THREAD

**Issue by peterbeck** [imapsync/imapsync#33]
I am trying to migrate Exchange folders (in german language). Somehow I am unable to get it working. I tried these combinations:

```
--regextrans2 s/Gel&APY-schte Objekte/Trash/
--regextrans2 s/(Gel&APY-schte Objekte)/Trash/
--regextrans2 s/Gelöschte Objekte/Trash/
--regextrans2 s/^Gelöschte Objekte$/Trash/
```
on most runs i get following error message:

error: eval regextrans2: Substitution pattern not terminated 

if I chose
```
--regextrans2 s/$Gelöschte/Trash/
```

it results on host1 to "Trash Objekte" - not exactly what I am expecting....

what am I doing wrong ? What is the correct, working to get it working ?

Regards
Peter

**Comment by gilleslamiral** [comment]
Hi Peter,

> I am trying to migrate Exchange folders (in german language). Somehow I am unable to get it working. I tried these combinations:

On Unix:

   imapsync ... --regextrans2 's/Gel&APY-schte Objekte/Trash/'

On Windows:

   imapsync ... --regextrans2 "s/Gel&APY-schte Objekte/Trash/"



-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by peterbeck** [comment]
Salut Gilles,

that was my bad - I tried it in a bash script with variables and while running the script it removed the bracket-signs....d'oh! ;-) Now everything is working fine. Thanks a lot !

Best Regards 
Peter
