### ISSUE TITLE
Wrong date using imapsync UBUNTU 20.04

### ISSUE THREAD

**Issue by ajax159** [imapsync/imapsync#345]
Hello, I am using imapsyn to migrate from one email to another, but the emails are uploaded with an incorrect date, in the inbox and sent.
In the other folders, the date has no problem (drafts, trash, etc).
It's 30 gb of emails.
Is there any way to fix the date of emails that have already been uploaded?
I am using the following parameters:
imapsync --nosyncacls --syncinternaldates --subscribe --host1 192.168.1.199 --user1 [adr@me.com](mailto:adr@me.com) --password1 AD$$ --host2 192.168.1.215 --user2 [adr@me.com](mailto:adr@me.com)/tb --password2 AD $$ --notls1 --automap

![Screenshot-2](https://user-images.githubusercontent.com/14226676/177335893-4befb4b4-b82c-493d-91b1-6905cb41a8c5.png)

**Comment by gilleslamiral** [comment]
> Is there any way to fix the date of emails that have already been uploaded?

No.

See https://imapsync.lamiral.info/FAQ.d/FAQ.Dates.txt
