### ISSUE TITLE
Map folder names?

### ISSUE THREAD

**Issue by atrandafir** [imapsync/imapsync#35]
On the destination server by default the folders are named differently so it creates new folders instead of using existing ones, example:

Creates INBOX.Deleted+Messages instead of using existing INBOX.Trash
Creates INBOX.Sent+Messages instead of using existing INBOX.Sent

Maybe this is because of the source server, maybe they are named that way there. Not sure but anyway I think it would be interesting to have parameters to map folder names from source to destination.

**Comment by gilleslamiral** [comment]
Hi,

http://imapsync.lamiral.info/FAQ.d/FAQ.Folders_Mapping.txt

Le 26/08/2015 18:52, Alexandru Trandafir Catalin a écrit :
> On the destination server by default the folders are named differently so it creates new folders instead of using existing ones, example:
>
> Creates INBOX.Deleted+Messages instead of using existing INBOX.Trash
> Creates INBOX.Sent+Messages instead of using existing INBOX.Sent
>
> Maybe this is because of the source server, maybe they are named that way there. Not sure but anyway I think it would be interesting to have parameters to map folder names from source to destination.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/35>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by atrandafir** [comment]
Hi thanks, I see you can do it with regex but I'm really not too familiar with regex, I taught there would be a simpler way. But good to know, for now I'll leave it the way it creates them. But I'll keep it in mind in the future.

**Comment by gilleslamiral** [comment]
Hi Alexandru,

Regex can be simple, for example:

   imapsync ...  --regextrans2 s,Deleted,Trash,

just does what expected:

   INBOX.Deleted -> INBOX.Trash

Give me a simpler way to substitute "Deleted" by "Trash" and
I'll carefully consider it.

In fact, I'm currently thinking of doing this by default
without any option, automagically.

Le 27/08/2015 00:24, Alexandru Trandafir Catalin a écrit :
> Hi thanks, I see you can do it with regex but I'm really not too familiar with regex, I taught there would be a simpler way. But good to know, for now I'll leave it the way it creates them. But I'll keep it in mind in the future.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/35#issuecomment-135195242>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by gilleslamiral** [comment]
It was implemented with the --automap option.
