### ISSUE TITLE
Overwrite mails already in host2 without deleting mails missing in host1

### ISSUE THREAD

**Issue by alfonsrv** [imapsync/imapsync#350]
Explicitly overwriting / retransferring mails in `host2` that are already in `host1` (identified via the regular mail matching / duplicate detection) would be a nice feature in case of mishaps.

E.g. UTF8 translation/encoding errors, wrong line endings or other issues that might arise could easily be eliminated that way by simply "re-syncing" the corrected mails from `host1`. This is especially useful if `host2` has already processed new mails, thus making a full deletion unviable.

**Comment by gilleslamiral** [comment]
> UTF8 translation/encoding errors, wrong line endings or other issues that might arise.

I don't get the point. Imapsync synchronizes messages as they are. If run twice, the message transferred the second time is the same as the first time.
