### ISSUE TITLE
--skipcrossduplicates won't check subfolders in host2

### ISSUE THREAD

**Issue by jayhasgin** [imapsync/imapsync#355]
This is the command I'm using,

```
imapsync 
	--dry 
	--useheader 'Message-ID' 
	--skipheader '^(?!Message-Id)' 
	--nousecache 
	--noid 
	--skipcrossduplicates 
	--regexflag 's/.*?(?:(\\(?:Answered|Flagged|Deleted|Seen|Draft)\s?)|$)/defined($1)?$1:q()/eg' 
	--include 'INBOX|Inbox|Drafts|Sent|Trash|Deleted|Archive|All'
	--folderlast 'Inbox' 
	--automap 
	--host1 '' --port1 '' --user1 '' --password1 '' --ssl1 --host2 'localhost' --port2 '' --user2 ''
```
	
Folder structures on host1 and host2,

```
Host1: folders list (first the raw imap format then the [X] = [Y]):
* LIST (\Archive \HasNoChildren) "/" "Archive"
* LIST (\Junk \HasNoChildren) "/" "Bulk"
* LIST (\Drafts \HasNoChildren) "/" "Draft"
* LIST (\HasNoChildren) "/" "Inbox"
* LIST (\Sent \HasNoChildren) "/" "Sent"
* LIST (\Trash \HasNoChildren) "/" "Trash"
13 OK LIST completed

[Archive]
[Bulk]
[Draft]
[Inbox]
[Sent]
[Trash]

Host2: folders list (first the raw imap format then the [X] = [Y]):
* LIST (\HasChildren \UnMarked \Archive) "." Archive
* LIST (\HasNoChildren \UnMarked) "." Archive.Test1
* LIST (\HasNoChildren \UnMarked) "." Archive.Test2
* LIST (\HasNoChildren \UnMarked \Drafts) "." Drafts
* LIST (\HasNoChildren \UnMarked \Trash) "." Trash
* LIST (\HasNoChildren \UnMarked \Sent) "." Sent
* LIST (\HasNoChildren \UnMarked \Junk) "." Spam
* LIST (\HasNoChildren) "." INBOX
10 OK List completed (0.001 + 0.000 secs).

[Archive]
[Archive.Test1]
[Archive.Test2]
[Drafts]
[INBOX]
[Sent]
[Spam]
[Trash]

Folders in host2 not in host1:
[Spam]
[Drafts]
[Archive.Test1]
[Archive.Test2]

```

While syncing, if a message on host1 folder `[Inbox]` is present in host2 sub-folder `[Archive.Test1]`, it doesn't skip as duplicate. However, when the same email is moved to the base folder `[Archive]`, it skips that message.

This issue is quite similar to #203, about moving message to another folder and still the duplicate being created. However, I am facing the issue only if the message is in a sub-folder. 

My questions;

1. Are the duplicates created because, the message is in a sub-folder `[Archive.Test1]` of host2? If yes, how to sync host2 sub-folders together with its parent? I tried `regextrans2` and `folderrec`, but no luck.

2. Or is it because the sub-folder `[Archive.Test1]` on host2, missing on host1? Is there way to sync correctly, without creating the sub-folders on host1? 

3. I've tried using `--f1f2 "Archive=Archive.Test1"`, and it perfectly skipped that message. But, by using this option, would it mean that only `[Archive.Test1]` subfolder on host2 can be linked to `[Archive]` folder on host1? Is there a way to link multiple host2 folders to a single host1 folder, like using regex on `--f1f2`?

**Comment by jayhasgin** [comment]
I've gone through the code, and think I've got answers to my questions 1 & 2. I don't know Perl, but from what i understood, it seems `--skipcrossduplicates` only checks at the end of the flow. To fix this, all sub folders in host2, and their messages, and their headers need to be checked. Sounds like lot of work.

So, I tried a quick fix by hard-coding a call to create the missing folders on host1, and it worked perfectly, and the sync skipped the duplicates.

```
if ( @h2_folders_not_in_1 ) {
        myprint( "Folders in host2 not in host1:\n",
        create_missing_folders_in_1( $sync ),
        jux_utf8_list( @h2_folders_not_in_1 ), "\n" ) ;
}
```

And the sub using the code from `create_folder_old`, 

```
sub create_missing_folders_in_1
{
	foreach my $h1_fold ( @h2_folders_not_in_1 ) {
		
		my $mysync = shift ;
		my $imap = $mysync->{ 'imap1' } || return ;

        myprint( "Creating (old way) folder [$h1_fold] on host1\n" ) ;
        if ( ( 'INBOX' eq uc  $h1_fold )
         and ( $imap->exists( $h1_fold ) ) ) {
                myprint( "Folder [$h1_fold] already exists\n"  ) ;
                next ;
        }
        if ( ! $mysync->{dry} ){
                if ( ! $imap->create( $h1_fold ) ) {
                        my $error = join q{},
                                "Could not create folder [$h1_fold]: ",
                                $imap->LastError(  ), "\n" ;
                        errors_incr( $mysync, $error ) ;
                        # success if folder exists ("already exists" error)
                        next if $imap->exists( $h1_fold ) ;
                        # failure since create failed
                        next ;
                }else{
                        #create succeeded
                        myprint( "Created ( the old way ) folder [$h1_fold] on host1\n"  ) ;
                        next ;
                }
        }else{
                # dry mode, no folder so many imap will fail, assuming failure
                myprint( "Created ( the old way ) folder [$h1_fold] on host1 $mysync->{dry_message}\n"  ) ;
                next ;
        }
	}
}
```

Can we have an option like "--createmissingfolders1", which takes regex input of folder names to create the missing folders on host1? It would be really helpful. Thanks!

**Comment by gilleslamiral** [comment]
> Can we have an option like "--createmissingfolders1", which takes regex input of folder names to create the missing folders on host1?

Well, I'm not eager to add this. It looks like a reverse presync does the trick.
You can create those missing folders by inverting the sync and use the `--justfolders` option.
You can also select the folders you want to create with any of the options selecting folders like 
`--folder --folderrec --include --exclude`
