### ISSUE TITLE
Possible to add a subject prefix?

### ISSUE THREAD

**Issue by Clete2** [imapsync/imapsync#359]
When syncing one mailbox into another, I'd like to prefix the subjects with `[MAILBOX_NAME]` so that I know where it came from. Is that possible?

**Comment by Clete2** [comment]
Thanks for the reply @gilleslamiral and also thanks for the awesome tool. I'm trying to get off GMail but I need to sync emails for a while and your tool helps me do that!

I put this option: `--regexmess='s|Subject\: |Subject\: GMail |g'`

And the error I get: `Found 1 extra arguments : [|Subject\: GMail |g']`

I am using Mailcow so all this is being done in the UI. They force me to put `--regexmess=...` rather than `--regexmess '...'`.

I tried different delimiters (`|``/``,`) and also escaping and not escaping the colon after Subject.

What could I be doing wrong here?

**Comment by Clete2** [comment]
@gilleslamiral OK so it's not an issue with `imapsync`. It's an issue with Mailcow's script that invokes `imapsync`. You got me the answer I needed to get to the next step -- which will be helping to fix the invocation script.

Thank you!

Ref: https://github.com/mailcow/mailcow-dockerized/issues/4786

**Comment by gilleslamiral** [comment]
Good luck!
