### ISSUE TITLE
Ubuntu installation instructions. 

### ISSUE THREAD

**Issue by plutocrat** [imapsync/imapsync#36]
Hi,
I followed the advice in INSTALL.d/INSTALL.Ubuntu.txt

I found I also needed 
"sudo cpan IO::Socket::IP"
"sudo cpan JSON::WebToken"
on my Ubuntu Mint 17.2 installation to get a clean read on the Perl Modules list. This is based on Ubuntu 14 LTS

Modules version list:
Mail::IMAPClient     3.35
IO::Socket           1.36
IO::Socket::IP       0.37
IO::Socket::INET     1.33
IO::Socket::SSL      1.965
Net::SSLeay          1.58
Compress::Zlib       2.063
Digest::MD5          2.52
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Term::ReadKey        2.31
File::Spec           3.40
Time::HiRes          1.9725
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON::WebToken       0.10
( use --no-modules_version to turn off printing this Perl modules list )

**Comment by gilleslamiral** [comment]
I don't have either IO::Socket::IP on my development box which is a Ubuntu 12.04.5 LTS. 
JSON::WebToken is only needed with XOAUTH authentication.  A  clean read without "?" on the Perl Modules list has never been mandatory.
