### ISSUE TITLE
issues compiling/installing on debian 

### ISSUE THREAD

**Issue by xevilstar** [imapsync/imapsync#369]
https://pastebin.com/0byap5mL

**Comment by gilleslamiral** [comment]
Did you follow this document first:
https://imapsync.lamiral.info/INSTALL.d/INSTALL.Debian.txt

**Comment by gilleslamiral** [comment]
And applied what is in the document?

**Comment by xevilstar** [comment]
yes

**Comment by gilleslamiral** [comment]
The log shows this command was not applied:

````
apt install -y            \
  libauthen-ntlm-perl     \
  libcgi-pm-perl          \
  libcrypt-openssl-rsa-perl   \
  libdata-uniqid-perl         \
  libencode-imaputf7-perl     \
  libfile-copy-recursive-perl \
  libfile-tail-perl        \
  libio-socket-inet6-perl  \
  libio-socket-ssl-perl    \
  libio-tee-perl           \
  libhtml-parser-perl      \
  libjson-webtoken-perl    \
  libmail-imapclient-perl  \
  libparse-recdescent-perl \
  libproc-processtable-perl \
  libmodule-scandeps-perl  \
  libreadonly-perl         \
  libregexp-common-perl    \
  libsys-meminfo-perl      \
  libterm-readkey-perl     \
  libtest-mockobject-perl  \
  libtest-pod-perl         \
  libunicode-string-perl   \
  liburi-perl              \
  libwww-perl              \
  libtest-nowarnings-perl  \
  libtest-deep-perl        \
  libtest-warn-perl        \
  make                     \
  time                     \
  cpanminus
````

**Comment by xevilstar** [comment]
solved

**Comment by gilleslamiral** [comment]
How did you solve it?

**Comment by xevilstar** [comment]
> The log shows this command was not applied:
> 
> ```
> apt install -y            \
>   libauthen-ntlm-perl     \
>   libcgi-pm-perl          \
>   libcrypt-openssl-rsa-perl   \
>   libdata-uniqid-perl         \
>   libencode-imaputf7-perl     \
>   libfile-copy-recursive-perl \
>   libfile-tail-perl        \
>   libio-socket-inet6-perl  \
>   libio-socket-ssl-perl    \
>   libio-tee-perl           \
>   libhtml-parser-perl      \
>   libjson-webtoken-perl    \
>   libmail-imapclient-perl  \
>   libparse-recdescent-perl \
>   libproc-processtable-perl \
>   libmodule-scandeps-perl  \
>   libreadonly-perl         \
>   libregexp-common-perl    \
>   libsys-meminfo-perl      \
>   libterm-readkey-perl     \
>   libtest-mockobject-perl  \
>   libtest-pod-perl         \
>   libunicode-string-perl   \
>   liburi-perl              \
>   libwww-perl              \
>   libtest-nowarnings-perl  \
>   libtest-deep-perl        \
>   libtest-warn-perl        \
>   make                     \
>   time                     \
>   cpanminus
> ```
