### ISSUE TITLE
No valid SSL certicate

### ISSUE THREAD

**Issue by jujucz** [imapsync/imapsync#37]
Hello,

My IMAP server is using SSL but without a valid SSL certficate

How can I tell imapsync to use SSL without a certicate? Like the novalidate-cert option?

Thanks.

SSL: SSL connect attempt failed with unknown error error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by gilleslamiral** [comment]
Hi jujucz,

Replace SSL_VERIFY_PEER by SSL_VERIFY_NONE
in the imapsync code.

On 09/10/2015 11:31, jujucz wrote:
> Hello,
>
> My IMAP server is using SSL but without a valid SSL certficate
>
> How can I tell imapsync to use SSL without a certicate? Like the novalidate-cert option?
>
> Thanks.
>
> SSL: SSL connect attempt failed with unknown error error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/37>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by gilleslamiral** [comment]
The default is now SSL_VERIFY_NONE since imapsync revision 1.653 date: 2015/09/05.
There is indication in the output to switch to SSL_VERIFY_PEER, like:

    Host1: Use --sslargs1 SSL_verify_mode=1 to have SSL_VERIFY_PEER, ie, 
           check the certificate server of host1
