### ISSUE TITLE
Using xoauth2 failures

### ISSUE THREAD

**Issue by Cyanic-Cloud** [imapsync/imapsync#375]
Hello,
We are recently trying to set up Oauth using ImapSync.  
I have created the required app reg and added all the API permissions I think are required (if not more).

**Delegated Permissions:**
- email
- IMAP.AccessAsUser.All
- Mail.Read
- offline_access
- openid
- POP.AccessAsUser.All
- profile
- SMTP.Send
- User.Read

**Application Permissions:**
- IMAP.AccessAsApp
- POP.AccessAsApp

I have created a new service principal using the AppID of the App Reg and Objectid of the enterprise app.

Using the **Get-IMAPAccessToken.ps1** that is available @ **https://github.com/DanijelkMSFT/ThisandThat/blob/main/Get-IMAPAccessToken.ps1** I am able to authenticate and query the mailbox no issue by passing in -tenantID "xxx" -clientId "xxx" -clientsecret 'xxx' -targetMailbox "user1@testing.com" -Verbose

**_The PowerShell script returns the folders within my mailbox user1@testing.com no problem._**

I want to get this working using ImapSync.  The syntax I am currently using is:

`/usr/local/bin/imapsync --host1 outlook.office365.com --user1 "user1@testing.com" --passfile1 /home/usertasks/usertasks_test --oauthdirect1 /var/tmp/test1 --host2 testserver001  --user2 usertasks --passfile2 /home/usertasks/imap`

The PowerShell script that I am using at the moment to acquire an access token is:

`Import-Module MSAL.PS 
Clear-MsalTokenCache
$clientID = "xxxx" 
$secret = ConvertTo-SecureString 'xxxx' -AsPlainText -Force`
`$TenantId = "testtest.onmicrosoft.com"`
`$scope = "https://graph.microsoft.com/.default"`
`$myAccessToken = Get-MsalToken -ClientId $clientID `
` -TenantId $tenantID `
` -Scopes "$($scope)" `
` -clientsecret $secret`
`$myAccessToken.AccessToken`

I have attempted to pass two types of Accesstoken:
A standard Accesstoken e.g. "htyFyeHeiUQfc etc etc" that doesn't contain user or bearer info
And the alternative like so "user1@testing.com auth=Bearer Ols0eXAiOiJKV etc etc"
Both produce the same error.

The error message I am getting is:
`Host1: connecting and login on host1 [outlook.office365.com] port [993] with user [user1@testing.com]
Host1 IP address: 1.1.1.1 Local IP address: 2.2.2.2
Host1 banner: * OK The Microsoft Exchange IMAP4 service is ready. [token removed]
Host1 capability before authentication: IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
Host1 failure: Error login on [outlook.office365.com] with user [user1@testing.com] auth [XOAUTH2 direct]: 2 NO AUTHENTICATE failed.
Host1: failed login on [outlook.office365.com] with user [user1@testing.com] auth [XOAUTH2 direct]`

Please can you tell me where I'm going wrong? or if the syntax I am using is incorrect?

**Comment by gilleslamiral** [comment]
The standard Accesstoken e.g. "htyFyeHeiUQfc etc etc" is to be used with `--oauthaccesstoken1 tokenfile`
The alternative like so "user=user1@testing.com auth=Bearer Ols0eXAiOiJKV etc etc" has to be encoded in base64 and then passed with ` --oauthdirect1 bearer64file`

https://imapsync.lamiral.info/README
````
     --oauthaccesstoken1 str : The access token to authenticate with OAUTH2.
                           It will be combined with the --user1 value to form the 
                           string to pass with XOAUTH2 authentication.
                           The password given by --password1 or --passfile1
                           is ignored but needed on the command line.
                           Instead of the access token itself, the value can be a
                           file containing the access token on the first line.
                           If the value is a file, imapsync reads its first line
                           and take this line as the access token. The advantage
                           of the file is that if the access token changes then
                           imapsync can read it again when it needs to reconnect 
                           during a run.


     --oauthaccesstoken2 str : same thing as --oauthaccesstoken1 

     --oauthdirect1 str  : The direct string to pass with XOAUTH2 authentication.
                           The password given by --password1 or --passfile1 and 
                           the user given by --user1 are ignored but they are 
                           needed to be on the command line. Consider it a bug.

     --oauthdirect2 str  : same thing as oauthdirect1
````

**Comment by gilleslamiral** [comment]
From https://github.com/Cyanic-Cloud by email:
Success
