### ISSUE TITLE
SmarterMail Folders to multiple IMAP accounts migration 

### ISSUE THREAD

**Issue by dfangys** [imapsync/imapsync#376]
Hello, 

i have moved the smartermail data from old server to new server by FTP for up tp 3000 user, 

now i need to create the email user in new server so i'll have all email and password but the problem is i need to migrate it from SmarterMail users folder to IMAP account. 

any idea  ?

**Comment by gilleslamiral** [comment]
> I have moved the smartermail data from old server to new server by FTP

Well, you must be desperate to ask help concerning FTP transfers here.
Did you use imapsync somehow?

**Comment by gilleslamiral** [comment]
Did you succeed?

**Comment by dfangys** [comment]
yes
