### ISSUE TITLE
add --rm to docker run command

### ISSUE THREAD

**Issue by oregonpillow** [imapsync/imapsync#384]
On the official docker hub page [https://hub.docker.com/r/gilleslamiral/imapsync/ ](https://hub.docker.com/r/gilleslamiral/imapsync/ ) the docker run command should include `--rm` otherwise the container is still left and not removed after running. This may not be obvious to people not experienced with docker. 

use of --rm is a good practice for all docker containers that are simply executing command line arguments.

```
docker run --rm gilleslamiral/imapsync imapsync  --host1 test1.lamiral.info  --user1 test1  --password1 'secret1' --host2 test2.lamiral.info  --user2 test2  --password2 'secret2'
```
great project!

**Comment by gilleslamiral** [comment]
> the docker run command should include `--rm` otherwise the container is still left and not removed after running. 

Ok
Done!
https://hub.docker.com/r/gilleslamiral/imapsync

> This may not be obvious to people not experienced with docker.
> 

It's not obvious to me

> use of --rm is a good practice for all docker containers that are simply executing command line arguments.
> 

Ok
