### ISSUE TITLE
520 BAD Command Argument Error. 11 for many Read receipt

### ISSUE THREAD

**Issue by adrensnyder** [imapsync/imapsync#389]
I see in many migrations that some mail with subject: "Read:" getting error "520 BAD Command Argument Error. 11"
In the last migration i get over 100 errors.

This is one debug log:
ERROR: 520 BAD Command Argument Error. 11 at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1364.
        Mail::IMAPClient::__ANON__('520 BAD Command Argument Error. 11\x{d}\x{a}') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1400
        Mail::IMAPClient::_get_response('Mail::IMAPClient=HASH(0x1b38e50)', 520, undef) called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1326
        Mail::IMAPClient::_imap_command_do('Mail::IMAPClient=HASH(0x1b38e50)', 'HASH(0x35ce308)', 'APPEND "Archives/LETTURA MAIL" (\Seen) "10-Dec-2021 18:25:50 ...') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1225
        Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x1b38e50)', 'HASH(0x35ce308)', 'APPEND "Archives/LETTURA MAIL" (\Seen) "10-Dec-2021 18:25:50 ...') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 2926
        Mail::IMAPClient::append_string('Mail::IMAPClient=HASH(0x1b38e50)', 'Archives/LETTURA MAIL', 'Return-Path: <MAILER-DAEMON>\x{d}\x{a}Delivered-To: mail@domain.com...', '\Seen', '"10-Dec-2021 18:25:50 +0100"') called at /usr/bin/imapsync line 12757
        main::append_message_on_host2('HASH(0x2ad3e68)', 'SCALAR(0x274d088)', 'Archives.LETTURA MAIL', 16605, 4553, 'Archives/LETTURA MAIL', 4553, '\Seen', '"10-Dec-2021 18:25:50 +0100"', ...) called at /usr/bin/imapsync line 11829
        main::copy_message('HASH(0x2ad3e68)', 16605, 'Archives.LETTURA MAIL', 'Archives/LETTURA MAIL', 'HASH(0x2e1ce58)', '/tmp/imapsync_cache/mail.domain.com/mail@domain.com/outlook.o...') called at /usr/bin/imapsync line 2875
        main::single_sync('HASH(0x2ad3e68)', 'HASH(0xebcc48)', 'HASH(0x2ad3e80)') called at /usr/bin/imapsync line 1367
ERROR: 520 BAD Command Argument Error. 11 at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1274.
        Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x1b38e50)', 'HASH(0x35ce308)', 'APPEND "Archives/LETTURA MAIL" (\Seen) "10-Dec-2021 18:25:50 ...') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 2926
        Mail::IMAPClient::append_string('Mail::IMAPClient=HASH(0x1b38e50)', 'Archives/LETTURA MAIL', 'Return-Path: <MAILER-DAEMON>\x{d}\x{a}Delivered-To: mail@domain.com...', '\Seen', '"10-Dec-2021 18:25:50 +0100"') called at /usr/bin/imapsync line 12757
        main::append_message_on_host2('HASH(0x2ad3e68)', 'SCALAR(0x274d088)', 'Archives.LETTURA MAIL', 16605, 4553, 'Archives/LETTURA MAIL', 4553, '\Seen', '"10-Dec-2021 18:25:50 +0100"', ...) called at /usr/bin/imapsync line 11829
        main::copy_message('HASH(0x2ad3e68)', 16605, 'Archives.LETTURA MAIL', 'Archives/LETTURA MAIL', 'HASH(0x2e1ce58)', '/tmp/imapsync_cache/mail.domain.com/mail@domain.com/outlook.o...') called at /usr/bin/imapsync line 2875
        main::single_sync('HASH(0x2ad3e68)', 'HASH(0xebcc48)', 'HASH(0x2ad3e80)') called at /usr/bin/imapsync line 1367

If i copy manually those mail works.

Any idea to resolve this problem?

**Comment by gilleslamiral** [comment]
https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt
...
````
======================================================================
Q. From XXX to Exchange 2010/2013 I get this error message
   sometimes: "BAD Command Argument Error 11". What does it mean?

R. This error message comes from Exchange IMAP server when it 
   encounters any problem. Most of the time it is one of the following:

  * Some messages are bigger than the size limit. 10 MB by default
    on Exchange. It can be upped by configuration for Exchange.
    Sometimes a reboot is needed to take configuration changes 
    into account.
    If you can't fix this limit on Exchange then use option
    --maxsize 10000000 for 10 MB, change it if needed) to tell
    imapsync to skip those messages.

  imapsync ... --maxsize 10000000 # 10 MB for Exchange


  * Quota reached. The whole account is full.
    It can be upped by configuration.

  * Some messages have some lines too long. Use option --maxlinelength
    to skip messages whose max line length is over a number of bytes.
    --maxlinelength 1000 is a RFC2822 must but most server support
    higher values. Exchange supports 9900 characters line length:

  imapsync ... --maxlinelength 9900 

  In case you prefer fixing messages with long lines the hard way,
  instead of skipping them with --maxlinelength 9900, just use:

  On Windows
  imapsync ... --regexmess "s,(.{9900}),$1\r\n,g"

  On Unix
  imapsync ... --regexmess 's,(.{9900}),$1\r\n,g'
  
Have also in mind that Exchange closes the connection after 10 errors
encountered so you might also see "BYE Connection closed" errors from
Exchange, which means Exchange leaves the session and say goodbye,
come back later. Rerun a sync then.

On Linux, there is a good Python script in the tarball that can 
fix several things that Exchange have issues with.

Use it like this:

  ./imapsync ... --pipemess W/tools/fix_email_for_exchange.py

It often does some miracles on messages.

======================================================================
````

**Comment by adrensnyder** [comment]
Thanks but I have already read your guide many times before opening an issue.
I'm asking for help as none of these situations are related to the problem or can solve it.
The messages are very small Read Receipts. I already use --regexmess with many values tested.
The account is not full but about at 70%.

It's a very strange situation. In the last 2 migrations I get errors most of the time (Like 90%) for "Read Receipt" messages.

If there are no other things you can suggest and debugging doesn't help i will continue to copy them by hand when they happen.

Thanks for support

**Comment by gilleslamiral** [comment]
Can you focus on a folder with a few messages failing to be copied and send me the output?

    imapsync ... --folder BUG --debugcontent
