### ISSUE TITLE
"The sync is not finished" but there is no detail on what mails they are

### ISSUE THREAD

**Issue by adrensnyder** [imapsync/imapsync#390]
In the last migration i get some accounts with this:
**The sync is not finished, there are 5 among 155313 identified messages in host1 that are not on host2**

I get no errors so I don't know how to figure out what emails they are so i can retrieve them manually.

Is there any way to know?

**Comment by gilleslamiral** [comment]
Can you show me the whole final stats?

Look at the lines that don't have "copied" in them (grep -v on Linux), there are interesting parts of the problems encountered.

**Comment by adrensnyder** [comment]
Those are the final lines:

```
Transfer started on                     : Thursday 13 April 2023-04-13 14:42:11 +0200 CEST
Transfer ended on                       : Thursday 13 April 2023-04-13 16:37:48 +0200 CEST
Transfer time                           : 6936.4 sec
Folders synced                          : 4841/4841 synced
Messages transferred                    : 84
Messages skipped                        : 166807
Messages found duplicate on host1       : 2509
Messages found duplicate on host2       : 10
Messages found crossduplicate on host2  : 0
Messages void (noheader) on host1       : 0
Messages void (noheader) on host2       : 0
Messages found in host1 not in host2    : 5 messages
Messages found in host2 not in host1    : 8 messages
Messages deleted on host1               : 0
Messages deleted on host2               : 10
Total bytes transferred                 : 42872444 (40.886 MiB)
Total bytes skipped                     : 86345666255 (80.416 GiB)
Message rate                            : 0.0 messages/s
Average bandwidth rate                  : 6.0 KiB/s
Reconnections to host1                  : 0
Reconnections to host2                  : 0
Memory consumption at the end           : 357.0 MiB (*time 687.9 MiB*h) (started with 96.2 MiB)
Load end is                             : 0.34 0.23 0.20 1/220 on 2 cores
CPU time and %cpu                       : 452.62 sec 6.5 %cpu 3.2 %allcpus
Biggest message transferred             : 7455426 bytes (7.110 MiB)
Memory/biggest message ratio            : 50.2
Start difference host2 - host1          : -2574 messages, -22920722919 bytes (-21.347 GiB)
Final difference host2 - host1          : -2511 messages, -22899826405 bytes (-21.327 GiB)
The sync is not finished, there are 5 among 155442 identified messages in host1 that are not on host2.
There is no unidentified message on host1.
The sync is not strict, there are 8 among 155445 identified messages in host2 that are not on host1. Use --delete2 and sync again to delete them and have a strict sync.
Detected 0 errors
This imapsync is up to date. ( local 2.231 >= official 2.229 )( Use --noreleasecheck to avoid this release check. )
Homepage: https://imapsync.lamiral.info/
Exiting with return value 0 (EX_OK: successful termination) 0/100 nb_errors/max_errors PID 9215
Removing pidfile /tmp/imapsync.pid
Log file is /var/log/imapsync/customer/2023-04-13/mail@dominio.com%2023-04-13_14-42 ( to change it, use --logfile filepath ; or use --nolog to turn off logging )
```
Imapsync version: 2.231

This is the command line executed:
```
/usr/bin/imapsync --errorsmax 100 --delete2 --addheader --automap --disarmreadreceipts --maxmessagespersecond 4 --f1f2 Files=Files_renamed_by_imapsync --regexmess s,(.{10239}),$1\r\n,g --ssl2 --oauthaccesstoken2 /usr/local/bin/migrazioni/customer/customer_token_imapsync -maxsize 149_000_000 --maxlinelength 10_500 --host1 mail.dominio.com --user1 mail@dominio.com --password1 MASKED --ssl1 --notls1 --host2 outlook.office365.com --user2 mail@dominio.com --password2 MASKED --notls2 --logdir /var/log/imapsync/customer/2023-04-13 --logfile mail@dominio.com%2023-04-13_14-42
```

I've already tried to grep the log without find anything useful. Also with 4k+ folders is very difficult

Another thing i see is that i used the "--delete2" option but i still get "The sync is not strict, there are 8 among 155445 identified messages in host2 that are not on host1. Use --delete2 and sync again to delete them and have a strict sync."

**Comment by eleucarlos** [comment]
I did it this way:
1- I created a script powershell to move the successfully completed log file to another directory.
2- I created a script powershell to generate a csv file adding errors and limits line by line with a column of account name, follow the script to create a csv:

$InputDir="E:\run\zcs2o365\import\imap\logs\"
$OutputDir="E:\run\zcs2o365\temp\ContasErrorLimitadas.csv"


$logs_list=Get-ChildItem $InputDir -filter *.txt | select -ExpandProperty fullname
    ForEach($file in $logs_list){
    (Get-Content $file).replace(';', ' ') | Set-Content $file
    }
    
    $list_errors = ""
    ForEach($file in $logs_list){
    $list_errors = Get-ChildItem $file | Select-String -Pattern "maxlinelength 9900 bytes|Err |Maximum size of appendable message has been exceeded" -AllMatches | %{$_.Line} 
    
    $file = $file.Split("_")[7]
    $file = $file -replace ".txt"

    echo "==== $list_errors"
   
   if ($list_errors) {
     ForEach($erro in $list_errors){
       Write-Output $file";""$($erro -Replace '- msg ', '')""" | Out-File -FilePath $OutputDir -Append
     }
   }
}


#If you use linux, just take the idea and logic and create it in bash or another language that you prefer

**Comment by adrensnyder** [comment]
@eleucarlos Thanks for your suggestions. It's a good idea but it doesn't solve the problem. I have no errors in the log which matches those matches maxlinelength 9900 bytes|Err |Maximum size of appendable message has been exceeded

In previous migrations I had some errors. At the bottom appeared "Err: " and, in the same line, the subject and the various info were presented as well as a possible explanation of why it did not copy
Example:
Err 1/2: - msg Posta al 20-9-2014.Posta in arrivo/155 {7844} could not append ( Subject:[], Date:["21-Nov-2011 11:00:06 +0100"], Size:[7844], Flags:[\Seen] ) to folder Posta al 20-9-2014/Posta in arrivo: 560 BAD Command Argument Error. 11

I'm asking why i get 5 errors but not 5 Err: at bottom with the details in this migration.

**Comment by adrensnyder** [comment]
Thanks @gilleslamiral 
Found the 5 messages with "skipped". Error: "445718186 exceeds maxsize limit 149000000 bytes".
400mb of mail. I'm scared

There are any chance to get those errors in the bottom with "Err: " in the next release?

**Comment by gilleslamiral** [comment]
> Can you get those errors in the bottom with "Err: " of "Skipped: " in the next release?

My problem with this request is that they are not errors, you chose to skip those messages. 
How about a --maxsize 10_000 on a 200k messages mailbox? Plenty of normal skipped reported at the end.
Remove the --maxsize and they eventually become errors if the destination server refuses them. 

I could add a statistic line with 
Messages skipped by --maxsize : 5

I'm lazy...

**Comment by adrensnyder** [comment]
@gilleslamiral yes you right. The 149m limit I've used it's for 365 limits. If I remove it, those message will give an error, probably. Now that I know why it appended i can do something about it

Thanks for your help

**Comment by adrensnyder** [comment]
@gilleslamiral I'm checking the skipped message today but the program don't give me details of the messate:
msg Drafts/12432 skipped (214026540 exceeds maxsize limit 153000000 bytes)

I get only che path anche the id (i think). Is possibile to retrieve also the date and subject in the skipped line?
Like what you do in the errors lines

Thanks for your patience

**Comment by gilleslamiral** [comment]
> It's possible to retrieve also the date and subject in the skipped line?

No.
To find this message, sort the folder by message size, it will appear at the top or bottom.

How much memory the host has?

**Comment by adrensnyder** [comment]
I'm already doing this by configuring on my computer with imap each account that has this problem.

The server has 4gb of ram. At the moment I can't upgrade it. If I can copy without the "Out of Memory" error limiting to 153 million, that's fine too

Thanks
