### ISSUE TITLE
Imapsync Issue

### ISSUE THREAD

**Issue by beno44** [imapsync/imapsync#397]
Hi,

Been using imapsync for a long time and never had that issue.

Connecting successfully to Host1 & 2.

Host1: found 22 folders.
Host1 folders list (first the raw imap format then the [X] = [Y]):
* LIST (\HasNoChildren) "." "Apple Mail To Do"
* LIST (\HasNoChildren) "." Archive
* LIST (\HasNoChildren) "." "Deleted Messages"
* LIST (\HasNoChildren \Drafts) "." Drafts
* LIST (\HasNoChildren) "." "Emails 2017"
* LIST (\HasNoChildren) "." "Emails 2018"
* LIST (\HasNoChildren) "." "emails 2019"
* LIST (\HasNoChildren) "." "Emails 2020"
* LIST (\HasNoChildren) "." "Emails 2021"
* LIST (\HasNoChildren) "." "Emails prior to 31-7-2013"
* LIST (\HasNoChildren) "." "Emails prior to 31122015"
* LIST (\HasNoChildren) "." "Google ads"
* LIST (\HasNoChildren \Junk) "." Junk
* LIST (\HasNoChildren) "." "Junk E-mail"
* LIST (\HasChildren) "." Notes
* LIST (\HasNoChildren) "." "Notes.changes "
* LIST (\HasChildren) "." Notes.RootFolder
* LIST (\HasNoChildren) "." "Notes.RootFolder.follow ups"
* LIST (\HasNoChildren) "." Quotes
* LIST (\HasNoChildren \Sent) "." "Sent Messages"
* LIST (\HasNoChildren \Trash) "." Trash
* LIST (\HasNoChildren) "." INBOX
11 OK List completed.

Nothing actually synchronises and get the following message (prior to completing the task)

_Folders sizes before the synchronization.
You can remove foldersizes listings by using "--nofoldersizes" and  "--nofoldersizesatend"
but then you will also loose the ETA (Estimation Time of Arrival) given after each message copy.
++++ Calculating sizes of 0 folders on Host1
Host1 Nb folders:                0 folders
Host1 Nb messages:               0 messages
Host1 Total size:                0 bytes (0.000 KiB)
Host1 Biggest message:           0 bytes (0.000 KiB)
Host1 Time spent:              2.2 seconds
++++ Calculating sizes of 0 folders on Host2
Host2 Nb folders:                0 folders
Host2 Nb messages:               0 messages
Host2 Total size:                0 bytes (0.000 KiB)
Host2 Biggest message:           0 bytes (0.000 KiB)
Host2 Time spent:              0.0 seconds
++++ Looping on each one of 0 folders to sync
++++ End looping on each folder

Folders sizes after the synchronization.
You can remove this foldersizes listing by using  "--nofoldersizesatend"
++++ Calculating sizes of 0 folders on Host1
Host1 Nb folders:                0 folders
Host1 Nb messages:               0 messages
Host1 Total size:                0 bytes (0.000 KiB)
Host1 Biggest message:           0 bytes (0.000 KiB)
Host1 Time spent:              0.1 seconds
++++ Calculating sizes of 0 folders on Host2
Host2 Nb folders:                0 folders
Host2 Nb messages:               0 messages
Host2 Total size:                0 bytes (0.000 KiB)
Host2 Biggest message:           0 bytes (0.000 KiB)
Host2 Time spent:              0.0 seconds
++++ Statistics
Transfer started on               : Wed May 17 18:39:22 2023
Transfer ended on                 : Wed May 17 18:39:25 2023
Transfer time                     : 2.3 sec
Folders synced                    : 0/0 synced
Messages transferred              : 0 
Messages skipped                  : 0
Messages found duplicate on host1 : 0
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 0
Messages void (noheader) on host2 : 0
Messages deleted on host1         : 0
Messages deleted on host2         : 0
Total bytes transferred           : 0 (0.000 KiB)
Total bytes duplicate host1       : 0 (0.000 KiB)
Total bytes duplicate host2       : 0 (0.000 KiB)
Total bytes skipped               : 0 (0.000 KiB)
Total bytes error                 : 0 (0.000 KiB)
Message rate                      : 0.0 messages/s
Average bandwidth rate            : 0.0 KiB/s
Reconnections to host1            : 0
Reconnections to host2            : 0
Memory consumption at the end     : 2569.1 MiB (started with 2558.7 MiB)
Biggest message                   : 0 bytes (0.000 KiB)
Memory/biggest message ratio      : NA
Start difference host2 - host1    : 0 messages, 0 bytes (0.000 KiB)
Final difference host2 - host1    : 0 messages, 0 bytes (0.000 KiB)
Detected 0 errors_

What I'm sending to imapsync: ./imapsync --nosyncacls --subscribe --syncinternaldates --nosslcheck --errorsmax 10000000 --addheader --host1 xxx.xxx.xxx.xxx --user1 user --password1 password --authmech1 LOGIN --folder Inbox --host2 xxx.xxx.xxx.xxx --user2 user --password2 password --SSL2 --authmech2 LOGIN --subfolder2 Enquiries

Been banging my head on the wall for a while, if anyone has any suggestions that would be amazing.

Tks

**Comment by gilleslamiral** [comment]
You use `--folder Inbox`
There is no folder Inbox here.
There is INBOX

**Comment by beno44** [comment]
Merci Gilles.

Thank you, annoying that I didn't pick that up.

Merci beaucoup ;o)
