### ISSUE TITLE
Trying to do oauth2 with Google Apps

### ISSUE THREAD

**Issue by dano000** [imapsync/imapsync#40]
Hi,

I've tried used IMAPSYNC with oauth2. I've set up the OAUTH2 consumer key/password in google developer console and made a service app for it.
I still get an error:

Undefined subroutine &main::encode_entities called at ./imapsync line 2446.

Being this code snippit: 

 my $ua = LWP::UserAgent->new();

I have double checked LWP::UserAgent is installed via CPAN.

Here is my input command:

/imapsync --justlogin --host1 imap.gmail.com -ssl1 --authmech1 xoauth2 --user1 user@example.com.au --password1 '1234556789-3d08030dsdkadfklksfl2313f213213sdks42lk@developer.gserviceaccount.com;notasecret.p12' --ssl2 --host2 mail.example.com.au --user2 alex.test@example.com.au --authuser2 admin@example.com.au --password2 password

(information has been changed, but you get the idea).

Here are the Perl Modules installed:

Modules version list:
Mail::IMAPClient     3.35
IO::Socket           1.38
IO::Socket::IP       0.37
IO::Socket::INET     1.35
IO::Socket::SSL      1.965
Net::SSLeay          1.65
Compress::Zlib       2.066
Digest::MD5          2.53
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Term::ReadKey        2.32
File::Spec           3.48_01
Time::HiRes          1.9726
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON::WebToken       0.10

This was from an Ubuntu 15.04 install. I did it on another machine, CENTOS 7. and it was the same problem. Is this the correct google API Endpoint? 'https://www.googleapis.com/oauth2/v3/token' ?

**Comment by gilleslamiral** [comment]
Hi,

In Imapsync, replace
  { grant_type => encode_entities('urn:ietf:params:oauth:grant-type:jwt-bearer'),
by
  { grant_type => HTML::Entities::encode_entities('urn:ietf:params:oauth:grant-type:jwt-bearer'),



On 20/10/2015 16:34, dano000 wrote:
> Hi,
>
> I've tried used IMAPSYNC with oauth2. I've set up the OAUTH2 consumer key/password in google developer console and made a service app for it.
> I still get an error:
>
> Undefined subroutine &main::encode_entities called at ./imapsync line 2446.
>
> Being this code snippit:
>
> my $ua = LWP::UserAgent->new();
>
> I have double checked LWP::UserAgent is installed via CPAN.
>
> Here is my input command:
>
> /imapsync --justlogin --host1 imap.gmail.com -ssl1 --authmech1 xoauth2 --user1 user@example.com.au <mailto:user@example.com.au> --password1 '1234556789-3d08030dsdkadfklksfl2313f213213sdks42lk@developer.gserviceaccount.com <mailto:1234556789-3d08030dsdkadfklksfl2313f213213sdks42lk@developer.gserviceaccount.com>;notasecret.p12' --ssl2 --host2 mail.example.com.au --user2 alex.test@example.com.au <mailto:alex.test@example.com.au> --authuser2 admin@example.com.au <mailto:admin@example.com.au> --password2 password
>
> (information has been changed, but you get the idea).
>
> Here are the Perl Modules installed:
>
> Modules version list:
> Mail::IMAPClient 3.35
> IO::Socket 1.38
> IO::Socket::IP 0.37
> IO::Socket::INET 1.35
> IO::Socket::SSL 1.965
> Net::SSLeay 1.65
> Compress::Zlib 2.066
> Digest::MD5 2.53
> Digest::HMAC_MD5 1.01
> Digest::HMAC_SHA1 1.03
> Term::ReadKey 2.32
> File::Spec 3.48_01
> Time::HiRes 1.9726
> Unicode::String 2.09
> IO::Tee 0.64
> File::Copy::Recursive 0.38
> Authen::NTLM 1.09
> URI::Escape 3.31
> Data::Uniqid 0.12
> JSON::WebToken 0.10
>
> This was from an Ubuntu 15.04 install. I did it on another machine, CENTOS 7. and it was the same problem. Is this the correct google API Endpoint? 'https://www.googleapis.com/oauth2/v3/token' ?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/40>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
