### ISSUE TITLE
folder INBOX: Could not select:

### ISSUE THREAD

**Issue by andersonmm** [imapsync/imapsync#402]
I run `imapsync --host1 outlook.office365.com --user1 mailbox@mycompany.com --oauthaccesstoken1 $(cat token.txt) --ssl1 --dry --host2 mail.server.com --user2 mailbox@mycompany.com --ssl2` and get the following error/failure:

++++ Listing folders
All foldernames are presented between brackets like [X] where X is the foldername.
When a foldername contains non-ASCII characters it is presented in the form
[X] = [Y] where
X is the imap foldername you have to use in command line options and
Y is the utf8 output just printed for convenience, to recognize it.

Trying command when NOT connected! at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 123.
	Mail::IMAPClient::LastError(Mail::IMAPClient=HASH(0x7f917148c210), "NO not connected") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1568
	Mail::IMAPClient::_send_line(Mail::IMAPClient=HASH(0x7f917148c210), "25 LIST \"\" *", 0) called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1344
	Mail::IMAPClient::_imap_command_do(Mail::IMAPClient=HASH(0x7f917148c210), "LIST \"\" *") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1248
	Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x7f917148c210), "LIST \"\" *") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 679
	Mail::IMAPClient::_list_or_lsub(Mail::IMAPClient=HASH(0x7f917148c210), "LIST") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 685
	Mail::IMAPClient::list(Mail::IMAPClient=HASH(0x7f917148c210)) called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 2297
	main::single_sync(HASH(0x7f9172c85f90), HASH(0x7f917000bc10), HASH(0x7f9172c92be0)) called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 1367
Trying command when NOT connected! LastError was: NO not connected at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 123.
	Mail::IMAPClient::LastError(Mail::IMAPClient=HASH(0x7f917148c210), "Error sending '25 LIST \"\" *': NO not connected") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1345
	Mail::IMAPClient::_imap_command_do(Mail::IMAPClient=HASH(0x7f917148c210), "LIST \"\" *") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1248
	Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x7f917148c210), "LIST \"\" *") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 679
	Mail::IMAPClient::_list_or_lsub(Mail::IMAPClient=HASH(0x7f917148c210), "LIST") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 685
	Mail::IMAPClient::list(Mail::IMAPClient=HASH(0x7f917148c210)) called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 2297
	main::single_sync(HASH(0x7f9172c85f90), HASH(0x7f917000bc10), HASH(0x7f9172c92be0)) called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 1367
Trying command when NOT connected! LastError was: Error sending '25 LIST "" *': NO not connected at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 123.
	Mail::IMAPClient::LastError(Mail::IMAPClient=HASH(0x7f917148c210), "Error sending '25 LIST \"\" *': NO not connected") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1298
	Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x7f917148c210), "LIST \"\" *") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 679
	Mail::IMAPClient::_list_or_lsub(Mail::IMAPClient=HASH(0x7f917148c210), "LIST") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 685
	Mail::IMAPClient::list(Mail::IMAPClient=HASH(0x7f917148c210)) called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 2297
	main::single_sync(HASH(0x7f9172c85f90), HASH(0x7f917000bc10), HASH(0x7f9172c92be0)) called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 1367
Use of uninitialized value $_[1] in print at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/IO/Tee.pm line 132.
Host1: folders list (first the raw imap format then the [X] = [Y]):
Use of uninitialized value $_[1] in print at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/IO/Tee.pm line 132.

Host2: folders list (first the raw imap format then the [X] = [Y]):
* LIST (\HasNoChildren \UnMarked) "." Junk
* LIST (\HasNoChildren \UnMarked) "." INBOX.Trash
* LIST (\HasNoChildren \UnMarked) "." INBOX.Junk
* LIST (\HasNoChildren \UnMarked) "." INBOX.Sent
* LIST (\HasNoChildren \UnMarked) "." INBOX.Drafts
* LIST (\HasChildren) "." INBOX
10 OK List completed (0.001 + 0.000 secs).

[INBOX]
[INBOX.Drafts]
[INBOX.Junk]
[INBOX.Sent]
[INBOX.Trash]
[Junk]

Folders in host2 not in host1:
[Junk]
[INBOX.Trash]
[INBOX.Sent]
[INBOX.Junk]
[INBOX.Drafts]
[INBOX]

Checking SEARCH ALL works on both accounts. To avoid that check, use --nochecknoabletosearch
Host1: checking if SEARCH ALL works on INBOX
Trying command when NOT connected! at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 123.
	Mail::IMAPClient::LastError(Mail::IMAPClient=HASH(0x7f917148c210), "NO not connected") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1568
	Mail::IMAPClient::_send_line(Mail::IMAPClient=HASH(0x7f917148c210), "26 SELECT INBOX", 0) called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1344
	Mail::IMAPClient::_imap_command_do(Mail::IMAPClient=HASH(0x7f917148c210), "SELECT INBOX") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1248
	Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x7f917148c210), "SELECT INBOX") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 864
	Mail::IMAPClient::select(Mail::IMAPClient=HASH(0x7f917148c210), "INBOX") called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 9695
	main::select_folder(HASH(0x7f9172c85f90), Mail::IMAPClient=HASH(0x7f917148c210), "INBOX", "Host1") called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 4747
	main::checknoabletosearch(HASH(0x7f9172c85f90), Mail::IMAPClient=HASH(0x7f917148c210), "INBOX", "Host1") called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 2358
	main::single_sync(HASH(0x7f9172c85f90), HASH(0x7f917000bc10), HASH(0x7f9172c92be0)) called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 1367
Trying command when NOT connected! LastError was: NO not connected at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 123.
	Mail::IMAPClient::LastError(Mail::IMAPClient=HASH(0x7f917148c210), "Error sending '26 SELECT INBOX': NO not connected") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1345
	Mail::IMAPClient::_imap_command_do(Mail::IMAPClient=HASH(0x7f917148c210), "SELECT INBOX") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1248
	Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x7f917148c210), "SELECT INBOX") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 864
	Mail::IMAPClient::select(Mail::IMAPClient=HASH(0x7f917148c210), "INBOX") called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 9695
	main::select_folder(HASH(0x7f9172c85f90), Mail::IMAPClient=HASH(0x7f917148c210), "INBOX", "Host1") called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 4747
	main::checknoabletosearch(HASH(0x7f9172c85f90), Mail::IMAPClient=HASH(0x7f917148c210), "INBOX", "Host1") called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 2358
	main::single_sync(HASH(0x7f9172c85f90), HASH(0x7f917000bc10), HASH(0x7f9172c92be0)) called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 1367
Trying command when NOT connected! LastError was: Error sending '26 SELECT INBOX': NO not connected at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 123.
	Mail::IMAPClient::LastError(Mail::IMAPClient=HASH(0x7f917148c210), "Error sending '26 SELECT INBOX': NO not connected") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 1298
	Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x7f917148c210), "SELECT INBOX") called at /usr/local/Cellar/imapsync/2.229_1/libexec/lib/perl5/Mail/IMAPClient.pm line 864
	Mail::IMAPClient::select(Mail::IMAPClient=HASH(0x7f917148c210), "INBOX") called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 9695
	main::select_folder(HASH(0x7f9172c85f90), Mail::IMAPClient=HASH(0x7f917148c210), "INBOX", "Host1") called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 4747
	main::checknoabletosearch(HASH(0x7f9172c85f90), Mail::IMAPClient=HASH(0x7f917148c210), "INBOX", "Host1") called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 2358
	main::single_sync(HASH(0x7f9172c85f90), HASH(0x7f917000bc10), HASH(0x7f9172c92be0)) called at /usr/local/Cellar/imapsync/2.229_1/libexec/bin/imapsync line 1367
Host1 folder INBOX: Could not select: Error sending '26 SELECT INBOX': NO not connected
Host1: can not SELECT folder [INBOX]
Host2: checking if SEARCH ALL works on INBOX
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
DEBUG: .../IO/Socket/SSL.pm:1177: global error: Undefined SSL object
Host2: folder [INBOX] has 0 messages mentioned by SELECT
Host2: folder [INBOX] has 0 messages found by SEARCH ALL
Host2: folder [INBOX] has the same messages count (0) by SELECT and SEARCH ALL
Good! SEARCH ALL works on both accounts.

Folders sizes before the synchronization. It can take some time. Be patient.
You can remove foldersizes listings by using "--nofoldersizes" and "--nofoldersizesatend"
but then you will also lose the ETA (Estimation Time of Arrival) given after each message copy.
Host1 Nb folders:                     0 folders
Host2 Nb folders:                     0 folders

Host1 Nb messages:                    0 messages
Host2 Nb messages:                    0 messages

Host1 Total size:                     0 bytes (0.000 KiB)
Host2 Total size:                     0 bytes (0.000 KiB)

Host1 Biggest message:                0 bytes (0.000 KiB)
Host2 Biggest message:                0 bytes (0.000 KiB)

Time spent on sizing:        39.3 seconds
++++ Looping on each one of 0 folders to sync
ETA: Friday 23 June 2023-06-23 10:40:11 -0400 EDT  0 s  0/0 msgs left
++++ End looping on each folder

Folders sizes after the synchronization.
You can remove this foldersizes listing by using  "--nofoldersizesatend"
++++ Statistics
Transfer started on                     : Friday 23 June 2023-06-23 10:39:32 -0400 EDT
Transfer ended on                       : Friday 23 June 2023-06-23 10:40:11 -0400 EDT
Transfer time                           : 39.3 sec
Folders synced                          : 0/0 synced
Messages transferred                    : 0 (could be 0 without dry mode)
Messages skipped                        : 0
Messages found duplicate on host1       : 0
Messages found duplicate on host2       : 0
Messages found crossduplicate on host2  : 0
Messages void (noheader) on host1       : 0  
Messages void (noheader) on host2       : 0
Messages found in host1 not in host2    : 0 messages
Messages found in host2 not in host1    : 0 messages
Messages deleted on host1               : 0
Messages deleted on host2               : 0
Total bytes transferred                 : 0 (0.000 KiB)
Total bytes skipped                     : 0 (0.000 KiB)
Message rate                            : 0.0 messages/s
Average bandwidth rate                  : 0.0 KiB/s
Reconnections to host1                  : 0
Reconnections to host2                  : 0
Memory consumption at the end           : 207.4 MiB (*time 2.3 MiB*h) (started with 188.3 MiB)
Load end is                             : 4.14 5.29 12.80 on 8 cores
CPU time and %cpu                       : 1.48 sec 3.8 %cpu 0.5 %allcpus
Biggest message transferred             : 0 bytes (0.000 KiB)
Memory/biggest message ratio            : NA
Start difference host2 - host1          : 0 messages, 0 bytes (0.000 KiB)
Final difference host2 - host1          : NA messages, NA bytes (NA)
The sync is strict, all 0 identified messages in host2 are on host1.
Detected 1 errors
This imapsync is up to date. ( local 2.229 >= official 2.229 )( Use --noreleasecheck to avoid this release check. )
Homepage: https://imapsync.lamiral.info/
++++ Listing 1 errors encountered during the sync ( avoid this listing with --noerrorsdump ).
Err 1/1: Host1 folder INBOX: Could not select: Error sending '26 SELECT INBOX': NO not connected
The most frequent error is ERR_SELECT. 
Failure: lost connection for host1 [outlook.office365.com]: (len=49) Error sending '26 SELECT INBOX': NO not connected
Exiting with return value 117 (EXIT_ERR_SELECT) 2/50 nb_errors/max_errors PID 26058
Removing pidfile /var/folders/cq/m8s5hw5d279fxj1ghbmbq7000000gn/T/imapsync.pid

**Comment by gilleslamiral** [comment]
Well a failure on a simple ` SELECT INBOX` is strange and a sign something is missing in this access.
The folder INBOX always exists and should always be selectable in a workable mailbox.

Can you access it with another imap software client like Thunderbird?

Found two items related in:
https://imapsync.lamiral.info/FAQ.d/FAQ.Office365.txt
````
======================================================================
Q. Office365 fails with "User is authenticated but not connected".

R1. "The message User is authenticated but not connected is due to a 
   bug in the Office365 server's IMAP implementation. If the client 
   presents a valid user name but an invalid password, the server 
   accepts the login, but subsequent commands fail with the 
   aforementioned error message." Source:
https://unix.stackexchange.com/questions/164823/user-is-authenticated-but-not-connected-after-changing-my-exchange-password
Thanks to James Abbottsmith for this link and explanation at
https://github.com/imapsync/imapsync/issues/32#issuecomment-153561647

R2. Miguel Alameda reported understanding and solving this issue 
    like this, the context was admin/authuser:
    "The admin user had not permission in the target mailbox."

======================================================================
````
Second one
````
======================================================================
Q. The sync fails with many "Trying command when NOT connected!".
   What can I do?

R. The --debugimap option can show you more details, especially 
   messages like this one:
   "BAD Request is throttled. Suggested Backoff Time: 178755 milliseconds"
   In that case, see the next faq item and its fixes.

======================================================================
````

**Comment by andersonmm** [comment]
You gave me a clue. I was running IMAPsync on a non-admin mailbox but authenticating to O365 with an admin email for the token. I just ran on an admin mailbox and used same admin user to acquire token, and it ran successfully! Anyway, it is currently moving 5000 messages.

**Comment by andersonmm** [comment]
Boom

`The sync looks good, all 5009 identified messages in host1 are on host2.
There is no unidentified message on host1.
The sync is strict, all 5009 identified messages in host2 are on host1.
Detected 0 errors`

Merci Gilles. I'll report back on non-admins and token regeneration.

**Comment by gilleslamiral** [comment]
Champagne!

**Comment by andersonmm** [comment]
New error on large admin user:

`Host1: folder INBOX : Could not fetch_hash 109795 msgs: Error sending '170 UID FETCH 3,6:39,41:107,109:121,123:125,127:134,136:142,144:160,163:165,167:1...92:24310,24312:24327,24329:24790,24792:24894 (FLAGS INTERNALDATE RFC822.SIZE)': NO not connected`

**Comment by gilleslamiral** [comment]
What happens on next run? same issue?

**Comment by andersonmm** [comment]
No, it ran fine next time.

**Comment by gilleslamiral** [comment]
Great!
