### ISSUE TITLE
How do you sync accounts in a csv on Windows with passwords using weird chars?

### ISSUE THREAD

**Issue by MarceloPedra** [imapsync/imapsync#405]
Hi there guys, I use to migrate accounts using the csv file running the DOS command in my Windows PC.
Today I have to migrate a series of email accounts where the passwords has semicolons within the string, and the csv file is rejecting due to the misspelled string. It fails even if I enclose the string with quotation marks.

Example:
192.168.0.1;info@somedomain.com;"cvw47P2$^;%?R";192.168.1.1;info@somedomain.com;"cvw47P2$^;%?R"

Notice that I have no access to the source server, so changing password to a simpler combination is not feasible.
What would you suggest?

**Comment by gilleslamiral** [comment]
Try with an unused character as the separator

https://imapsync.lamiral.info/examples/sync_loop_windows.bat
...
````
@FOR /F "tokens=1,2,3,4,5,6,7 delims=; eol=#" %%G IN (%csvfile%) DO (
````
There is `delims=;` in the previous line.

Now good luck to find an unused character as the separator...

**Comment by MarceloPedra** [comment]
Thank you very much! It worked, nice workaround :-)

**Comment by gilleslamiral** [comment]
Great!
