### ISSUE TITLE
Gmail - INBOX Label/Folder - Avoiding Duplicates

### ISSUE THREAD

**Issue by dbrennand** [imapsync/imapsync#414]
Hi there,

Firstly, thanks for continuing to maintain this tool. It has potentially saved me A LOT of time. So thank you!

I recently performed a sync from Gmail to another provider and it worked very well 🙂 However, one issue which I didn't realise was that Gmail has a default `INBOX` label which has taken precedence over my custom label applied to an email... 😞   Reading the FAQ further, I now understand why this has happened:

Extract from https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt:

```
An issue with --skipcrossduplicates is that the first label synced by
imapsync goes to its corresponding folder but other labels are then
ignored. You can choose what labels have priority by using the
--folderfirst option. For example, --folderfirst "Work" will sync
messages labelled "Work" before messages labelled "CanWait" or
"Urgent". By default imapsync syncs folders (Gmail labels) using the
classical alphanumeric order.
```

Furthermore, I understand that for my desired behaviour, I *should* have initially used:

```
... --gmail1 --folderlast 'INBOX'
```

However, now that these emails have transferred, I'm not sure what the best approach is to re-sync these emails with my custom label, and also **not** have them as duplicates (as they are now on the destination email account) with the `INBOX` label?

Any assistance is greatly appreciated.

**Comment by dbrennand** [comment]
Resolved this by running `... --delete1 --noexpungeaftereach` on the destination mail account to remove all emails. Then performed another fresh sync with:

```
imapsync --errorsmax 200 --user1 mail1 --password1 "" --host2 host2 --ssl2 --user2 mail2 --password2 "" --gmail1 --folderlast "INBOX" --folderlast "[Gmail]/All Mail"
```

**Comment by gilleslamiral** [comment]
> Resolved this by running `... --delete1 --noexpungeaftereach` on the destination mail account to remove all emails. 

Ok. 
You were able to delete all the messages at the destination, it's less challenging than keeping new ones coming from elsewhere.

> Then performed another fresh sync with:
> 
> ```
> imapsync --errorsmax 200 --user1 mail1 --password1 "" --host2 host2 --ssl2 --user2 mail2 --password2 "" --gmail1 --folderlast "INBOX" --folderlast "[Gmail]/All Mail"
> ```

With --delete2 added, you could have done the deletions on the same sync with some bandwidth gain compared to the primary deletion of all the messages.

Without the possibility of deleting all the messages. it's trickier.
