### ISSUE TITLE
starttls does not work as expected

### ISSUE THREAD

**Issue by slemke76** [imapsync/imapsync#42]
Hello,

I have a problem using imapsync with the german hoster "hetzner" - the starttls sequence is not being started correctly. I have already tried several command line options without success. It seems the sequence is not being initiated correctly. 
After "1 OK Begin TLS negotiation now" the Negotiation does NOT take place.
I tried also older versions of imapsync ans also the last one from the git repository without success.

If needed I can provide a mail-account on that server.

Here is my console log:
root@hetzner1:~/mailSync# ./sync_loop_unix.sh
Looping on account credentials found in file.txt

==== Syncing user sourcebox@ims-firmen.de to user targetbox@mail.your-server.de ====
Transfer started at Thu Oct 29 18:18:59 2015
PID is 14789
Log file is LOG_imapsync/2015_10_29_18_18_59_targetbox@mail.your-server.de.txt  ( to change it, use --logfile filepath ; or use --nolog to turn off logging )
$RCSfile: imapsync,v $ $Revision: 1.644 $ $Date: 2015/07/17 01:22:52 $
Here is a [linux] system (Linux someserver.internet.local 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64)
With perl 5.10.1 Mail::IMAPClient  3.34
Command line used:
./imapsync --host1 mail.ims-firmen.de --user1 sourcebox@ims-firmen.de --password1 MASKED --host2 mail.your-server.de --user2 targetbox@mail.your-server.de --password2 MASKED --tls2 --port2 143 --debugimap2 --usecache --useuid --tmpdir ./cache
Temp directory is ./cache  ( to change it use --tmpdir dirpath )
PID file is ./cache/imapsync.pid ( to change it use --pidfile filepath ; to avoid it use --pidfile "" )
Modules version list:
Mail::IMAPClient     3.34
IO::Socket           1.31
IO::Socket::IP       ?
IO::Socket::INET     1.31
IO::Socket::SSL      1.31
Net::SSLeay          1.35
Compress::Zlib       2.021
Digest::MD5          2.39
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.01
Term::ReadKey        2.30
File::Spec           3.3
Time::HiRes          1.9721
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         ?
URI::Escape          3.29
Data::Uniqid         ?
JSON::WebToken       ?
( use --no-modules_version to turn off printing this Perl modules list )
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Info: will try to use LOGIN authentication on host1
Info: will try to use LOGIN authentication on host2
Info: imap connexions timeout is 120 seconds
Host1: IMAP server [mail.ims-firmen.de] port [143] user [sourcebox@ims-firmen.de]
Host2: IMAP server [mail.your-server.de] port [143] user [targetbox@mail.your-server.de]
Host1: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.
Host1: mail.ims-firmen.de says it has CAPABILITY for AUTHENTICATE LOGIN
Host1: success login on [mail.ims-firmen.de] with user [sourcebox@ims-firmen.de] auth [LOGIN]
Host2 connection
Connecting with IO::Socket::INET PeerAddr mail.your-server.de PeerPort 143 Proto tcp Timeout 120 Debug 1
Connected to mail.your-server.de
Read:   * OK [CAPABILITY IMAP4 IMAP4rev1 STARTTLS UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION] perdition ready on sslproxy01.your-server.de 0002f017
Host2: * OK [CAPABILITY IMAP4 IMAP4rev1 STARTTLS UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION] perdition ready on sslproxy01.your-server.de 0002f017
Sending: 1 STARTTLS
Sent 12 bytes
Read:   1 OK Begin TLS negotiation now
Sending: 2 CAPABILITY
Sent 14 bytes
Read:   * CAPABILITY IMAP4 IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION
Read:   2 OK CAPABILITY
Host2: mail.your-server.de says it has NO CAPABILITY for AUTHENTICATE LOGIN
Sending literal: 3 LOGIN targetbox@mail.your-server.de {13}
        then: itsmypassword
Sending: 3 LOGIN targetbox@mail.your-server.de {13}
Sent 44 bytes
Read:   + OK ready for additional input
Sending: itsmypassword
Sent 14 bytes
Read:   3 NO failed: Re-Authentication Failure
ERROR: 3 NO failed: Re-Authentication Failure at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1364
        Mail::IMAPClient::__ANON__('3 NO failed: Re-Authentication Failure\x{d}\x{a}') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1400
        Mail::IMAPClient::_get_response('Mail::IMAPClient=HASH(0x121c230)', 3, undef) called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1326
        Mail::IMAPClient::_imap_command_do('Mail::IMAPClient=HASH(0x121c230)', 'LOGIN targetbox@mail.your-server.de {13}\x{d}\x{a}itsmypassword\x{d}') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1225
        Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x121c230)', 'LOGIN targetbox@mail.your-server.de {13}\x{d}\x{a}itsmypassword\x{d}') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 576
        Mail::IMAPClient::login('Mail::IMAPClient=HASH(0x121c230)') called at ./imapsync line 2269
        main::authenticate_imap('Mail::IMAPClient=HASH(0x121c230)', 'mail.your-server.de', 143, 'targetbox@mail.your-server.de', undef, 'itsmypassword\x{d}', 1, 120, 0, ...) called at ./imapsync line 2236
        main::login_imap('mail.your-server.de', 143, 'targetbox@mail.your-server.de', undef, 'itsmypassword\x{d}', 1, 120, 0, undef, ...) called at ./imapsync line 1017
ERROR: 3 NO failed: Re-Authentication Failure at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1274
        Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x121c230)', 'LOGIN targetbox@mail.your-server.de {13}\x{d}\x{a}itsmypassword\x{d}') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 576
        Mail::IMAPClient::login('Mail::IMAPClient=HASH(0x121c230)') called at ./imapsync line 2269
        main::authenticate_imap('Mail::IMAPClient=HASH(0x121c230)', 'mail.your-server.de', 143, 'targetbox@mail.your-server.de', undef, 'itsmypassword\x{d}', 1, 120, 0, ...) called at ./imapsync line 2236
        main::login_imap('mail.your-server.de', 143, 'targetbox@mail.your-server.de', undef, 'itsmypassword\x{d}', 1, 120, 0, undef, ...) called at ./imapsync line 1017
Failure: error login on [mail.your-server.de] with user [targetbox@mail.your-server.de] auth [LOGIN]: 3 NO failed: Re-Authentication Failure
==== End syncing user sourcebox@ims-firmen.de to user targetbox@mail.your-server.de ====

Thanks,
Sebastian

**Comment by gilleslamiral** [comment]
Hi Sebastian,

What makes you believe the Negotiation did not take place?
It look like it's just a normal authentication issue
with error message"NO failed: Re-Authentication Failure" from the server.

Do the exact same credentials work with a classic imap client like Thunderbird
or Outlook in imap?

On 29/10/2015 18:27, slemke76 wrote:
> Hello,
>
> I have a problem using imapsync with the german hoster "hetzner" - the starttls sequence is not being started correctly. I have already tried several command line options without success. It seems the sequence is not being initiated correctly.
> After "1 OK Begin TLS negotiation now" the Negotiation does NOT take place.
> I tried also older versions of imapsync ans also the last one from the git repository without success.
>
> Sending: 3 LOGIN targetbox@mail.your-server.de <mailto:targetbox@mail.your-server.de> {13}
> Sent 44 bytes
> Read: + OK ready for additional input
> Sending: xxx
> Sent 14 bytes
> Read: 3 NO failed: Re-Authentication Failure

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by slemke76** [comment]
Good evening,

thanks for the quick reply. I have checked the credentials in Thunderbird without problems. 
This is what I am wondering about:

v1.644:
Sending: 1 STARTTLS
Sent 12 bytes
Read:   1 OK Begin TLS negotiation now
Sending: 2 CAPABILITY

v1.516
Read: * OK [CAPABILITY IMAP4 IMAP4rev1 STARTTLS UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION] perdition ready on sslproxy01.your-server.de 0002f017
Entering starttls
Sending: 1 CAPABILITY
Sent 14 bytes
Read:   * CAPABILITY IMAP4 IMAP4rev1 STARTTLS UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION
Read:   1 OK CAPABILITY
Read tls: z00 OK Begin TLS negotiation now
Calling start_SSL
Socket successfuly converted to SSL
Ending starttls


With 1.644 I miss the "Socket successfuly converted to SSL" output or is it simply to being displayed?
It seems to me after "1 OK Begin TLS negotiation now" imapsync responds with "CAPABILITY" ?

Regards,
Sebastian

**Comment by slemke76** [comment]
Some additional Information: 
The Provider is "Hetzner" - I have just tested it with another account, double checked with thunderbird, same problem.

**Comment by slemke76** [comment]
Back again.

I am sorry. Finally found it. I am using the file.txt from the examples-subdir of the imapsync-1.644.tgz tarball. But - this is a DOS-Style-File with CR LF. 
Using this DOS-Styled file.txt on a Linux-System causes the same problems as described in sync_loop_unix.sh - after adding the fake parameter everything works fine (I could also convert file.txt to a unix-style file). 
Perhaps it´s a good idea to use everytime the fake-parameter? This would work in all scenarios.
Perhaps it´s also a good idea to move the host1 and host2 parameter also to file.txt? 
If you would like, I can provide new samples for this.

Sebastian

**Comment by gilleslamiral** [comment]
Hi,

It's just because STARTTLS was done directly in imapsync before.
Now it's done directly by the underlying Mail::IMAPClient
Ok, I'll add back "Socket successfuly converted to SSL".

On 29/10/2015 19:28, slemke76 wrote:
> Good evening,
>
> thanks for the quick reply. I have checked the credentials in Thunderbird without problems.
> This is what I am wondering about:
>
> v1.644:
> Sending: 1 STARTTLS
> Sent 12 bytes
> Read: 1 OK Begin TLS negotiation now
> Sending: 2 CAPABILITY
>
> v1.516
> Read: * OK [CAPABILITY IMAP4 IMAP4rev1 STARTTLS UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION] perdition ready on sslproxy01.your-server.de 0002f017
> Entering starttls
> Sending: 1 CAPABILITY
> Sent 14 bytes
> Read: * CAPABILITY IMAP4 IMAP4rev1 STARTTLS UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION
> Read: 1 OK CAPABILITY
> Read tls: z00 OK Begin TLS negotiation now
> Calling start_SSL
> Socket successfuly converted to SSL
> Ending starttls
>
> With 1.644 I miss the "Socket successfuly converted to SSL" output or is it simply to being displayed?
> It seems to me after "1 OK Begin TLS negotiation now" imapsync responds with "CAPABILITY" ?


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by slemke76** [comment]
Sorry for the confusion.
Sebastian

**Comment by gilleslamiral** [comment]
Hi Sebastian,

> I am sorry. Finally found it. I am using the file.txt from the examples-subdir of the imapsync-1.644.tgz tarball.
>But - this is a DOS-Style-File with CR LF.

Ah yes. I consider Windows users less technically aware of this issue
or more likely my last tests about this file were on Windows.

> Using this DOS-Styled file.txt on a Linux-System causes the same problems as described
>in sync_loop_unix.sh - after adding the fake parameter everything works fine
>(I could also convert file.txt to a unix-style file).

Ok.

> Perhaps it´s a good idea to use everytime the fake-parameter? This would work in all scenarios.

Yes. Good point.

> Perhaps it´s also a good idea to move the host1 and host2 parameter also to file.txt?

I am sure, the more variable parameters the

> If you would like, I can provide new samples for this.

I'll surely consider them.

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by slemke76** [comment]
Hello,

my files are attached.

These are the changes:
#  - Added host1 and host2 in file.txt
#  - Added fake paremeter for preventing CR character goes in p2 
variable on **nix systems with dos-styled file.txt
#  - Added possibility to provide additional parameters to pass to 
imapsync
#  - changed call to ./imapsync instead of imapsync
You can remove my name from the file, I have added it for internal 
documentation proposes.

I have added the possibility to pass command line options through the 
script towards to imapsync.
So the user do not have to make any changes to the script itself.
Therefore it makes sense to move the mail-host also into file.txt.

imapsync is a fantastic piece of software. I am happy to give something 
"back".


Grüße,
Sebastian Lemke



infoworxx GmbH // integrated IT-Solutions
Alenconer Straße 30 // 49610 Quakenbrück
Tel.: 05431-90777-7 // Fax: 05431-90777-99
http://www.infoworxx.de <http://www.infoworxx.de/> // 
s.lemke@infoworxx.de

Geschäftsführender Gesellschafter: Sebastian Lemke
Amtsgericht Osnabrück HRB 203731




------ Originalnachricht ------
Von: "Gilles LAMIRAL" <notifications@github.com>
An: "imapsync/imapsync" <imapsync@noreply.github.com>
Cc: "slemke76" <s.lemke@infoworxx.de>
Gesendet: 31.10.2015 14:16:33
Betreff: Re: [imapsync] starttls does not work as expected (#42)

>Hi Sebastian,
>
> > I am sorry. Finally found it. I am using the file.txt from the 
>examples-subdir of the imapsync-1.644.tgz tarball.
> >But - this is a DOS-Style-File with CR LF.
>
>Ah yes. I consider Windows users less technically aware of this issue
>or more likely my last tests about this file were on Windows.
>
> > Using this DOS-Styled file.txt on a Linux-System causes the same 
>problems as described
> >in sync_loop_unix.sh - after adding the fake parameter everything 
>works fine
> >(I could also convert file.txt to a unix-style file).
>
>Ok.
>
> > Perhaps it´s a good idea to use everytime the fake-parameter? This 
>would work in all scenarios.
>
>Yes. Good point.
>
> > Perhaps it´s also a good idea to move the host1 and host2 parameter 
>also to file.txt?
>
>I am sure, the more variable parameters the
>
> > If you would like, I can provide new samples for this.
>
>I'll surely consider them.
>
>--
>Au revoir, 09 51 84 42 42
>Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
>—
>Reply to this email directly or view it on GitHub.
>
# Example file.txt for imapsync massive migration.
#
# Each line contains 6 columns, columns are parameters for --host1 --user1 --password1 --host2 --user2 --password2
#
# IMPORTANT: Every line needs an ending ";" !!!!
#
mail.host1.de;user1@host1.de;secret1;mail.host2.de;user2@host2.de;secret2;

**Comment by gilleslamiral** [comment]
Hi Sebastian,

> These are the changes:
> # - Added host1 and host2 in file.txt
> # - Added fake parameter for preventing CR character goes in p2
> variable on **nix systems with dos-styled file.txt
> # - Added possibility to provide additional parameters to pass to
> imapsync
> I have added the possibility to pass command line options through the
> script towards to imapsync.
> So the user do not have to make any changes to the script itself.
> Therefore it makes sense to move the mail-host also into file.txt.

All added and tested upstream.

> # - changed call to ./imapsync instead of imapsync

Not changed.

> You can remove my name from the file, I have added it for internal
> documentation proposes.

You're now named you in CREDITS file.
http://imapsync.lamiral.info/CREDITS
(after next publish)

> imapsync is a fantastic piece of software. I am happy to give something
> "back".

Thanks to you!

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by slemke76** [comment]
Hello,

very nice - Thanks a lot.
Have you also adapted the windows-version of the script?
If not, should I do so?
Grüße,
Sebastian Lemke



infoworxx GmbH // integrated IT-Solutions
Alenconer Straße 30 // 49610 Quakenbrück
Tel.: 05431-90777-7 // Fax: 05431-90777-99
http://www.infoworxx.de // s.lemke@infoworxx.de

Geschäftsführender Gesellschafter: Sebastian Lemke
Amtsgericht Osnabrück HRB 203731





------ Originalnachricht ------
Von: "Gilles LAMIRAL" <notifications@github.com>
An: "imapsync/imapsync" <imapsync@noreply.github.com>
Cc: "slemke76" <s.lemke@infoworxx.de>
Gesendet: 04.11.2015 19:36:30
Betreff: Re: [imapsync] starttls does not work as expected (#42)

**Comment by gilleslamiral** [comment]
Hi Sebastian,

> Have you also adapted the windows-version of the script?

Yes, and tested it.

In fact, while playing with the changes and noticing I don't know how to
add "$@" in a batch file, I though it could be a nice thing to add
a seventh field in file.txt that would contain all extra parameters.
This way, extra parameters could be specific per transfer, if needed,
and still no change to be made in the loop script.




-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by slemke76** [comment]
Good Morning,

this will work this way for Windows/DOS-Scripts (just tested) - the 
magic is the "shift" command:

@echo off

rem used for local variables (%arguments%)
setlocal enabledelayedexpansion
rem empty agruments (it could be that some other script has used it 
before)
set arguments=

if %1. EQU . (
     echo.
     echo Usage:
     echo.
     echo %~0 param1 param2 ... paramx
     echo.
     goto end
)

:args_loop
set arguments=%arguments% %1

shift
if %1. NEQ . goto args_loop

:args_loop_end

echo %arguments%

:end


After all in %arguments% are all command line arguments.

My personal option is that it´s better to provide the arguments on the 
command line, but it´s the same discussion as the mail-host ;-)

Have a nice day!





Grüße,
Sebastian Lemke



infoworxx GmbH // integrated IT-Solutions
Alenconer Straße 30 // 49610 Quakenbrück
Tel.: 05431-90777-7 // Fax: 05431-90777-99
http://www.infoworxx.de // s.lemke@infoworxx.de

Geschäftsführender Gesellschafter: Sebastian Lemke
Amtsgericht Osnabrück HRB 203731





------ Originalnachricht ------
Von: "Gilles LAMIRAL" <notifications@github.com>
An: "imapsync/imapsync" <imapsync@noreply.github.com>
Cc: "slemke76" <s.lemke@infoworxx.de>
Gesendet: 12.11.2015 06:36:21
Betreff: Re: [imapsync] starttls does not work as expected (#42)

**Comment by gilleslamiral** [comment]
Hi Sebastian,

Thanks fir the tip!
I added arguments stuff in the batch and tested it.

http://imapsync.lamiral.info/examples/sync_loop_windows.bat

On 12/11/2015 08:46, slemke76 wrote:
> Good Morning,
>
> this will work this way for Windows/DOS-Scripts (just tested) - the
> magic is the "shift" command:
>
> @echo off
>
> rem used for local variables (%arguments%)
> setlocal enabledelayedexpansion
> rem empty agruments (it could be that some other script has used it
> before)
> set arguments=
>
> if %1. EQU . (
> goto end
> )
>
> :args_loop
> set arguments=%arguments% %1
> shift
> if %1. NEQ . goto args_loop
> echo %arguments%
> :end
>
>
> After all in %arguments% are all command line arguments.
>
> My personal option is that it´s better to provide the arguments on the
> command line, but it´s the same discussion as the mail-host ;-)


> ------ Originalnachricht ------
> Von: "Gilles LAMIRAL" <notifications@github.com>
> An: "imapsync/imapsync" <imapsync@noreply.github.com>
> Cc: "slemke76" <s.lemke@infoworxx.de>
> Gesendet: 12.11.2015 06:36:21
> Betreff: Re: [imapsync] starttls does not work as expected (#42)
>
>>Hi Sebastian,
>>
>> > Have you also adapted the windows-version of the script?
>>
>>Yes, and tested it.
>>
>>In fact, while playing with the changes and noticing I don't know how
>>to
>>add "$@" in a batch file, I though it could be a nice thing to add
>>a seventh field in file.txt that would contain all extra parameters.
>>This way, extra parameters could be specific per transfer, if needed,
>>and still no change to be made in the loop script.

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
