### ISSUE TITLE
Question: Deleting what was not synced only from host1

### ISSUE THREAD

**Issue by terba** [imapsync/imapsync#421]
I'm building an email backup and archive solution for family emails. My goal is to keep 2 years of mail in sync with host2 and delete mail older than 2 years from host1 but preserve them on host2. I would like to ask if it's possible somehow based on the command below, or it is only possible in 2 steps, so starting an another imapsync just to delete from host1 what is older than 2 years (by syncing server1 to server1 with --delete1 and --minage 730, not tested yet).

```sh
imapsync --maxage 730 --delete2 --host1 server1 --user1 myuser@mydomain.org --password1 abc --host2 server2 --user2 myuser@mydomain.org --password2 abc
```

This makes the last 2 years synced on server2 and doesn't touch anything older on both. But I would like to delete older on server1 only and keeping them on server2.

Thanks in advance.

**Comment by gilleslamiral** [comment]
You need two commands with imapsync to achieve your goal, exactly like you mentioned.

Why keep old emails not easily accessible?

**Comment by terba** [comment]
Thanks for the answer.

> Why keep old emails not easily accessible?

To spare on paid storage, so a cheaper hosting plan is enough. The archive on home server is also easily accessible via IMAP or RoundCube from home LAN when rarely needed.
