### ISSUE TITLE
Changelog version 2.269

### ISSUE THREAD

**Issue by Jip-Hop** [imapsync/imapsync#423]
Hi Gilles,

I'm looking for the changelog of version 2.269. This currently is the only version remaining on Docker Hub:
https://hub.docker.com/r/gilleslamiral/imapsync/tags
And I can see this is also the version currently used on:
https://imapsync.lamiral.info/X/

I'm currently using the gilleslamiral/imapsync:2.257 docker image (which is no longer available) and I'd be interested to know what changed between this version and the current version.

Would you be able to share the changelog here or could you update [the news page](https://imapsync.lamiral.info/S/news.shtml)?

Thanks in advance.

**Comment by gilleslamiral** [comment]
https://imapsync.lamiral.info/ChangeLog
This link is present at
https://imapsync.lamiral.info/S/news.shtml
near the beginning
See [ChangeLog](https://imapsync.lamiral.info/ChangeLog) to read what has been done in detail since 2001.

**Comment by Jip-Hop** [comment]
Thanks but those links mention nothing about version 2.269.

**Comment by gilleslamiral** [comment]
Just updated  https://imapsync.lamiral.info/ChangeLog

**Comment by Jip-Hop** [comment]
Thanks!

**Comment by Jip-Hop** [comment]
Hi Gilles. Would you be able to update the changelog for the just released [2.271](https://hub.docker.com/layers/gilleslamiral/imapsync/2.271/images/sha256-59a0255cdf93d79979ab0fc2154031ac4ff42df9ee903ded44d5d43c88681d4c?context=explore) version?

**Comment by gilleslamiral** [comment]
https://imapsync.lamiral.info/ChangeLog
````
total revisions: 1171;	selected revisions: 1171
description:
----------------------------
revision 2.271	locked by: gilles;
date: 2023/11/30 18:51:58;  author: gilles;  state: Exp;  lines: +110 -58
Bugfix. Button "Abort!" now working in Docker+CGI context. Added a pid file in that context.
2092 unit tests.
----------------------------
revision 2.270
date: 2023/11/25 20:34:53;  author: gilles;  state: Exp;  lines: +301 -245
Added in final stats the number of Folders deleted on host2
Added in final stats the number of Folders failed to be deleted on host2, if any
Refactoring. Deglobalized $delete2folders $delete2foldersonly $delete2foldersbutnot
----------------------------

````

**Comment by gilleslamiral** [comment]
Hi Jip!
I updated the Makefile to generate and upload the ChangeLog file as a prerequisite to a new docker imapsync image release.
So, you shouldn't report this lack here anymore.

**Comment by Jip-Hop** [comment]
Thanks! That's great :)
