### ISSUE TITLE
SSL_verify_mode must be a number and not a string

### ISSUE THREAD

**Issue by markk** [imapsync/imapsync#43]
Having just upgraded to Fedora 23 I am getting this new error when running imapsync.

```
get options: [1]
date_str: 2015_11_13_09_27_27
Transfer started at Fri Nov 13 09:27:27 2015
PID is 29282
check_last_release: [1.644]
$RCSfile: imapsync,v $ $Revision: 1.644 $ $Date: 2015/07/17 01:22:52 $ 
Here is a [linux] system (Linux localhost 4.2.5-300.fc23.x86_64 #1 SMP Tue Oct 27 04:29:56 UTC 2015 x86_64)
With perl 5.22.0 Mail::IMAPClient  3.35
Command line used:
/usr/bin/imapsync --nolog --host1 localhost --ssl1 --host2 localhost --justconnect --debug
Temp directory is /tmp  ( to change it use --tmpdir dirpath )
PID file is /tmp/imapsync.pid ( to change it use --pidfile filepath ; to avoid it use --pidfile "" )
Modules version list:
Mail::IMAPClient     3.35
IO::Socket           1.38
IO::Socket::IP       0.37
IO::Socket::INET     1.35
IO::Socket::SSL      2.019
Net::SSLeay          1.71
Compress::Zlib       2.068
Digest::MD5          2.54
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Term::ReadKey        2.33
File::Spec           3.56
Time::HiRes          1.9726
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON::WebToken       ?
( use --no-modules_version to turn off printing this Perl modules list )
IMAPClient 3.35
SSL_verify_mode must be a number and not a string at /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm line 2092.
```

I tried using the constants from IO::Socket::SSL as per this diff:

```patch
485c485
< #use IO::Socket::SSL ;
---
> use IO::Socket::SSL ;
2327c2327
< 		SSL_verify_mode => 'SSL_VERIFY_PEER',
---
> 		SSL_verify_mode => SSL_VERIFY_PEER,
2338c2338
< 		SSL_verify_mode => 'SSL_VERIFY_NONE',
---
> 		SSL_verify_mode => SSL_VERIFY_NONE,
```

...but then the imap connection just fails:

```
IMAPClient 3.35
Can not open imap connection on [localhost]: Unable to connect to localhost: 
```

Thanks!

**Comment by gilleslamiral** [comment]
Try SSL_verify_mode => SSL_VERIFY_NONE
for both.


On 13/11/2015 10:38, markk wrote:
> Having just upgraded to Fedora 23 I am getting this new error when running imapsync.

>> use IO::Socket::SSL ;
> 2327c2327
> < SSL_verify_mode => 'SSL_VERIFY_PEER',
> ---
>>       SSL_verify_mode => SSL_VERIFY_PEER,
> 2338c2338
> < SSL_verify_mode => 'SSL_VERIFY_NONE',
> ---
>>       SSL_verify_mode => SSL_VERIFY_NONE,
>
> ...but then the imap connection just fails:
>
> |IMAPClient 3.35 Can not open imap connection on [localhost]: Unable to connect to localhost: |

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by markk** [comment]
Yes, it works, thanks! But does this effectively disable VERIFY_PEER?

**Comment by gilleslamiral** [comment]
Hi,

On 13/11/2015 13:47, markk wrote:
> Yes, it works, thanks! But does this effectively disable VERIFY_PEER?

Yes, but since your certificate is not valid for "localhost" it
may be  what you need.


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by markk** [comment]
Oh, I was just using localhost there as an example to avoid posting my server details in public... The point is that imapsync will no longer work with perl IO::Socket::SSL as somewhere between version 2.012
and version 2.019 it will die if SSL_verify_mode is a string (instead of a constant).

**Comment by gilleslamiral** [comment]
Hi markk,

This issue is already fixed on my hardisk, for any IO::Socket::SSL version.
Available publicly on next public release then.

On 13/11/2015 18:44, markk wrote:
> Oh, I was just using localhost there as an example to avoid posting my server details in public... The point is that imapsync will no longer work with perl IO::Socket::SSL as somewhere between version 2.012
> and version 2.019 it will die if SSL_verify_mode is a string (instead of a constant).
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/43#issuecomment-156498488>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
