### ISSUE TITLE
could not be fetched: socket closed while reading data from server (4x) The most frequent error is ERR_Host1_FETCH.

### ISSUE THREAD

**Issue by marcelloinfoweb** [imapsync/imapsync#433]
++++ Listing 1 errors encountered during the sync ( avoid this listing with --noerrorsdump ).
Err 1/1: - msg INBOX.Contabilidade/235 {2697452} S[1262838] F[\Seen unknown-3] I[19-Aug-2022 11:06:17 -0300] could not be fetched: socket closed while reading data from server (4x)
The most frequent error is ERR_Host1_FETCH.
Exiting with return value 115 (EXIT_ERR_FETCH) 1/50 nb_errors/max_errors PID 34160

Command:
imapsync --host1 MAILSERVER --user1 SOURCEMAIL --password1 SOURCEPASS --ssl1 --port1 993 --host2 MAILSERVER --user2 SOURCEMAIL --password2  SOURCEPASS --ssl2 --port2 993 --idatefromheader --usecache

HELP please!

**Comment by gilleslamiral** [comment]
What happens on next run?

**Comment by marcelloinfoweb** [comment]
I discovered that the error was an email that did not have the attachment file itself, just the information in the email, that is, the email showed two attachments and when I clicked on one of them it gave an error when opening. I had to export manually, unfortunately.

This error should be handled.

**Comment by gilleslamiral** [comment]
Ok good.
