### ISSUE TITLE
Build fails on Windows  

### ISSUE THREAD

**Issue by defkev** [imapsync/imapsync#44]
Just for the record:
Building on Windows fails will running *make test* for *Unicode::String* with
> t/charname.t ... Can't use 'defined(%hash)' (Maybe you should just omit the defined()?) at C:\STRAWB~1\cpan\build\Unicode-String-2.09-mFsIO0\blib\lib/Unicode/CharName.pm line 80.

According to https://rt.cpan.org/Public/Bug/Display.html?id=74354
> This affects all perls from 5.21.0 onwards

So, use Strawberry Perl 5.20.3.1

Cheers

**Comment by gilleslamiral** [comment]
Hi,

"defined(something)" that goes fatal is just plainly stupid for basic Perl types.
I guess "%hash = undef" does the same if coherence is in mind.
Where goes Perl?

I hope this stupid fatal change will be retracted.

On 16/11/2015 16:59, defkev wrote:
> Just for the record:
> Compilation on Windows fails due to
>
> So, use
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/44>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by gilleslamiral** [comment]
It's Unicode-String bug anyway.
