### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by team-techchef** [imapsync/imapsync#446]
Your website seems down https://imapsync.lamiral.info/X/

**Comment by florenthemmi** [comment]
Works for me! 😃

**Comment by gilleslamiral** [comment]
I changed the DNS provider of lamiral.info from Gandi to OVH. 
I didn't know the timing, just a few minutes, and I believed they would have transferred the zone with their values.
I discovered I was wrong this morning.
It's fixed now.

**Comment by team-techchef** [comment]
Its UP!
