### ISSUE TITLE
Password Starting $

### ISSUE THREAD

**Issue by txt3rob** [imapsync/imapsync#45]
If your password starts with $ it will say output:

```
Option password2 requires an argument
```

**Comment by gilleslamiral** [comment]
Hi Robbie,

Quote the password string.

----- Mail original -----
De: "Robbie" <notifications@github.com>
À: "imapsync/imapsync" <imapsync@noreply.github.com>
Envoyé: Mercredi 18 Novembre 2015 11:17:34
Objet: [imapsync] Password Starting $ (#45)

If your password starts with $ it will say output:

```
Option password2 requires an argument
```

---
Reply to this email directly or view it on GitHub:
https://github.com/imapsync/imapsync/issues/45
