### ISSUE TITLE
Invalid Perl type for string

### ISSUE THREAD

**Issue by RahimRamzanAli** [imapsync/imapsync#455]
Hi,

I have successfully followed your guide to get the token for office365 which part is working. Imapsync is installed and when trying to use this command

imapsync \
  --nosslcheck \
  --host1 outlook.office365.com \
  --user1 test@abc.com \
  --authmech1 XOAUTH2 \
  --password1 "/root/tokens/oauth2_tokens_test@abc.com.txt" \
  --host2 mail.xyz.com \
  --user2 test2@xyz.com \
  --password2 ************
  
  
 I am getting this error, PKCS12_new_from: Invalid Perl type for string or file was passed (0x0). at /usr/bin/imapsync line 8947.

can you please help me to resolve it, Thanks

**Comment by gilleslamiral** [comment]
It's not the recent way to use a token file with imapsync but since you closed the ticket, I guess you figured it out.
