### ISSUE TITLE
Office365 INBOX not synced ?

### ISSUE THREAD

**Issue by gnc-tibo** [imapsync/imapsync#459]
Hello,

I use this command to sync a Microsoft 365 mailbox to another (same tenant) using delegation on my admin account : 
``` imapsync.exe --host1 outlook.office365.com --user1 archive.user@domain.net --authuser1 admin@domain.net --oauthaccesstoken1 tokens\oauth2_tokens.txt --host2 outlook.office365.com --user2 user@domain.net --authuser2 admin@domain.net --oauthaccesstoken2 tokens\oauth2_tokens.txt --delete2duplicates --skipemptyfolders --skipcrossduplicates``` 

Everything works fine except for the inbox and its subfolders.

``` Host1: will not syncing empty folders on host1. Use --noskipemptyfolders to create them anyway on host2
Checking SEARCH ALL works on both accounts. To avoid that check, use --nochecknoabletosearch
Host1: checking if SEARCH ALL works on INBOX
Host1 folder INBOX: Could not select: 10 NO INBOX doesn't exist.
Host1: can not SELECT folder [INBOX]
Host2: checking if SEARCH ALL works on INBOX
Host2: folder [INBOX] has 4 messages mentioned by SELECT
Host2: folder [INBOX] has 4 messages found by SEARCH ALL
Host2: folder [INBOX] has the same messages count (4) by SELECT and SEARCH ALL
Good! SEARCH ALL works on both accounts.
``` 

What can explain this?

Thanks !

**Comment by gnc-tibo** [comment]
Finally found a `Inbox` empty folder at the root of the mailbox.

Deleting it seems to have solved the problem, `INBOX` correctly now !

**Comment by gilleslamiral** [comment]
> Finally found a `Inbox` empty folder at the root of the mailbox.
> 
> Deleting it seems to have solved the problem, `INBOX` syncs correctly now !

Great!
