### ISSUE TITLE
Set logfile-path or logfile?

### ISSUE THREAD

**Issue by JHCD** [imapsync/imapsync#46]
Hi,

there is a confusing description for `--logfile`.

Starting imapsync will write the following line in the logfile:
`Log file is LOG_imapsync/xxx.txt  ( to change it, use --logfile filepath ; or use --nolog to turn off logging )`

The documentation will tell you another truth:
`--logfile     <string> : Change the default logfile pathname and filename.`

Wish:
1.) One correct descripton
2.) It would be nice, when you could set the filepath without a specific filename

Regards,
Jens

**Comment by gilleslamiral** [comment]
Hi Jens,

Ok, is it better with

filepath = dirname + filename.

--logfile <string> : Change the default logfile filepath (dirname + filename).

> Starting imapsync will write the following line in the logfile:
> |Log file is LOG_imapsync/xxx.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )|
>
> The documentation will tell you another truth:
> |--logfile <string> : Change the default logfile pathname and filename.|
>
> 1.) One correct description

Which one?

> 2.) It would be nice, when you could set the filepath without a specific filename

You mean --logdir?


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by JHCD** [comment]
Hi Gilles,

the documentation seems to be the correct description...
So you should change the text in the script (line 672) to the same.

`print "Log file is $logfile  ( to change it, use --logfile pathname and filename; or use --nolog to turn off logging )\n" if ( $log ) ;`

Normaly filepath is only the filedir, not filedir + filename

Regards,
Jens

**Comment by gilleslamiral** [comment]
Hi Jens,

I wonder if using only "path" would be a shorter, clearer solution.
https://en.wikipedia.org/wiki/Path_%28computing%29

During execution:
Log file is $logfile ( to change it, use --logfile path; or use --nolog to turn off logging )

In http://imapsync.lamiral.info/OPTIONS
--logfile <string> : Change the default logfile path.


On 21/11/2015 23:40, Jens Herrmann wrote:
> Hi Gilles,
>
> the documentation seems to be the correct description...
> So you should change the text in the script (line 672) to the same.
>
> |print "Log file is $logfile ( to change it, use --logfile pathname and filename; or use --nolog to turn off logging )\n" if ( $log ) ;|
>
> Normaly filepath is only the filedir, not filedir + filename
>
> Regards,
> Jens
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/46#issuecomment-158688321>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by JHCD** [comment]
Hi Gilles,

I tried wanted to save the logfiles in `/var/log/imapsync` so I tried the following parameters:
```
imapsync \
   --host1 xxx \
   --host2 yyy \
   --sep2 / \
   --prefix2 "" \
   --folderrec Archiv \
   --subfolder2 Sicherung \
   --usecache \
   --pidfilelocking \
   --tmpdir /var/tmp \
   --logfile /var/log/imapsync
```

I get the following error message:
`Can not open /var/log/imapsync for write: Ist ein Verzeichnis at ./imapsync line 6893`

As far as I'm reading the code (line 662):
`$logfile      = defined( $logfile )    ? $logfile : logfile( $timestart, $user2 ) ;`
This will take `--logfile` or call lofgile() to generate the filename, won't it?

And logfile(): will never use a given filepath (line 6851):
`return( "LOG_imapsync/${date_str}${sep}${suffix}.txt" )`

If I set an hard-coded logfile, f.e. `/var/log/imapsync/logfile.txt` the script works, but there will be no separated logfile for every call.

For me it is fine, when you could set only a specific filepat+filename and not only a filepath, but than you have to correct the documentation. Or you could implement `--logfilepath`.

As workaround I have changed line 6851 to hard coded `/var/log/imapsync/`

Regards,
Jens

**Comment by gilleslamiral** [comment]
Hi Jens,

You still don't understand the --logfile parameter
--logfile is not --logdir and --logdir doesn't exist.

The current usage is either the logfile is set by imapsync,
a unique file per run under ./LOG_imapsync/,
either the user chooses it and so he has to specify it completely,
dirname and filename.

You can also make a LOG_imapsync symlink to avoid filling
the current directory.

It's a definition issue.
For me a filepath is a path, not for you. Ok I removed it.
The path includes the directory and the file names, according to my brain and Wikipedia.

So I fixed the doc, there is no filepath word anymore, just path.

The inline help clearly shows the --logfile is a complete path
like dir/filename.txt, which confirms what the doc said.


On 23/11/2015 17:22, Jens Herrmann wrote:
> Hi Gilles,
>
> I tried wanted to save the logfiles in |/var/log/imapsync| so I tried the following parameters:
>
> |imapsync \ --host1 xxx \ --host2 yyy \ --sep2 / \ --prefix2 "" \ --folderrec Archiv \ --subfolder2 Sicherung \ --usecache \ --pidfilelocking \ --tmpdir /var/tmp \ --logfile /var/log/imapsync |
>
> I get the following error message:
> |Can not open /var/log/imapsync for write: Ist ein Verzeichnis at ./imapsync line 6893|
>
> As far as I'm reading the code (line 662):
> |$logfile = defined( $logfile ) ? $logfile : logfile( $timestart, $user2 ) ;|
> This will take |--logfile| or call lofgile() to generate the filename, won't it?
>
> And logfile(): will never use a given filepath (line 6851):
> |return( "LOG_imapsync/${date_str}${sep}${suffix}.txt" )|
>
> If I set an hard-coded logfile, f.e. |/var/log/imapsync/logfile.txt| the script works, but there will be no separated logfile for every call.
>
> For me it is fine, when you could set only a specific filepat+filename and not only a filepath, but than you have to correct the documentation. Or you could implement |--logfilepath|.
>
> As workaround I have changed line 6851 to hard coded |/var/log/imapsync/|
>
> Regards,
> Jens
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/46#issuecomment-158985532>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by JHCD** [comment]
Hi Gilles,

I had understand the implementation of the parameter, but the definition/description was not clear (for me).
So I would prefer the clear description: "--logfile pathname and filename" as you used in the code.

Regards,
Jens

**Comment by gilleslamiral** [comment]
Hi Jens,

The doc is now:
--logfile      str  : Change the default logfile path (dirname+filename).


In case it helps, before --logfile exists, the script was like this:

          NOW=`date +%Y_%m_%d_%H_%M_%S`
          echo syncing to user "$u2"
          imapsync --host1 imap.side1.org --user1 "$u1" --password1 "$p1" \
                   --host2 imap.side2.org --user2 "$u2" --password2 "$p2" \
                   > LOG/log_${u2}_$NOW.txt 2>&1


It is equivalent to --logfile LOG/log_${u2}_$NOW.txt


On 23/11/2015 19:35, Jens Herrmann wrote:
> Hi Gilles,
>
> I had understand the implementation of the parameter, but the definition/description was not clear (for me).
> So I would prefer the clear description: "--logfile pathname and filename" as you used in the code.
>
> Regards,
> Jens


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by gilleslamiral** [comment]
Now there is also the --logdir option:

````
  OPTIONS/log

     --nolog             : Turn off logging on file
     --logfile      str  : Change the default log filename (can be dirname/filename).
     --logdir       str  : Change the default log directory. Default is LOG_imapsync/

````
