### ISSUE TITLE
3 BAD Unexpected ')'

### ISSUE THREAD

**Issue by CarrotCruncher** [imapsync/imapsync#47]
Just downloaded the latest version, and then amended as per:
[changed calls to SSL/TLS to include the right arguments](https://github.com/imapsync/imapsync/pull/41)
to avoid the "SSL_verify_mode must be a number and not a string" error.

My email accounts use special characters, including the closing bracket ')'. imapsync throws the following error:
`Failure: error login on [{server}] with user [{user}@{domain}] auth [LOGIN]: 3 BAD Unexpected ')'`

If I change the password so it doesn't include the closing bracket then it works OK.

I've tried escaping the special character and / or quoting the password but to no avail.

Am I doing something wrong, or does this need a code change? Cheers.

**Comment by gilleslamiral** [comment]
Hi CarrotCruncher,

BAD Unexpected ')' message comes from the IMAP server, then reported by imapsync.

I found no problem with ) characters in passwords on my side.
Several clues:

*Try --debugimap to see the whole IMAP LOGIN line.
* Try to login via IMAP from another client, like Thunderbird.
* Check also Mail::IMAPClient release used.

On 02/12/2015 18:42, CarrotCruncher wrote:

> My email accounts use special characters, including the closing bracket ')'. imapsync throws the following error:
> |Failure: error login on [{server}] with user [{user}@{domain}] auth [LOGIN]: 3 BAD Unexpected ')'|
>
> If I change the password so it doesn't include the closing bracket then it works OK.
>
> I've tried escaping the special character and / or quoting the password but to no avail.
>
> Am I doing something wrong, or does this need a code change? Cheers.


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by CarrotCruncher** [comment]
Thanks for the hint. After a bit of trial and error I ended up having to have the unescaped password within double quotes surrounded by single quotes to get it to work.

**Comment by gilleslamiral** [comment]
Hi,

I used this solution years ago but it is fixed now.
What is the Mail::IMAPClient release used?

On 03/12/2015 19:09, CarrotCruncher wrote:
> Thanks for the hint. After a bit of trial and error I ended up having to have the unescaped password within double quotes surrounded by single quotes to get it to work.


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by CarrotCruncher** [comment]
This is on a Fedora 23 server. The package installed is:
perl-Mail-IMAPClient-3.37-1.fc23.noarch

**Comment by mrl22** [comment]
I had this same issue and solved by running cpan upgrade Mail::IMAPClient
