### ISSUE TITLE
Is it possible to Sync All mails and apply --minage for deleting only?

### ISSUE THREAD

**Issue by austonpramodh** [imapsync/imapsync#486]
I am trying to sync all messages from gmail, including the latest ones. And I would like to delete messages that are older than 365 days on gmail(Host1).

I do understand I can achieve this by running two different commands, one for sync and another for delete with minage. Would I be possible to do it with just one command?

Related:
https://github.com/imapsync/imapsync/issues/200

**Comment by gilleslamiral** [comment]
> I am trying to sync all messages from gmail, including the latest ones. And I would like to delete messages that are older than 365 days on gmail(Host1).
> Would I be possible to do it with just one command?

No.

**Comment by austonpramodh** [comment]
Ok, Thanks. Ill close this issue now.
