### ISSUE TITLE
Sync using an SSH port forward

### ISSUE THREAD

**Issue by jperkin** [imapsync/imapsync#487]
Hi,

I have a somewhat esoteric setup, where the only real option of syncing to a particular server is over an SSH tunnel where I run a pre-authenticated `rimapd` that is port-forwarded back to my local machine.

The problem is I can't find a way to tell imapsync to not issue a `LOGIN` command. I am already pre-authenticated over the SSH tunnel, `--host2 localhost` and `--port2 1143` works fine in terms of connecting over SSH, I just need it to continue as if `LOGIN` was already successful. I can't find a way to turn this off, and obviously after already being authenticated, any attempt at another `LOGIN` command just fails.

Is there a way to do this that I'm missing? I think I've tried all the available options. If not is it something that can easily be supported?

Many thanks.

**Comment by gilleslamiral** [comment]
Try:
````
imapsync ... --authmech2 PREAUTH
````

**Comment by jperkin** [comment]
Aha, thanks! I didn't see this in the list of options.

**Comment by gilleslamiral** [comment]
I just updated
https://imapsync.lamiral.info/FAQ.d/FAQ.Authentication_failure.txt
with the following:
````
=======================================================================
Q. I am already pre-authenticated, how to tell imapsync to not issue 
   a LOGIN command?

A. Try:

  imapsync ... --authmech1 PREAUTH

=======================================================================
````
