### ISSUE TITLE
Timeout does not work on --justconnect

### ISSUE THREAD

**Issue by plindgren** [imapsync/imapsync#49]
I didnt want to wait 120 seconds for --justconnect to fail in a test im running. So i set the parameter --timeout 5. This did not work however, it seems like --timeout does not work when using --justconnect

**Comment by gilleslamiral** [comment]
Hi,

Yes you're right, --timeout is not taken into account with --justconnect

On 15/12/2015 09:56, plindgren wrote:
> I didnt want to wait 120 seconds for --justconnect to fail in a test im running. So i set the parameter --timeout 5. This did not work however, it seems like --timeout does not work when using --justconnect


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by gilleslamiral** [comment]
Fixed. --timeout taken into account with --justconnect in next public release.
