### ISSUE TITLE
--f1f2    str1=str2 without effect

### ISSUE THREAD

**Issue by cwittmer** [imapsync/imapsync#50]
Hi,
tried to sync mails from IMAP (courier) to SBS 2011 (Exchange 2010) with the following options:

`--f1f2 Drafts='Entw&APw-rfe'`
`--f1f2 Junk='Junk-E-Mail'`
`--f1f2 Sent='Gesendete Elemente'`
`--f1f2 Trash='Gel&APY-schte Elemente'`

... imapsync (1.670) is showing the following remapping

`Folders mapping from --f1f2 options, it overrides --automap:`
`[Trash]                                  -> [Gel&APY-schte Elemente] = [Gelöschte Elemente]`
`[Sent]                                   -> [Gesendete Elemente]                    `
`[Drafts]                                 -> [Entw&APw-rfe] = [Entwürfe]            `
`[Junk]                                   -> [Junk-E-Mail]`

... but is ignoring them and creating the missing folders instead of syncing to mapped folders as wanted with the --f1f2 option

++++ Looping on each one of 5 folders to sync
    1/5 [INBOX]                             -> [INBOX]                            
    2/5 [INBOX.Drafts]                      -> [Drafts]                           
Creating folder [Drafts] on host2
Created  folder [Drafts] on host2
    3/5 [INBOX.Junk]                        -> [Junk]                             
Creating folder [Junk] on host2
Created  folder [Junk] on host2
    4/5 [INBOX.Sent]                        -> [Sent]                             
Creating folder [Sent] on host2
Created  folder [Sent] on host2
msg INBOX.Sent/2 {406}             copied to Sent/1          0.74 msgs/s  0.292 KiB/s 0.396 KiB copied  ETA: Thu Dec 17 13:55:36 2015  0 s  0/1 msgs left
    5/5 [INBOX.Trash]                       -> [Trash]                            
Creating folder [Trash] on host2
Created  folder [Trash] on host2
++++ End looping on each folder

**Comment by gilleslamiral** [comment]
Hi Wittmer,

> tried to sync mails from IMAP (courier) to SBS 2011 (Exchange 2010) with the following options:
>
> |--f1f2 Drafts='Entw&APw-rfe'|

> imapsync (1670) is showing the following remapping
>
> |Folders mapping from --f1f2 options, it overrides --automap:|
> |[Drafts] -> [Entw&APw-rfe] = [Entwürfe]|

There is no exact Drafts on host1 but a INBOXDrafts so use:

--f1f2 INBOXDrafts='Entw&APw-rfe'


> but is ignoring them and creating the missing folders instead of syncing to mapped folders as wanted with the --f1f2 option
>
> ++++ Looping on each one of 5 folders to sync
> 1/5 [INBOX] -> [INBOX]
> 2/5 [INBOXDrafts] -> [Drafts]


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by cwittmer** [comment]
ahh OK ... but the `.` between `INBOX.Drafts` is important.
It is not shown in your answer, but it works with the following options

`--f1f2 INBOX.Drafts='Entw&APw-rfe'`
`--f1f2 INBOX.Junk='Junk-E-Mail'`
`--f1f2 INBOX.Sent='Gesendete Elemente'`
`--f1f2 INBOX.Trash='Gel&APY-schte Elemente'`

Thanks :)

**Comment by gilleslamiral** [comment]
Hi,

Ah yes, sorry. The strange thing is I received the folder names with no dots
so I adapted the solution to those weird names.
The github web archive is ok.

On 17/12/2015 15:37, Wittmer, Christian wrote:
> ahh OK ... but the |.| between |INBOX.Drafts| is important.
> It is not shown in your answer, but it works with the following options
>
> |--f1f2 INBOX.Drafts='Entw&APw-rfe'|
> |--f1f2 INBOX.Junk='Junk-E-Mail'|
> |--f1f2 INBOX.Sent='Gesendete Elemente'|
> |--f1f2 INBOX.Trash='Gel&APY-schte Elemente'|
>
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/50#issuecomment-165468176>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
