### ISSUE TITLE
fix version for Mail::IMAPClient

### ISSUE THREAD

**Issue by cwittmer** [imapsync/imapsync#51]
Hi,

when using
`Mail::IMAPClient 3.29`

with imapsync (1.670) then I get the following error:
`Not a SCALAR reference at /usr/lib/perl5/vendor_perl/5.10.0/Mail/IMAPClient.pm line 426.`

with
`Mail::IMAPClient 3.32`

it works

**Comment by gilleslamiral** [comment]
Hi,

I think it's fixed before 3.32, in 3.30:
http://cpansearch.perl.org/src/PLOBBES/Mail-IMAPClient-3.37/Changes
...
version 3.30: Fri Nov 11 09:37:00 EST 2011
	- rt.cpan.org#72347: Starttls array ref argument dereferenced twice
	  [Jonathan Buhacoff]

So ssl should work also with 3.30.

On 17/12/2015 15:27, Wittmer, Christian wrote:
> Hi,
>
> when using
> |Mail::IMAPClient 329|
>
> with imapsync (1670) then I get the following error:
> |Not a SCALAR reference at /usr/lib/perl5/vendor_perl/5100/Mail/IMAPClientpm line 426|
>
> with
> |Mail::IMAPClient 332|
>
> it works


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by gilleslamiral** [comment]
Fixed in next release.
