### ISSUE TITLE
Getting error for one specific account 

### ISSUE THREAD

**Issue by ahildoer** [imapsync/imapsync#55]
Hi, migrating several accounts from Google apps to Office 365 Exchange via IMAP. Process is working beautifully for 4 accounts, but one account has constant errors in the logs and doesn't seem to be progressing. 

I am getting this error, and the process for this account doesn't ever seem to end even though it has 10% as much data as the rest of the accounts, in terms of number of folders, number of messages and byte size of all attachments and messages.

``````
Use of uninitialized value $sockargs[11] in join or string at /usr/share/perl5/Mail/IMAPClient.pm line 360.
Host2 folder Bufkin Cara 1512 selected: 230 messages,  duplicates: 0
 43/758 [Bufkin Cara 1601]                  -> [Bufkin Cara 1601]
Host2: Subscribing to folder Bufkin Cara 1601
Host2 folder Bufkin Cara 1601 selected: 185 messages,  duplicates: 0
 44/758 [Buonopane Katy 1509]               -> [Buonopane Katy 1509]
Host2: Subscribing to folder Buonopane Katy 1509
Use of uninitialized value $sockargs[11] in join or string at /usr/share/perl5/Mail/IMAPClient.pm line 360.```


Here is my code:

```bash

cd /opt/mailSyncConfigs/${username}

runSync() {
        imapsync \
                --no-modules_version \
                --host1 imap.gmail.com --port1 993 --ssl1 --authmech1 PLAIN --user1 "${username}@${domain1}" --passfile1 pass1 \
                --host2 outlook.office365.com --port2 993 --ssl2 --authmech2 PLAIN --user2 "${username}@${domain2}" --passfile2 pass2 \
                --delete2duplicates \
                --noexpunge \
                --pidfile "/opt/mail/${username}/imapsync.pid" \
                --pidfilelocking \
                --logdir "." \
                --logfile "sync.log" \
                --tmpdir "./tmp"
}
``````

Each dir in mailSyncConfig has pass1 and pass2 text files. All 5 users setup the same on both sides and in the sync configs. 

Any ideas?

**Comment by gilleslamiral** [comment]
Hi Anthony,

I don't know.
What is Mail::IMAPClient version?
Upgrade Mail/IMAPClient.pm

> but one account has constant errors in the logs and doesn't seem to be progressing.
>
> I am getting this error:
>
> |Use of uninitialized value $sockargs[11] in join or string at /usr/share/perl5/Mail/IMAPClient.pm line 360.


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by junglon** [comment]
same problems here, imapsync function properly before, then suddenly I'm getting this error too..

**Comment by MattMencel** [comment]
Did anyone get this figured out?  I'm having the same problem.

```
With perl 5.10.1 Mail::IMAPClient  3.38
Command line used:
/usr/bin/imapsync --host1 zcs-proxy01 --port1 993 --ssl1 --user1 EMAIL --password1 MASKED --host2 imap.gmail.com --ssl2 --user2 EMAIL --password2 MASKED --justfoldersizes --nofoldersizes --authmech2 XOAUTH2 --debug
Temp directory is /tmp  ( to change it use --tmpdir dirpath )
PID file is /tmp/imapsync.pid ( to change it use --pidfile filepath ; to avoid it use --pidfile "" )
Modules version list:
Mail::IMAPClient     3.38
IO::Socket           1.31
IO::Socket::IP       0.37
IO::Socket::INET     1.31
IO::Socket::SSL      1.31
Net::SSLeay          1.35
Compress::Zlib       2.069
Digest::MD5          2.39
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.01
Term::ReadKey        2.30
File::Spec           3.3
Time::HiRes          1.9721
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.29
Data::Uniqid         0.12
JSON                 2.90
JSON::WebToken       0.10
Crypt::OpenSSL::RSA  0.28
LWP                  6.15
HTML::Entities       3.69
Filesys::DfPortable  0.85
( use --no-modules_version to turn off printing this Perl modules list )
Use --sslargs1 SSL_verify_mode=1 for SSL_VERIFY_PEER on host1
Use --sslargs2 SSL_verify_mode=1 for SSL_VERIFY_PEER on host2
ssl debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
IMAPClient 3.38
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use XOAUTH2 authentication on host2
Host1: imap connexion timeout is 120 seconds
Host2: imap connexion timeout is 120 seconds
Host1: IMAP server [zcs-proxy01] port [993] user [EMAIL]
Host2: IMAP server [imap.gmail.com] port [993] user [EMAIL]
Host1: connecting and login on host1 [zcs-proxy01] port [993] with user [EMAIL]
Use of uninitialized value $sockargs[9] in join or string at /usr/local/share/perl5/Mail/IMAPClient.pm line 360.
Host1 banner: * OK IMAP4 ready
Host1: zcs-proxy01 says it has NO CAPABILITY for AUTHENTICATE LOGIN
Host1: success login on [zcs-proxy01] with user [EMAIL] auth [LOGIN]
Host2: connecting and login on host2 [imap.gmail.com] port [993] with user [EMAIL]
Use of uninitialized value $sockargs[9] in join or string at /usr/local/share/perl5/Mail/IMAPClient.pm line 360.
Host2 failure: can not open imap connection on host2 [imap.gmail.com] with user [EMAIL]: Unable to connect to imap.gmail.com:
```

It's not attempting the Host2 IMAP connection to gmail because I'm not seeing it in the firewall logs.

Matt

**Comment by MarceloPedra** [comment]
@MattMencel hi, I wanted to try the script yesterday and got the same error mentioning the line 360.
Note that I was trying to sync two imap servers in separated vps servers.

Any idea anybody?

**Comment by gilleslamiral** [comment]
Hi Matt,

http://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt

=======================================================================
Q. Can not open imap connection on [imap.gmail.com]:
    Unable to connect to imap.gmail.com

R0. It looks like this issue is related to ipv6. Both ipv4 and ipv6
protocols should work with gmail and imapsync, I test that regularly,
imapsync works fine for both ipv4 and ipv6.
If you disable ipv6 then disable also ipv6 resolution!
Or at least, make ipv4 answers be taken before ipv6 since the default
names resolution order is to present ipv6 name resolutions first.

R1. A first simple solution is to use directly gmail ipv4 ip address:

   imapsync ... --host1 64.233.184.108

In case it changes, get it with any command showing the imap.gmail.com
name resolution, try one of those:

   nslookup imap.gmail.com
   host     imap.gmail.com
   ping     imap.gmail.com

Or go to http://ping.eu/nslookup/ to get the resolution.

R2. Second solution. Fix imapsync with the line:

   use IO::Socket::SSL 'inet4' ;

Thanks to Chris Nolan to report, understand and fix this issue!

=======================================================================
On 18/02/2016 16:37, Matt Mencel wrote:
> Did anyone get this figured out? I'm having the same problem.
>
> Host2 failure: can not open imap connection on host2 [imap.gmail.com] with user [EMAIL]: Unable to connect to imap.gmail.com: |
>
> It's not attempting the Host2 IMAP connection to gmail because I'm not seeing it in the firewall logs.
>
> Matt

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by scottyinzeo** [comment]
Thanks @gilleslamiral - this seemed to make it work again!
