### ISSUE TITLE
Stay connected to get and transfer new incoming mails

### ISSUE THREAD

**Issue by retog** [imapsync/imapsync#58]
Is there a more efficient way to achieve continuous sync than repeatedly invoke imapsync?

**Comment by gilleslamiral** [comment]
Hi Reto,

Remove "useless" behavior taking time, use --nofoldersizes, use --usecache or --useuid
Use offlineimap.

----- Mail original -----
De: "Reto Gmür" <notifications@github.com>
À: "imapsync/imapsync" <imapsync@noreply.github.com>
Envoyé: Vendredi 12 Février 2016 20:52:10
Objet: [imapsync] Stay connected to get and transfer new incoming mails (#58)

Is there a more efficient way to achieve continuous sync than repeatedly invoke imapsync?

---
Reply to this email directly or view it on GitHub:
https://github.com/imapsync/imapsync/issues/58

**Comment by retog** [comment]
Thanks @gilleslamiral , I've npw set up a cronjob with `--nofoldersizes --usecache --folder Inbox` to transfer the emails from the account that doesn't support forwarding or POP3.

**Comment by gilleslamiral** [comment]
Hi Reto,

You can use --delete to delete messages from host1 after the copy.

> Thanks @gilleslamiral <https://github.com/gilleslamiral> , I've npw set
> up a cronjob with |--nofoldersizes --usecache --folder Inbox| to
> transfer the emails from the account that doesn't support forwarding or
> POP3.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/imapsync/imapsync/issues/58#issuecomment-184869714>.
> 

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
