### ISSUE TITLE
Login failure when IMAP is disabled

### ISSUE THREAD

**Issue by javierav** [imapsync/imapsync#60]
Hi!

I'm trying to sync an email account like this "user@my-domain.com" but the IMAP server returns the following message:

```
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connexion timeout is 120 seconds
Host2: imap connexion timeout is 120 seconds
Host1: IMAP server [mail.example.com] port [143] user [user@my-domain.com]
Host2: IMAP server [mx.example.es] port [143] user [user@my-domain.com]
Host1: connecting and login on host1 [mail.example.com] port [143] with user [user@my-domain.com]
Host1 banner: * OK IceWarp 10.4.4 IMAP4rev1 Wed, 24 Feb 2016 21:07:50 +0100
Host1: mail.example.com says it has CAPABILITY for AUTHENTICATE LOGIN
Host1 failure: Error login on [mail.example.com] with user [user@my-domain.com] auth [LOGIN]: 2 NO LOGIN Unknown user or incorrect password
```

When I sync another account with a domain that not contains a dash character, the migration is sucessful.

I'm using the lastest version of imapsync.

```
imapsync --host1 mail.example.com --user1 "user@my-domain.com" --password1 "12345" --host2 mx.example.es --user2 "user@my-domain.com" --password2 "12345"

$RCSfile: imapsync,v $ $Revision: 1.678 $ $Date: 2016/01/21 19:47:02 $

Modules version list:
Mail::IMAPClient     3.35
IO::Socket           1.36
IO::Socket::IP       ?
IO::Socket::INET     1.33
IO::Socket::SSL      1.965
Net::SSLeay          1.58
Compress::Zlib       2.06
Digest::MD5          2.52
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Term::ReadKey        2.31
File::Spec           3.40
Time::HiRes          1.9725
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON                 ?
JSON::WebToken       ?
Crypt::OpenSSL::RSA  ?
LWP                  6.05
HTML::Entities       3.69
Filesys::DfPortable  ?
```

**Comment by gilleslamiral** [comment]
Hi Javier,

It may be the quote bug with Mail::IMAPClient 3.35
Either upgrade Mail::IMAPClient to 3.38 or use the following workaround:
Addsingle quotes around double-quotes like this:

   imapsync ...--user1 '"user@my-domain.com"'

Tell me if it works.

Le 24/02/2016 21:24, Javier Aranda a écrit :
> Hi!
>
> I'm trying to sync an email account like this "user@my-domain.com <mailto:user@my-domain.com>" but the IMAP server returns the following message:
>
> |Host1: will try to use LOGIN authentication on host1 Host2: will try to use LOGIN authentication on host2 Host1: imap connexion timeout is 120 seconds Host2: imap connexion timeout is 120 seconds Host1: IMAP server [mail.example.com] port [143] user [user@my-domain.com] Host2: IMAP server [mx.example.es] port [143] user [user@my-domain.com] Host1: connecting and login on host1 [mail.example.com] port [143] with user [user@my-domain.com] Host1 banner: * OK IceWarp 10.4.4 IMAP4rev1 Wed, 24 Feb 2016 21:07:50 +0100 Host1: mail.example.com says it has CAPABILITY for AUTHENTICATE LOGIN Host1 failure: Error login on [mail.example.com] with user [user@my-domain.com] auth [LOGIN]: 2 NO LOGIN Unknown user or incorrect password |
>
> When I sync another account with a domain that not contains a dash character, the migration is sucessful.
>
> I'm using the lastest version of imapsync.
>
> |imapsync --host1 mail.example.com --user1 "user@my-domain.com" --password1 "12345" --host2 mx.example.es --user2 "user@my-domain.com" --password2 "12345" $RCSfile: imapsync,v $ $Revision: 1.678 $ $Date: 2016/01/21 19:47:02 $ Modules version list: Mail::IMAPClient 3.35 IO::Socket 1.36 IO::Socket::IP ? IO::Socket::INET 1.33 IO::Socket::SSL 1.965 Net::SSLeay 1.58 Compress::Zlib 2.06 Digest::MD5 2.52 Digest::HMAC_MD5 1.01 Digest::HMAC_SHA1 1.03 Term::ReadKey 2.31 File::Spec 3.40 Time::HiRes 1.9725 Unicode::String 2.09 IO::Tee 0.64 File::Copy::Recursive 0.38 Authen::NTLM 1.09 URI::Escape 3.31 Data::Uniqid 0.12 JSON ? JSON::WebToken ? Crypt::OpenSSL::RSA ? LWP 6.05 HTML::Entities 3.69 Filesys::DfPortable ? |
>


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by javierav** [comment]
Hi Guilles,

I have tried both solutions and none of them work :(

```
$RCSfile: imapsync,v $ $Revision: 1.678 $ $Date: 2016/01/21 19:47:02 $

Modules version list:
Mail::IMAPClient     3.38
IO::Socket           1.38
IO::Socket::IP       0.37
IO::Socket::INET     1.35
IO::Socket::SSL      2.024
Net::SSLeay          1.72
Compress::Zlib       2.068
Digest::MD5          2.54
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Term::ReadKey        2.33
File::Spec           3.56
Time::HiRes          1.9726
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON                 ?
JSON::WebToken       ?
Crypt::OpenSSL::RSA  ?
LWP                  6.15
HTML::Entities       3.69
Filesys::DfPortable  ?
```

**Comment by gilleslamiral** [comment]
Can you login via Thunderbird or another client?


> I have tried both solutions and none of them work :(
>
> |$RCSfile: imapsync,v $ $Revision: 1.678 $ $Date: 2016/01/21 19:47:02 $ Modules version list: Mail::IMAPClient 3.38 IO::Socket 1.38 IO::Socket::IP 0.37 IO::Socket::INET 1.35 IO::Socket::SSL 2.024 Net::SSLeay 1.72 Compress::Zlib 2.068 Digest::MD5 2.54 Digest::HMAC_MD5 1.01 Digest::HMAC_SHA1 1.03 Term::ReadKey 2.33 File::Spec 3.56 Time::HiRes 1.9726 Unicode::String 2.09 IO::Tee 0.64 File::Copy::Recursive 0.38 Authen::NTLM 1.09 URI::Escape 3.31 Data::Uniqid 0.12 JSON ? JSON::WebToken ? Crypt::OpenSSL::RSA ? LWP 6.15 HTML::Entities 3.69 Filesys::DfPortable ? |
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/issues/60#issuecomment-189269971>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by javierav** [comment]
Yes! I use this ruby script and I can login sucessful.

```
#!/usr/bin/env ruby

require 'net/imap'

imap = Net::IMAP.new('mail.example.com', port: 993, ssl: { verify_mode: 0 })
imap.login('user@my-domain.com', '12345')

puts imap.list('', '**').inspect

imap.logout
imap.disconnect
```

**Comment by gilleslamiral** [comment]
Hi Javier,

Do you specify --ssl1 with imapsync?

Le 03/03/2016 09:08, Javier Aranda a écrit :
> Yes! I use this ruby script and I can login successful.
>
> |#!/usr/bin/env ruby require 'net/imap' imap = Net::IMAP.new('mail.example.com', port: 993, ssl: { verify_mode: 0 })


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by javierav** [comment]
I tried it and it does not work!

```
imapsync --host1 mail.example.com --user1 "user@my-domain.com" --password1 "12345" --host2 mx.example.es --user2 "user@my-domain.com" --password2 "12345" --ssl1 --ssl2
```

**Comment by javierav** [comment]
I give you a extended debug info about this.

```
$ imapsync --host1 mail.server1.com --user1 'user@my-domain.com' --password1 '12345' --host2 mail.server2.com --user2 'user@my-domain.com' --password2 '12345' --ssl1 --ssl2 --debug --debugimap

get options: [1]
date_str: 2016_03_07_08_00_03
logfile : LOG_imapsync/2016_03_07_08_00_03_user@my-domain.com.txt
Transfer started at Mon Mar  7 08:00:03 2016
PID is 1
Log file is LOG_imapsync/2016_03_07_08_00_03_user@my-domain.com.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
$RCSfile: imapsync,v $ $Revision: 1.678 $ $Date: 2016/01/21 19:47:02 $ 
Here is a [linux] system (Linux 046f570cbfcb 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64)
With perl 5.22.1 Mail::IMAPClient  3.38
Command line used:
/usr/bin/imapsync --host1 mail.server1.com --user1 'user@my-domain.com' --password1 MASKED --host2 mail.server2.com --user2 'user@my-domain.com' --password2 MASKED --ssl1 --ssl2 --debug --debugimap
Temp directory is /tmp  ( to change it use --tmpdir dirpath )
PID file is /tmp/imapsync.pid ( to change it use --pidfile filepath ; to avoid it use --pidfile "" )
Modules version list:
Mail::IMAPClient     3.38
IO::Socket           1.38
IO::Socket::IP       0.37
IO::Socket::INET     1.35
IO::Socket::SSL      2.024
Net::SSLeay          1.72
Compress::Zlib       2.068
Digest::MD5          2.54
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Term::ReadKey        2.33
File::Spec           3.56
Time::HiRes          1.9726
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON                 ?
JSON::WebToken       ?
Crypt::OpenSSL::RSA  ?
LWP                  6.15
HTML::Entities       3.69
Filesys::DfPortable  ?
( use --no-modules_version to turn off printing this Perl modules list )
Use --sslargs1 SSL_verify_mode=1 for SSL_VERIFY_PEER on host1
Use --sslargs2 SSL_verify_mode=1 for SSL_VERIFY_PEER on host2
ssl debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
IMAPClient 3.38
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connexion timeout is 120 seconds
Host2: imap connexion timeout is 120 seconds
Host1: IMAP server [mail.server1.com] port [993] user [user@my-domain.com]
Host2: IMAP server [mail.server2.com] port [993] user [user@my-domain.com]
Host1: connecting and login on host1 [mail.server1.com] port [993] with user [user@my-domain.com]
Use of uninitialized value $sockargs[13] in join or string at /usr/share/perl5/Mail/IMAPClient.pm line 360.
Connecting with IO::Socket::SSL PeerAddr mail.server1.com PeerPort 993 Proto tcp Timeout 120 Debug 1 SSL_verifycn_scheme imap SSL_version  SSL_verify_mode 0
Connected to mail.server1.com
Read: 	* OK IceWarp 10.4.4 IMAP4rev1 Mon, 07 Mar 2016 08:59:38 +0100
Host1 banner: * OK IceWarp 10.4.4 IMAP4rev1 Mon, 07 Mar 2016 08:59:38 +0100
Sending: 1 CAPABILITY
Sent 14 bytes
Read: 	* CAPABILITY IMAP4rev1 AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5 AUTH=GSSAPI SORT THREAD=ORDEREDSUBJECT UIDPLUS QUOTA ACL NAMESPACE CHILDREN IDLE ID UNSELECT METADATA X-ICEWARP-SERVER X-MOVE MSEARCH XLIST CREATE-SPECIAL-USE
  	1 OK CAPABILITY Completed
Host1: mail.server1.com says it has CAPABILITY for AUTHENTICATE LOGIN
Sending: 2 LOGIN user@my-domain.com [Redact: Count=2 Showcredentials=OFF]
Sent 62 bytes
Read: 	2 NO LOGIN Unknown user or incorrect password
ERROR: 2 NO LOGIN Unknown user or incorrect password at /usr/share/perl5/Mail/IMAPClient.pm line 1365.
	Mail::IMAPClient::__ANON__("2 NO LOGIN Unknown user or incorrect password\x{d}\x{a}") called at /usr/share/perl5/Mail/IMAPClient.pm line 1401
	Mail::IMAPClient::_get_response(Mail::IMAPClient=HASH(0x15af320), 2, undef) called at /usr/share/perl5/Mail/IMAPClient.pm line 1327
	Mail::IMAPClient::_imap_command_do(Mail::IMAPClient=HASH(0x15af320), "LOGIN user\@my-domain.com 12345") called at /usr/share/perl5/Mail/IMAPClient.pm line 1226
	Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x15af320), "LOGIN user\@my-domain.com 12345") called at /usr/share/perl5/Mail/IMAPClient.pm line 584
	Mail::IMAPClient::login(Mail::IMAPClient=HASH(0x15af320)) called at /usr/bin/imapsync line 2876
	main::authenticate_imap(Mail::IMAPClient=HASH(0x15af320), "mail.server1.com", 993, "user\@my-domain.com", undef, "12345", 1, 120, 0, ...) called at /usr/bin/imapsync line 2843
	main::login_imap("mail.server1.com", 993, "user\@my-domain.com", undef, "12345", 1, 120, 0, 1, ...) called at /usr/bin/imapsync line 1222
ERROR: 2 NO LOGIN Unknown user or incorrect password at /usr/share/perl5/Mail/IMAPClient.pm line 1275.
	Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x15af320), "LOGIN user\@my-domain.com 12345") called at /usr/share/perl5/Mail/IMAPClient.pm line 584
	Mail::IMAPClient::login(Mail::IMAPClient=HASH(0x15af320)) called at /usr/bin/imapsync line 2876
	main::authenticate_imap(Mail::IMAPClient=HASH(0x15af320), "mail.server1.com", 993, "user\@my-domain.com", undef, "12345", 1, 120, 0, ...) called at /usr/bin/imapsync line 2843
	main::login_imap("mail.server1.com", 993, "user\@my-domain.com", undef, "12345", 1, 120, 0, 1, ...) called at /usr/bin/imapsync line 1222
Host1 failure: Error login on [mail.server1.com] with user [user@my-domain.com] auth [LOGIN]: 2 NO LOGIN Unknown user or incorrect password
```

**Comment by javierav** [comment]
Hi!

You can close this issue. After spend a few hours debugging this issue we resolved the problem: for some strange reason some accounts have disabled the IMAP protocol. Apologies for the inconvenience and thanks for your time.

**Comment by gilleslamiral** [comment]
Hi Javier

Ok good!
It doesn't explain why the ruby code has worked with the same account,


Le 07/03/2016 11:29, Javier Aranda a écrit :
> Hi!
>
> You can close this issue. After spend a few hours debugging this issue we resolved the problem: for some strange reason some accounts have disabled the IMAP protocol. Apologies for the inconvenience and thanks for your time.
>


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by javierav** [comment]
In the ruby code we used a test user with IMAP enabled(the default behaviour in the server)...

**Comment by gilleslamiral** [comment]
When using a key on a door and it fails to open, it can be not sufficient to test that another key on another door succeeds :-)
