### ISSUE TITLE
Gmail Too Many Simultaneous Connections Workaround

### ISSUE THREAD

**Issue by MattMencel** [imapsync/imapsync#61]
Anyone know of a way around the 15 connection limitation?  I've written a script to allow me to multi-thread imapsyncs of individual folders for my accounts.  I thought I'd be able to push dozens but just discovered that Gmail kills connections after 15.  :(

**Comment by gilleslamiral** [comment]
Hi Matt,

I didn't know there was this limit.
15 simultaneous connections on the same account seems reasonable.
https://support.google.com/mail/answer/97150

Le 02/03/2016 05:48, Matt Mencel a écrit :
> Anyone know of a way around the 15 connection limitation? I've written a script to allow me to multi-thread imapsyncs of individual folders for my accounts. I thought I'd be able to push dozens but just discovered that Gmail kills connections after 15. :(


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
