### ISSUE TITLE
only 'Top' folder of --f1f2 is correct redirected but not subfolders

### ISSUE THREAD

**Issue by computersalat** [imapsync/imapsync#62]
Did sync from HOST1 (Exchange 2013) to HOST2 (IMAP by jimdo.com)
imapsync,v $ $Revision: 1.670
--f1f2 'Gesendete Elemente'='INBOX.Sent'

```
Folders mapping from --f1f2 options, it overrides --automap:
[INBOX]                                  -> [Eingang]                               
[Gesendete Elemente]                     -> [INBOX.Sent]                            
[Entw&APw-rfe] = [Entwürfe]             -> [INBOX.Drafts]                          
[Gel&APY-schte Elemente] = [Gelöschte Elemente] -> [INBOX.Trash]                           
[Junk-E-Mail]                            -> [INBOX.spam]
```

but only the top folder is remapped ...

```
 74/183 [Gesendete Elemente]                -> [INBOX.Sent]                       
 75/183 [Gesendete Elemente/Kunden]         -> [INBOX.Gesendete Elemente.Kunden]
```

when I use

```
--regextrans2 's/INBOX\.Gesendete\ Elemente/INBOX\.Sent/'
```

then it works ...

```
74/183 [Gesendete Elemente]                -> [INBOX.Sent]                       
 75/183 [Gesendete Elemente/Kunden]         -> [INBOX.Sent.Kunden]                
Creating folder [INBOX.Sent.Kunden] on host2
```

but the doku is saying that ...

```
--f1f2 overrides --automap and --regextrans2
```

which is not true in this case ...
if you need more info then please let me know ...
Thank you :)

**Comment by gilleslamiral** [comment]
Hi Christian,

> --f1f2 'Gesendete Elemente'='INBOX.Sent'
>
> Folders mapping from --f1f2 options, it overrides --automap:
> [INBOX] -> [Eingang]
> [Gesendete Elemente] -> [INBOX.Sent]
> ...
> but only the top folder is synced ...
>
> 74/183 [Gesendete Elemente] -> [INBOX.Sent]
>75/183 [Gesendete Elemente/Kunden] -> [INBOX.Gesendete Elemente.Kunden] |
>
> when I use
>
> |--regextrans2 's/INBOX\.Gesendete\ Elemente/INBOX\.Sent/' |
>
> then it works ...
>
> 74/183 [Gesendete Elemente] -> [INBOX.Sent]
>75/183 [Gesendete Elemente/Kunden] -> [INBOX.Sent.Kunden] Creating folder [INBOX.Sent.Kunden] on host2 |
>
> but the doku is saying that ...
>
> |--f1f2 overrides --automap and --regextrans2 |
>
> which is not true in this case ...

Option --f1f2 is a pure one to one folder mapping, ie,
a single --f1f2 folder1=folder2 can't change several folder names.

I haven't enough element to understand that
--f1f2 doesn't override --automap nor --regextrans2 in your case.
I need all options --f1f2 --regextrans2 and all the folders listings.

It looks like a feature not understood and not well documented.

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by branzo** [comment]
+1 on this. It seems that --f1f2 does not take into account subfolders of a given directory as --regextrans2 does when figuring out the correct location of the destination.

As an example: 

imapsync options: --f1f2 'Sent\ Items=Sent' --f1f2 'Sent\ items=Sent' --f1f2 'Posta\ Inviata=Sent' --f1f2 'Posta\ inviata=Sent' --f1f2 'Posta\ Eliminata=Trash' --f1f2 'Posta\ eliminata=Trash'

Host1 folders list:
[...]
[Posta inviata]
[Posta inviata/Posta locale]
[Posta inviata/Posta locale/Drafts]
[Posta inviata/Posta locale/Strutture Semplici]
[Posta inviata/Posta locale/Templates]
[Posta inviata/Posta locale/Unsent Messages]
[...]

and this happens:

Folder    9/14 [Posta inviata]                     -> [Sent]
Folder   10/14 [Posta inviata/Posta locale]        -> [Posta inviata/Posta locale]
Folder   11/14 [Posta inviata/Posta locale/Drafts] -> [Posta inviata/Posta locale/Drafts]

You can easily reproduce this even while using a --justfolders... 

Brando B.

**Comment by gilleslamiral** [comment]
Hi Brando,



Le 21/02/2017 à 17:46, Brando a écrit :
> +1 on this. It seems that --f1f2 does not take into account subfolders of a given directory as --regextrans2 does when figuring out the correct location of the destination.

Yes this is a feature, I understand the need anyway for what you complain,
I might fix that one day.


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by branzo** [comment]
I see. No problems on this, i'll fall back using regextrans2, thanks for the clarification!

**Comment by gilleslamiral** [comment]
I plan to extend the automap to subfolders. Another issue still open about this:
https://github.com/imapsync/imapsync/issues/73

**Comment by gilleslamiral** [comment]
````
Q. How to remove the string "INBOX." in the name of destination folders?


https://imapsync.lamiral.info/FAQ.d/FAQ.Folders_Mapping.txt
...
R. To remove "INBOX." in the name of destination folders:

On Linux:

  imapsync ... --regextrans2 's/^INBOX\.(.+)/$1/'

On Windows:

  imapsync ... --regextrans2 "s/^INBOX\.(.+)/$1/"
````
