### ISSUE TITLE
Possible to delete messages using pipemess?

### ISSUE THREAD

**Issue by retorquere** [imapsync/imapsync#64]
Is there a way to have the pipemess script signal that I don't want to copy an individual message, but I do want it deleted on the source end? Our work printing system uses print-by-email so I have a lot of messages to `printer@work.com`, and I'd rather just delete them while I archive the rest of my mail.

**Comment by gilleslamiral** [comment]
Hi,

http://imapsync.lamiral.info/FAQ.d/FAQ.Messages_Selection.txt

You can avoid messages to printer@work.com with:

   imapsync ... --search "NOT TO printer@work.com"


Le 28/04/2016 à 15:56, retorquere a écrit :
> Is there a way to have the pipemess script signal that I don't want to copy an individual message, but I do want it deleted on the source end? Our work printing system uses print-by-email so I have a lot of messages to |printer@work.com|, and I'd rather just delete them while I archive the rest of my mail.



-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by retorquere** [comment]
But not in the pipemess script then? The search would leave the messages on the source, I figured since I can change everything else from the message, I might be able to also say "keep nothing of this message"

**Comment by gilleslamiral** [comment]
Hi,

--pipemess doesn't touch the message at host1 so "keep nothing of this message" would only apply to host2
which is what already does the --search mentioned. The --search is rather "don't sync this message".

Plus, --pipemess generating an empty message will add an empty message on host2,
which is a true (empty) message, I'm not sure it is what you want.

Have a try and tell us.

On 29/04/2016 00:12, retorquere wrote:
> But not in the pipemess script then? The search would leave the messages on the source,
>I figured since I can change everything else from the message, I might be able to also say "keep nothing of this message"



-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by gilleslamiral** [comment]
Summary:
* --pipemess can change the message copied on host2 but not on host1.
* --search allow to avoid syncing some messages

I add that imapsync can also serve as a destroyer of messages on host1 if a sync is done between host1 and host1 with --delete1 option. Added to a --search it allows to select messages to be deleted. Special care is mandatory in this scenario...
