### ISSUE TITLE
messages deletes without using --delete2 flag

### ISSUE THREAD

**Issue by rudepython** [imapsync/imapsync#65]
deleted messages on host1 are deleted from host2 also without using --delete2 flag

**Comment by gilleslamiral** [comment]
Hi rudepython,

On 02/05/2016 11:58, rudepython wrote:
> deleted messages on host1 are deleted from host2 also without using --delete2 flag

Yes, it happen if you don't use --expunge1 but use --expunge2.
The messages marked on host1 are transfered and marked \Deleted on host2,
like they are on host1, and also removed by EXPUNGE as asked by --expunge2

Are you in this context?


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by morfair** [comment]
I have same problem!
I want to make backup imap server with all messages. But when I remove message on host1, this message on host2 remove to... How to avoid this?

**Comment by morfair** [comment]
@rudepython 
Do u solve this issue?

**Comment by morfair** [comment]
I want remove message if it was move to another folder (Trash or subfoled), but I don't want fully remove message if it was deleted from Trash or Shift+Del. My backup imap specialy for accidentally delete.

**Comment by gilleslamiral** [comment]
Hi!

 >  I want remove message if it was move to another folder (Trash or
 > subfoled), but I don't want fully remove message if it was deleted
 > from Trash or Shift+Del.

Imapsync apply the options given on the command line to all folders or
to the folders specified on the command line via --folders or
--include or --exclude etc. If a behavior is desired for a set of
folders but not for another set of folders then the solution is to run
imapsync with different option sets.

So your needs may be reached with two separate runs, one with
--delete2 and one without it:

  imapsync ... --exclude Trash --delete2
  imapsync ... --include Trash


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by morfair** [comment]
@gilleslamiral 
Help me please with params. My conditions:
If message moved to the another folder, I want remove this message from 1st folder and get this message in new folder, without dublicate. But if message expunge from host1, I don't want remove it from host and stay it in last place for can restore.
I make backup imap server.

**Comment by gilleslamiral** [comment]
In IMAP, a move is a copy followed by a destruction. 
The goal "sync deletions of messages but not the last, without duplicates" is not stateless among several syncs. 
And how about moving folders or renaming folders? A headache!

A solution to keep all messages and also sync the deletions is to have a catchall folder on host2 that keeps all the messages.
