### ISSUE TITLE
Different signatures generated from identical header

### ISSUE THREAD

**Issue by patwork** [imapsync/imapsync#66]
Hello,

I've come across a problem with some messages being downloaded every time I run imapsync. After adding --debug and checking logs I think there's an issue with parsing multiline fields in headers.

Example mail below. Raw header is identical on Host1 and Host2, but generated signatures are different. Notice that only Host1 is using BODY[PEEK.HEADER]. IPs and emails are xxx-ed for privacy reasons.

> Host1 banner: \* OK xxx IdeaImapServer v0.80.1 ready
> Host1 capability: IMAP4rev1 LITERAL+ CHILDREN I18NLEVEL=1 IDLE SORT UIDPLUS UNSELECT XLIST
> 
> Host2 banner: \* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN] Dovecot ready.
> Host2 capability: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SPECIAL-USE
> 
> Host1 uid 163 head nb pass one: 0
> Host1 uid 163 no header by parse_headers so taking whole header with BODY.PEEK[HEADER]
> Host1 uid 163 head nb pass two: 16
> Host1 uid 163 header [MESSAGE-ID: <000001D0185A$B3B6A880$1B23F980$xxxx>]
> **Host1 uid 163 header [RECEIVED: FROM SAMSUNG (xxx) (USING TLSV1.2 WITH CIPHER ECDHE-RSA-AES256-SHA384 (256/256 BITS)) (NO CLIENT CERTIFICATE REQUESTED)]**
> Host1 uid 163 header [RECEIVED: FROM xxx (xxx) (HELO xxx) BY xxx (xxx) WITH SMTP (IDEASMTPSERVER V0.80) ID BEFCBBB97BE6C685; MON, 15 DEC 2014 12:31:43 +0100]
> Host1 uid 163 sig **rnW1WGRAqqaVVoT+rbqnTQ** size 6541 idate 15-Dec-2014 12:31:43 +0100
> 
> Host2 uid 163 head nb pass one: 2
> Host2 uid 163 header [MESSAGE-ID: <000001D0185A$B3B6A880$1B23F980$xxxx>]
> **Host2 uid 163 header [RECEIVED: FROM SAMSUNG (xxx) (USING TLSV1.2 WITH CIPHER ECDHE-RSA-AES256-SHA384 (256/256 BITS)) (NO CLIENT CERTIFICATE REQUESTED) (AUTHENTICATED SENDER: xxx) BY xxx (xxx) WITH ESMTPSA ID 3K1L6643D9ZZ9TKR FOR <xxx>; MON, 15 DEC 2014 12:31:41 +0100 (CET)]**
> Host2 uid 163 header [RECEIVED: FROM xxx (xxx) (HELO xxx) BY xxx (xxx) WITH SMTP (IDEASMTPSERVER V0.80) ID BEFCBBB97BE6C685; MON, 15 DEC 2014 12:31:43 +0100]
> Host2 uid 163 sig **2ZYv8JufO+9wznsB8bQwSw** size 6541 idate 15-Dec-2014 12:31:43 +0100

And this is raw header, 100% identical on both hosts if fetched with BODY[PEEK.HEADER]. What is interesting, first "Received" field has spaces and second has tabulators:

> Return-Path: <xxx>\r\nReceived: from xxx (xxx) (HELO xxx)\r\n by xxx (xxx) with SMTP (IdeaSmtpServer v0.80)\r\n id befcbbb97be6c685; Mon, 15 Dec 2014 12:31:43 +0100\r\nReceived: from Samsung (xxx)\r\n\t(using TLSv1.2 with cipher ECDHE-RSA-AES256-SHA384 (256/256 bits))\r\n\t(No client certificate requested)\r\n\t(Authenticated sender: xxx)\r\n\tby xxx (xxx) with ESMTPSA id 3k1L6643d9zZ9tKr\r\n\tfor <xxx>; Mon, 15 Dec 2014 12:31:41 +0100 (CET)\r\nDKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=xxx; s=2011;\r\n\tt=1418643102; bh=9Sa9ZJBmGCXolg5K372V7XiTHd9ZHueYVH8WHTAqyEI=;\r\n\th=From:To:References:In-Reply-To:Subject:Date:Message-ID:\r\n\t MIME-Version:Content-Type;\r\n\tb=qYK+YNGvsplPI0fueGSin3VotAFHOUtnFVfSIvteBJGwv+7Bh5H0jCH9ueTau/x90\r\n\t 4EwuZfCVPzma5+PpoPN5YmhLVOOiuvFsPZtGrIEFDQ1X7SIzBNvs/JzaTeIEw0OZv9\r\n\t nmy3eisN4f535cYJFU/zCSmLYBtWpLgZNkbES7to=\r\nFrom: "xxx" <xxx>\r\nTo: "\'xxx\'" <xxx>\r\nReferences: <000f01d0183e$8e4a3010$aade9030$xxxx>\r\nIn-Reply-To: <000f01d0183e$8e4a3010$aade9030$xxxx>\r\nSubject: xxx\r\nDate: Mon, 15 Dec 2014 12:31:42 +0100\r\nMessage-ID: <000001d0185a$b3b6a880$1b23f980$xxxx>\r\nMIME-Version: 1.0\r\nContent-Type: multipart/alternative;\r\n\tboundary="----=_NextPart_000_0001_01D01863.157B1080"\r\nX-Mailer: Microsoft Outlook 15.0\r\nThread-Index: xxx\r\nContent-Language: pl\r\n\r\n

First "Received":

> Received: from xxx (xxx) (HELO xxx)\r\n
> **(space)**by xxx (xxx) with SMTP (IdeaSmtpServer v0.80)\r\n
> **(space)**id befcbbb97be6c685; Mon, 15 Dec 2014 12:31:43 +0100\r\n

Second:

> Received: from Samsung (xxx)\r\n
> \t(using TLSv1.2 with cipher ECDHE-RSA-AES256-SHA384 (256/256 bits))\r\n
> \t(No client certificate requested)\r\n
> \t(Authenticated sender: xxx)\r\n
> \tby xxx (xxx) with ESMTPSA id 3k1L6643d9zZ9tKr\r\n
> \tfor <xxx>; Mon, 15 Dec 2014 12:31:41 +0100 (CET)\r\n

I hope this is sufficient information to fix this problem.

**Comment by gilleslamiral** [comment]
Hello Patwork,

Thanks for your feedback!

Imapsync already changes tabulations to spaces to generate the signatures used to compare messages
on both sides. So it might be something else.

The best is to isolate a unique "buggy" message in a folder and run imapsync on this folder
with --debug option, even --debugcontent if the message is small.

See also http://imapsync.lamiral.info/FAQ.d/FAQ.Duplicates.txt
for more details about that.

What's done on headers to fix that king of problem is in the subroutine header_line_normalize()

sub header_line_normalize {
	my( $header_key,  $header_val ) = @_ ;
	
         # no 8-bit data in headers !
         $header_val =~ s/[\x80-\xff]/X/xog;

         # change tabulations to space (Gmail bug on with "Received:" on multilines)
         $header_val =~ s/\t/\ /xgo ;

         # remove the first blanks ( dbmail bug? )
         $header_val =~ s/^\s*//xo;

         # remove the last blanks ( Gmail bug )
         $header_val =~ s/\s*$//xo;

         # remove successive blanks ( Mailenable does it )
         $header_val =~ s/\s+/ /xgo;

         # remove Message-Id value domain part ( Mailenable changes it )
         if ( ( $messageidnodomain ) and ( 'MESSAGE-ID' eq uc( $header_key ) ) ) { $header_val =~ s/^([^@]+).*$/$1/xo ; }

         # and uppercase header line
         # (dbmail and dovecot)

         my $header_line = uc("$header_key: $header_val") ;

	return( $header_line ) ;
}


> I've come across a problem with some messages being downloaded every time I run imapsync.
>After adding --debug and checking logs I think there's an issue with parsing multiline fields in headers.
>
> Example mail below. Raw header is identical on Host1 and Host2, but generated signatures are different.
>Notice that only Host1 is using BODY[PEEK.HEADER]. IPs and emails are xxx-ed for privacy reasons.
>
>     Host1 banner: * OK xxx IdeaImapServer v0.80.1 ready

Never saw this one before!
Thanks.

> And this is raw header, 100% identical on both hosts if fetched with BODY[PEEK.HEADER]. What is interesting, first "Received" field has spaces and second has tabulators:
> I hope this is sufficient information to fix this problem.



-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by gilleslamiral** [comment]
No news. Closing.
