### ISSUE TITLE
"Invalid option linkage for sslargs1=s%"

### ISSUE THREAD

**Issue by hooch** [imapsync/imapsync#67]
It doesn't matter whether I run imapsync with my usual arguments or without arguments at all, I always see the following:

    Invalid option linkage for "sslargs1=s%"
    Invalid option linkage for "sslargs2=s%"

Am I doing something wrong?  Thank you

**Comment by hooch** [comment]
No issue with imapsync on a newer distro.

**Comment by gilleslamiral** [comment]
Hi Hooch,

What was the Perl and Getopt::Long releases?

Le 16/05/2016 à 06:32, hooch a écrit :
> It doesn't matter whether I run imapsync with my usual arguments or without arguments at all, I always see the following:
>
> |Invalid option linkage for "sslargs1=s%" Invalid option linkage for "sslargs2=s%" |
>
> Am I doing something wrong? Thank you


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by TheLinuxNinja** [comment]
I'm having the same issue. Some update did this. imapsync was working before, now it's borked:

Invalid option linkage for "sslargs1=s%"
Invalid option linkage for "sslargs2=s%"

**Comment by gilleslamiral** [comment]
Hi Bryan,

Update perl module Getopt::Long

On 10/06/2016 01:14, Bryan L. Gay wrote:
> I'm having the same issue. Some update did this. imapsync was working before, now it's borked:
>
> Invalid option linkage for "sslargs1=s%"
> Invalid option linkage for "sslargs2=s%"


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
