### ISSUE TITLE
Account won't get synced besides it has emails

### ISSUE THREAD

**Issue by mad4dweb** [imapsync/imapsync#70]
I have successfully migrated 200 accounts with imapsync, how ever im having an issue with 2 accounts that have emails but the emails won't get synced

you will se imapsync is detecting the size of the account on host 1

-rwxrwxrwx  1 md-hvers md-hvers 7.4G Jun 27 07:04 reservaciones2

Host1 folder     1/2 [INBOX]                             Size: 7986656845 Messages: 56811 Biggest:  35746047
Host2 folder     1/2 [INBOX]                             Size:  84574837 Messages:   192 Biggest:  10044433

how ever when syncing after 2 minutes it closes, we transferred several accounts over 7GB and they get transferred without errors and the Log files gets saved without data.

-rw-r--r--. 1 root     root        0 jun 28 01:20 2016_06_28_01_20_50_reservaciones2@

Here is the Log ( i replaced de domain info)

syncing to user reservaciones2@DOMAIN
Transfer started at Wed Jun 29 00:32:10 2016
PID is 21957
Log file is LOG_imapsync/2016_06_29_00_32_10_reservaciones2@DOMAIN.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
$RCSfile: imapsync,v $ $Revision: 1.684 $ $Date: 2016/03/17 08:35:03 $ 
Here is a [linux] system (Linux SERVER 3.10.0-123.8.1.el7.x86_64 #1 SMP Mon Sep 22 19:06:58 UTC 2014 x86_64)
With perl 5.16.3 Mail::IMAPClient  3.34
Command line used:
/usr/bin/imapsync --uidexpunge2 --usecache --tmpdir /var/tmp --host1 HOST1/ --user1 reservaciones2@DOMAIN --password1 MASKED --host2 127.0.0.1 --user2 reservaciones2@DOMAIN --password2 MASKED --exclude Trash|Junk|Drafts|Spam|Deleted|Eliminado|Borrado|Basura
Temp directory is /var/tmp  ( to change it use --tmpdir dirpath )
PID file is /var/tmp/imapsync.pid ( to change it use --pidfile filepath ; to avoid it use --pidfile "" )
Modules version list:
Mail::IMAPClient     3.34
IO::Socket           1.34
IO::Socket::IP       0.21
IO::Socket::INET     1.33
IO::Socket::SSL      1.94
Net::SSLeay          1.55
Compress::Zlib       2.061
Digest::MD5          2.52
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Term::ReadKey        2.30
File::Spec           3.40
Time::HiRes          1.9725
Unicode::String      2.09
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON                 ?
JSON::WebToken       ?
Crypt::OpenSSL::RSA  ?
LWP                  ?
HTML::Entities       ?
Filesys::DfPortable  ?
( use --no-modules_version to turn off printing this Perl modules list )
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connexion timeout is 120 seconds
Host2: imap connexion timeout is 120 seconds
Host1: IMAP server [HOST1/] port [143] user [reservaciones2@DOMAIN]
Host2: IMAP server [127.0.0.1] port [143] user [reservaciones2@DOMAIN]
Host1: connecting and login on host1 [HOST1/] port [143] with user [reservaciones2@DOMAIN]
Host1 banner: \* OK Dovecot ready.
Host1: HOST1/ says it has NO CAPABILITY for AUTHENTICATE LOGIN
Host1: success login on [HOST1/] with user [reservaciones2@DOMAIN] auth [LOGIN]
Host2: connecting and login on host2 [127.0.0.1] port [143] with user [reservaciones2@DOMAIN]
Host2 banner: \* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Host2: 127.0.0.1 says it has CAPABILITY for AUTHENTICATE LOGIN
Host2: success login on [127.0.0.1] with user [reservaciones2@DOMAIN] auth [LOGIN]
Host1: state Authenticated
Host2: state Authenticated
Host1 capability: IMAP4rev1 SASL-IR SORT THREAD=REFERENCES MULTIAPPEND UNSELECT LITERAL+ IDLE CHILDREN NAMESPACE LOGIN-REFERRALS
Host2 capability: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE
Host1: found 5 folders.
Host2: found 5 folders.
Including all folders found by default. Use --subscribed or --folder or --folderrec or --include to select specific folders. Use --exclude to unselect specific folders.
Excluding folders matching pattern Trash|Junk|Drafts|Spam|Deleted|Eliminado|Borrado|Basura
[Drafts]
[Spam]
[Trash]

Host1: checking all wanted folders exist.
Host1: checking all wanted folders are selectable. Use --nocheckselectable to avoid this check.
Host1: guessing separator from folder listing: [/]
Host1: separator given by NAMESPACE: [/]
Host2: guessing separator from folder listing: [/]
Host2: separator given by NAMESPACE: [.]
Host1: guessing prefix from folder listing: []
Host1: prefix given by NAMESPACE: []
Host2: guessing prefix from folder listing: []
Host2: prefix given by NAMESPACE: []
Host1 separator and prefix: [/][]
Host2 separator and prefix: [.][]
Turned off automapping folders ( use --automap to turn on automapping )

++++ Listing folders
All foldernames are presented between brackets like [X] where X is the foldername.
When a foldername contains non-ASCII characters it is presented in the form
[X] = [Y] where
X is the imap foldername you have to use in command line options and
Y is the uft8 output just printed for convenience, to recognize it.

Host1 folders list:
[Drafts]
[INBOX]
[Sent]
[Spam]
[Trash]

Host2 folders list:
[Drafts]
[INBOX]
[Sent]
[Spam]
[Trash]

Folders mapping from --automap feature (use --f1f2 to override any mapping):

Folders mapping from --f1f2 options, it overrides --automap:

Folders sizes before the synchronization.
You can remove foldersizes listings by using "--nofoldersizes" and  "--nofoldersizesatend"
but then you will also loose the ETA (Estimation Time of Arrival) given after each message copy.
++++ Calculating sizes of 2 folders on Host1
Host1 folder     1/2 [INBOX]                             Size: 7986656845 Messages: 56811 Biggest:  35746047
Host1 folder     2/2 [Sent]                              Size:         0 Messages:     0 Biggest:         0
Host1 Nb folders:                2 folders
Host1 Nb messages:           56811 messages
Host1 Total size:       7986656845 bytes (7.438 GiB)
Host1 Biggest message:    35746047 bytes (34.090 MiB)
Host1 Time spent:              5.4 seconds
++++ Calculating sizes of 2 folders on Host2
Host2 folder     1/2 [INBOX]                             Size:  84574837 Messages:   192 Biggest:  10044433
Host2 folder     2/2 [Sent]                              Size:         0 Messages:     0 Biggest:         0
Host2 Nb folders:                2 folders
Host2 Nb messages:             192 messages
Host2 Total size:         84574837 bytes (80.657 MiB)
Host2 Biggest message:    10044433 bytes (9.579 MiB)
Host2 Time spent:              0.1 seconds
++++ Looping on each one of 2 folders to sync
    1/2 [INBOX]                             -> [INBOX]  
cache directory: /var/tmp/imapsync_cache/HOST1//reservaciones2@DOMAIN/127.0.0.1/reservaciones2@DOMAIN/INBOX/INBOX
CACHE h1 h2: 0 files

./imapsync1.sh: línea 13: 21957 Terminado (killed)      imapsync --uidexpunge2 --usecache --tmpdir /var/tmp --host1 "$s1" --user1 "$u1" --password1 "$p1" --host2 "$s2" --user2 "$u2" --password2 "$p2" --exclude 'Trash|Junk|Drafts|Spam|Deleted|Eliminado|Borrado|Basura'
syncing to user 
Transfer started at Wed Jun 29 00:32:58 2016
PID is 21967
Log file is LOG_imapsync/2016_06_29_00_32_58.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
$RCSfile: imapsync,v $ $Revision: 1.684 $ $Date: 2016/03/17 08:35:03 $ 
Here is a [linux] system (Linux SERVER 3.10.0-123.8.1.el7.x86_64 #1 SMP Mon Sep 22 19:06:58 UTC 2014 x86_64)
With perl 5.16.3 Mail::IMAPClient  3.34
Command line used:
/usr/bin/imapsync --uidexpunge2 --usecache --tmpdir /var/tmp --host1  --user1  --password1 MASKED --host2  --user2  --password2 MASKED --exclude Trash|Junk|Drafts|Spam|Deleted|Eliminado|Borrado|Basura
Temp directory is /var/tmp  ( to change it use --tmpdir dirpath )
PID file is /var/tmp/imapsync.pid ( to change it use --pidfile filepath ; to avoid it use --pidfile "" )
/var/tmp/imapsync.pid already exists, overwriting it ( use --pidfilelocking to avoid concurrent runs )
Modules version list:

**Comment by gilleslamiral** [comment]
Hi mad4dweb,

An empty log file and a process killed are strange. What gives commands df and df -i

   df -i
   df


On 29/06/2016 07:45, mad4dweb wrote:
> I have successfully migrated 200 accounts with imapsync, how ever im having an issue with 2 accounts that have emails but the emails won't get synced
>
> you will se imapsync is detecting the size of the account on host 1
>
> -rwxrwxrwx 1 md-hvers md-hvers 7.4G Jun 27 07:04 reservaciones2
>
> Host1 folder 1/2 [INBOX] Size: 7986656845 Messages: 56811 Biggest: 35746047
> Host2 folder 1/2 [INBOX] Size: 84574837 Messages: 192 Biggest: 10044433
>
> how ever when syncing after 2 minutes it closes, we transferred several accounts over 7GB and they get transferred without errors and the Log files gets saved without data.
>
> -rw-r--r--. 1 root root 0 jun 28 01:20 2016_06_28_01_20_50_reservaciones2@
>
> Here is the Log ( i replaced de domain info)
>
> ...
> cache directory: /var/tmp/imapsync_cache/HOST1//reservaciones2@DOMAIN/127.0.0.1/reservaciones2@DOMAIN/INBOX/INBOX
> CACHE h1 h2: 0 files
>
> ./imapsync1.sh: línea 13: 21957 Terminado (killed) imapsync --uidexpunge2 ...

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
mails are stored in /mailvolumes/vol1

yes it is strange because i run any other sync and works fine except for this account


/dev/xvda1          20510288  2032140    17413240  11% /
devtmpfs              243056        0      243056   0% /dev
tmpfs                 248236        0      248236   0% /dev/shm
tmpfs                 248236    28976      219260  12% /run
tmpfs                 248236        0      248236   0% /sys/fs/cgroup
/dev/xvdb1         103079864 70823716    26996936  73% /mailvolumes/vol1



[root@imap ~]# df -i
S.ficheros     Nodos-i NUsados NLibres NUso% Montado en
/dev/xvda1     1310720   47370 1263350    4% /
devtmpfs         60764     303   60461    1% /dev
tmpfs            62059       1   62058    1% /dev/shm
tmpfs            62059     374   61685    1% /run
tmpfs            62059      13   62046    1% /sys/fs/cgroup
/dev/xvdb1     6553600  315509 6238091    5% /mailvolumes/vol1

**Comment by gilleslamiral** [comment]
Hi,

What happen on next runs? Same termination?

Le 01/07/2016 à 01:52, mad4dweb a écrit :
> mails are stored in /mailvolumes/vol1
>
> yes it is strange because i run any other sync and works fine except for this account
>


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
yes same termination

2016-06-30 19:49 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:

**Comment by gilleslamiral** [comment]
Hi,

What happens with --useuid?

   imapsync ... --useuid

> yes same termination
>
>> What happen on next runs? Same termination?


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
It worked!!!!

what does --useuid do?

2016-07-02 3:36 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:

**Comment by gilleslamiral** [comment]
Issue solved. Closing.
