### ISSUE TITLE
Simplified LOG

### ISSUE THREAD

**Issue by mad4dweb** [imapsync/imapsync#71]
Is there a way that when syncing multiple accounts 
to use a simple Log
Example

account1@domain.com    Host1/Folders1/Messages1/    Host2/Folders2/Messages2/  Synced/Folders2/Messages2/

this is in order to find unsynced accounts

**Comment by gilleslamiral** [comment]
Hi,

I don't understand what you describe.
Can you develop a little?

An unsynced account is an account that has not been synced yet
or synced with some errors.

Le 04/07/2016 à 01:57, mad4dweb a écrit :
> Is there a way that when syncing multiple accounts
> to use a simple Log
> Example
>
> account1@domain.com  Host1/Folders1/Messages1/ Host2/Folders2/Messages2/ Synced/Folders2/Messages2/
>
> this is in order to find unsynced accounts


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
When you sync accounts imapsync generates individual txt under LOG_imapsync
y mean to generate a Log or output that says the status of sync process


"An unsynced account is an account that has not been synced yet
or synced with some errors."

Exactly what i mean if you have to look over 500 accounts if there is a way
to create log

synced.txt
unsynced.txt

or general status LOG

account@domain.com  100% synced
account2@domain.com  80% synced   200 emails waiting to be synced
account3@domain.com   0%               Errors






2016-07-03 19:49 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:

**Comment by gilleslamiral** [comment]
Hi,

Imapsync job deals with one account at a time.
So what you describe is the job of a tool upper imapsync,
for example the shell script launching each imapsync process.

It's not that hard to get
PID
logfile
ETA
Nb errors
exit status

Doing some head/grep/tail in the log file will give many useful values.
Of course, it's easier to say that than writing this script.

A start is modifying the loop in
https://imapsync.lamiral.info/examples/sync_loop_unix.sh

   { while ..
       do
          ...
          imapsync ...
          EXIT_STATUS=$?
          if test 0 -eq $EXIT_STATUS ; then
              echo "SUCCESS imapsync from host1 $h1 user1 $u1 to host2 $h2 user2 $u2" >> synced.txt
          else
              echo "FAILURE imapsync from host1 $h1 user1 $u1 to host2 $h2 user2 $u2" >> unsynced.txt
          fi
       done
} < file.txt




On 04/07/2016 04:00, mad4dweb wrote:
> When you sync accounts imapsync generates individual txt under LOG_imapsync
> y mean to generate a Log or output that says the status of sync process
>
>
> "An unsynced account is an account that has not been synced yet
> or synced with some errors."
>
> Exactly what i mean if you have to look over 500 accounts if there is a way
> to create log
>
> synced.txt
> unsynced.txt
>
> or general status LOG
>
> account@domain.com 100% synced
> account2@domain.com 80% synced 200 emails waiting to be synced
> account3@domain.com 0% Errors
>
>
>
>
>
>
> 2016-07-03 19:49 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:
>
>> Hi,
>>
>> I don't understand what you describe.
>> Can you develop a little?
>>
>> An unsynced account is an account that has not been synced yet
>> or synced with some errors.
>>
>> Le 04/07/2016 à 01:57, mad4dweb a écrit :
>> > Is there a way that when syncing multiple accounts
>> > to use a simple Log
>> > Example
>> >
>> > account1@domain.com Host1/Folders1/Messages1/ Host2/Folders2/Messages2/
>> Synced/Folders2/Messages2/
>> >
>> > this is in order to find unsynced accounts
>>
>>
>> --
>> Au revoir, 09 51 84 42 42
>> Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/imapsync/imapsync/issues/71#issuecomment-230185617>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ATQ6NQOXnmRxnrKg0sfjD_f5CTQybVtOks5qSFiKgaJpZM4JD-bj>
>> .
>>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/imapsync/imapsync/issues/71#issuecomment-230190780>, or mute the thread <https://github.com/notifications/unsubscribe/ADKDheIBaWdyGhuE-8xPaBC-CSFsrvroks5qSGlZgaJpZM4JD-bj>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
it work to know the account with the errors

But When going to the LOG_imapsync the log for this account has no
information its blank

#!/bin/sh

{ while IFS=';' read s1 u1 p1 s2 u2 p2

    do

       { echo "$u1" | egrep "^#" ; } > /dev/null && continue

         NOW=`date +%Y_%m_%d_%H_%M_%S`

         echo syncing to user "$u2"

     #    imapsync --delete2 --uidexpunge2 \

          imapsync --uidexpunge2 --no-modules_version --useuid\

                  --host1 "$s1" --user1 "$u1" --password1 "$p1" \

                  --host2 "$s2" --user2 "$u2" --password2 "$p2" \

                  --exclude
'Trash|Junk|Drafts|Spam|Deleted|Eliminado|Borrado|Basura'


EXIT_STATUS=$?

if test 0 -eq $EXIT_STATUS ; then

echo "SUCCESS imapsync from host1 $s1 user1 $u1 to host2 $s2 user2 $u2" >>
synced.txt

else

echo "FAILURE imapsync from host1 $s1 user1 $u1 to host2 $s2 user2 $u2" >>
unsynced.txt

fi




    done

} < imapaccounts2sync.txt

2016-07-04 5:12 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:

**Comment by gilleslamiral** [comment]
Hi,

> it work to know the account with the errors

Good start.
  
> But When going to the LOG_imapsync the log for this account has no
> information its blank

Strange. Run the script with only this account and send us the output
with both stderr and stdout. It sounds a shell scripting or permission issue.

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
unsynced.txt


FAILURE imapsync from host1 mail.mad4dweb.net user1 maytee@domain.com to
host2 127.0.0.1 user2 maytee@domain.com

FAILURE imapsync from host1 mail.mad4dweb.net user1 rarroyo@domain.com to
host2 127.0.0.1 user2 rarroyo@domain.com

FAILURE imapsync from host1 mail.mad4dweb.net user1
reservaciones2@domain.com to host2 127.0.0.1 user2 reservaciones2@domain.com

FAILURE imapsync from host1 mail.mad4dweb.net user1 reservaciones@domain.com to
host2 127.0.0.1 user2 reservaciones@domain.com


LOG_imapsync dir

-rw-r--r--. 1 root     root        0 jul  4 11:08
2016_07_04_11_08_22_rarroyo@domain.com.txt

-rw-r--r--. 1 root     root     8,3K jul  4 11:09
2016_07_04_11_08_57_rarroyo@domain.com.txt

-rw-r--r--. 1 root     root     8,1K jul  4 11:09
2016_07_04_11_09_29_rarroyo@domain.pa.txt

-rw-r--r--. 1 root     root     7,6K jul  4 11:09
2016_07_04_11_09_35_rbarreiro@domain.com.txt

-rw-r--r--. 1 root     root     7,5K jul  4 11:09
2016_07_04_11_09_42_recepcion@domain.com.txt

-rw-r--r--. 1 root     root     7,9K jul  4 11:09
2016_07_04_11_09_46_relacionesprofesionales@domain.org.pa.txt

-rw-r--r--. 1 root     root        0 jul  4 11:09
2016_07_04_11_09_58_reservaciones2@domain.com.txt




[root@imap LOG_imapsync]# ls -lh |grep may

-rw-r--r--. 1 root root    0 jun 29 01:04 2016_06_29_01_04_36_*may*
tee@grupogardellini.com.txt

-rw-r--r--. 1 root root    0 jul  3 17:00 2016_07_03_17_00_19_*may*
tee@grupogardellini.com.txt

-rw-r--r--. 1 root root    0 jul  3 17:31 2016_07_03_17_31_19_*may*
tee@grupogardellini.com.txt

-rw-r--r--. 1 root root    0 jul  4 11:02 2016_07_04_11_02_49_*may*
tee@grupogardellini.com.txt


Out when running imapsync

syncing to user maytee@grupogardellini.com

Transfer started at Mon Jul  4 11:02:49 2016

PID is 19857

Log file is LOG_imapsync/2016_07_04_11_02_49_maytee@grupogardellini.com.txt
( to change it, use --logfile path ; or use --nolog to turn off logging )

$RCSfile: imapsync,v $ $Revision: 1.684 $ $Date: 2016/03/17 08:35:03 $

Here is a [linux] system (Linux imap.mad4dweb.net 3.10.0-123.8.1.el7.x86_64
#1 SMP Mon Sep 22 19:06:58 UTC 2014 x86_64)

With perl 5.16.3 Mail::IMAPClient  3.34

Command line used:

/usr/bin/imapsync --uidexpunge2 --no-modules_version --host1
mail.mad4dweb.net --user1 maytee@grupogardellini.com --password1 MASKED
--host2 127.0.0.1 --user2 maytee@grupogardellini.com --password2 MASKED
--exclude Trash|Junk|Drafts|Spam|Deleted|Eliminado|Borrado|Basura|Correo
electr&APM-nico no deseado|Elementos Eliminados

Temp directory is /tmp  ( to change it use --tmpdir dirpath )

PID file is /tmp/imapsync.pid ( to change it use --pidfile filepath ; to
avoid it use --pidfile "" )

Info: turned ON syncinternaldates, will set the internal dates (arrival
dates) on host2 same as host1.

Host1: will try to use LOGIN authentication on host1

Host2: will try to use LOGIN authentication on host2

Host1: imap connexion timeout is 120 seconds

Host2: imap connexion timeout is 120 seconds

Host1: IMAP server [mail.mad4dweb.net] port [143] user [
maytee@grupogardellini.com]

Host2: IMAP server [127.0.0.1] port [143] user [maytee@grupogardellini.com]

Host1: connecting and login on host1 [mail.mad4dweb.net] port [143] with
user [maytee@grupogardellini.com]

Host1 banner: * OK Dovecot ready.

Host1: mail.mad4dweb.net says it has NO CAPABILITY for AUTHENTICATE LOGIN

Host1: success login on [mail.mad4dweb.net] with user [
maytee@grupogardellini.com] auth [LOGIN]

Host2: connecting and login on host2 [127.0.0.1] port [143] with user [
maytee@grupogardellini.com]

Host2 banner: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS
ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.

Host2: 127.0.0.1 says it has CAPABILITY for AUTHENTICATE LOGIN

Host2: success login on [127.0.0.1] with user [maytee@grupogardellini.com]
auth [LOGIN]

Host1: state Authenticated

Host2: state Authenticated

Host1 capability: IMAP4rev1 SASL-IR SORT THREAD=REFERENCES MULTIAPPEND
UNSELECT LITERAL+ IDLE CHILDREN NAMESPACE LOGIN-REFERRALS

Host2 capability: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE
SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT
MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS
LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN
CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE

Host1: found 1 folders.

Host2: found 1 folders.

Including all folders found by default. Use --subscribed or --folder or
--folderrec or --include to select specific folders. Use --exclude to
unselect specific folders.

Excluding folders matching pattern
Trash|Junk|Drafts|Spam|Deleted|Eliminado|Borrado|Basura|Correo
electr&APM-nico no deseado|Elementos Eliminados


Host1: checking all wanted folders exist.

Host1: checking all wanted folders are selectable. Use --nocheckselectable
to avoid this check.

Host1: guessing separator from folder listing: [/]

Host1: separator given by NAMESPACE: [/]

Host2: guessing separator from folder listing: [/]

Host2: separator given by NAMESPACE: [.]

Host1: guessing prefix from folder listing: []

Host1: prefix given by NAMESPACE: []

Host2: guessing prefix from folder listing: []

Host2: prefix given by NAMESPACE: []

Host1 separator and prefix: [/][]

Host2 separator and prefix: [.][]

Turned off automapping folders ( use --automap to turn on automapping )


++++ Listing folders

All foldernames are presented between brackets like [X] where X is the
foldername.

When a foldername contains non-ASCII characters it is presented in the form

[X] = [Y] where

X is the imap foldername you have to use in command line options and

Y is the uft8 output just printed for convenience, to recognize it.


Host1 folders list:

[INBOX]


Host2 folders list:

[INBOX]


Folders mapping from --automap feature (use --f1f2 to override any mapping):


Folders mapping from --f1f2 options, it overrides --automap:



Folders sizes before the synchronization.

You can remove foldersizes listings by using "--nofoldersizes" and
"--nofoldersizesatend"

but then you will also loose the ETA (Estimation Time of Arrival) given
after each message copy.

++++ Calculating sizes of 1 folders on Host1

Host1 folder     1/1 [INBOX]                             Size: 5845090186
Messages: 13621 Biggest:  30347899

Host1 Nb folders:                1 folders

Host1 Nb messages:           13621 messages

Host1 Total size:       5845090186 bytes (5.444 GiB)

Host1 Biggest message:    30347899 bytes (28.942 MiB)

Host1 Time spent:              3.0 seconds

++++ Calculating sizes of 1 folders on Host2

Host2 folder     1/1 [INBOX]                             Size: 5042278990
Messages: 11471 Biggest:  30347899

Host2 Nb folders:                1 folders

Host2 Nb messages:           11471 messages

Host2 Total size:       5042278990 bytes (4.696 GiB)

Host2 Biggest message:    30347899 bytes (28.942 MiB)

Host2 Time spent:              0.6 seconds

++++ Looping on each one of 1 folders to sync

    1/1 [INBOX]                             -> [INBOX]


./imapsync.sh: línea 21: 19857 Terminado (killed)      imapsync
--uidexpunge2 --no-modules_version --host1 "$s1" --user1 "$u1" --password1
"$p1" --host2 "$s2" --user2 "$u2" --password2 "$p2" --exclude
'Trash|Junk|Drafts|Spam|Deleted|Eliminado|Borrado|Basura|Correo
electr&APM-nico no deseado|Elementos Eliminados'

syncing to user mcastillo@grupogardellini.com

Transfer started at Mon Jul  4 11:03:20 2016

PID is 19896

Log file is
LOG_imapsync/2016_07_04_11_03_20_mcastillo@grupogardellini.com.txt ( to
change it, use --logfile path ; or use --nolog to turn off logging )

$RCSfile: imapsync,v $ $Revision: 1.684 $ $Date: 2016/03/17 08:35:03 $

Here is a [linux] system (Linux imap.mad4dweb.net 3.10.0-123.8.1.el7.x86_64
#1 SMP Mon Sep 22 19:06:58 UTC 2014 x86_64)

With perl 5.16.3 Mail::IMAPClient  3.34



2016-07-04 14:33 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:

**Comment by gilleslamiral** [comment]
Hi,

Here is the explanation:

> ./imapsync.sh: línea 21: 19857 Terminado (killed) imapsync

When killed, a process may not have the time to write anything.

Can you supervise the memory for those killed process? (just before they're killed)


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
using the command top?

The memory on both servers?

host 1 and Host2 ?



2016-07-04 16:33 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:

**Comment by gilleslamiral** [comment]
Hi,

The memory where imapsync runs and finish killed, it can be any host.
We're searching why it is killed.

Le 06/07/2016 à 00:35, mad4dweb a écrit :
> using the command top?
>
> The memory on both servers?
>
> host 1 and Host2 ?


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
Attached Images of top  when running map sync and when ended.

when runned with --useuid and only the account can't find any process killed 


![screen shot 2016-07-07 at 7 25 51 am](https://cloud.githubusercontent.com/assets/20199989/16653369/08d5cdd0-4416-11e6-98b0-1dc0eaef9154.png)
![screen shot 2016-07-07 at 7 32 57 am](https://cloud.githubusercontent.com/assets/20199989/16653371/08fb4024-4416-11e6-83de-dc00dd376df3.png)
![screen shot 2016-07-07 at 7 33 15 am](https://cloud.githubusercontent.com/assets/20199989/16653370/08f6d6ce-4416-11e6-8b9e-534d1ac0607f.png)

**Comment by gilleslamiral** [comment]
Hi,

Only 500 MB of total ram?


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
yes its a VM but with the accounts there hasn't been any issue

2016-07-07 16:34 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:

**Comment by gilleslamiral** [comment]
Hi,

You may find useful to figure out why imapsync is killed sometimes,
as shown by the logs you sent me.
Memory could be the issue.

On 08/07/2016 01:22, mad4dweb wrote:
> yes its a VM but with the accounts there hasn't been any issue
>
> 2016-07-07 16:34 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:
>
>> Hi,
>>
>> Only 500 MB of total ram?

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by mad4dweb** [comment]
thanks ill try to increase the memory whats the recommended memory for the
machine that runs map sync




2016-07-12 9:07 GMT-05:00 Gilles LAMIRAL <notifications@github.com>:

**Comment by gilleslamiral** [comment]
Hi,

The current release crunches 5x the biggest message size in memory.
Next will do 2x.

Le 14/07/2016 à 08:19, mad4dweb a écrit :
> thanks ill try to increase the memory whats the recommended memory for the
> machine that runs map sync

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
