### ISSUE TITLE
Duplicate Emails on Sync

### ISSUE THREAD

**Issue by mad4dweb** [imapsync/imapsync#72]
When running with command  --useuid

 imapsync --uidexpunge2 --no-modules_version --useuid

Emails are duplicated 

Can we remove duplicates?

![screen shot 2016-07-07 at 7 35 26 am](https://cloud.githubusercontent.com/assets/20199989/16653559/ef13b49c-4416-11e6-931f-98e55c55f767.png)
![screen shot 2016-07-07 at 7 44 56 am](https://cloud.githubusercontent.com/assets/20199989/16653558/ef0e19b0-4416-11e6-8588-f4d0b0d46c0c.png)
![screen shot 2016-07-07 at 7 45 06 am](https://cloud.githubusercontent.com/assets/20199989/16653560/ef151c42-4416-11e6-95bb-9476bab6a79c.png)

**Comment by gilleslamiral** [comment]
Hi,

You can remove duplicates with --delete2 but be careful


      --delete2           : Delete messages in host2 that are not in
                            host1 server. Useful for backup or pre-sync.
      --delete2duplicates : Delete messages in host2 that are duplicates.
                            Works only without --useuid since duplicates are
                            detected with an header part of each message.


Le 07/07/2016 à 14:48, mad4dweb a écrit :
> When running with command --useuid
>
> imapsync --uidexpunge2 --no-modules_version --useuid
>
> Emails are duplicated
>
> Can we remove duplicates?


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06
