### ISSUE TITLE
How to get around "NO CAPABILITY for AUTHENTICATE LOGIN"

### ISSUE THREAD

**Issue by larryathey** [imapsync/imapsync#74]
I see this error far too often and only know how to get around it in Gmail by enabling their feature that allows access by less secure apps. But, now I'm dealing with a hosted Exchange server (hosted by Intermedia) and have no way to get around this on the host's end. As a matter of fact, they're not even slightly willing to help because they seem to think that imapsync is a product of a competitor (no idea how they came up with that notion).

At any rate, the host only allows IMAP connections on port 993 with SSL. I've tried every command line option there is and I can't get imapsync to authenticate with the Microsoft IMAP4 server. Even though the capability response says AUTH=PLAIN I've tried using --authmech2 PLAIN and the server drops me like a hot potato. I'm out of ideas.

Host2: connecting and login on host2 [west.EXCH081.serverdata.net] port [993] with user [accounting@domain.com]
Connecting with IO::Socket::SSL PeerAddr west.EXCH081.serverdata.net PeerPort 993 Proto tcp Timeout 120 Debug 1 SSL_verify_mode 0 SSL_verifycn_scheme imap
Connected to west.EXCH081.serverdata.net
Read:   \* OK The Microsoft Exchange IMAP4 service is ready.
Host2 banner: \* OK The Microsoft Exchange IMAP4 service is ready.
Sending: 1 CAPABILITY
Sent 14 bytes
Read:   \* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
    1 OK CAPABILITY completed.
Host2: west.EXCH081.serverdata.net says it has NO CAPABILITY for AUTHENTICATE LOGIN
Sending literal: 2 LOGIN accounting@domain.com {10}
    then: [Redact: Count=2 Showcredentials=OFF]
Sending: 2 LOGIN accounting@domain.com {10}
Sent 40 bytes
Read:   + Ready for additional command text.
Sending: [Redact: Count=2 Showcredentials=OFF]
Sent 11 bytes
Read:   \* BYE Connection is closed. 13

**Comment by larryathey** [comment]
With --authmech2 PLAIN, same passwords at both hosts, Outlook has both accounts working so I know that host2 isn't rejecting it based on an incorrect password.

Host2: connecting and login on host2 [west.EXCH081.serverdata.net] port [993] with user [accounting@domain.com]
Connecting with IO::Socket::SSL PeerAddr west.EXCH081.serverdata.net PeerPort 993 Proto tcp Timeout 120 Debug 1 SSL_verify_mode 0 SSL_verifycn_scheme imap
Connected to west.EXCH081.serverdata.net
Read: 	* OK The Microsoft Exchange IMAP4 service is ready.
Host2 banner: * OK The Microsoft Exchange IMAP4 service is ready.
Sending: 1 CAPABILITY
Sent 14 bytes
Read: 	* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
  	1 OK CAPABILITY completed.
Host2: west.EXCH081.serverdata.net says it has CAPABILITY for AUTHENTICATE PLAIN
Sending: 2 AUTHENTICATE PLAIN
Sent 22 bytes
Read: 	+
Sending: [Redact: Count=2 Showcredentials=OFF]
Sent 86 bytes
Read: 	2 NO AUTHENTICATE failed.

**Comment by gilleslamiral** [comment]
Hi Larry,

The message "NO CAPABILITY for AUTHENTICATE LOGIN" is not relevant.
I've never seen any server refusing to authenticate via LOGIN.

Double check the complete triplet: host & user & password.

Read:
http://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt
http://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Windows.txt

> I see this error far too often and only know how to get around it in Gmail by enabling their feature that allows access by less secure apps. But, now I'm dealing with a hosted Exchange server (hosted by Intermedia) and have no way to get around this on the host's end. As a matter of fact, they're not even slightly willing to help because they seem to think that imapsync is a product of a competitor (no idea how they came up with that notion).
>
> At any rate, the host only allows IMAP connections on port 993 with SSL. I've tried every command line option there is and I can't get imapsync to authenticate with the Microsoft IMAP4 server. Even though the capability response says AUTH=PLAIN I've tried using --authmech2 PLAIN and the server drops me like a hot potato. I'm out of ideas.
>
> Host2: connecting and login on host2 [west.EXCH081.serverdata.net] port [993] with user [accounting@domain.com <mailto:accounting@domain.com>]
> Connecting with IO::Socket::SSL PeerAddr west.EXCH081.serverdata.net PeerPort 993 Proto tcp Timeout 120 Debug 1 SSL_verify_mode 0 SSL_verifycn_scheme imap
> Connected to west.EXCH081.serverdata.net
> Read: * OK The Microsoft Exchange IMAP4 service is ready.
> Host2 banner: * OK The Microsoft Exchange IMAP4 service is ready.
> Sending: 1 CAPABILITY
> Sent 14 bytes
> Read: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
> 1 OK CAPABILITY completed.
> Host2: west.EXCH081.serverdata.net says it has NO CAPABILITY for AUTHENTICATE LOGIN
> Sending literal: 2 LOGIN accounting@domain.com <mailto:accounting@domain.com> {10}
> then: [Redact: Count=2 Showcredentials=OFF]
> Sending: 2 LOGIN accounting@domain.com <mailto:accounting@domain.com> {10}
> Sent 40 bytes
> Read: + Ready for additional command text.
> Sending: [Redact: Count=2 Showcredentials=OFF]
> Sent 11 bytes
> Read: * BYE Connection is closed. 13


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by larryathey** [comment]
Arrrggghhh, had to escape characters in the passwords. I figured putting them in quotes would solve it. Thanks for the lesson! :-)

**Comment by propagare** [comment]
How did you escape the characters correctly?

**Comment by gilleslamiral** [comment]
Read:
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Windows.txt
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt

**Comment by propagare** [comment]
It worked! Thank you!

**Comment by propagare** [comment]
It worked! Thank you! 

May I ask you something OT?

**Comment by gilleslamiral** [comment]
No problem.
If it's something different than authentication then open a new issue on it. 
It's the green button "new issue" up right of this page

**Comment by gilleslamiral** [comment]
Solved

**Comment by anilnetmente** [comment]
I am facing the same issue but i am migrating my emails from gmail.com to cpanel

**Comment by gilleslamiral** [comment]
1) It looks like you use an old imapsync. This useless warning is no longer showed in the log.

2) You might have an authenticate issue.
Read:
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Windows.txt
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt

Tell me if it works.

**Comment by anilnetmente** [comment]
>     1. It looks like you use an old imapsync. This useless warning is no longer showed in the log.
> 
>     2. You might have an authenticate issue.
>        Read:
>        https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Windows.txt
>        https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt
> 
> 
> Tell me if it works.
Thank you gilleslamiral, Issue is resolved when i use upadated version :+1:
