### ISSUE TITLE
Can not go to tls encryption on host2 :1 BAD invalid command

### ISSUE THREAD

**Issue by oupala** [imapsync/imapsync#76]
I'm trying to connect an imap server from free.fr, and I get the following error:

```
Host2: connecting and login on host2 [imap.free.fr] port [143] with user [anotheruser]
Host2 banner: * OK IMAP4 ready
Host2 failure: Can not go to tls encryption on host2 [imap.free.fr]:1 BAD invalid command
```

My command was:

```
imapsync --host1 mail.example.org --user1 user@example.org \
 --passfile1 mailsync.server1.passwd --tls1 --host2 imap.free.fr \
 --user2 anotheruser --passfile2 mailsync.server2.passwd --tls2 \
 --justfoldersizes
```

Is it normal to connect on port 149 and not on port 993?

Is there anything wrong with the `imap.free.fr` server or its certificate?

The same command without `--tls2` parameter disabled is successful.

**Comment by oupala** [comment]
Might be linked to #69.

**Comment by oupala** [comment]
imapsync is [known to work well](http://morgantreize.com/migrer-une-boite-mail-avec-imapsync/) (or having worked well) with `imap.free.fr`.

**Comment by gilleslamiral** [comment]
Hi Oupala,

Use --ssl1 --ssl2 instead of --tls1 --tls2


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by oupala** [comment]
It works with `ssl` instead of `tls`.

Thanks !
