### ISSUE TITLE
wrong port with TLS enabled

### ISSUE THREAD

**Issue by oupala** [imapsync/imapsync#77]
I have a proxy problem with the following configuration:

```bash
imapsync --dry --host1 mail.isp.net --user1 user@isp.net --passfile1 /home/user/conf/mailsync.server1.passwd --tls1 --host2 imap.new-example.fr --user2 myusername --passfile2 /home/user/conf/mailsync.server2.passwd --tls2 --exclude  --useheader Message-ID --skipsize --sub
scribe --expunge1 --expunge2 --delete2 --syncinternaldates
```

And the log is:

```log
Host1: IMAP server [mail.isp.net] port [143] user [myuser]
Host2: IMAP server [imap.new-example.fr] port [143] user [myuser]
```

It appears that the script is launched on port 143 instead of port 993.

How can that be explained?

**Comment by gilleslamiral** [comment]
Hi Oupala,

The default port for TLS in imap is the same as the default imap port 143.
The default port for imaps (imap over ssl) is 993.

Forcing port 993 for TLS is usually a mistake.
Anyway it can be done with

   imapsync ...  --tls1 --port1 993


Le 31/08/2016 à 02:01, oupala a écrit :
> hi
>
> imapsync --dry --host1 mail.isp.net  --tls1 --host2 imap.new-example.fr --tls2 --exclude
> And the log is:
>
> |Host1: IMAP server [mail.isp.net] port [143] user [myuser] Host2: IMAP server [imap.new-example.fr] port [143] user [myuser] |
>
> It appears that the script is launched on port 143 instead of port 993.
>
> How can that be controlled?


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by oupala** [comment]
Ok, so using TLS with IMAP does not set the default port ti 993 but stays to 143.

But you seem to make a difference between:

- imap over ssl, named *imaps* which default port is 993
- imap over tls which default port is still 143

Am I right?

As a counter-example, two major french mail service provider seem to use port 993 for imap with SSL/TLS:

- [Free](http://www.free.fr/assistance/2513.html)
- [Gandi](https://wiki.gandi.net/fr/mail/standard-settings#parametres_popimap)

The main point explaining my confusion is that service providers often don't do any difference between SSL and TLS in their documentation.

**Comment by gilleslamiral** [comment]
Hi Oupala,

> Ok, so using TLS with IMAP does not set the default port ti 993 but stays to 143.
>
> But you seem to make a difference between:
>
>   * imap over ssl, named /imaps/ which default port is 993
>   * imap over tls which default port is still 143
>
> Am I right?

You are!
More precisely, tls is ssl "inside" imap, ie, a transition to encryption after an initial and standard imap connection,
it's why it is on the same port: same start, same port.

> As a counter-example, two major french mail service provider seem to use port 993 for imap with SSL/TLS:
>
>   * Free <http://www.free.fr/assistance/2513.html>
>   * Gandi <https://wiki.gandi.net/fr/mail/standard-settings#parametres_popimap>
>
> The main point explaining my confusion is that service providers often don't do any difference between SSL and TLS in their documentation.

TLS is done after and imap command "STARTTLS" => ssl inside imap
SSL is done before imap "SSL/TLS"  => imap over ssl


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by oupala** [comment]
Wow, the difference between *ssl inside imap* and *imap over ssl* was hard to get.

Thanks for these explanations.

I'm now using `--tls1` for Gandi and `--ssl2` for Free.

**Comment by gilleslamiral** [comment]
Hi,

More precisely it is more "before/after" than "over/inside" but you got the idea.

Le 01/09/2016 à 23:18, oupala a écrit :
> Wow, the difference between /ssl inside imap/ and /imap over ssl/ was hard to get.
>
> Thanks for these explanations.
>
> I'm now using |--tls1| for Gandi and |--ssl2| for Free.

Ok.

-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by oupala** [comment]
I like to be precise, and it could be useful to other users.

So, let's sum up:

- on port 143, you can have standard IMAP, or secured IMAP with TLS (which start with standard IMAP, then add the TLS security layer)
- on port 993, you can have IMAP secured by SSL (which is from the start of the connection secured by SSL)

But as SSL is known to be unsecure now (it has many security holes), we should use IMAP on port 143 with TLS encrpytion. Right?

**Comment by gilleslamiral** [comment]
Hi Oupala,

Le 02/09/2016 à 10:16, oupala a écrit :
> I like to be precise, and it could be useful to other users.

Few people read this list.

> So, let's sum up:
>
>   * on port 143, you can have standard IMAP, or secured IMAP with TLS (which start with standard IMAP, then add the TLS security layer)
>   * on port 993, you can have IMAP secured by SSL (which is from the start of the connection secured by SSL)

Yes.

> But as SSL is known to be unsecure now (it has many security holes), we should use IMAP on port 143 with TLS encrpytion. Right?

Both are unsecure now, depending on the cipher used.

-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by oupala** [comment]
For you, it'a list.

For me, it's an issue on GitHub.
