### ISSUE TITLE
Installation Debian Jessie

### ISSUE THREAD

**Issue by Sylvain303** [imapsync/imapsync#81]
Following [INSTALL.d/INSTALL.Debian.txt](https://github.com/imapsync/imapsync/blob/master/INSTALL.d/INSTALL.Debian.txt)

It misses 

```
apt-get install libmail-imapclient-perl
```

**Comment by gilleslamiral** [comment]
Hi Sylvain,

In fact it's written:

This second command also installs manually Perl module Mail::IMAPClient because
it is good to be up to date:

   cpanm Data::Uniqid Mail::IMAPClient

Le 17/10/2016 à 17:51, Sylvain303 a écrit :
> Following INSTALL.d/INSTALL.Debian.txt <https://github.com/imapsync/imapsync/blob/master/INSTALL.d/INSTALL.Debian.txt>
>
> It misses
>
>   apt-get install libmail-imapclient-perl


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by amcorreia** [comment]
Hi,

But seems better to install packages from Debian instead of CPAN. Not everybody knows how update packages from CPAN, but Debian a simple "apt-get upgrade" is enough.

**Comment by gilleslamiral** [comment]
Hi,

* "apt-get upgrade" updates only packages known to have severe security issues
* Data::Uniqid is not packaged in Debian 7
* https://github.com/imapsync/imapsync/blob/master/INSTALL.d/INSTALL.Debian.txt
   gives apt-get install for most of the needed packages
* Not everybody can read


Le 21/01/2017 à 13:45, amcorreia a écrit :
> Hi,
>
> But seems better to install packages from Debian instead of CPAN. Not everybody knows how update packages from CPAN, but Debian a simple "apt-get upgrade" is enough.
>
>

-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by amcorreia** [comment]
> * "apt-get upgrade" updates only packages known to have severe security issues


From man apt-get
` 
           upgrade is used to install the newest versions of all packages currently installed on the system from the sources enumerated in /etc/apt/sources.list. Packages currently installed with new versions available are
           retrieved and upgraded; 
......
`

> * Data::Uniqid is not packaged in Debian 7

Good point. I didn't notice that.

> * https://github.com/imapsync/imapsync/blob/master/INSTALL.d/INSTALL.Debian.txt
   gives apt-get install for most of the needed packages

Yes, I read that... my point is.... keep all installed packages from Debian.

**Comment by gilleslamiral** [comment]
Hi,

>       * "apt-get upgrade" updates only packages known to have severe security issues
>
> From man apt-get
> |upgrade is used to install the newest versions of all packages currently installed on the system from the sources enumerated in /etc/apt/sources.list.
 > Packages currently installed with new versions available are retrieved and upgraded; ......|

Yes, this is the same point, new versions available are only packages known to have severe security issues.
Know your Debian. And if you argument that changing sources.list is the good thing
to do to have latest imapsync well working in Debian then ok, upgrade your Debian.
I could add: upgrade your system to one that has imapsync packaged in it.
Or package imapsync in Debian:
https://lists.debian.org/debian-user/2016/11/msg00849.html

>       * Data::Uniqid is not packaged in Debian 7
>
> Good point. I didn't notice that.
>
>       * https://github.com/imapsync/imapsync/blob/master/INSTALL.d/INSTALL.Debian.txt
>         gives apt-get install for most of the needed packages
>
> Yes, I read that... my point is.... keep all installed packages from Debian.

My point is the same except for Mail::IMAPClient,  wheezy one (3.31) is 5 years old and
known to work badly in several cases. In fact, I even don't know if it works at all with
the latest imapsync. So cpanm command might be mandatory for Mail::IMAPClient


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42
