### ISSUE TITLE
Uninitialized value line 2829

### ISSUE THREAD

**Issue by dh3wr** [imapsync/imapsync#83]
Using 1.727:
++++ Calculating sizes of 96 folders on Host2
Host2 folder    1/96 [Archive]                           Size:         0 Messages:     0 Biggest:         0
Host2 folder    2/96 [Archives/2014]                     Size:         0 Messages:     0 Biggest:         0
Host2 folder    3/96 [Bulk Mail]                         Size:         0 Messages:     0 Biggest:         0
Host2 folder    4/96 [Draft]                            Use of uninitialized value $size in addition (+) at ./imapsync line 4479.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $size in addition (+) at ./imapsync line 4479.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $size in addition (+) at ./imapsync line 4479.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $size in addition (+) at ./imapsync line 4479.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $size in addition (+) at ./imapsync line 4479.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $size in addition (+) at ./imapsync line 4479.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
 Size:         0 Messages:     6 Biggest:
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
Host2 folder    5/96 [Entw&APw-rfe] = [Entwürfe]        Size:         0 Messages:     0 Biggest:         0
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Use of uninitialized value $list[0] in sort at ./imapsync line 2829.
Host2 folder    6/96 [Gel&APY-scht] = [Gelöscht]        Size:         0 Messages:     0 Biggest:         0
Host2 folder    7/96 [Gel&APY-schte Objekte] = [Gelöschte Objekte] Size:   9404201 Messages:  1212 Biggest:    439210
Host2 folder    8/96 [Gesendet]                          Size:         0 Messages:     0 Biggest:         0
Host2 folder    9/96 [Inbox]                             Size: 2711332922 Messages:  7439 Biggest:  39097176

**Comment by gilleslamiral** [comment]
Hi Ralf,

What is the host2 imap server software?
Can you give us the output of:

   imapsync ... --folder Draft --debugimap2 --justfoldersizes

Le 28/12/2016 à 22:56, Ralf Wilke DH3WR a écrit :
> Using 1.727:
> ++++ Calculating sizes of 96 folders on Host2
> Host2 folder 1/96 [Archive] Size: 0 Messages: 0 Biggest: 0
> Host2 folder 2/96 [Archives/2014] Size: 0 Messages: 0 Biggest: 0
> Host2 folder 3/96 [Bulk Mail] Size: 0 Messages: 0 Biggest: 0
> Host2 folder 4/96 [Draft] Use of uninitialized value $size in addition (+) at ./imapsync line 4479.
> Use of uninitialized value $list[1] in sort at ./imapsync line 2829.
> Use of uninitialized value $list[1] in sort at ./imapsync line 2829
> Size: 0 Messages: 6 Biggest:

-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by bkazez** [comment]
I'm experiencing this as well with Gmail as host2.

**Comment by gilleslamiral** [comment]
Too old.
