### ISSUE TITLE
search1 vs minage

### ISSUE THREAD

**Issue by superfunnl** [imapsync/imapsync#84]
Hi,

Ive got the following setup going, except it goes wrong. I use --search1 to only delete unflagged messages, older than 45 days (--minage). But imapsync ends up deleting ALL unmarked messages. Withouth the search1, minage works as intended. I also encountered it did a double copy (did not detect duplicates on destination with --search1 enabled).

Am i missing something? Thanks.

```
frank@servert:/scripts# /usr/bin/imapsync -v
1.727
```

`/usr/bin/imapsync --host1 mailmailmail --user1 useruseruser --password1 passpasspass --ssl1 --search1 "UNFLAGGED" --host2 mailmailmail --user2 useruseruser --password2 passpasspass --expunge1 --delete1 --expunge1 --minage 45 --skipcrossduplicates --addheader`

**Comment by gilleslamiral** [comment]
Hi,

Any --search masks any --minage --maxage
Consider it a bug or a feature.

You have to add the minage value in the --search
having in mind only dates are possible in --search,
not minage values

See
https://imapsync.lamiral.info/FAQ.d/FAQ.Messages_Selection.txt


Le 31/12/2016 à 13:54, superfunnl a écrit :
> Hi,
>
> Ive got the following setup going, except it goes wrong. I use --search1 to only delete unflagged messages, older than 45 days (--minage). But imapsync ends up deleting ALL unmarked messages. Withouth the search1, minage works as intended. I also encountered it did a double copy (did not detect duplicates on destination with --search1 enabled).
>
> Am i missing something? Thanks.


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by superfunnl** [comment]
Hi, happy new year. Thanks for the quick response, ill consider it a feature then ;)

Any idea with my second issue why duplicated e-mail would not be detected with --search1 enabled?

**Comment by gilleslamiral** [comment]
Hi,

Duplicates are not related to --search
Try:

      imapsync ... --useheader Message-Id

On 02/01/2017 13:47, superfunnl wrote:
> Hi, happy new year. Thanks for the quick response, ill consider it a feature then ;)
>
> Any idea with my second issue why duplicated e-mail would not be detected with --search1 enabled?


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by superfunnl** [comment]
Thanks
