### ISSUE TITLE
XOAUTH2 authentication

### ISSUE THREAD

**Issue by tibbsbrookside** [imapsync/imapsync#87]
I've been using imapsync successfully for years now (thanks for a great tool).

I'm now trying to use it with Gmail (as a regular user) using XOAUTH2 authentication.

I've reviewed the following documentation:
https://imapsync.lamiral.info/FAQ.d/FAQ.XOAUTH2.txt

but I'm not clear what I have to do in the Google API Console.

So far I have:
1. Logged in to https://console.developers.google.com.
2. Created a new project.
3. Enabled the Gmail API.
4. Created a new service account, choosing the following options:
Service account name : imapsync
Role : Viewer (not sure what this has to be)
Furnish a new private key : checked
Enable G Suite Domain-wide Delegation : unchecked
5. Downloaded the JSON private key.

Using this JSON key in imapsync returns the error:
{
 "error": "unauthorized_client",
 "error_description": "Unauthorized client or scope in request."
}

But I cannot work out how I do the following as per the FAQ:
R. In order to work you also have to allow the service https://mail.google.com/ 
   in the Google client API manager for OAUTH2.
   "Select OAuth 2.0 scopes:"

If anyone can clarify the steps I need to take it would be much appreciated.

Thanks.

**Comment by gilleslamiral** [comment]
Hi,

Well, as the author of this FAQ.XOAUTH2.txt I can't say that much
since I also have the same error

"error": "unauthorized_client",
"error_description": "Unauthorized client or scope in request."

but I know I'm an "Unauthorized client" and I have always failed
this way with my OAUTH2 tests.

If you find something useful, drop me a note, I'll update the FAQ!


Le 29/01/2017 à 18:27, tibbsbrookside a écrit :
> I've been using imapsync successfully for years now (thanks for a great tool).
>
> I'm now trying to use it with Gmail (as a regular user) using XOAUTH2 authentication.
>
> I've reviewed the following documentation:
> https://imapsync.lamiral.info/FAQ.d/FAQ.XOAUTH2.txt
>
> but I'm not clear what I have to do in the Google API Console.
>
> So far I have:
>
>  1. Logged in to https://console.developers.google.com.
>  2. Created a new project.
>  3. Enabled the Gmail API.
>  4. Created a ne> {

> "error": "unauthorized_client",

> "error_description": "Unauthorized client or scope in request."

> }

w service account, choosing the following options:
>     Service account name : imapsync
>     Role : Viewer (not sure what this has to be)
>     Furnish a new private key : checked
>     Enable G Suite Domain-wide Delegation : unchecked
>  5. Downloaded the JSON private key.
>
> Using this JSON key in imapsync returns the error:
>
> But I cannot work out how I do the following as per the FAQ:
> R. In order to work you also have to allow the service https://mail.google.com/
> in the Google client API manager for OAUTH2.
> "Select OAuth 2.0 scopes:"
>
> If anyone can clarify the steps I need to take it would be much appreciated.

-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by tibbsbrookside** [comment]
Thanks for the quick response.

I'm just an end user, with little knowledge of how APIs and XOAUTH2 works.

All I can say is that I use a number of other applications that access Google data via an API and authenticate using XOAUTH2, with these I simply make sure the relevant API is enabled for the project and then create a "OAuth 2.0 client IDs" of type "Other". I've never had to create a "Service account" before.

I created an "OAuth 2.0 client IDs" of type "Other" for use with imapsync but I notice that the associated JSON file that can be downloaded is in a different format to one associated with a "Service account" and the imapsync tool was failing to extract the relevant information from it.

My knowledge of Perl isn't that great either but I'll continue to test a few combinations of keys / settings and I'll let you know if anything ends up working.

**Comment by tibbsbrookside** [comment]
After a day of investigating, I have found the following (note that if anyone has this working then everything I'm about to say is incorrect):

1. I can find various comments on the web suggesting that "Service Accounts" don't work with the Gmail API and / or regular (non G Suite / Google Apps) accounts.

2. Using various sources on the web, I have come up with this bit of code that successfully authenticates to Gmail via xoauth2 using a "OAuth 2.0 client ID":

`#!/usr/bin/perl

use HTTP::Request::Common qw(POST); 
use LWP::UserAgent; 
use Data::Dumper;
use Mail::IMAPClient;
use URI::Escape;
use MIME::Base64;

print "\n\nType your email address here: ";
$username = <STDIN>; 
chomp($username);

print "\n\nPaste the client_id here: ";
$client_id = <STDIN>; 
chomp($client_id);

print "\n\nPaste the client_secret here: ";
$client_secret = <STDIN>; 
chomp($client_secret);

$scope_string = "https%3A%2F%2Fmail.google.com%2F";

print "Please open the following in your web browser:\n\nhttps://accounts.google.com/o/oauth2/auth?scope=$scope_string&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&client_id=$client_id";

print "\n\nPaste the code here: ";
$code = <STDIN>; 
chomp($code);

$ENV{'PERL_LWP_SSL_VERIFY_HOSTNAME'} = 0;
my $ua = LWP::UserAgent->new;
$ua->timeout(10);
$ua->env_proxy;

print "Exchanging the code for an access token and refresh token...\n";
my $exchange_response = $ua->request(POST 'https://accounts.google.com/o/oauth2/token',
            'Content_Type'  => 'application/x-www-form-urlencoded',
            'Content'       => [
                'code'         =>  $code,
                'client_id'         =>  $client_id,
                'client_secret'     =>  $client_secret,
                'redirect_uri'     =>  'urn:ietf:wg:oauth:2.0:oob',
                'grant_type'        =>  'authorization_code',
            ],
        );

my ($access_token) = ($exchange_response->decoded_content =~ m/access_token".*"(.*)"/);
my ($refresh_token) = ($exchange_response->decoded_content =~ m/refresh_token".*"(.*)"/);

print "access token: $access_token\n";
print "refresh token: $refresh_token\n";

print "Refreshing the access token...\n";
my $auth_response = $ua->request(POST 'https://accounts.google.com/o/oauth2/token',
            'Host'          => 'accounts.google.com',
            'Content_Type'  => 'application/x-www-form-urlencoded',
            'Content'       => [
                'client_id'         =>  $client_id,
                'client_secret'     =>  $client_secret,
                'refresh_token'     =>  $refresh_token,
                'grant_type'        =>  'refresh_token',
            ],
        );

my ($access_token) = ($auth_response->decoded_content =~ m/access_token".*"(.*)"/);


my $oauth_sign = encode_base64("user=". $username ."\x01auth=Bearer ". $access_token ."\x01\x01", '');

my $imap = Mail::IMAPClient->new(
	Server	=>	'imap.gmail.com',
	Port	=>	993,
	Ssl		=> 1,
	Uid		=> 1,
) or die('Can\'t connect to imap server.');
$imap->authenticate('XOAUTH2', sub { return $oauth_sign }) or die("Auth error: ". $imap->LastError);

print join(", ",$imap->folders),".\n" or die("List folders error: ". $imap->LastError);`

As I previously mentioned, I use other apps that have an option to retrieve an access token, store it in a file, and then read it as input when authenticating. The other thing I would add is that there are a lot of references to:
https://accounts.google.com/.well-known/openid-configuration
for a list of the latest Google API URIs, but if I use:
https://www.googleapis.com/oauth2/v4/token
as the token endpoint URI then I get an "authorization failed" error.

I'm not sure if any of this is useful or can be adapted to work with imapsync, but I thought I'd let you know  just in case.

**Comment by gilleslamiral** [comment]
Hi,

Well it sounds very good!
I'll try it and include it if success and agreed from you

Does this license sweet you:
https://imapsync.lamiral.info/LICENSE

Le 31/01/2017 à 09:04, tibbsbrookside a écrit :
> After a day of investigating, I have found the following (note that if anyone has this working then everything I'm about to say is incorrect):
>
>     Using various sources on the web, I have come up with this bit of code that successfully authenticates to Gmail via xoauth2 using a "OAuth 2.0 client ID":
>

> $imap->authenticate('XOAUTH2', sub { return $oauth_sign }) or die("Auth error: ". $imap->LastError);
>
> print join(", ",$imap->folders),".\n" or die("List folders error: ". $imap->LastError);`

-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by tibbsbrookside** [comment]
None of that code is mine, it's all taken from publicly available sources on the web. As far as I'm concerned, you can do what you like with it :-)

**Comment by Enoima** [comment]
Hi, has anyone use this tool for Zimbra to Office 365 migration before?
I am currently trying out the tool to migrate mailboxes from Zimbra to O365. I was able to migrate single mailbox (test mailboxes) using username and password successfully.
Now, I want to do batch migration using the loop window batch file. I am very good with scripting so I just try to understand but I think it is not enough. The problem now is that I do not know the password for the users and want to user super user account for log in at both host1 and host2 but I am stuck currently because I don't know the parameter to specify the username and password for both hosts and where to specify it.

I would appreciate if anyone could help me out.

Thank you in advance.

**Comment by gilleslamiral** [comment]
Hi,

For Zimbra I don't if auth admin is possible, tell me if you find
something, I'll then update the FAQ.Admin_Authentication.txt

For Exchange:

https://imapsync.lamiral.info/FAQ.d/FAQ.Admin_Authentication.txt
==============================================
    Imapsync tips about admin authentication.
==============================================

It can be useful to authenticate without knowing each user password.
Using an admin account to authenticate is not a standard feature
supported by all imap servers. Sometimes it is implemented via --authuser1
sometimes not. It depends on the server software and its configuration.
You have to figure out what is the imap software server,
find out if it supports an admin account and how,
if an admin account is actually configured and
finally check an authentication via this admin account for
a standard user.

Known imap server software supporting admin authentication:

   * Exchange 2003/2007/2010/2013. See the file FAQ.Exchange.txt
   * Office365. See the file FAQ.Exchange.txt
   * Gmail. See the file FAQ.XOAUTH2.txt
   * Dovecot. See the file FAQ.Dovecot.txt
   * UW-imap. See the file FAQ.General.txt
   * Cyrus-imap. See the file FAQ.General.txt
   * Sun Java Enterprise System/SunOne/iPlanet. See the file FAQ.General.txt

https://imapsync.lamiral.info/FAQ.d/FAQ.Exchange.txt
...
======================================================================
Q. How to migrate from or to Office 365 with an admin/authuser account?

Note from Yago Torres Fernandez:
(a working command using admin/authuser on host2 Office 365)

   imapsync ... --authuser2 user_admin@domain.com --user2 user_to_be_migrated@domain.com  ^
                --password2 XXXX --ssl2  ^

but previous in Office365 you must do something like that, using powershell:

   Add-MailboxPermission -identity user_to_be_migrated@domain.com -user user_admin@domain.com -accessrights fullaccess -inheritancetype all

PLAIN authentication is the only way to go with --authuser1 for now.
So don't use --authmech1 SOMETHING with --authuser1 admin_user,
it will not work.
Same behavior with the --authuser2 option.

See also:
http://www.linux-france.org/prj/imapsync_list/msg02203.html

======================================================================

Le 21/02/2017 à 20:55, Enoima a écrit :
> Hi, has anyone use this tool for Zimbra to Office 365 migration before?
> I am currently trying out the tool to migrate mailboxes from Zimbra to O365. I was able to migrate single mailbox (test mailboxes) using username and password successfully.
> Now, I want to do batch migration using the loop window batch file. I am very good with scripting so I just try to understand but I think it is not enough. The problem now is that I do not know the password for the users and want to user super user account for log in at both host1 and host2 but I am stuck currently because I don't know the parameter to specify the username and password for both hosts and where to specify it.
>
> I would appreciate if anyone could help me out.
>

-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by gilleslamiral** [comment]
For the XOAUTH2 part of this issue I added to try the code 
https://github.com/imapsync/imapsync/issues/87#issuecomment-276298841
in the imapsync TODO file.

For Zimbra admin authentication the response is Zimbra can do admin authentication and it's documented at
https://imapsync.lamiral.info/FAQ.d/FAQ.Zimbra.txt
https://zimbra.github.io/adminguide/8.8.9/index.html#_administrator_accounts
```` ...
=======================================================================
Q. How to migrate from Zimbra with an admin account?

R. Use:

  imapsync ... --user1 "normal_user" --authuser1 "admin_user"  --password1 "admin_user_password"

To setup or use a Zimbra admin user see:
https://zimbra.github.io/adminguide/8.8.9/index.html#_administrator_accounts

Thanks to Richard Street from thinkround for this tip.
=======================================================================
````

I'm closing this thread.
