### ISSUE TITLE
Prolem Sync zarafa -> Exchange 2016

### ISSUE THREAD

**Issue by brockz** [imapsync/imapsync#88]
Hello

i synced an imap Account vrom zarafa to exchange 2016 with imapsync with the following command:

 ./imapsync --host1 localhost  --port1 8143 --user1 xxx@xxx.org --password1 Blub --host2 x.x.x.x --authuser2 xxx@xxx.org --user2 xxx_temp --password2 xxxxxxxx --maxsize 5000000000     --maxlinelength 9900     --maxmessagespersecond 4     --regexflag 's/\\Flagged//g'     --disarmreadreceipts     --maxlinelengthcmd 'reformime -r7' --usecache --addheader

99% of the Mailbox get synced fine. But i have 23 Errors listed below. Whats going wrong here ? Host 1 is the zarafa Server and Host 2 is the Exchange Server.

This imapsync is up to date
Homepage: http://imapsync.lamiral.info/
++++ Listing 26 errors encountered during the sync ( avoid this listing with --noerrorsdump ).
Err 1/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX: Could not select: 310 NO SELECT error getting mails in folder
Err 2/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX/Impfausweis: Could not select: 311 NO SELECT error getting mails in folder
Err 3/26: - msg Deleted Items/878388 {1761} couldn't append  (Subject:[FS XXXX (Chur XXXX)]) to folder Deleted Items: 319 BAD Command Argument Error. 11
Err 4/26: - msg Deleted Items/882247 {2414} couldn't append  (Subject:[=?utf-8?Q?WG=3A_Doodle=3A_Link_f=C3=BCr_=22Polstergruppen_etc=2E=22?=]) to folder Deleted Items: 320 BAD Command Argument Error. 11
Err 5/26: - msg Deleted Items/882885 {1426} couldn't append  (Subject:[XXXX]) to folder Deleted Items: 321 BAD Command Argument Error. 11
Err 6/26: - msg Deleted Items/884216 {13526} couldn't append  (Subject:[=?utf-8?Qcht_Physik_XXXX_XXXX_=28?=]) to folder Deleted Items: 322 BAD Command Argument Error. 11
Err 7/26: - msg Deleted Items/889068 {1242} couldn't append  (Subject:[=?UTF-8?Q?M=]) to folder Deleted Items: 323 BAD Command Argument Error. 11
Err 8/26: - msg Deleted Items/903923 {1864} couldn't append  (Subject:[=?UTF-8?Q?Ja]) to folder Deleted Items: 324 BAD Command Argument Error. 11
Err 9/26: - msg Deleted Items/917863 {1173} couldn't append  (Subject:[]) to folder Deleted Items: 325 BAD Command Argument Error. 11
Err 10/26: - msg Deleted Items/939357 {1983} couldn't append  (Subject:[MS XXXX (XXXX)]) to folder Deleted Items: 326 BAD Command Argument Error. 11
Err 11/26: - msg Deleted Items/944238 {1349} couldn't append  (Subject:[Ev. XXXX ]) to folder Deleted Items: 327 BAD Command Argument Error. 11
Err 12/26: - msg Deleted Items/956765 {1629} couldn't append  (Subject:[) to folder Deleted Items: 328 BAD Command Argument Error. 11
Err 13/26: - msg Deleted Items/958422 {1487} couldn't append  (Subject:[J nur evtl)]) to folder Deleted Items: 329 BAD Command Argument Error. 11
Err 14/26: - msg Deleted Items/965870 {1184} couldn't append  (Subject:[ich helfe an der Bar!]) to folder Deleted Items: 330 BAD Command Argument Error. 11
Err 15/26: - msg Deleted Items/991054 {42715} couldn't append  (Subject:[AW: AW: AW: Lieferung Sofa]) to folder Deleted Items: 331 BAD Command Argument Error. 11
Err 16/26: - msg INBOX/EHCD/943502 {19588328} couldn't append  (Subject:[AW: Teamfoto XXXX]) to folder INBOX/EHCD: Error sending 'APPEND INBOX/EHCD (\Seen) "14-Nov-2016 16:43:07 +0000" {19588328}': 386 BAD Command Argument Error. 11
Err 17/26: - msg INBOX/IG RLZ Kutu F/Z&APw-riGymDays 2016/Helfershirts/729097 {13291098} couldn't append  (Subject:[T-Shirt Design]) to folder INBOX/IG RLZ Kutu F/Z&APw-riGymDays 2016/Helfershirts: Error sending 'APPEND "INBOX/IG RLZ Kutu F/Z&APw-riGymDays 2016/Helfershirts" (\Seen) "13-Feb-2016 14:03:27 +0000" {13291098}': 515 BAD Command Argument Error. 11
Err 18/26: Host1 folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX: Could not select: 683 NO SELECT error getting mails in folder
Err 19/26: Host1 folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX/Impfausweis: Could not select: 684 NO SELECT error getting mails in folder
Err 20/26: - msg INBOX/XXXX/KunstXXXX/Infos/2010-2015/822956 {17325360} couldn't append  (Subject:[=?utf-8?Q?Update_TSZ_und_Danke_f=C3=BCrs_2015?=]) to folder INBOX/XXXX/KunstXXXX/Infos/2010-2015: Error sending 'APPEND INBOX/XXXX/KunstXXXX/Infos/2010-2015 (\Seen) "09-Dec-2015 15:02:14 +0000" {17325360}': * BYE Connection closed. 14; 600 BAD Command Argument Error. 11
Err 21/26: - msg Sent Items/30500 {26491147} couldn't append  (Subject:[BVG zum 2.]) to folder Sent Items: Error sending 'APPEND "Sent Items" (\Seen) "15-Apr-2014 12:45:00 +0000" {26491147}': 738 BAD Command Argument Error. 11
Err 22/26: - msg Sent Items/136810 {15547545} couldn't append  (Subject:[Film]) to folder Sent Items: Error sending 'APPEND "Sent Items" (\Seen) "15-Aug-2015 15:18:37 +0000" {15547545}': * BYE Connection closed. 14; 742 BAD Command Argument Error. 11
Err 23/26: - msg Sent Items/136814 {10658847} couldn't append  (Subject:[Film]) to folder Sent Items: Error sending 'APPEND "Sent Items" (\Seen) "15-Aug-2015 15:25:04 +0000" {10658847}': 743 BAD Command Argument Error. 11
Err 24/26: - msg Sent Items/906402 {15171137} couldn't append  (Subject:[XXXX]) to folder Sent Items: Error sending 'APPEND "Sent Items" (\Seen) "27-Sep-2016 04:11:23 +0000" {15171137}': * BYE Connection closed. 14; 747 BAD Command Argument Error. 11
Err 25/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX: Could not select: 1033 NO SELECT error getting mails in folder
Err 26/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX/Impfausweis: Could not select: 1034 NO SELECT error getting mails in folder
Exiting with return value 111
Log file is LOG_imapsync/2017_01_31_11_27_50_ang_temp.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )

Thanks

Br Stefan

**Comment by gilleslamiral** [comment]
Hi Stefan,

Can you access the 2 first folders with a classical email client like Thunderbid?
 > Err 1/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX: Could not select: 310 NO SELECT error getting mails in folder
 > Err 2/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX/Impfausweis: Could not select: 311 NO SELECT error getting mails in folder


Some errors seem the Exchange size limit like the 26 MB message "Err 21/26: - msg Sent Items/30500 {26491147}"
Other might be malformed messages reformime doesn't fix.



Le 31/01/2017 à 12:17, brockz a écrit :
> Hello
>
> i synced an imap Account vrom zarafa to exchange 2016 with imapsync with the following command:
>
> ./imapsync --host1 localhost --port1 8143 --user1 xxx@xxx.org <mailto:xxx@xxx.org> --password1 Blub --host2 x.x.x.x --authuser2 xxx@xxx.org <mailto:xxx@xxx.org> --user2 xxx_temp --password2 xxxxxxxx --maxsize 5000000000 --maxlinelength 9900 --maxmessagespersecond 4 --regexflag 's/\Flagged//g' --disarmreadreceipts --maxlinelengthcmd 'reformime -r7' --usecache --addheader
>
> 99% of the Mailboix get synced fine. But i have 23 Errors listed below. Whats going wrong here ?
>
> This imapsync is up to date
> Homepage: http://imapsync.lamiral.info/
> ++++ Listing 26 errors encountered during the sync ( avoid this listing with --noerrorsdump ).
> Err 1/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX: Could not select: 310 NO SELECT error getting mails in folder
> Err 2/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX/Impfausweis: Could not select: 311 NO SELECT error getting mails in folder
> Err 3/26: - msg Deleted Items/878388 {1761} couldn't append (Subject:[FS XXXX (Chur XXXX)]) to folder Deleted Items: 319 BAD Command Argument Error. 11
> Err 4/26: - msg Deleted Items/882247 {2414} couldn't append (Subject:[=?utf-8?Q?WG=3A_Doodle=3A_Link_f=C3=BCr_=22Polstergruppen_etc=2E=22?=]) to folder Deleted Items: 320 BAD Command Argument Error. 11
> Err 5/26: - msg Deleted Items/882885 {1426} couldn't append (Subject:[XXXX]) to folder Deleted Items: 321 BAD Command Argument Error. 11
> Err 6/26: - msg Deleted Items/884216 {13526} couldn't append (Subject:[=?utf-8?Qcht_Physik_XXXX_XXXX_=28?=]) to folder Deleted Items: 322 BAD Command Argument Error. 11
> Err 7/26: - msg Deleted Items/889068 {1242} couldn't append (Subject:[=?UTF-8?Q?M=]) to folder Deleted Items: 323 BAD Command Argument Error. 11
> Err 8/26: - msg Deleted Items/903923 {1864} couldn't append (Subject:[=?UTF-8?Q?Ja]) to folder Deleted Items: 324 BAD Command Argument Error. 11
> Err 9/26: - msg Deleted Items/917863 {1173} couldn't append (Subject:[]) to folder Deleted Items: 325 BAD Command Argument Error. 11
> Err 10/26: - msg Deleted Items/939357 {1983} couldn't append (Subject:[MS XXXX (XXXX)]) to folder Deleted Items: 326 BAD Command Argument Error. 11
> Err 11/26: - msg Deleted Items/944238 {1349} couldn't append (Subject:[Ev. XXXX ]) to folder Deleted Items: 327 BAD Command Argument Error. 11
> Err 12/26: - msg Deleted Items/956765 {1629} couldn't append (Subject:[) to folder Deleted Items: 328 BAD Command Argument Error. 11
> Err 13/26: - msg Deleted Items/958422 {1487} couldn't append (Subject:[J nur evtl)]) to folder Deleted Items: 329 BAD Command Argument Error. 11
> Err 14/26: - msg Deleted Items/965870 {1184} couldn't append (Subject:[ich helfe an der Bar!]) to folder Deleted Items: 330 BAD Command Argument Error. 11
> Err 15/26: - msg Deleted Items/991054 {42715} couldn't append (Subject:[AW: AW: AW: Lieferung Sofa]) to folder Deleted Items: 331 BAD Command Argument Error. 11
> Err 16/26: - msg INBOX/EHCD/943502 {19588328} couldn't append (Subject:[AW: Teamfoto XXXX]) to folder INBOX/EHCD: Error sending 'APPEND INBOX/EHCD (\Seen) "14-Nov-2016 16:43:07 +0000" {19588328}': 386 BAD Command Argument Error. 11
> Err 17/26: - msg INBOX/IG RLZ Kutu F/Z&APw-riGymDays 2016/Helfershirts/729097 {13291098} couldn't append (Subject:[T-Shirt Design]) to folder INBOX/IG RLZ Kutu F/Z&APw-riGymDays 2016/Helfershirts: Error sending 'APPEND "INBOX/IG RLZ Kutu F/Z&APw-riGymDays 2016/Helfershirts" (\Seen) "13-Feb-2016 14:03:27 +0000" {13291098}': 515 BAD Command Argument Error. 11
> Err 18/26: Host1 folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX: Could not select: 683 NO SELECT error getting mails in folder
> Err 19/26: Host1 folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX/Impfausweis: Could not select: 684 NO SELECT error getting mails in folder
> Err 20/26: - msg INBOX/XXXX/KunstXXXX/Infos/2010-2015/822956 {17325360} couldn't append (Subject:[=?utf-8?Q?Update_TSZ_und_Danke_f=C3=BCrs_2015?=]) to folder INBOX/XXXX/KunstXXXX/Infos/2010-2015: Error sending 'APPEND INBOX/XXXX/KunstXXXX/Infos/2010-2015 (\Seen) "09-Dec-2015 15:02:14 +0000" {17325360}': * BYE Connection closed. 14; 600 BAD Command Argument Error. 11
> Err 21/26: - msg Sent Items/30500 {26491147} couldn't append (Subject:[BVG zum 2.]) to folder Sent Items: Error sending 'APPEND "Sent Items" (\Seen) "15-Apr-2014 12:45:00 +0000" {26491147}': 738 BAD Command Argument Error. 11
> Err 22/26: - msg Sent Items/136810 {15547545} couldn't append (Subject:[Film]) to folder Sent Items: Error sending 'APPEND "Sent Items" (\Seen) "15-Aug-2015 15:18:37 +0000" {15547545}': * BYE Connection closed. 14; 742 BAD Command Argument Error. 11
> Err 23/26: - msg Sent Items/136814 {10658847} couldn't append (Subject:[Film]) to folder Sent Items: Error sending 'APPEND "Sent Items" (\Seen) "15-Aug-2015 15:25:04 +0000" {10658847}': 743 BAD Command Argument Error. 11
> Err 24/26: - msg Sent Items/906402 {15171137} couldn't append (Subject:[XXXX]) to folder Sent Items: Error sending 'APPEND "Sent Items" (\Seen) "27-Sep-2016 04:11:23 +0000" {15171137}': * BYE Connection closed. 14; 747 BAD Command Argument Error. 11
> Err 25/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX: Could not select: 1033 NO SELECT error getting mails in folder
> Err 26/26: Host1 Folder INBOX/XXXX/KunstXXXX/XXXXberichtemed.Berichte XXXX/Impfausweis: Could not select: 1034 NO SELECT error getting mails in folder
> Exiting with return value 111
> Log file is LOG_imapsync/2017_01_31_11_27_50_ang_temp.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )
>
> Thanks
>
> Br Stefan


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by gilleslamiral** [comment]
No news good news! Closing.
