### ISSUE TITLE
Inform Docs: Yahoo needs to activate "allow less secure login"

### ISSUE THREAD

**Issue by EugenMayer** [imapsync/imapsync#89]
For imapsync to be able to auth with yahoo, you need to go to Yahoo, security and enable "Allow less secure apps to login", otherwise the login will not work ( with SSL whats over)

**Comment by gilleslamiral** [comment]
Hi Eugen,

I've updated the FAQ, thanks!

https://imapsync.lamiral.info/FAQ.d/FAQ.Yahoo.txt

Le 05/02/2017 à 11:44, Eugen Mayer a écrit :
> For imapsync to be able to auth with yahoo, you need to go to Yahoo, security and enable "Allow less secure apps to login", otherwise the login will not work ( with SSL whats over)


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42
