### ISSUE TITLE
Importing from a mail server in French, Sent items syncing in a different folder

### ISSUE THREAD

**Issue by Mouradif** [imapsync/imapsync#91]
Hello there,

This is a minor issue but I think it would be interesting to fix. I am using imapsync to migrate e-mails from 1&1 to a dedicated server running mailinabox. It's working perfectly but since my  1&1 account is in French, Sent mails are copied under the folder "Objets envoyés" (French for "Sent items") instead of the regular "Sent" folder. This is only an issue for me since 80% of the e-mail accounts are consulted in Apple Mail client and it's a bit tricky to find the other folders besides the regular "Inbox" and "Sent items".

Looking at all the existing parameters to be passed (concerning folder especially) I was thinking it might be something like a parameter like
`--movefolder oldname newname`
or
`--folder1 oldname --folder2 newname`
to give all the responsobility in translating the folder names to imapsync user.

**Comment by gilleslamiral** [comment]
Hi Mourad,

There is already --automap which will operate on exact folders names
Éléments envoyés
Envoyé

I can add "Objets envoyés" if you confirm the exact spelling and if it
is not a personnal configuration.

Anyway to fix it now use:

   imapsync ... --f1f2 "Objets envoyés=Sent"

The option

   --f1f2 oldname=newname

is equivalent to your described

   --movefolder oldname newname

Read also
https://imapsync.lamiral.info/FAQ.d/FAQ.Folders_Mapping.txt

 >  This is a minor issue but I think it would be interesting to fix. I
 > am using imapsync to migrate e-mails from 1&1 to a dedicated server
 > running mailinabox. It's working perfectly but since my 1&1 account
 > is in French, Sent mails are copied under the folder "Objets
 > envoyés" (French for "Sent items") instead of the regular "Sent"
 > folder. This is only an issue for me since 80% of the e-mail
 > accounts are consulted in Apple Mail client and it's a bit tricky to
 > find the other folders besides the regular "Inbox" and "Sent items".
 >
 >  Looking at all the existing parameters to be passed (concerning
 > folder especially) I was thinking it might be something like a
 > parameter like |--movefolder oldname newname| to give all the
 > responsobility in translating the folder names to imapsync user.



-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by Mouradif** [comment]
Hello Gilles,

This is great ! I wasn't aware of the --f1f2 option. About the "Objets envoyés" it seems to be the name of the Sent items mailbox for all 1&1 email accounts I am in charge of migrating so I believe it's a default thing. Here's a little screenshot : http://img4.hostingpics.net/pics/277783obj.png

**Comment by gilleslamiral** [comment]
Hi Mourad,

Ok,
"Objets envoyés" aka "Objets envoy&AOk-s"
added in imapsync with --automap

Thanks!

 >  This is great ! I wasn't aware of the --f1f2 option. About the
 > "Objets envoyés" it seems to be the name of the Sent items mailbox
 > for all 1&1 email accounts I am in charge of migrating so I believe
 > it's a default thing. Here's a little screenshot :
 > http://img4.hostingpics.net/pics/277783obj.png


-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by Mouradif** [comment]
Sweet ! Thanks !

**Comment by gilleslamiral** [comment]
Added in imapsync  1.790
```
----------------------------
revision 1.790
date: 2017/04/04 11:27:09;  author: gilles;  state: Exp;  lines: +10 -10
Added 'Objets envoy&AOk-s' for --automap
----------------------------
```
