### ISSUE TITLE
error with some special character on last character of password

### ISSUE THREAD

**Issue by fferraro87** [imapsync/imapsync#92]
Hi,
i'm trying to migrate some accounts from an exchange server to a zimbra one, but on some accounts that has password ending with a special character (like that    password1888;   ) i've problem to authenticate.

i've already trying to surround password and username with quote or double quote but it doesn't works. i've also try ^ before special character and also \ before special character but all my test doesn't works.
How can i fix this problem?

i'm working on arch linux OS

Thanks

**Comment by gilleslamiral** [comment]
Hi,

 > i'm trying to migrate some accounts from an exchange server to a
 > zimbra one, but on some accounts that has password ending with a
 > special character (like that password1888; ) i've problem to
 > authenticate.  i've already trying to surround password and username
 > with quote or double quote but it doesn't works. i've also try ^
 > before special character and also \ before special character but all
 > my test doesn't works.  How can i fix this problem?

Change the password in case the following doesn't work
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Windows.txt
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt

-- 
Au revoir,
Gilles Lamiral. France, Baulon (35580)
mob 06 19 22 03 54
tel 09 51 84 42 42

**Comment by fferraro87** [comment]
Ok thanks

**Comment by sneakyx** [comment]
I tried with single quotes.
