### ISSUE TITLE
skipemptyfolders and minage/maxage

### ISSUE THREAD

**Issue by jh1995** [imapsync/imapsync#95]
Use case scenario.
I am copying an IMAP tree restricting the message age with --minage/--maxage. It can happen that some host1 folders contain messages that do not fall within the specified interval, so no messages will be copied. In this case I do not want to create the corresponding folder on host2, that would result empty. Currently (1.727) the decision is taken based on the total number of messages in folder and not on the result of the filtered SELECT (line 1682).

Is it possible to fix it, or have a second switch to force the behaviour described above? Thanks.

**Comment by jh1995** [comment]
This is an extract from the log:

`++++ Calculating sizes of 63 folders on Host1`
[cut]
`Host1 folder   36/63 [INBOX/LEGALE/FAVELLATO]            Size:         0 Messages:     0 Biggest:         0`
[cut]
`++++ Calculating sizes of 63 folders on Host2`
[cut]
`Host2 folder   36/63 [INBOX/Posta archiviata/2015/LEGALE/FAVELLATO] does not exist yet`
[cut]
```
Folder   36/63 [INBOX/LEGALE/FAVELLATO]            -> [INBOX/Posta archiviata/2015/LEGALE/FAVELLATO]
Host1 folder [INBOX/LEGALE/FAVELLATO] has 4 messages in total (mentioned by SELECT)
Creating folder [INBOX/Posta archiviata/2015/LEGALE/FAVELLATO] on host2
Created folder [INBOX/Posta archiviata/2015/LEGALE/FAVELLATO] on host2
Host2 folder [INBOX/Posta archiviata/2015/LEGALE/FAVELLATO] has 0 messages in total (mentioned by SELECT)
Host1: Expunging INBOX/LEGALE/FAVELLATO
Host2: Subscribing to folder INBOX/Posta archiviata/2015/LEGALE/FAVELLATO
Host1 folder [INBOX/LEGALE/FAVELLATO] considering 0 messages
Host2 folder [INBOX/Posta archiviata/2015/LEGALE/FAVELLATO] considering 0 messages
Host1: Expunging folder INBOX/LEGALE/FAVELLATO
```

As you can see, during the "Folders sizes before the synchronization." phase the folder is reported to have 0 messages, and it does not exist on host2. Then when processing each folder, host1 says it contains 4 messages (which is true, but not in the range maxage...minage), and then again "Host1 ... considering 0 messages". The source folder does contain 4 messages, from year 2016 outside of the requested range.

**Comment by jh1995** [comment]
I did some debugging and wrote a patch that seems to work. But now knowing all internals of the IMAP library and being unable to test all possible scenarios, I strongly reccommend to test it out before using in production.

Search for the first occurrence of $h1_fold_nb_messages, it is around line 1680 in 1.727. Comment it out and add:
```
        my $h1_msgs_all_hash_ref_tmp = {  } ;
        my @h1_msgs_tmp = select_msgs( $imap1, $h1_msgs_all_hash_ref_tmp, $search1, $h1_fold );
        last FOLDER if $imap1->IsUnconnected(  ) ;

        my $h1_fold_nb_messages = scalar  @h1_msgs_tmp  ;
```
This is a replica of the same code found few dozens of lines further down since I was not sure if I could move it at this point right away.

**Comment by gilleslamiral** [comment]
Hi jh1995,

You found how to fix it.
I'm not sure I will add a switch for this
Maybe upon a second user demand

**Comment by gilleslamiral** [comment]
Patch applied and tested in imapsync release 1.889
Thanks jh1995!
