### ISSUE TITLE
unknown imapsync problem

### ISSUE THREAD

**Issue by razula** [imapsync/imapsync#96]
Hello!
i have a problem when im triyng to sync mailbox from host1 with 97520 messages to host2
it seems like it sees that the mailbox has 97520 but in the end it says "considering 0"

THE LOG:
imapsync --host1 source.email.server --authmech1 LOGIN --port1 143 --user1 test@test.com --password1 "password" --host2 my.email.server --user2 test@test.com --password2 "password"  --syncinternaldates --ssl2
Transfer started at Wed May 17 11:10:59 2017
PID is 32542
Log file is LOG_imapsync/2017_05_17_11_10_59_test@test.com.txt ( to change it, use --logfile path ; or use --nolog to turn off logging )
$RCSfile: imapsync,v $ $Revision: 1.727 $ $Date: 2016/08/19 10:30:36 $
Here is a [linux] system (Linux o.email.server 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64)
with Perl 5.22.1 Mail::IMAPClient 3.38
Command line used:
/usr/bin/imapsync --host1 source.email.server --authmech1 LOGIN --port1 143 --user1 test@test.com --password1 MASKED --host2 my.email.server --user2 test@test.com --password2 MASKED --syncinternaldates --ssl2
Temp directory is /tmp  ( to change it use --tmpdir dirpath )
PID file is /tmp/imapsync.pid ( to change it use --pidfile filepath ; to avoid it use --pidfile "" )
Wrinting my PID 32542 in /tmp/imapsync.pid
Modules version list:
Mail::IMAPClient     3.38
IO::Socket           1.38
IO::Socket::INET     1.35
IO::Socket::INET6    2.72
IO::Socket::SSL      2.024
Net::SSLeay          1.72
Compress::Zlib       2.068
Digest::MD5          2.54
Digest::HMAC_MD5     1.01
Digest::HMAC_SHA1    1.03
Term::ReadKey        2.37
File::Spec           3.56
Time::HiRes          1.9726
Unicode::String      2.10
IO::Tee              0.64
File::Copy::Recursive 0.38
Authen::NTLM         1.09
URI::Escape          3.31
Data::Uniqid         0.12
JSON                 2.90
JSON::WebToken       0.10
Crypt::OpenSSL::RSA  0.28
LWP                  ?
HTML::Entities       3.69
Getopt::Long         2.45
Test::MockObject     1.20161202
( use --no-modulesversion to turn off printing this Perl modules list )
SSL debug mode level is --debugssl 1 (can be set from 0 meaning no debug to 4 meaning max debug)
Host2: SSL default mode is like --sslargs2 SSL_verify_mode=0 meaning SSL_VERIFY_NONE on host2 (do not check the certificate server)
Host2: Use --sslargs2 SSL_verify_mode=1 for SSL_VERIFY_PEER on host2
Info: turned ON syncinternaldates, will set the internal dates (arrival dates) on host2 same as host1.
Host1: will try to use LOGIN authentication on host1
Host2: will try to use LOGIN authentication on host2
Host1: imap connexion timeout is 120 seconds
Host2: imap connexion timeout is 120 seconds
Host1: IMAP server [source.email.server] port [143] user [test@test.com]
Host2: IMAP server [my.email.server] port [993] user [test@test.com]
Host1: connecting and login on host1 [source.email.server] port [143] with user [test@test.com]
Host1 banner: * OK IMAP4rev1 SmarterMail
Host1: source.email.server says it has NO CAPABILITY for AUTHENTICATE LOGIN
Host1: success login on [source.email.server] with user [test@test.com] auth [LOGIN]
Host2: connecting and login on host2 [my.email.server] port [993] with user [test@test.com]
Host2 banner: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
Host2: my.email.server says it has CAPABILITY for AUTHENTICATE LOGIN
Host2: success login on [my.email.server] with user [test@test.com] auth [LOGIN]
Host1: state Authenticated
Host2: state Authenticated
Host1 capability: IMAP4 IMAP4rev1
Host2 capability: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SPECIAL-USE QUOTA ACL RIGHTS=texk

Host2: found quota, presented in raw IMAP
Sending: 4 GETQUOTAROOT INBOX
Sent 22 bytes
Read:   * QUOTAROOT INBOX user
        * QUOTA user (STORAGE 139 2097152)
        4 OK Getquotaroot completed (0.000 + 0.000 secs).

Host2: Quota current storage is 142336 bytes. Limit is 2147483648 bytes. So 0.01 % full
Host1: found 1 folders.
Host2: found 5 folders.
Including all folders found by default. Use --subscribed or --folder or --folderrec or --include to select specific folders. Use --exclude to unselect specific folders.
Host1: checking all wanted folders exist.
Host1: checking all wanted folders are selectable. Use --nocheckselectable to avoid this check.
Host1: guessing separator from folder listing: [/]
Host1: No NAMESPACE capability, so using guessed separator [/]
You can set the separator character with the --sep1 option,
the complete listing of folders may help you to find it
[Inbox]
Host2: guessing separator from folder listing: [/]
Host2: separator given by NAMESPACE: [/]
Host1: guessing prefix from folder listing: []
Host1: No NAMESPACE capability so using guessed prefix []
You can set the prefix namespace with the --prefix1 option,
the folowing listing of folders may help you to find it:
[Inbox]
Host2: guessing prefix from folder listing: []
Host2: prefix given by NAMESPACE: []
Host1 separator and prefix: [/][]
Host2 separator and prefix: [/][]
Turned off automapping folders ( use --automap to turn on automapping )

++++ Listing folders
All foldernames are presented between brackets like [X] where X is the foldername.
When a foldername contains non-ASCII characters it is presented in the form
[X] = [Y] where
X is the imap foldername you have to use in command line options and
Y is the uft8 output just printed for convenience, to recognize it.

Host1 folders list:
[Inbox]

Host2 folders list:
[Drafts]
[INBOX]
[Junk]
[Sent]
[Trash]

Folders in host2 not in host1:
[Trash]
[Sent]
[Junk]
[Drafts]

Folders mapping from --automap feature (use --f1f2 to override any mapping):

Folders mapping from --f1f2 options, it overrides --automap:

Folders sizes before the synchronization.
You can remove foldersizes listings by using "--nofoldersizes" and  "--nofoldersizesatend"
but then you will also loose the ETA (Estimation Time of Arrival) given after each message copy.
++++ Calculating sizes of 1 folders on Host1
Host1 folder     1/1 [Inbox]                             Size:         0 Messages:     0 Biggest:         0
Host1 Nb folders:                1 folders
Host1 Nb messages:               0 messages
Host1 Total size:                0 bytes (0.000 KiB)
Host1 Biggest message:           0 bytes (0.000 KiB)
Host1 Time spent:            484.2 seconds
++++ Calculating sizes of 1 folders on Host2
Host2 folder     1/1 [INBOX]                             Size:    145182 Messages:    75 Biggest:      7093
Host2 Nb folders:                1 folders
Host2 Nb messages:              75 messages
Host2 Total size:           145182 bytes (141.779 KiB)
Host2 Biggest message:        7093 bytes (6.927 KiB)
Host2 Time spent:              0.3 seconds
++++ Looping on each one of 1 folders to sync
Folder     1/1 [Inbox]                             -> [INBOX]
Host1 folder [Inbox] has 97520 messages in total (mentioned by SELECT)
Host2 folder [INBOX] has 75 messages in total (mentioned by SELECT)
Host1 folder [Inbox] considering 0 messages
Host2 folder [INBOX] considering 75 messages
++++ End looping on each folder

Folders sizes after the synchronization.
You can remove this foldersizes listing by using  "--nofoldersizesatend"
++++ Calculating sizes of 1 folders on Host1
Host1 folder     1/1 [Inbox]                             Size:         0 Messages:     0 Biggest:         0
Host1 Nb folders:                1 folders
Host1 Nb messages:               0 messages
Host1 Total size:                0 bytes (0.000 KiB)
Host1 Biggest message:           0 bytes (0.000 KiB)
Host1 Time spent:            481.4 seconds
++++ Calculating sizes of 1 folders on Host2
Host2 folder     1/1 [INBOX]                             Size:    145182 Messages:    75 Biggest:      7093
Host2 Nb folders:                1 folders
Host2 Nb messages:              75 messages
Host2 Total size:           145182 bytes (141.779 KiB)
Host2 Biggest message:        7093 bytes (6.927 KiB)
Host2 Time spent:              0.3 seconds
++++ Statistics
Transfer started on               : Wed May 17 11:10:59 2017
Transfer ended on                 : Wed May 17 11:35:06 2017
Transfer time                     : 1447.8 sec
Folders synced                    : 1/1 synced
Messages transferred              : 0
Messages skipped                  : 0
Messages found duplicate on host1 : 0
Messages found duplicate on host2 : 0
Messages void (noheader) on host1 : 0
Messages void (noheader) on host2 : 0
Messages deleted on host1         : 0
Messages deleted on host2         : 0
Total bytes transferred           : 0 (0.000 KiB)
Total bytes duplicate host1       : 0 (0.000 KiB)
Total bytes duplicate host2       : 0 (0.000 KiB)
Total bytes skipped               : 0 (0.000 KiB)
Total bytes error                 : 0 (0.000 KiB)
Message rate                      : 0.0 messages/s
Average bandwidth rate            : 0.0 KiB/s
Memory consumption                : 216.1 MiB
Biggest message                   : 0 bytes (0.000 KiB)
Memory/biggest message ratio      : NA
Start difference host2 - host1    : 75 messages, 145182 bytes (141.779 KiB)
Final difference host2 - host1    : 75 messages, 145182 bytes (141.779 KiB)
Detected 0 errors

Homepage: http://imapsync.lamiral.info/
Exiting with return value 0
Log file is LOG_imapsync/2017_05_17_11_10_59_test@test.com.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )

Thank you!
Raz

**Comment by gilleslamiral** [comment]
Well, I have no clue!
What gives a run with --debugimap1 

    imapsync ... --debugimap1

**Comment by razula** [comment]
hey gilles 
thank you for your answer
i did as you said: imapsync --host1 source.email.server --authmech1 LOGIN --port1 143 --user1 test@test.com --password1 "password" --debugimap1 --host2 my.email.server --user2 test@test.com --password2 "password" --syncinternaldates --ssl2.

it created a log file of 300 mg;)

some how somthing like 3000 messages from year 2013 could pass.
after that there was errors about imap module:
Read:   * 5645 FETCH (BODY[]     UID 5645)
        88669 OK UID completed
internal date from host1: [9-Oct-2013 16:02:02 +0300]
internal date from host1: ["09-Oct-2013 16:02:02 +0300"] (fixed)
Host1 flags init msg Inbox/5645 date ["09-Oct-2013 16:02:02 +0300"] flags [] size [9724]
Host1 flags filt msg Inbox/5645 date ["09-Oct-2013 16:02:02 +0300"] flags [] size [9724]
msg Inbox/5645 {9724}         copied to INBOX/4118       0.76 msgs/s  4.900 KiB/s 24.475 MiB copied  ETA: Fri May 26 03:35:09 2017  61181 s  46204/97520 msgs left
msg Inbox/5646 copying to INBOX
Sending: 88670 UID FETCH 5646 BODY.PEEK[]
Sent 34 bytes
LITERAL: received literal in line * 5646 FETCH (BODY[]  of length 9669; attempting to retrieve from the 0 bytes in: <END_OF_iBuffer>
Received ret=3072 3072 of 9669
Received ret=5120 8192 of 9669
Received ret=1477 9669 of 9669
Read:   * 5646 FETCH (BODY[]     UID 5646)
        88670 OK UID completed
internal date from host1: [9-Oct-2013 16:02:02 +0300]
internal date from host1: ["09-Oct-2013 16:02:02 +0300"] (fixed)
Host1 flags init msg Inbox/5646 date ["09-Oct-2013 16:02:02 +0300"] flags [] size [9669]
Host1 flags filt msg Inbox/5646 date ["09-Oct-2013 16:02:02 +0300"] flags [] size [9669]
msg Inbox/5646 {9669}         copied to INBOX/4119       0.76 msgs/s  4.901 KiB/s 24.484 MiB copied  ETA: Fri May 26 03:34:53 2017  61165 s  46203/97520 msgs left
msg Inbox/5647 copying to INBOX
Sending: 88671 UID FETCH 5647 BODY.PEEK[]
Sent 34 bytes
Read:   88671 BAD UID Bad Arguments
ERROR: 88671 BAD UID Bad Arguments at /usr/share/perl5/Mail/IMAPClient.pm line 1365.
        Mail::IMAPClient::__ANON__("88671 BAD UID Bad Arguments\x{d}\x{a}") called at /usr/share/perl5/Mail/IMAPClient.pm line 1401
        Mail::IMAPClient::_get_response(Mail::IMAPClient=HASH(0x3db2088), HASH(0x131b4408), 88671, undef) called at /usr/share/perl5/Mail/IMAPClient.pm line 1327
        Mail::IMAPClient::_imap_command_do(Mail::IMAPClient=HASH(0x3db2088), HASH(0x131b6828), "UID FETCH 5647 BODY.PEEK[]") called at /usr/share/perl5/Mail/IMAPClient.pm line 1226
        Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x3db2088), HASH(0x131b6828), "UID FETCH 5647 BODY.PEEK[]") called at /usr/share/perl5/Mail/IMAPClient.pm line 1437
        Mail::IMAPClient::_imap_uid_command(Mail::IMAPClient=HASH(0x3db2088), HASH(0x131b6828), "FETCH", 5647, "BODY.PEEK[]") called at /usr/share/perl5/Mail/IMAPClient.pm line 937
        Mail::IMAPClient::message_to_file(Mail::IMAPClient=HASH(0x3db2088), SCALAR(0x2d3cb88), 5647) called at /usr/bin/imapsync line 5141
        main::message_for_host2(HASH(0x1eeaf30), 5647, "Inbox", 9659, "", "9-Oct-2013 16:02:05 +0300", HASH(0x5d68758), SCALAR(0x2d3cb88)) called at /usr/bin/imapsync line 5021
        main::copy_message(HASH(0x1eeaf30), 5647, "Inbox", "INBOX", HASH(0x5d68758), "", "/tmp/imapsync_cache/source.server.com/renew\@example.com/my.d"...) called at /usr/bin/imapsync line 2051
ERROR: 88671 BAD UID Bad Arguments at /usr/share/perl5/Mail/IMAPClient.pm line 1275.
        Mail::IMAPClient::_imap_command(Mail::IMAPClient=HASH(0x3db2088), HASH(0x131b6828), "UID FETCH 5647 BODY.PEEK[]") called at /usr/share/perl5/Mail/IMAPClient.pm line 1437
        Mail::IMAPClient::_imap_uid_command(Mail::IMAPClient=HASH(0x3db2088), HASH(0x131b6828), "FETCH", 5647, "BODY.PEEK[]") called at /usr/share/perl5/Mail/IMAPClient.pm line 937
        Mail::IMAPClient::message_to_file(Mail::IMAPClient=HASH(0x3db2088), SCALAR(0x2d3cb88), 5647) called at /usr/bin/imapsync line 5141
        main::message_for_host2(HASH(0x1eeaf30), 5647, "Inbox", 9659, "", "9-Oct-2013 16:02:05 +0300", HASH(0x5d68758), SCALAR(0x2d3cb88)) called at /usr/bin/imapsync line 5021
        main::copy_message(HASH(0x1eeaf30), 5647, "Inbox", "INBOX", HASH(0x5d68758), "", "/tmp/imapsync_cache/source.server.com/renew\@example.com/my.d"...) called at /usr/bin/imapsync line 2051
- msg Inbox/5647 {0} S[9659] F[] I[9-Oct-2013 16:02:05 +0300] could not be fetched: 88671 BAD UID Bad Arguments
- msg Inbox/5647 skipped.

thank you

Raz

**Comment by gilleslamiral** [comment]
Hi Raz,

No more clue!
Does it happen each time at the same message UID?

**Comment by gilleslamiral** [comment]
Since host1 is SmarterMail, I guess that this issue could be solved with the option ` --noabletosearch1`
See: https://imapsync.lamiral.info/FAQ.d/FAQ.SmarterMail.txt
```
=======================================================================
    Imapsync tips for SmarterMail. Specific issues and solutions.
=======================================================================

=======================================================================
Q. Synchronizing from SmarterMail to XXX

On Unix:
imapsync --host1 imap.d1.org --user1 joe --password1 secret1 \
         --host2 imap.d2.org --user2 joe --password2 secret2 \
         --sep1 "/" --prefix1 "" --useheader Message-Id --noabletosearch1 \
	 --regextrans2 "s,Deleted Items,Trash," \
	 --regextrans2 "s,Junk E-Mail,Junk," \
         --regextrans2 "s,Sent Items,Sent," 

On Windows:
imapsync.exe --host1 imap.d1.org --user1 joe --password1 secret1 ^
         --host2 imap.d2.org --user2 joe --password2 secret2  ^
         --sep1 "/" --prefix1 "" --useheader Message-Id --noabletosearch1 ^
         --regextrans2 "s,Deleted Items,Trash,"  ^
	 --regextrans2 "s,Junk E-Mail,Junk,"    ^
	 --regextrans2 "s,Sent Items,Sent,"

Maybe add other --regextrans2 to change folder names, for this
see also http://imapsync.lamiral.info/FAQ.d/FAQ.Folders_Mapping.txt

=======================================================================
Q. Synchronizing from XXX to SmarterMail

On Unix:
imapsync --host1 imap.d1.org --user1 joe --password1 secret1  \
         --host2 imap.d2.org --user2 joe --password2 secret2  \
         --sep2 "/" --prefix2 "" --useheader Message-Id --noabletosearch2

On Windows:
imapsync.exe --host1 imap.d1.org --user1 joe --password1 secret1 ^
             --host2 imap.d2.org --user2 joe --password2 secret2 ^
             --sep2 "/" --prefix2 "" --useheader Message-Id --noabletosearch2


=======================================================================
```
