### ISSUE TITLE
Adding the rest of folder mapping

### ISSUE THREAD

**Issue by Debeet** [imapsync/imapsync#97]
Would it be possible for you to add the rest of folder mapping from [here](https://stackoverflow.com/questions/2185391/localized-gmail-imap-folders/2185548#2185548) to build_possible_special()?

I'd make a pull request myself but I'm not sure how special characters (e.g. chinese) are treated in the code.

**Comment by gilleslamiral** [comment]
Since all Gmail translations are automatically supported by automagic rfc6154 I don't plan to add them anymore.

**Comment by gilleslamiral** [comment]
rfc6154 special folders are:
\All \Archive \Drafts \Flagged \Junk \Sent \Trash

See
https://tools.ietf.org/html/rfc6154

**Comment by Debeet** [comment]
Since I've opened this issue I've had multiple situation where clients' messages would end up in subfolders, e.g. /Inbox/Spam instead of just /Spam.

Expanding automapping by myself in imapsync solved this issue. Here's what my version of `build_possible_special()` looks like (I've added Polish phrases):

```
$possible_special->{'\All'}     = [ 'All', 'All Messages', '&BBIEQQQ1-' ] ;
$possible_special->{'\Archive'} = [ 'Archive', 'Archives', '&BBAEQARFBDgEMg-' ] ;
$possible_special->{'\Drafts'}  = [ 'Drafts', 'DRAFTS', '&BCcENQRABD0EPgQyBDgEOgQ4-', 'Szkice', 'Wersje robocze' ] ;
$possible_special->{'\Flagged'} = [ 'Flagged', 'Starred', '&BB8EPgQ8BDUERwQ1BD0EPQRLBDU-' ] ;
$possible_special->{'\Junk'}    = [ 'Junk', 'SPAM', 'Spam', '&BCEEPwQwBDw-', 'Potwierdzony spam', 'Wiadomo&AVs-ci-&AVs-mieci' ] ;
$possible_special->{'\Sent'}    = [ 'Sent', 'SENT', 'Sent Messages', 'Sent Items',
                                            'Gesendete Elemente', 'Gesendete Objekte',
                                            '&AMk-l&AOk-ments envoy&AOk-s', 'Envoy&AOk-',
                                            'Elementos enviados',
                                            '&kAFP4W4IMH8wojCkMMYw4A-',
                                            '&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-',
                                            'Elementy wys&AUI-ane'] ;
$possible_special->{'\Trash'}   = [ 'Trash', 'TRASH', '&BCMENAQwBDsENQQ9BD0ESwQ1-', '&BBoEPgRABDcEOAQ9BDA-', 'Kosz', 'Deleted Items' ] ;
```

Please reconsider expanding it.

**Comment by gilleslamiral** [comment]
Hi Debeet,

Thanks!
Patch applied in imapsync release 1.838
