### ISSUE TITLE
Space in passwords

### ISSUE THREAD

**Issue by tdeleeuw** [imapsync/imapsync#99]
Hi 

I have users with spaces in passwords and special characters. When a space is present I got error
"2 BAD Unexpected extra arguments to LOGIN"

I believe it is because the password should be surrounded by double quotes (at least, storing the password in a file with double quotes around it worked around the problem ;-) )

Here is the relevant imap debug output (anonymized)

Sending: 2 LOGIN xxx.yyy@zzz.aa aaaaa bbbbbbbbb cccccccc ddddddddd@#!.,?
Sent 56 bytes
Read:   2 BAD Unexpected extra arguments to LOGIN
ERROR: 2 BAD Unexpected extra arguments to LOGIN at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1364.
        Mail::IMAPClient::__ANON__('2 BAD Unexpected extra arguments to LOGIN\x{d}\x{a}') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1400
        Mail::IMAPClient::_get_response('Mail::IMAPClient=HASH(0x1922088)', 2, undef) called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1326
        Mail::IMAPClient::_imap_command_do('Mail::IMAPClient=HASH(0x1922088)', 'LOGIN xxx.yyy@zzz.aa aaaaa bbbbbbbbb cccccccc ddddddddd@#!.,?') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1225
        Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x1922088)', 'LOGIN xxx.yyy@zzz.aa aaaaa bbbbbbbbb cccccccc ddddddddd@#!.,?') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 583
        Mail::IMAPClient::login('Mail::IMAPClient=HASH(0x1922088)') called at /usr/bin/imapsync line 3170
        main::authenticate_imap('Mail::IMAPClient=HASH(0x1922088)', 123.456.789.123, 993, 'xxx.yyy@zzz.aa', undef, 'aaaaa bbbbbbbbb cccccccc ddddddddd@#!.,?', 1, 120, 0, ...) called at /usr/bin/imapsync line 3137
        main::login_imap(123.456.789.123, 993, 'xxx.yyy@zzz.aa', undef, 'aaaaa bbbbbbbbb cccccccc ddddddddd@#!.,?', 1, 120, 0, 1, ...) called at /usr/bin/imapsync line 1365
ERROR: 2 BAD Unexpected extra arguments to LOGIN at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 1274.
        Mail::IMAPClient::_imap_command('Mail::IMAPClient=HASH(0x1922088)', 'LOGIN xxx.yyy@zzz.aa aaaaa bbbbbbbbb cccccccc ddddddddd@#!.,?') called at /usr/share/perl5/vendor_perl/Mail/IMAPClient.pm line 583
        Mail::IMAPClient::login('Mail::IMAPClient=HASH(0x1922088)') called at /usr/bin/imapsync line 3170
        main::authenticate_imap('Mail::IMAPClient=HASH(0x1922088)', 123.456.789.123, 993, 'xxx.yyy@zzz.aa', undef, 'aaaaa bbbbbbbbb cccccccc ddddddddd@#!.,?', 1, 120, 0, ...) called at /usr/bin/imapsync line 3137
        main::login_imap(123.456.789.123, 993, 'xxx.yyy@zzz.aa', undef, 'aaaaa bbbbbbbbb cccccccc ddddddddd@#!.,?', 1, 120, 0, 1, ...) called at /usr/bin/imapsync line 1365

**Comment by gilleslamiral** [comment]
This is an old issue that had several answers strongly depending on the underlying Perl package Mail::IMAPClient release. See
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt
```
===================================================================
              Imapsync issues with passwords on Unix.
===================================================================

===================================================================
Q. On Unix, some passwords contain some *(),;& characters. Login fails.

R. Use double-quotes within single-quotes in order to enclose the 
   password    within double-quotes in the imap LOGIN command:

    imapsync ... --password1 '"passw*(),;&rd"'

===================================================================
```
